### ISSUE TITLE
Adaptation of the keyboard under the eink screen

### ISSUE THREAD

**Issue by Ilia1** [AnySoftKeyboard/AnySoftKeyboard#1005]
I like your app, could you rewrite it to work on the eink screen, please? The official website has documentation for working with the eink screen. 
https://yotaphone.com/ru-ru/developer/docs/develop/building-first-app-epd/ 
Before the release of the yotaphone 3 it would be very helpful. A standard keyboard is not satisfied, want to use your keyboard on the second screen too 😃

**Comment by AnXh3L0** [comment]
Hi there @Ilia1, is this still something you would like to have? We are currently prioritizing more important bugs and probably won't be able to work on this anytime soon.

**Comment by Ilia1** [comment]
Unfortunately yota SDK is no longer available. I close the ticket
