### ISSUE TITLE
Auto correction modifies URL in the browser URL bar

### ISSUE THREAD

**Issue by AndrewPy** [AnySoftKeyboard/AnySoftKeyboard#1014]
### Steps to reproduce
1. Open Opera Mini or Mozilla Firefox
2. Enter the first piece of an URL (before the dot) in the browser URL bar.
3. Enter the dot.

### Expected behaviour
There should be no auto correction in the URL bar. (As with AnySoftKeyboard v 1.8-r10.) 

### Actual behaviour
The auto correction modifies the word/URL. (AnySoftKeyboard v 1.8-r11)

**Android OS version:**
5.1.1

**Device manufacturer and model:**
Wiko Pulp 4G

**List of installed add-ons (like languages, or themes):**
German Language Package

**Comment by menny** [comment]
Happens on Chrome as well. I'll fix this quickly.

Thanks for the report
