### ISSUE TITLE
Dictionary not loaded on tablet nexus 7 (java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memmove" referenced) ******** Could not load native library anysoftkey2_jni ********

### ISSUE THREAD

**Issue by PashaLaptev** [AnySoftKeyboard/AnySoftKeyboard#1025]
### Steps to reproduce
1. Open Keyboard
2. Open Android Monitor, Choose Error Logs  
3. You'll see java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memmove" referenced.  at com.neurokeys.base.utils.CompatUtils.loadNativeLibrary
******** Could not load native library anysoftkey2_jni ********

### Expected behaviour
Must load dictionary

**Android OS version:**
6.0.1. But on the other devices with the same android version works OK
**Device manufacturer and model:**
Nexus 7

**Comment by menny** [comment]
Does AnySoftKeyboard  crash?
How about suggestions? Do you get those?
