### ISSUE TITLE
Allow users to disable specific KEYBOARD-INPUT-MODEs

### ISSUE THREAD

**Issue by Larx** [AnySoftKeyboard/AnySoftKeyboard#1030]
### Steps to reproduce
1. Enter some text in Firefox's URL field (maybe other browsers, too)
2. The space bar is reduced to make space for an extra key with .com (or whatever TLD you have configured)
3. The space bar now is too small, at least I always type .com instead. I have not yet found a method to get rid of the domain shortcut.

I really don't know if this is an issue with Firefox, ASK or my layout (I use German). However, this TLD field is _extremely_  annoying as it completely destroys the usual keyboard layout for an very relevant key like space. And nowadays at least I most of the time use the URL field of Firefox not to enter URLs directly, but to search the web or browse the history.

Is it possible to disable this custom layout?

### Expected behaviour
The keyboard layout should remain the same.

### Actual behaviour
The space bar is drastically reduced in size.

**Comment by menny** [comment]
I'll revise this request just a bit

**Comment by menny** [comment]
Users should be able to disable the support for rows targeting specific input-modes:
 [ ] IM
 [ ] URL
 [ ] EMAIL
 [ ] PASSWORD

**Comment by menny** [comment]
This means that the current "AskPrefs.supportPasswordKeyboardRowMode" should be removed.

**Comment by Larx** [comment]
Thanks for considering my proposal. Looks better the way you put it ;-).

**Comment by Larx** [comment]
Is there any ETA for this?

**Comment by anmith** [comment]
I would also appreciate it to be able to have the same keyboard for ALL input fields. As with a hardware keyboard I'd love to have all the keys at the same place all the time.

In texts, I'm used to do a long press on "." (right of space key) to get the popup and select ":"

In the Chrome URL field, there's no ":" when I do a long press on "." as the ":" is left of space key which is meant as comfort option but for me it's pressing ".", wondering where the ":" went, selecting something, deleting it and then pressing ":" afterwards.
