### ISSUE TITLE
Double-tap Caps Lock Non-functional At Start Of Sentence

### ISSUE THREAD

**Issue by efwb001** [AnySoftKeyboard/AnySoftKeyboard#1037]
### Steps to reproduce
1. Make sure the keyboard is set up to auto-capitalize the first word of a sentence (setting "Auto-capitalization" under Languages-->Even more).
2. At the start of a sentence or blank text field, rapidly double-tap the capitalization (shift) key.

### Expected behaviour
The keyboard should enter caps-lock (all letters will be capitalized until you hit the capitalization/shift key again).

### Actual behaviour
Nothing happens. More specifically, it looks like it quickly switches to lower-case then back to capitalized.

**Android OS version:**
5.1 (ASK Version 1.8.844, version-code 2169)

**Device manufacturer and model:**
Moto X 2nd gen

**List of installed add-ons (like languages, or themes):**
Nothing but the defaults for US English.

Setup details:
Keyboard: Reproduced with both English (QWERTY Latin keyboard) and English (QWERTY Latin keyboard with symbols (on long press))
Bottom row: Reproduced with both Regular and Old School

**Comment by menny** [comment]
Yes, this is a problematic issue. In the next release, we'll also have long-press to flip caps-lock state.
I suggest you use long-press rather than double-tapping.

The new release should be available in the next couple of days

**Comment by menny** [comment]
I'm closing this for now. If you feel the new method (long-press) is not working for you, re-open this ticket again.

**Comment by efwb001** [comment]
Thanks, that works for me. I appreciate your time and efforts on this app.
