### ISSUE TITLE
Add standard double and single curly quotes to the English keyboards

### ISSUE THREAD

**Issue by terrycloth** [AnySoftKeyboard/AnySoftKeyboard#1038]
## the problem

It seems funny to me that, if you're willing to dig for it, you can use the French angle quotation marks (`«` and `»`) but not the standard double and single curly quotation marks used in English:

* `“` — Left Double Quotation Mark, U+201C
* `”` — Right Double Quotation Mark, U+201D
* `‘` — Left Single Quotation Mark, U+2018
* `’` — Right Single Quotation Mark,  U+2019

## possible solution

I think it would make sense to add these to the long-press on the straight apostrophe and/or straight double quotes.

## my device and software

**Android OS version:** 5.0.1 (unmodified ROM)

**Device manufacturer and model:** Samsung Galaxy S4

**List of installed add-ons (like languages, or themes):**

* AnySoftKeyboard 1.8.844
* Spanish Language Pack (by Menny Even Danan) 2.0
* Esperanto Language Pack (by Menny Even Danan) 20100613
* Italian for AnySoftKeyboard (by Lado Kumsiashvili) 20101125-better-layout

**Comment by menny** [comment]
is this the same as https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1043 ?
