### ISSUE TITLE
Complete support quotation marks

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#1043]
Please, complete support quotation marks in bottom row. Currently single quote ' double quote " and u201d ” and u201e „ are supported, see:

    $ cd app/src/main/res
    $ grep -riI 201d *
    ...
    xml/ext_kbd_bottom_row_regular_with_voice.xml
    xml/symbols.xml
    xml/ext_kbd_bottom_row_ng.xml
    xml/ext_kbd_bottom_row_regular.xml
    xml-ar/ext_kbd_bottom_row_regular.xml
    xml-land/ext_kbd_bottom_row_regular.xml

What needs to be added are u201c “ and u2018 ‘ and u2019 ’

When adding these, the total number of extra characters on the key for single quote ' will be six, meaning that the extra characters will still be shown in one row.

The change would be from

    android:popupCharacters="&#34;\u201e\u201d"/>

to

    android:popupCharacters="&#34;\u201c\u201e\u201d\u2018\u2019"/>

in order to keep the order relevant to the general usage.

**Comment by menny** [comment]
Is this the same as https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1038 ?

**Comment by terrycloth** [comment]
Yes, I believe this is a duplicate of #1038, though I like that this issue talks a little about the implementation details.

**Comment by menny** [comment]
@terrycloth thanks for confirming.

**Comment by menny** [comment]
@PanderMusubi want to submit a PR to add those to all layouts?

**Comment by PanderMusubi** [comment]
Sure

**Comment by PanderMusubi** [comment]
See PR https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1051

**Comment by PanderMusubi** [comment]
Perhaps something for later, add lower single opening quote and double and single guillemots.

**Comment by menny** [comment]
Please open another ticket for that, so we'll not forget
