### ISSUE TITLE
Dvorak doesn't have accented 'e's or 'u's

### ISSUE THREAD

**Issue by alexander-b** [AnySoftKeyboard/AnySoftKeyboard#1045]
### Steps to reproduce
1. Select Dvorak layout
2. Try to type accented 'e's or 'u's, such as é or ü

### Expected behaviour
Long-press option for accented 'e's and 'u's like with 'a', 'i', etc.

### Actual behaviour
Can't get accented 'e's or 'u's -- there's no long-press options for 'e' or 'u'

**Android OS version:** 6.0.1

**Device manufacturer and model:** Motorola Moto X Style

**List of installed add-ons (like languages, or themes):** None

I'm on AnySoftKeyboard 1.8.844 from F-Droid.

**Comment by menny** [comment]
@friesenkiwi can you fix this?

**Comment by friesenkiwi** [comment]
@menny yes, I will send a PR over.

**Comment by alexander-b** [comment]
Great! Can someone make sure to release the fix to F-Droid ASAP?
