### ISSUE TITLE
[Enhancement] Word-Ballons for ALL Words Option

### ISSUE THREAD

**Issue by qrcoder** [AnySoftKeyboard/AnySoftKeyboard#1055]
Auto correction action causes a word to come up in a balloon like manner. It would be nice to have an option that allows ALL words to pop up like that after space / punctuation characters. This would allow nicely to write without having to look up to the actual text.

**Comment by menny** [comment]
Ya, we can do that

**Comment by qrcoder** [comment]
:-)

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1194

**Comment by menny** [comment]
Will be available in ALPHA channel later today, and BETA channel later this week.
