### ISSUE TITLE
Shift button doesn't go off in latest beta

### ISSUE THREAD

**Issue by Tahvok** [AnySoftKeyboard/AnySoftKeyboard#1060]
### Steps to reproduce
1. Click on shift
2. Press any key
3. The shift stays there, and doesn't go off

### Expected behaviour
Shift should go off by itself after first key press

### Actual behaviour
The shift stays on

**Android OS version:**
Latest lineageos

**Device manufacturer and model:**
zte axon 7

**List of installed add-ons (like languages, or themes):**
hebrew and russian keyboards

**Comment by menny** [comment]
Which version are you running? I fixed a similar issue, but that may not have been released to _beta_ yet.

**Comment by Tahvok** [comment]
on latest beta: 1.8.1182 2507

**Comment by menny** [comment]
I see. I pushed a new beta, you should see an update shortly. Please verify it is fixed

**Comment by Tahvok** [comment]
Nop, not fixed unfortunately

**Comment by menny** [comment]
Do you long-press the SHIFT?

**Comment by Tahvok** [comment]
Of course not, I've read the changelog.
Anyway, I've figured the problem. I have multitap timeout set to disabled.
If I set it to any other value, the shift is working fine! So is it a bug, or intended behaviour?

**Comment by ragcsalo** [comment]
I have the same problem...
I have also disabled multitap timeot, because I often write 3 dots (...) quickly in a row, and it only can be done if you disable multitap timeout.
So I think SHIFT key locking when multitap is disabled is a bug, should be fixed. :-)

**Comment by menny** [comment]
Will roll out a fix shortly.
You can subscribe to the beta channel to get it faster.
