### ISSUE TITLE
[feature request] option to resize keys 

### ISSUE THREAD

**Issue by kilroythe5th** [AnySoftKeyboard/AnySoftKeyboard#1068]
Since most peoples typing patterns don't occur in straight lines, it would be nice to be able to resize/move keys
![img_20170710_233414](https://user-images.githubusercontent.com/20712758/28387043-6ae729d4-6c82-11e7-9086-2469aa4149eb.jpg)

**Comment by menny** [comment]
Can you explain more about this request?
Also, what is the source of this image?

**Comment by kilroythe5th** [comment]
The image is a Swiftkey heatmap. Due to the patterns that happen, it would be useful to be able to resize or shift keys to reduce errors.

**Comment by kilroythe5th** [comment]
Interestingly, the curve visible in the heatmap is common enough that "ergonomic" keyboards look a lot like that
