### ISSUE TITLE
Autotext not working for Dutch Language Pack

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#1069]
Autotext is not working for Dutch Language Pack. in the autotext XML file is the e.g. the entry:

    <word src="gewandeldt">gewandeld</word>

but when I type `gewandelt`, it doesn't change to `gewandeld`. Can someone confirm this and point how to fix this?

**Comment by menny** [comment]
Is the latest release in Play Store?

**Comment by PanderMusubi** [comment]
Yes

**Comment by menny** [comment]
@PanderMusubi this is fixed?
