### ISSUE TITLE
Where is specific suggestion originating from

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#1070]
This can be tested with the Dutch Language pack. The dictionary contains `gin` (correct) and `tonic` (correct) but not `gin-tonic` (correct) and not `gintonic` (incorrect). When I type `gintonic`, the active suggestion is `gint-tonic`.

Now, all my personal word lists in the ASP app are all empty and I have disabled using the fallback User-dictionary. I am wondering where this suggestion originates. Even though it is correct, I still want to be in control what gets suggested and what not. Can someone reproduce and explain this?

**Comment by menny** [comment]
I don't see this at all.

We can add a log output (in debug builds) which print to logcat each suggested word and its source.
Will that be okay?

**Comment by PanderMusubi** [comment]
@menny yes, such debug function would be desireable
