### ISSUE TITLE
Return key not complete shown

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1073]
Minor problem
### Steps to reproduce
1. fill in an URL in firefox browser
2.
3.

### Expected behaviour
Tell us what should happen
Complete keyboard

### Actual behaviour
Tell us what happens instead
The  red Return key right under isn't shown complete, see:
![screenshot_20170720-200355-2](https://user-images.githubusercontent.com/25467829/28434055-5245f93e-6d8e-11e7-8aa8-e605276a70cb.png)

**Android OS version:**
7.0

**Device manufacturer and model:**
Samsung Galaxy S7

**List of installed add-ons (like languages, or themes):**
Dutch Language

**Comment by menny** [comment]
Which theme are you using?
And can you verify that for other themes?

**Comment by Joppla** [comment]
I'm using the normal light theme with old school for the lowest row.
-- 
Met vriendelijke groet,
Jop
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Joppla** [comment]
PS. An other theme has the same. Another lowest row not.

**Comment by deu13434** [comment]
I just want to add that I have the same problem, "Old School" row + Firefox 56. Other apps don't seem to show that problem. See screenshots in #1145.

Android OS version:
8.0

Device manufacturer and model:
Sony Xperia XZ1 Compact

List of installed add-ons (like languages, or themes):
German language

**Comment by menny** [comment]
Is any of you used the zoom/scale factor to change the height of the keyboard?

**Comment by deu13434** [comment]
No, I don't use that feature. The factor is set to 1.0 for portrait and landscape mode (which by the way both show the same problem).

@menny is the problem not showing up for you while using Firefox? As @Joppla is using a completely different device and OS version than me, I'd guess the bug should be rather easy to trigger using any phone with Firefox.

**Comment by menny** [comment]
Okay, I found the issue.
It will be fixed with the next release, and in the next beta.
