### ISSUE TITLE
 Caps Lock Non-functional When Already Capitalized

### ISSUE THREAD

**Issue by efwb001** [AnySoftKeyboard/AnySoftKeyboard#1078]
Reopening https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1037 as it is still an issue after the update, and affects the new 'long-press' method as well.

### Steps to reproduce
1.  Make sure capitalization is turned on for the next letter (as it often is at the start of a sentence, start of a text field, or when you hit the shift key once).
2.  Either double-tap _or long-press_ the shift key.

### Expected behaviour
The keyboard should enter caps-lock (all letters will be capitalized until you hit the capitalization/shift key again).

### Actual behaviour
The gesture is ignored; nothing happens. If you long press, the app registers it as a short press. If you double-tapped, the app registers it as two slow single taps (turns to lower case, then turns back to capital letter mode.

**Android OS version:**
5.1

**Device manufacturer and model:**
Moto X 2nd gen

**List of installed add-ons (like languages, or themes):**
Nothing but the defaults for US English.

**Comment by HoWilgh** [comment]
I would also expect that the first letter can be changed from lower to upper case and back again. ... simply by selecting the word and hitting the caps/shift key.
Thanks in advance.
