### ISSUE TITLE
No suggestions/dictionnary since 1.8.844

### ISSUE THREAD

**Issue by tuxayo** [AnySoftKeyboard/AnySoftKeyboard#1080]
Happens on 1.8.844 but not on 1.8.735
Build: F-Droid

### Steps to reproduce
1. Update the app from 735 to 844
2. Open an app with a text field
3. Type 'test'

### Expected behaviour
There should be suggestions

### Actual behaviour
There are no suggestions

**Android OS version:**
4.1.2

**Device manufacturer and model:**
Wiki CINK PEAX 2

**List of installed add-ons (like languages, or themes):**
Esperanto
French
Spanish
All from F-Droid

**Logs**
https://framagit.org/snippets/610
There is a lot of garbage.
It's been collected using `adb logcat '*:V'`
Is there a way to reduce the noise without missing things?

It was done at the first start after update, that's why the app is killed in the beginning of the logcat:
https://framagit.org/snippets/610#L719

**Comment by tuxayo** [comment]
Still happens with 1.8.1241

**Comment by canaaerus** [comment]
Works for me in 1.8.1333. Do you still experience the issue?

**Comment by tuxayo** [comment]
Can't reproduice anymore with1.8.1241 (it works) and 1.8.1333 works.

There must have been also an external factor.

**Comment by menny** [comment]
thanks for reporting back
