### ISSUE TITLE
Black keys on black background in horizontal position

### ISSUE THREAD

**Issue by Knysliux001** [AnySoftKeyboard/AnySoftKeyboard#1081]
### Steps to reproduce
1. Turn the phone on it's side
2. Bring up the keyboard in horizontal view
3. Bottom half of the keyboard comes up black with black letters intermittently (not every time)
4. Impossible to type, switching to vertical and back to horizontal fixes the theme

### Expected behaviour
Normal theme based picture

### Actual behaviour
Bottom half of the keyboard turns black
http://tinypic.com/r/2gtb0bc/9
**Android OS version:**
7.0
**Device manufacturer and model:**
vernee Model:thor
**List of installed add-ons (like languages, or themes):**
Selected standard minimal light theme, no add-ons
Languages: selected Lithuanian, English, SSH

**Comment by AnXh3L0** [comment]
Hello there @Knysliux001, does this still happen for you in the latest ASK version? I couldn't manage to reproduce this bug on my device.

**Comment by Knysliux001** [comment]
The device listed is no longer working and the one I have now is on a different OS version and works flawlessly.
Cannot reproduce it myself, closing.
