### ISSUE TITLE
Feature matrix for also competing keyboards

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#1083]
Perhaps first in the wiki in GutHub and later on the website, make a eature matrix for AnySoftKeyboard which also lists competing keyboards.

Make a clear distinction between from a FOSS point of view features and anti-features such as your personal usage, words or even texts are send to a server in order to improve the app but at the same time for a security issue.

A fair overview of features and also to see where AnySoftKeyboard is lacking and how to solve that.

**Comment by AnXh3L0** [comment]
Since the new website refresh a while back, I think the ASK features are easier to discern. I will work on also adding a feature comparision to the website soon. Closing this for now.

**Comment by Jonta** [comment]
@AnXh3L0 Status? =)
