### ISSUE TITLE
4 characters deleted after a smiley inserted & backspace pressed

### ISSUE THREAD

**Issue by ragcsalo** [AnySoftKeyboard/AnySoftKeyboard#1086]
### Steps to reproduce
1. I insert a smiley by pressing the SMILEY button (smiley is 4 characters long)
2. I go back in the sentence and try to delete one character
3. 4 characters are deleted instead of one

### Expected behaviour
Only 1 character should be deleted when I press the backspace button!

### Actual behaviour
4 characters are deleted instead of one...

**Android OS version:**
7.0

**Device manufacturer and model:**
Samsung Galaxy S7 Edge

**List of installed add-ons (like languages, or themes):**
Hungarian add-on

So in detail:
I have set the smiley button to display a ":-) " smiley with one space at the end (4 characters total).
When I press the backspace button, the app tries to be too smart.... it remembers that I inserted a smiley (4 characters long), so it deletes 4 characters. This is no problem if I try to delete the smiley... But is's a problem when I go back in the sentence to correct a word, and 4 characters will be deleted instead of one!!! I hope you understand the problem... The backspace button should delete only 1 characters, always... If I want to delete the smiley, I will press it 4 times, no problem. :-)

**Comment by menny** [comment]
I am unable to reproduce this.
Can you share a video of this issue?

**Comment by ragcsalo** [comment]
Sure, I try to attach the screen recording. :-)

  ASK_bug_smiley.mp4
<https://drive.google.com/file/d/0ByW-iob86LG5OUVoTzR1UVR3ZXM/view?usp=drivesdk>

**Comment by ragcsalo** [comment]
So again: this bug only occurs if I insert a custom smiley (settings - even more - tweaks - smiley text) by pressing the smiley key (bottom left). The smiley text is 4 characters long: ":-) ". The app is smart, and remembers that I've inserted a 4-character long smiley, so when I hit the backspace button, it assumes I'm deleting the smiley, so it deletes 4 characters. BUT if I don't want to delete the smiley, instead I go back and want to delete another character, it stilldeletes 4 characters! So some more AI tweaking is necessary... :-) I suggest that the backspace key should always delete 1 character only, even if I inserted a smiley...

Thanks for responding to the bug report so quickly!!! :-) I hope you can solve this soon. :-)

**Comment by menny** [comment]
Are suggestions disabled?

**Comment by ragcsalo** [comment]
Yes... but that doesn't have to do anything with this bug, does it?
This bug is a simple smart function which has to be disabled....
You still can't reproduce the bug? :-O

**Comment by menny** [comment]
I can only reproduce it with suggestions set to _off_.

I have a fix here: https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/581837d67f1971d1c5c388417472273d889bab2a

**Comment by menny** [comment]
I'll start a release process around this.

**Comment by ragcsalo** [comment]
Oh I see, so this is related to suggestions. Well, it's a good start if you can reproduce this... :-)
Waiting for the fix! :-)

**Comment by menny** [comment]
Will roll this out to production tomorrow
