### ISSUE TITLE
SHIFT key also locked when short pressed (multiple touches turned off)

### ISSUE THREAD

**Issue by ragcsalo** [AnySoftKeyboard/AnySoftKeyboard#1087]
### Steps to reproduce
1. I press the SHIFT key to enter an Uppercase letter
2. SHIFT will stay turned on (CAPS)
3. I have to turn it off by pressing it again

### Expected behaviour
Short pressing SHIFT key shouldn't lock CAPS mode.

### Actual behaviour
Short pressing SHIFT key locks CAPS mode.

**Android OS version:**
7.0

**Device manufacturer and model:**
Samsung Galaxy S7 Edge

**List of installed add-ons (like languages, or themes):**
Hungarian add-on

So I have turned off multiple touches, because I often write 3 dots in a row (...) so I press the dot quickly 3 times... this can't be done if multiple touches are enabled. BUT if this feature is turned off, short pressing the SHIFT key will lock CAPS mode!!! Which is very annoying... So please correct this bug, so when I short press the SHIFT key, it should not stay locked! Thanks! :-)

**Comment by menny** [comment]
Where and how did you disabled multiple touches?

**Comment by ragcsalo** [comment]
Settings - Fine tuning - Behaviour fine tuning - Speed of multiple touches: set to Disabled
(As I'm using the Hungarian add-on, I could only send a Hungarian screenshot...)
