### ISSUE TITLE
hide input vocal button to maximize space-bar

### ISSUE THREAD

**Issue by giupardeb** [AnySoftKeyboard/AnySoftKeyboard#1098]
Hello everybody, why don't allow us to hide input vocal button (that I don't use) to maximize space-bar?

Thank you

**Comment by yaomtc** [comment]
I would also like this, I never use voice input. Surprised this isn't already an option. SwiftKey has it hidden under the comma key.

**Comment by schodet** [comment]
Did you try the setting in UI -> Tweaks and more -> Common bottom generic row ?

**Comment by eladhen** [comment]
> Did you try the setting in UI -> Tweaks and more -> Common bottom generic row ?

As of current version (1.10.606) this feature isn't available. It used to be, and I can still restore it from a settings backup from older versions, but this is really a problem. Having a key that takes space and when pressed by mistake takes you into a different interface is a problem.

**Comment by Dpunkt** [comment]
Please fix this. The ability to customize "my" keyboard to remove strange buttons was one  of the main reasons to use this Keyboard.

**Comment by menny** [comment]
`UI -> Tweaks and more -> Common bottom generic row` should be visible for 1.10.606.
In any case, the next release is rolling out right now.

**Comment by menny** [comment]
can I close this issue? As there is an option to switch to a row that does not have the mic.

Also, we have a ticket to allow editing of those rows.

**Comment by Dpunkt** [comment]
This option works for me, issue can be closed.
