### ISSUE TITLE
Odd symbols when using copy/paste in Telegram

### ISSUE THREAD

**Issue by Aiurek** [AnySoftKeyboard/AnySoftKeyboard#1116]
ASK Version 1.8.1333 (2658)
Lenovo Moto G4 plus, Android 7.0

The keyboard is illustrating very strange characters instead of the words 'copy' and 'paste' while copying or pasting stuff in Telegram. So far, I haven't recognized this issue outside of Telegram.

![photo_2017-09-10_16-31-26234](https://user-images.githubusercontent.com/27865200/30249933-ff5e3f16-95fa-11e7-8e74-9bf1ae6863da.jpg)

**Comment by rickkode** [comment]
I also have this problem, same device too.

**Comment by menny** [comment]
That's strange.. do you override the locale in ASK? Does it happen if you use a different keyboard app?

**Comment by rickkode** [comment]
I got it fixed by installing another language in telegram, I got koffagram

**Comment by huehnerlady** [comment]
@rickkode how do you install another language in telegram?

**Comment by AnXh3L0** [comment]
Does this happen anymore for you @Aiurek in the latest version of ASK?

**Comment by jwsp1** [comment]
this is not an issue of ASK. It was an issue of koffagram. I've tested it several times and have no malfunction. I think this issue can be closed.

**Comment by AnXh3L0** [comment]
Ok then, closing the issue.

**Comment by Aiurek** [comment]
Sorry for the late reply @AnXh3L0 ...
Unfortunately the issue is still there :/ I'm still using ASK but it's still annoying to me, although I got kinda used to it...
I'm using the current play store version of ASK and Telegram

![photo_2020-06-08_23-23-56](https://user-images.githubusercontent.com/27865200/84081932-2dd5aa00-a9df-11ea-965b-4d51af69095a.jpg)

**Comment by Aiurek** [comment]
@kojid0 I've never used koffagram...
It's only there with ASK, not there with any other keyboard -.-
