### ISSUE TITLE
Backup next word suggestions

### ISSUE THREAD

**Issue by matthias-g** [AnySoftKeyboard/AnySoftKeyboard#1117]
Is there a way to backup the learned data for the next word suggestions?

If I understand [this](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/nextword/src/main/java/com/anysoftkeyboard/nextword/NextWordsStorage.java) correctly the suggestions are stored in an internal file. Is it possible to store these outside the app, too? And to import them later?

**Comment by menny** [comment]
Been implemented, and will be released with 1.9-r2

**Comment by matthias-g** [comment]
:+1: Thank you!
