### ISSUE TITLE
Intent protocole to delegate input to third-party apps

### ISSUE THREAD

**Issue by ezzarghili** [AnySoftKeyboard/AnySoftKeyboard#1118]
### Intent protocole to delegate input to third-party apps

The goal of the intent protocole is to provide an api for integrating third-party apps IME in ASK.

This protocole will allow the community to create applications with some special IME reading capabilities (e.g. barcode scanning, NFC reader, GIF,  image input ...Etc) and return the data to ASK to set the input.

**Comment by nitrocode** [comment]
@menny only reason I haven't switched to this awesome keyboard is because I cannot send gifs like I can with the google keyboard :(

**Comment by menny** [comment]
This idea has been on my wishlist for a very long time, but. .... lack of time.
I will create this API.

**Comment by nitrocode** [comment]
@menny any update? 😄 

Also commenting due to the bot planning to close this ticket.
