### ISSUE TITLE
BUG: keyboard shrinks to half size (horizontally(

### ISSUE THREAD

**Issue by nine7nine** [AnySoftKeyboard/AnySoftKeyboard#1124]
### Steps to reproduce
1. open keyboard to write (in any app)
2. use three fingers and start mashing on keys

### Expected behaviour
the keyboard shouldn't shrink/scale down smaller and just type out input.

### Actual behaviour
keyboard shrinks/scales to half size horizontally. I have to restart anysoftkeyboard to get the normal (full-sized) keyboard back.

**Android OS version: Android 8.0 Oreo (although it occurs on 7.1.1 too).

**Device manufacturer and model: Google Pixel (Sailfish)

**List of installed add-ons (like languages, or themes): Lean dark theme

**Comment by menny** [comment]
You have activated one (or several) of the condense gestures.
You can reset that state by opening the _Utility Keyboard_ (swipe up from the space-bar), and click the _FULL KEYBOARD_ icon (bottom, fourth from the left).

You can also cancel those gestures by going to the settings app configure the gestures to _None_.
