### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#1125]
Created by @1jr

**Comment by menny** [comment]
Examples: 
![](https://imgur.com/HbqPioA.png)
![](https://imgur.com/hyAJ1th.png)
![](https://imgur.com/r3kqlQC.png)
![](https://imgur.com/rHV0j6r.png)

**Comment by maverick74** [comment]
Looks awesome :D

**Comment by menny** [comment]
I think so too. But I still need some help from @1jr to be able to incorporate it into the app.

**Comment by 1jr** [comment]
![ask-squircle](https://user-images.githubusercontent.com/11556789/30693055-3696e2ea-9ece-11e7-8f74-c9e44e3588a8.png)

![swedish-squircle](https://user-images.githubusercontent.com/11556789/30693060-3a429754-9ece-11e7-97e5-3a076e1d77ff.png)

**Comment by 1jr** [comment]
I'm more than willing to help if you tell me what to do. :)

**Comment by menny** [comment]
@1jr thanks.
For the first step, I need the background image.
According to https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
The background is 108x108dp.
I'll need that for mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi densities:
mdpi | @ 108.00dp | = 108.00px
hdpi | @ 108.00dp | = 162.00px
xhdpi | @ 108.00dp | = 216.00px
xxhdpi | @ 108.00dp | = 324.00px
xxxhdpi | @ 108.00dp | = 432.00px

Or, if you can create an SVG of that background, that should work too, and I can use that for all densities.

**Comment by menny** [comment]
I think it is best if you can create the two versions (purple and gray).

Thanks!

**Comment by 1jr** [comment]
[Icons.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/1324031/Icons.zip)

**Comment by 1jr** [comment]
The zip contains two SVGs, one gray and one purple. The foreground and background are separated into different layers.

**Comment by 1jr** [comment]
![ask-2-squircle](https://user-images.githubusercontent.com/11556789/30740054-cddf2a10-9f8f-11e7-99b0-b1ad5a39541e.png)
![ask-2-squircle-gray](https://user-images.githubusercontent.com/11556789/30740053-cddf0d00-9f8f-11e7-8b9c-6f11c16482a9.png)

**Comment by 1jr** [comment]
Two more versions. The second gray version doesn't use flags as some languages (like arabic) doesn't have a flag.

**Comment by 1jr** [comment]
![ask-2 1-squircle](https://user-images.githubusercontent.com/11556789/30740299-c2c0d650-9f90-11e7-9789-a89055925d93.png)

**Comment by 1jr** [comment]
![ask-2-squircle-ssh](https://user-images.githubusercontent.com/11556789/30740619-08dd8dee-9f92-11e7-89b9-20802d795786.png)

The latest design is easy customizable for other types of addons as well. This is a mockup of the SSH keyboard layout.

**Comment by friesenkiwi** [comment]
I think, it is a good fallback alternative to have the 3-letter-code space, but for most packs/languages a flag will be available and very helpful to recognize for the users. Could you try a version with flag?

**Comment by 1jr** [comment]
![4 5 swe-circle](https://user-images.githubusercontent.com/11556789/30741988-7e690e94-9f97-11e7-8502-a58f92d23ef7.png)
![4 6 mkd-circle](https://user-images.githubusercontent.com/11556789/30741989-7e6d1cf0-9f97-11e7-98b6-54bac612477b.png)
![4 7 usa-circle](https://user-images.githubusercontent.com/11556789/30741987-7e68eb26-9f97-11e7-8b42-2ba841f62811.png)

Placing flags without distortion when the borders are flexible is really hard. The only safe Place is in the center. Here are preview versions for Swedish, Macedonian and US-English.

**Comment by 1jr** [comment]
The flags are resized to the height of the keyboard row and centered horizontally. As the colors of the flags are very different from one another the background is painted in shades of gray.

**Comment by 1jr** [comment]
The SVGs for the later version.
[V4.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/1426799/V4.zip)

**Comment by menny** [comment]
@1jr I'm ready to work on the icon now.

A few ideas:
I have to say that I like the background you use at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1125#issuecomment-331126718
I want you to tweak it a bit: instead of having uniform squares, I would like something that is more like a  QWERTY keyboard, in the sense that the keys are offset a bit between rows. Something like we have in the current logo (https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/StoreStuff/ask_logo.png). One thing that I don't like in the current logo is that the keys are not the same size.

**Comment by Something2** [comment]
New icon looks real nice.
But I'm confused. Is it "Ask keyboard" or AnySoft keyboard?

**Comment by p3732** [comment]
So I had this idea of integrating the name into the keyboard and went ahead to try it out
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/ask.svg.png)
I also tried to make a localized version, by putting a flag where the globe (for switching keyboard layouts) is usually placed
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/ask_sv.svg.png)
The .svg files are in ![my repo](https://github.com/p3732/various/tree/master/ASK_logo).

I am no quite happy with it yet, but I think the idea could work. Any thoughts?

**Comment by p3732** [comment]
I took some design inspirations from this thread and @1jr's minimalistic designs:
-no '3D' shade
-no outer boundry
-gradient as background
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/ask_minimal.svg.png)
Liking this one a lot more.

**Comment by Something2** [comment]
I like it too.

**Comment by menny** [comment]
@p3732, I like this:
![image](https://user-images.githubusercontent.com/481272/41744485-e0721d1e-7571-11e8-9fd4-45ba562f69fe.png)

I have a few requests:
1) can you use our accent color for the keys? Or for the `ASK` letter? The color is #663399
2) In newer versions of Android, we need to use a layer-icon (https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/res/mipmap-anydpi/ic_launcher.xml). Which means we are breaking the icon into background (which can be the gradient), and a foreground. Can you provide me with those?

Thanks! Awesome work.

**Comment by p3732** [comment]
I tried both variants, accent on keys and accent on logo:
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/font_accent/ask_minimal_accent_font.svg.png)
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/keys_accent/ask_minimal_accent_keys.svg.png)
I don't really have a preference with those, but when placing a flag for localisations:
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/font_accent/ask_minimal_accent_font_sv.svg.png)
![](https://raw.githubusercontent.com/p3732/various/master/ASK_logo/keys_accent/ask_minimal_accent_keys_sv.svg.png)
I do prefer the upper, brighter variant.

**Comment by p3732** [comment]
According to the ![adaptive icon design guideline](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) the icons should be of size 108x108 dp (![not px](https://stackoverflow.com/questions/2025282/what-is-the-difference-between-px-dip-dp-and-sp)) with 18 dp empty on each site. Here are the links to 512x512px images, that can be made into adaptive icons following ![this guide](https://developer.android.com/studio/write/image-asset-studio#create-adaptive):
![gradient](https://github.com/p3732/various/blob/master/ASK_logo/ask_minimal_accent_gradient.svg.png)
![accent on logo](https://github.com/p3732/various/blob/master/ASK_logo/font_accent/ask_minimal_accent_font_foreground.svg)
![accent on keys](https://github.com/p3732/various/blob/master/ASK_logo/keys_accent/ask_minimal_accent_keys_foreground.svg.png)

**Comment by maverick74** [comment]
I prefer the 2nd.
However, i believe the flag will became too small to be noticed on the icon.
Maybe using 2 "key-lines"...

**Comment by AnXh3L0** [comment]
Hello @menny,
In my opinion this icon works best on the squircle. Can we maybe try to make the content a bit smaller in the other adaptive shapes?

**Comment by maverick74** [comment]
@menny
I like them! I tend to prefer number 4 fallowed closely by number 2.

How will this work for language packs - the ones with the flags? Do you have any test on that already?

I agree with @AnXh3L0 on number 5. Because the outer shape is not symmetric, I think content should be a bit smaller...

**Comment by menny** [comment]
Building: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1501

**Comment by AnXh3L0** [comment]
We have a new app icon merged, closing this issue.
Marked as solved.
