### ISSUE TITLE
The Jawi Keyboard

### ISSUE THREAD

**Issue by faizthefreelancer** [AnySoftKeyboard/AnySoftKeyboard#1129]
### Steps to reproduce
1. Making new layout or new language the jawi keyboard. The Jawi Keyboard it like arabic font but it has extra fonts example : ݢ ۏ ڽ ڤ چ ڠ ‌‌٢
2. This link for your guys making the example what it like the jawi keyboard and font. 
[ https://drive.google.com/drive/folders/0B7F-FYj9_qaTZW9sZkZveUhPQmM?usp=sharing ]
This program for windows, you guys must install it and enjoy for new language font but it better for touchscreen laptop  :D

### Expected behaviour
This Jawi keyboard will making a perfect boom for your apps anysoftkeyboard. 

### Actual behaviour
Nice and Perfect New Languages Boom

**Android OS version:**
Yes, Android OS

**Device manufacturer and model:**
All Model Android Device

**List of installed add-ons (like languages, or themes):**
The Jawi Language Keyboard

**Comment by menny** [comment]
That sounds like a great idea.
Please open this issue at https://github.com/AnySoftKeyboard/LanguagePack/issues where we track language-packs.

Thanks.
