### ISSUE TITLE
enlarge the keyboard

### ISSUE THREAD

**Issue by wilfried18** [AnySoftKeyboard/AnySoftKeyboard#1136]
Hello
I have a problem, it seems to me that before I could enlarge the keyboard for a person with health concerns.
But I can not find any more
Thank you
I tried on different phone (xiaomi mi max, zuk z1 leeco lemax2)

**Comment by menny** [comment]
You can find that in the Theme tweaks page. Go to the Themes page, and
click the overflow menu at the top right. Pick "Tweaks". In the Tweaks
page, scroll down to "Height factor"

**Comment by wilfried18** [comment]
Can you make screenshots (I use it in French)

**Comment by ArenaL5** [comment]
I can enlarge the keyboard just fine, as per @menny instructions:

![Screenshot_20191106-015641](https://user-images.githubusercontent.com/37388405/68259067-b7c82980-0030-11ea-87ae-4dd6a7ff246d.png)

If this used to be a bug, it was probably fixed within these two years.

**Comment by AnXh3L0** [comment]
This bug has been fixed in the past. Closed as fixed.
