### ISSUE TITLE
[Question] repeatable key and longpress key could not be one key?

### ISSUE THREAD

**Issue by suntabu** [AnySoftKeyboard/AnySoftKeyboard#1140]
I wanna make the delete key : 
When single tab, delete characters one by one;
When longpress, delete words one by one.

But when I add 
 ask:longPressCode="-7"
```
<Key android:keyWidth="15%p" android:codes="-5" ask:longPressCode="-7" android:keyEdgeFlags="right" android:isRepeatable="true"  ask:isFunctional="true"/>
```
to my qwerty.xml file. The long press key could only run once, not repeat as I expect.

**Comment by suntabu** [comment]
Problem solved!

**Comment by menny** [comment]
Great. Want to share your solution?
Also, holding SHIFT and delete will delete a word.

**Comment by suntabu** [comment]
@menny Ok,I'll submit a pull request later.

**Comment by suntabu** [comment]
@menny I've submited #1142 PL

**Comment by menny** [comment]
Thank you
