### ISSUE TITLE
How to change Theme without hideWindow & showWindow

### ISSUE THREAD

**Issue by suntabu** [AnySoftKeyboard/AnySoftKeyboard#1153]
When changing to a new theme, the old view is removed and a new one is created to be added into the keyboard container.
Is there a way changing the theme by replacing resources of the keyboard and invalidating view?

**Comment by menny** [comment]
I guess it is possible, but it was easier to start clean :)

I would guess that calling `AnyKeyboardViewBase#resetKeyboardTheme` with new Theme details will reset the Theme values and for a re-draw

**Comment by suntabu** [comment]
Ok, I'll have it a try.
