### ISSUE TITLE
[QUESTION] Chosen Theme - how it is set, stored and retrieved?

### ISSUE THREAD

**Issue by gnomex909** [AnySoftKeyboard/AnySoftKeyboard#1156]
Hello,
I'm trying to wrap my head about ASK, but one thing escapes my grasp. I can quite easily find and see moment of change of all the other settings, but i can't find what method is used to set a Theme, where (and how) it is stored, and then from where it is retrieved.

I will be really glad for any hints or explanations.

Have a nice day :)

**Comment by menny** [comment]
A `Theme` is an Add-on: a set of resources, grouped by a styleable.

All the _Addons_ in the system have the same life-cycle. Check out `AddOnsFactory` for base implementation, and `AddOnImpl` for the base implementation for all addons (including Theme).

**Comment by gnomex909** [comment]
Huge Thanks!
I failed hugely by not looking at extended classes. Now i found what I desired to know and made changes. 
I wish you happy halloween and carry on with good job :)
