### ISSUE TITLE
In UI settings you can't change keyboard effects and tweak settings

### ISSUE THREAD

**Issue by ashirviskas** [AnySoftKeyboard/AnySoftKeyboard#1167]
### Steps to reproduce
1. Open AnysoftKeyboard
2. Go to UI tab -> Keyboard effects and experience
3. Clicking on 1st and 3rd option does nothing. It also shows "<option specific text>. Currently: %s"

**Android OS version:**
7.0
**Device manufacturer and model:**
LG G6, H870
**List of installed add-ons (like languages, or themes):**
Lithuanian language pack.

**Comment by ashirviskas** [comment]
Here's a screenshot:

https://ibb.co/hqLwLw

**Comment by menny** [comment]
thanks for reporting
