### ISSUE TITLE
White rectangle on statusbar when keyboard is enabled.

### ISSUE THREAD

**Issue by worg** [AnySoftKeyboard/AnySoftKeyboard#1173]
### Steps to reproduce
1. Install version 1.9.503 from play store [AnySoftKeyboard Canary]
2. Enable it
3. Switch between apps with keyboard input

### Expected behaviour
Status bar should not display a white rectangle
####  Screenshot with GBoard
<img title="gboard" width="60%" src="https://image.prntscr.com/image/BBYbIU24R22QEOhL_K3kZg.jpg" />

### Actual behaviour
Status bar displays a white rectangle when ASK is enabled
####  Screenshot with ASK Canary
<img title="ask" width="60%" src="https://image.prntscr.com/image/j-SkC7X2Q9ulgcPu8syFJw.jpg" />

**Android OS version:**
7.1.2

**Device manufacturer and model:**
Xiaomi A1

**List of installed add-ons (like languages, or themes):**
Spanish Language Pack

**Comment by menny** [comment]
Can you share a screenshot?

**Comment by worg** [comment]
Sorry I edited the issue after submitting, I assume you're replying from email, here is a screenshot [also attached to the issue now, along with a screenshot of gboard not showing the same behavior]
https://image.prntscr.com/image/j-SkC7X2Q9ulgcPu8syFJw.jpg

**Comment by menny** [comment]
I wonder, do you have "Show keyboard icon in status-bar" enabled? Look for that checkbox under UI->tweaks

**Comment by worg** [comment]
Yes, unchecking that option removes the white rectangle.
This is a new install, I changed phone recently, so I wanted to keep my settings and trying to do so I found an unrelated issue: some settings can’t be modified, here is a screenshot https://image.prntscr.com/image/8TFJ4MeyT0_6uqQA--CeiQ.jpg

**Comment by menny** [comment]
The issue in the last screenshot was fixed a short while ago, and you can check out the latest ALPHA to see if it fixed for you too.

**Comment by worg** [comment]
Thanks!
Where can I get the alpha?

**Comment by menny** [comment]
You can get the latest alpha by subscribing to the Google+ community https://plus.google.com/communities/106050362696748221135 and then opt-in to Alpha release by visiting https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard

**Comment by menny** [comment]
Regarding the white rectangle, which languages do you have enabled on your AnySoftKeyboard, and which locale is your phone set to?

**Comment by worg** [comment]
I have enabled English and Spanish on AnySoftKeyboard, my phone locale is set to English

**Comment by AnXh3L0** [comment]
This issue has been fixed, closing.
