### ISSUE TITLE
Key popups appear at the top of the screen

### ISSUE THREAD

**Issue by Likivik** [AnySoftKeyboard/AnySoftKeyboard#1177]
Key popups appear at the top of the screen, instead of right on top of the key.
Both in beta and stable.
Snapshot:
![screenshot_20171129-235942](https://user-images.githubusercontent.com/11075952/33403675-56377b98-d572-11e7-8952-e9d29bb53bab.png)

Xiaomi Redmi 3
LinageOS 14.1 + (GAPPS pico)
add-ons:
-Russian Language Pack

**Comment by menny** [comment]
Is this still an issue for you?

**Comment by Likivik** [comment]
Nah, my bad, deleted, rebooted, installed again and now it works properly!
