### ISSUE TITLE
Gesture typing not switching along keyboard language

### ISSUE THREAD

**Issue by suntabu** [AnySoftKeyboard/AnySoftKeyboard#1178]
### Steps to reproduce
1. Install some language packs
2. Gesture Type some characters
3. Not suggested with the selected language words
### Expected behaviour

When switching language keyboard, gesture typing suggestion also switched

### Actual behavior
Gesture typing not switching along keyboard language

**Comment by menny** [comment]
This is now fixed on the Alpha channel.
