### ISSUE TITLE
Android Oreo ROM integration

### ISSUE THREAD

**Issue by phhusson** [AnySoftKeyboard/AnySoftKeyboard#1184]
Hello,

I'm trying to make an usable opensource Android ROM, which would integrate AnySoftKeyboard as primary IME.
Currently this doesn't work, even if AnySoftKeyboard is the only IME, it won't be enabled by default.

As far as I can tell, you'd need to add many subtypes as LatinIME does:
https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/java/res/xml/method.xml

AOSP's framework's selection is done here:
https://android.googlesource.com/platform/frameworks/base.git/+/master/core/java/com/android/internal/inputmethod/InputMethodUtils.java#360

What's your recommendation there?
Thanks

**Comment by menny** [comment]
1. I don't think I it's a good idea to add all those sub-types without actually supporting them.
2. ASK should say it supports a given subtype if the language/layout is enabled. This, of course, includes English by default.
3. I see that in the code that you pointed to, the check is specifically about ENGLISH. Have you tried to add a static EN subtype for AnySoftKeyboard?

I'm here to help you get ASK into the ROM you are building.

**Comment by phhusson** [comment]
Ah, I didn't notice it would always fallback to english, thanks for the pointer.
I'll try that, thanks

**Comment by menny** [comment]
Also, I would try changing ASK's `method.xml` file to something like this:
```
<input-method xmlns:android="http://schemas.android.com/apk/res/android"
    android:isDefault="false"
    android:settingsActivity="com.anysoftkeyboard.ui.settings.MainSettingsActivity"
    android:supportsSwitchingToNextInputMethod="true">
    <subtype
        android:icon="@drawable/ic_stat_en"
        android:imeSubtypeExtraValue="c7535083-4fe6-49dc-81aa-c5438a1a343a"
        android:imeSubtypeLocale="en"
        android:imeSubtypeMode="keyboard"
        android:isAsciiCapable="true"
        android:label="@string/eng_keyboard"
        android:languageTag="en" />
</input-method>
```
I'll update _master_ with it as well.
