### ISSUE TITLE
[Feature Request] Treat ’ like ' in suggestions

### ISSUE THREAD

**Issue by undergroundquizscene** [AnySoftKeyboard/AnySoftKeyboard#1188]
Could the curly apostrophe (’) be treated like a regular apostrophe (') in suggestions?

For example, I like to type using the curly apostrophe, which I access by long-pressing on the regular apostrophe key and sliding across to it. However, on some words (e.g. haven’t), the suggestion with the regular apostrophe is automatically accepted when I enter the curly apostrophe (e.g. resulting in haven't’), and then I have to undo this manually.

A basic improvement would be for the curly apostrophe not to trigger suggestions. The ideal would allow me to enable an option to make all suggestions use curly apostrophes instead of regular apostrophes.

**Comment by menny** [comment]
I can look into this. It definitely makes sense.

**Comment by menny** [comment]
@undergroundquizscene It seems harder than I expected... I mean, it's easy, but not very performant - which is a problem for a software running on phones.
I have a partial solution, but I'll need you to test it out for me. Sounds good?

**Comment by menny** [comment]
Also, how do you type that character?

**Comment by menny** [comment]
nevermind, I see that there is a simple long-press to get it.

**Comment by undergroundquizscene** [comment]
Sorry I didn’t see your last message! Thanks for looking into it, and I am definitely happy to test it out for you – what do you need me to do?

**Comment by menny** [comment]
@undergroundquizscene once the change passes - https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1203, I'll send you a link to a debug APK for you to test. Run with it for a day or two and let me know how it is.

**Comment by menny** [comment]
Please test: https://1740-4063516-gh.circle-artifacts.com/0/apks/canary/app-canary.apk

**Comment by undergroundquizscene** [comment]
@menny Sorry for the delay, just getting back to this now.

When I try to install the apk, it tells me it hasn't installed because it conflicts with an existing package by the same name – what should I do about this?

**Comment by menny** [comment]
I've started rolling out a release. You can either wait for an update from
Play Store, or if you want to test now, uninstall the version you have and
install this.

**Comment by undergroundquizscene** [comment]
Ah, I understand! I’m sorry for the slow responses :)

**Comment by menny** [comment]
No worries. It's a good idea.
