### ISSUE TITLE
Internet permission

### ISSUE THREAD

**Issue by quentinus95** [AnySoftKeyboard/AnySoftKeyboard#1193]
Hi,

The README of this repository claims:

```
STABLE release does not include the Internet permission.
```

But when going on Google PlayStore, the permission tab states:

![image](https://user-images.githubusercontent.com/8060564/33988324-5bcb6ea4-e0c4-11e7-8ab7-6df344204661.png)

So it seems that the keyboard have access to the internet after all. Can you confirm / explain where I'm wrong?

**Comment by menny** [comment]
Only the beta/alpha channel have internet access. Are you signed-up to those channels in the Play-Store?

**Comment by quentinus95** [comment]
No, I access the PlayStore without being connected to a Google account here:

https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard

When clicking on "view details" under Permissions, `full network access` is listed.

**Comment by menny** [comment]
wow... that's strange..
This is the details of the APK currently in production:
![image](https://user-images.githubusercontent.com/481272/34307902-828664a4-e718-11e7-82ba-403d83c076cf.png)

**Comment by menny** [comment]
I believe it's a bug, or something, with Play Store.

**Comment by quentinus95** [comment]
Ok, I just checked on F-Droid and everything seems OK: https://f-droid.org/packages/com.menny.android.anysoftkeyboard/

I'll download it from there. Thanks!

**Comment by menny** [comment]
makes sense. Thanks for letting me know.
