### ISSUE TITLE
Please add undo / redo to utility keyboard on marshmellow+

### ISSUE THREAD

**Issue by jeske** [AnySoftKeyboard/AnySoftKeyboard#1195]
Marshmellow+ support undo (ctrl-z) and redo (ctrl-shift-z).

Please add undo / redo keys to the utility keyboard on marshmellow+

**Comment by menny** [comment]
I couldn't find any API calls for undo/redo. I also checked to see if GBoard has that, and it seems that it does not.
Can you refer me to anywhere it is implemented? I will try to reverse-engineer that.

**Comment by jeske** [comment]
On Mon, Dec 18, 2017 at 12:21 PM, Menny Even Danan <notifications@github.com
> wrote:

> I couldn't find any API calls for undo/redo. I also checked to see if
> GBoard has that, and it seems that it does not.
> Can you refer me to anywhere it is implemented? I will try to
> reverse-engineer that.
>
You can see undo in action by installing something like "hacker keyboard"
and typing "control-z" or "control shift z".

I don't know if there are any higher level calls to inject undo events. The
system controls themselves might be hard-coded to look for the key
sequences. I also don't know what happens when using languages other than
english.

I suspect Gboard doesn't implement undo because it's not totally flushed
out yet and marketed as a working feature. That said, it is so useful that
I keep hacker keyboard installed just to I can awkwardly switch to it and
hit control-z to get back a bunch of text I laboriously wrote that somehow
gets eaten. However, the number of taps required to toggle modifier keys to
undo and redo is really awkward. Three undo operations is 6 taps on tiny
keys, and a redo is another 3 taps.

Since I most often run into the need to undo when I'm trying to do region
operations with cut/copy/paste, the AnySoftKeyboard's "utility" keyboard
seems like a great place to have undo and redo buttons, because it already
has the copy and paste actions. I also wish it had some way to to do
selection extension, for those times where the android selection handles
are confused (which happens often).

**Comment by menny** [comment]
This was a surprisingly helpful comment. I have an implementation of undo-redo that works on my phone. Can you try it on your devices?

**Comment by jeske** [comment]
Great! I'm not just an Android user, I'm a programmer, and a former Google
employee.

Yes, I can test it out.. can you email me an APK?   I have a Galaxy S8+ and
a Droid Turbo 2 to test on.

You probably want to have a setting to turn it off (in case some phone
doesn't support it), and have it auto-disable before Android 6.0
Marshmallow, as I'm pretty sure it didn't work before then.

While we are chatting.. it would also be nice if there was a to access the
utility keyboard that wasn't as error-prone was the up-swipe. For me the
up-swipe only opens the utility keyboard 15% of the time. Long press space,
or long-press the "123~#()" keyboard selector? Or even another button on
the top row with the arrows and keyboard selectors. there is plenty of room
there on my phone.

On Tue, Dec 19, 2017 at 11:25 AM, Menny Even Danan <notifications@github.com
> wrote:

> This was a surprisingly helpful comment. I have an implementation of
> undo-redo that works on my phone. Can you try it on your devices?
>

**Comment by menny** [comment]
For testing: you can download a _debug_ signed APK from here: https://1715-4063516-gh.circle-artifacts.com/0/apks/debug/app-debug.apk, or wait for the next _beta_ release tonight.

I'll limit the keys starting with Android 6.

I agree about the discoverability of the utility-popup and extension keyboard... I'm thinking about adding tool-keys to the suggestions bar (I think GBoard has something like that) and have keys to open the utility keyboard.

If you have ideas and suggestions, you can always join gitter at https://gitter.im/AnySoftKeyboard

**Comment by menny** [comment]
oh, one more thing: regarding "selection-extension", I think AnySoftKeyboard has something similar to that. Long-pressing the `Select-all` key in the utility-keyboard will allow you to fine-select around the cursor (or previously selected text) with the left&right keys.

**Comment by jeske** [comment]
On Tue, Dec 19, 2017 at 7:10 PM, Menny Even Danan <notifications@github.com>
wrote:

> oh, one more thing: regarding "selection-extension", I think
> AnySoftKeyboard has something similar to that. Long-pressing the
> Select-all key in the utility-keyboard will allow you to fine-select
> around the cursor (or previously selected text) with the left&right keys.
>
Whoa that's totally non-obvious... I gave it a try... and while it might
solve some problems, it's not that useful to me because up/down don't work.

The way I'd prefer to do this is more the way it's done on desktops... With
the cursor in a location, i'd like a button to just "begin selection" (like
holding shift on the desktop), and then I'd like to use all four arrows to
move around the other side of the selection. That way I can press down
arrow 5 times to get 5 lines, instead of holding right arrow for a year.
