### ISSUE TITLE
Could you add missing pinyin characters on long press?

### ISSUE THREAD

**Issue by vicmz** [AnySoftKeyboard/AnySoftKeyboard#1196]
Hello, 

This is not really an issue, but a request. When Chinese is written in latin alphabet, some diacritics are used to represent the tones. Some of them are already in standard AnySoftKeyboard on long press. I'm posting the list marking the missing ones in bold. Would you add them on long press?

**ā** á **ǎ** à
ē é **ě** è
ī í **ǐ** ì
ō ó **ǒ** ò
ū ú **ǔ** ù

**Comment by menny** [comment]
thanks.
So, I'll add ā ě ǒ ǔ
Right?
