### ISSUE TITLE
Autocorrect multiple words

### ISSUE THREAD

**Issue by bobolea** [AnySoftKeyboard/AnySoftKeyboard#1200]
### Steps to reproduce
1.Type without putting a space in between two or more words 
2.
3.

### Expected behaviour
It should auto correct to two separate words or more as GBoard does

### Actual behaviour
It suggests a single word that looks like the two words joined together.

**Android OS version:**
7.1.2
**Device manufacturer and model:**
Nokia 6 ta 1025

**List of installed add-ons (like languages, or themes):**
No additional languages or themes installed.

**Comment by menny** [comment]
This is a good idea, I guess it is possible with a powerful enough phone.

**Comment by bobolea** [comment]
Thats good to hear, hopefully most phones will be able to handle it.

**Comment by jfmcbrayer** [comment]
I have an older phone (Moto G 2013), and SwiftKey and Gboard are able to do this without any lag. Not only with omitted spaces, but also with extraneous characters (from the center bottom row, eg) instead of space.

**Comment by woj-tek** [comment]
While SwiftKey can do this it does it to aggressively which leads to making really weird suggestions when trying to type more complex words so if this would be implemented please make it optional.

**Comment by jfmcbrayer** [comment]
Or with configurable aggressiveness.

**Comment by xmiseggs** [comment]
It happens to me very often, I inadvertently think I inserted a space to separate the words but in the end I end up with several words without spaces. Please fix this in a way that would be a great advance in typing speed and would greatly improve this good keyboard.

**Comment by WorldCodeCentral** [comment]
This feature is actually already implemented in Lineage OS's keyboard, which is just the AOSP keyboard from Android 5 I think (after that they didn't develop it further and switched to the proprietary/nonlibre Gboard).

The source code is here I think:
https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/java/src/com/android/inputmethod/keyboard/

(BTW there are other good implementations that might be useful that seem to work better for me at least, like next word suggestion, special characters in the suggestion row when there are no correction suggestions and the option to use a language but still keep the keyboard layout of your first language. Just as a side not if anyone's interested.)
