### ISSUE TITLE
Refactor backup/restore mechanism

### ISSUE THREAD

**Issue by orenoren** [AnySoftKeyboard/AnySoftKeyboard#1207]
### Steps to reproduce
1. Open settings --> abbrevations editor
2. click the 3 dots --> "backup"
3. although it writes "backup successfuly" - only the UserWords.xml (user dictionary) is written to the storage.

And indeed, the function "private void backupToStorage()" exists only in **UserDictionaryEditorFragment** and not in **AbbreviationDictionaryEditorFragment**.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**
android 7.0

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
* Backup/restore to an XML file using a file browser.
* Should allow backup/restore multiple areas:
  * user-words
  * abbrevations
  * prefs
* user should be able to pick which settings to backup/restore

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1241
