### ISSUE TITLE
[feature request] Switch capitalisation of highlighted word by pressing shift button

### ISSUE THREAD

**Issue by jo-b-r** [AnySoftKeyboard/AnySoftKeyboard#1219]
I recently switched from WindowsPhone to Android and this is one very useful feature of WPs keyboard that I haven't found on any Android keyboards.

If you highlight, say, an all-lowercase word and then press the shift button on your keyboard, the word gets its first letter capitalised, if you then press shift again, it becomes all-caps, and if you then press it again, it becomes all-lowercase again. After this, the cycle repeats.

Obviously the cycle starts at different points depending on whether the highlighted word is all-lowercaps, capitalised or all-caps.

I would _love_ to see this feature coming to AnySoftKeyboard! Thanks to everybody working on this project :)

**Comment by menny** [comment]
That's a pretty good idea!
Thanks

**Comment by ViXXoR** [comment]
This has been added with #1294 

Great idea!

**Comment by menny** [comment]
will be available in the next beta

**Comment by menny** [comment]
Thank you, @ViXXoR , for implementing this.
