### ISSUE TITLE
Show decimal comma instead of decimal point in german number keyboard

### ISSUE THREAD

**Issue by trevor87** [AnySoftKeyboard/AnySoftKeyboard#1223]
### Steps to reproduce
1. Open an app in which you have to enter a number using german keyboard layout (e.g. MoneyBalance from fdroid)
2. Go to the number field
3. This shows a modified keyboard with only numbers. It displays a decimal point instead of a decimal comma, which is used as a seperator in germany. The point is not necessary using german numbers.

### Expected behaviour
Show a decimal comma instead of a decimal point

**Android OS version:**
Lineage OS 14.1

Thanks everybody!

**Comment by ArenaL5** [comment]
This is a good detailed an polite report. :smile: 

As of November the 6th, there are commas in every current number layout. I believe this is simpler and equally useful.

Close the issue?
