### ISSUE TITLE
Punctuation and automation of capital letters

### ISSUE THREAD

**Issue by XlllllllX** [AnySoftKeyboard/AnySoftKeyboard#1230]
### Steps to reproduce
1. type a text anywhere
2. use this sign […] at the end of a sentence
3. start a new sentence after this sign and a space

### Expected behaviour
with auto uppercase, the first letter should become a capital letter

### Actual behaviour
The first letter stay as lowercase

**Android OS version:**
6.0.1

**Device manufacturer and model:**
ARCHOS 55 Diamond Selfie

**List of installed add-ons (like languages, or themes):**
I use AnysoftKeyBoard with "French Bépo" only.
The version of AnysoftKeyBoard is the last available on F-Droid, 1.8.1333 VC 2658

(Many thanks for your work :-))

**Comment by menny** [comment]
Is this solved?

**Comment by XlllllllX** [comment]
as is.
If there is no solution, there is no problem ;)
It's a little bit more difficult to choose how it need to be.
