### ISSUE TITLE
[Feature Request] Gboard Theme

### ISSUE THREAD

**Issue by returntrip** [AnySoftKeyboard/AnySoftKeyboard#1235]
Could you please add a Gboard clone theme? Not because it is better, but because of muscle memory, I keep hitting the wrong keys :(.

Thanks for the great OS keyboard!

**Comment by schneekluth** [comment]
@returntrip I,ve just switched and am totally stunned how mighty a brain and muscle memory can be in typing routines. A gBoard layout is badly needed for all folks willing to switch.

**Comment by thegreatestminer** [comment]
Any news or response for this? I've seen issues made 13 days ago and they got closed pretty quickly.

**Comment by menny** [comment]
closing this in favor of tracking with https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1557
