### ISSUE TITLE
Kaomoji in Emoji

### ISSUE THREAD

**Issue by AeliusSaionji** [AnySoftKeyboard/AnySoftKeyboard#1247]
Requesting a group of kaomoji, separated by newline

Tried to keep it streamlined. There are too many of these.

```
(╯°□°）╯︵ ┻━┻
( •_•)>⌐■-■
(⌐■_■)
ヽ(⌐■_■)ノ♪♬
(ノ^_^)ノ
(╯✧∇✧)╯
ಠ_ಠ
ಥ_ಥ
/(;-_-)
（ー_ー；）
¯\_(⊙︿⊙)_/¯
¯\_(ツ)_/¯
( ͡° ͜ʖ ͡°)
(╬ಠ益ಠ)
(☞ﾟヮﾟ)☞
☜(ﾟヮﾟ☜)
```
gitter log: https://gitter.im/AnySoftKeyboard/Lobby?at=5a6e113e97cedeb0482e8593

**Comment by menny** [comment]
@AeliusSaionji can you provide _tags_ for each? This will help when users search for emojis.
something like: 
¯\_(ツ)_/¯ -> shrug, face
etc.

**Comment by AeliusSaionji** [comment]
Sorry,  do you still want me to suggest tags?

**Comment by menny** [comment]
Yes, please.
This is the list of Kaomoji I created:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/res/xml/popup_kaomoji.xml
I need a couple of words for each of them. Thanks. Also, if you have
suggestions for adding/removing/revising the list let me know

**Comment by qwertyuser1983** [comment]
Noobs Q, sorry. 

How to use these Kaomoji? :)

**Comment by menny** [comment]
Enable the kaomoji group in the Quick Text settings.

**Comment by qwertyuser1983** [comment]
Sorry for late reply,

I am using version 3692. The Quick Text Groups is at far down left-hand side. 

I've seen a bunch of groups like emoticons, people, accessories, to shorter smiley key, but no kaomoji. Am I missing something? :)
