### ISSUE TITLE
Pop-up of selected key is misplaced when in expanded desktop

### ISSUE THREAD

**Issue by codingchipmunk** [AnySoftKeyboard/AnySoftKeyboard#1255]
### Steps to reproduce
1. Activate expanded desktop (any mode)
2. Start typing something

### Expected behaviour
Same like without expanded desktop

### Actual behaviour
Pop-ups are misplaced 
![Screenshot showing misplaced pop-ups](https://user-images.githubusercontent.com/36039591/36302892-68a14e64-130a-11e8-9d2a-c66f75ceb2d3.png)

**Android OS version:** LineageOS 14.1 / Android 7.1.2

**Device manufacturer and model:** LG G4 H815

**List of installed add-ons (like languages, or themes):** Nothing additional

**Comment by bretello** [comment]
Can confirm this is happening on the latest Lineage nightly (as of today, Feb 19th)
