### ISSUE TITLE
Allow us to remove the emoji menu entirely

### ISSUE THREAD

**Issue by gappleto97** [AnySoftKeyboard/AnySoftKeyboard#1259]

**Comment by menny** [comment]
Do you mean that you do not want the emoji key on the bottom row?

**Comment by gappleto97** [comment]
Correct. I never use emoji at all. Most of the time I enter the menu is when I miss the comma.

**Comment by menny** [comment]
Then, if that's the case, you can switch the _generic bottom row_ with something else. Look it up at the settings app: In the User-Interface tab, click "Tweaks and more".
