### ISSUE TITLE
[Feature Request]: Add real DEL key

### ISSUE THREAD

**Issue by RockyJE** [AnySoftKeyboard/AnySoftKeyboard#1263]
Please add a DEL key equivalent to the kind found on hardware keyboards, i.e. a key that deletes characters located to the RIGHT of the cursor.

I am often switching to the Terminal keyboard just to move the cursor right a few spaces so I can Backspace in order to delete a few characters.

I think a good placement would be on the right side of the current Backspace key. Some may say there isn't enough room, but I'd be willing to sacrifice for this very useful feature. 😀

Thank you
Rocky

**Comment by menny** [comment]
I'm debating what to do here.
I'm thinking that I'll add API support for that, and then maybe add a key in the symbols keyboard. but that's boring.

**Comment by menny** [comment]
Another option is to have a setting that will flip the current BACKSPACE with DELETE

**Comment by menny** [comment]
Thoughts?

**Comment by RockyJE** [comment]
Of the two options I like the "flip" better.  However, if it were a gesture action option I think it would be quicker to switch to the DEL when needed. I can foresee myself using one the existing gestures to make the switch. [I currently use 3 different gestures all the time, and a few more less often, so adding another one to my typing routine would be a natural for me].

Thanks for your work on this great keyboard

**Comment by menny** [comment]
Will be available in the next release.
