### ISSUE TITLE
Stress marks for Ukrainian keyboard

### ISSUE THREAD

**Issue by legoscia** [AnySoftKeyboard/AnySoftKeyboard#127]
It would be nice if it were possible to input stress marks on vowels using the Ukrainian keyboard. Stress marks are not used in normal text, but only in dictionaries and books for children/learners, me being in the latter category.

For each of the letters Е, Ї, І, А, О, Є, Я, И and Ю, there should be a popup that lets you input the corresponding letter plus U+0301, a combining acute accent.

I would have tried doing it myself, but I couldn't find the files for the Ukrainian language pack. Are they on Github somewhere?

**Comment by friesenkiwi** [comment]
@menny Since the PR is long merged, I suggest this could be closed?

**Comment by menny** [comment]
Right

**Comment by legoscia** [comment]
I don't see this in the Play Store yet - I only see version 20110102 of "Ukrainian Language Pack". Is there a way to access the new version without building the APK yourself?

**Comment by friesenkiwi** [comment]
@menny it seems, the code at https://github.com/AnySoftKeyboard/LanguagePack/tree/Ukrainian is still in the old eclipse-based style? So we'd need to uplift it to Android Studio to re-release?

**Comment by menny** [comment]
@friesenkiwi yes, it seems so. I wont be able to release otherwise.

**Comment by friesenkiwi** [comment]
@menny I did it in https://github.com/AnySoftKeyboard/LanguagePack/pull/42 but it has conflicts (because of rebasing and force pushing), I hope it works somehow?

**Comment by friesenkiwi** [comment]
@legoscia there is a new Ukrainian pack with these changes incorporated at: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.ukrainian Can you check, whether this issue is fixed by that?

**Comment by legoscia** [comment]
@friesenkiwi Yes, the new package works fine. Thanks!
