### ISSUE TITLE
[RFE] Add option to not add space after inserting word from suggestion list

### ISSUE THREAD

**Issue by genodeftest** [AnySoftKeyboard/AnySoftKeyboard#1275]
### Steps to reproduce
1. type any text
2. auto-complete a word (e.g. from the suggestion list)
3. have a look at the text you wrote

### Expected behaviour
Do not add a space after the auto-completed word.

### Actual behaviour
AnySoftKeyboard always adds a space after the words inserted.

### Additional info
I think this change is not popular so it might be useful to add it behind an option switch. This option would be more useful for languages with composite words written as one word such as German.

**Android OS version:**
8.0.0

**Device manufacturer and model:**
Nokia/HMD Global: Nokia 5, TA-1053

**List of installed add-ons (like languages, or themes):**
AnySoft 1.8.1333 from F-Droid store. This is 1.8-r12.2 on the github repo, released 2017-07-27.
Themes: none
Language packs:
* German
* Hebrew
* Neo2
* Rусский (Russian)

**Comment by schodet** [comment]
Actually, this option exists yet in Language -> Tweaks and more -> Tweaks -> Space after candidate pick.

**Comment by genodeftest** [comment]
Oh, sorry, I must have missed that. Thank you!
