### ISSUE TITLE
BUG - double clicking a word sometimes deletes it in Gmail + Flickering problem + more

### ISSUE THREAD

**Issue by sabisab** [AnySoftKeyboard/AnySoftKeyboard#1280]
The method `AnysoftKeyboard::performRestartWordSuggestion` is "patchy" because it does the following:
```
ic.deleteSurroundingText(toLeft.length(), toRight.length());
ic.setComposingText(word, 1);
```
The input connection doesn't have to delete text and re paste it, just for the suggestions to work. Please consider using `setComposingRegion` or something else.

This current mechanism causes several problems: flickering upon moving the cursor, problems with styled text (for example in facebook), and the following problem:

### Steps to reproduce
0. Enable "_suggestions restart_" in the keyboard settings.
1. Compose a new message in **Gmail**
2. Write some words (with spaces between them)
3. double click some words several times until the bug happens.

### Expected behaviour
Double clicking a word should select it.

### Actual behaviour
Sometimes the word is **deleted** from the input.

**Android OS version:**
7.1.1

**Device manufacturer and model:**
Samsung Note 8

**List of installed add-ons (like languages, or themes):**
defaults

**Comment by menny** [comment]
Let me take a shot at it.

**Comment by sabisab** [comment]
Any idea? it looks like a design problem.

**Comment by menny** [comment]
`setComposingRegion` was introduced in API level 9. We just recently moved to min-sdk 9.

I can try to convert to use `setComposingRegion`. See if the behavior is similar.

**Comment by menny** [comment]
I have a PR: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1310
Locally, it seems to work fine. I'll test this out for a few days.

**Comment by menny** [comment]
you can try a debug build from here: https://2609-4063516-gh.circle-artifacts.com/0/apks/debug/app-debug.apk

**Comment by sabisab** [comment]
working great :)

**Comment by menny** [comment]
Great! Thanks for verifying

**Comment by menny** [comment]
@sabisab and thank you for the tip.
