### ISSUE TITLE
Emoji Keyboard don't dismiss when app goes to background

### ISSUE THREAD

**Issue by carlosgorillalogic** [AnySoftKeyboard/AnySoftKeyboard#1281]
### Steps to reproduce
1. Open any app ( I used google keep)
1. Set the focus on some edittext and open the keyboard
2. Show the emoji keyboard
3. Press home button

### Expected behaviour
Dismiss the keyboard

### Actual behaviour
The keyboard still opened.

**Android OS version:**
Android 6.0.1

**Device manufacturer and model:**
OnePlus 2

**List of installed add-ons (like languages, or themes):**
The default one, I just download and installed the app from the store.

**Comment by paulhovey** [comment]
This seems the same as https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1278 .

**Comment by menny** [comment]
fixed in https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1298 and https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1309
