### ISSUE TITLE
Type suggestion not showing up when leaving comments on Google Plus 

### ISSUE THREAD

**Issue by SuperSentient** [AnySoftKeyboard/AnySoftKeyboard#1282]
### Steps to reproduce
1.Try leaving a comment on Google Plus
2.
3.

### Expected behaviour
Tell us what should happen
Type suggestions show up on Google Plus
### Actual behaviour
Tell us what happens instead
Type suggestions aren't showing when leaving a comment Google Plus
**Android OS version:**
7.0
**Device manufacturer and model:**
Samsung SM-G95OU/Galaxy S8
**List of installed add-ons (like languages, or themes):**
AnySoftKetboard 3D(Theme), Gingerbread (Theme), ICS Theme for AnySoftKetboard

**Comment by menny** [comment]
It seems that in the latest version of G+ the issue was solved. Can you verify that @SuperSentient

**Comment by SuperSentient** [comment]
Yeah its fixed.

**Comment by menny** [comment]
thank you.
