### ISSUE TITLE
getBigramsNative

### ISSUE THREAD

**Issue by JinXinUp** [AnySoftKeyboard/AnySoftKeyboard#1286]
### Steps to reproduce
1. Why did this method comment
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by AnXh3L0** [comment]
Incomplete description, closing this issue.
