### ISSUE TITLE
custom bottom line

### ISSUE THREAD

**Issue by silencshadow** [AnySoftKeyboard/AnySoftKeyboard#1287]
Hello,

Im really missing my bottom line from ios ... where are the designes with just a dot exclamation mark emoji and space? I don't want a '''''' in my bottom line I want a dot no, ,,,

**Comment by schodet** [comment]
Did you try the setting in UI -> Tweaks and more -> Common bottom generic row ?

**Comment by alensiljak** [comment]
> Did you try the setting in UI -> Tweaks and more -> Common bottom generic row ?

That's not enough. For example, when using the Dvorak layout, there are duplicate comma and period keys but one can't have the microphone, question mark, and emoji instead. The default row is good but the space key is kinda small. Plus everyone has their own preferences.
