### ISSUE TITLE
In french, there is a space before punctuations with two parts, space should not be swaped in this case

### ISSUE THREAD

**Issue by schodet** [AnySoftKeyboard/AnySoftKeyboard#1288]
### Steps to reproduce
1. Use French
2. Enable the punctuation swap option
3. Type a question with a question mark

### Expected behaviour
There should be a space before and after the question mark.

### Actual behaviour
The space before the question mark is removed.

**Android OS version:**
Any.

**Device manufacturer and model:**
Any.

**List of installed add-ons (like languages, or themes):**
French language extension.

This behavior depends on the typed language, I suppose it could be activated based on the chosen dictionary, but what if several dictionaries are selected? Sometime I type English, sometime French :)

The space must be present before ? ! : ;

The space must not be present before . ... ,

**Comment by Valeryan24** [comment]
Hi, I confirm. If the option "Swap space and punctuation" is activated, even if we write " ?" or " !", the space before punctuation is automatically deleted.

It could be good to add the automatic space before and after double punctuation in French, as said for ? ! ; : 

Thanks !

**Comment by menny** [comment]
Implemented with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1302
