### ISSUE TITLE
Cursor jumps back automatically 

### ISSUE THREAD

**Issue by giedriusc** [AnySoftKeyboard/AnySoftKeyboard#1290]
### Steps to reproduce
1. Type quickly 
2.
3.

### Expected behaviour
Tell us what should happen

Typed symbols should appear in the order they were typed

### Actual behaviour
Tell us what happens instead

Cursor lags behind or jumps back and you start typing in the middle of the word. For example if I type quickly the word "example", I get something like "expleam"

**Android OS version:**

8.0

**Device manufacturer and model:**

Huawei mate 9

**List of installed add-ons (like languages, or themes):**

Lithuanian language and main AnySoftKeyboard app.

**Comment by wbrawner** [comment]
+1 on this, makes it very difficult to use the keyboard.

**Comment by giedriusc** [comment]
It looks like not everyone have this issue. I wonder what's causing this issue and what the solution could be?

**Comment by srbaker** [comment]
I have this issue on a Huawei P10

**Comment by Ajudu** [comment]
It is still happening on my Huawei P20 Pro, running Android 9

**Comment by giedriusc** [comment]
I stopped using it years ago because of that.

**Comment by juacq97** [comment]
I have the same issue, I changed the delay but still present

**Comment by EhVedadoOAnonimato** [comment]
I confirm this happens on Huawei P20 Pro when I type fast. It's extremely annoying. Any tips on how to workaround?

**Comment by fahadmaqsood** [comment]
I actually found the problem... This code in the file "AnySoftKeyboardSuggestions.java":

(Line: 556-560)
>                     int cursorPosition = newSelEnd - candidatesStart;
>                     if (mWord.setCursorPosition(cursorPosition)) {
>                         Logger.d(
>                                 TAG, "onUpdateSelection: cursor moving inside the predicting word");
>                     }

When I comment that out... the keyboard works properly... I see no cursor jumping at all.

**Comment by jtourille** [comment]
Same issue with a OnePlus 2 running LineageOS 16.0 with French Layout.

**Comment by daraul** [comment]
I think @menny closed this by mistake. I'm also having the problem.

**Comment by menny** [comment]
Have you tried the latest beta version? You can sign up for the beta channel here:
https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard

**Comment by daraul** [comment]
Just did and testing it out right now. This does seem to be working better, thanks.
