### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by qalbhussain** [AnySoftKeyboard/AnySoftKeyboard#1292]
AnySoftkeyboard is successfully build. But when i run the application on my device i get this Error:

# **## Error:java.util.NoSuchElementException**

I dont know how to resolve this issue. If anybody could help me, that'll be great.

Thanks

**Comment by menny** [comment]
Can you provide the complete logcat?
Also, which OS  are you using developing on? And which Android version runs on your device?

**Comment by qalbhussain** [comment]
![capture](https://user-images.githubusercontent.com/19609920/37888861-0a02b414-30e3-11e8-86d8-a2987353ece6.PNG)

Sorry for the late response Menny. Attach is the complete logcat.
I'm using Windows and i'm running Android 7.0 in my device.

**Comment by dtoledos** [comment]
I have the same problem, How is possible fix this proble, i am using window and android 7 and 5.
Do you hHave some version that is working, please?

These errors when i want execute in my devices
Warning:The option 'android.enableAapt2' is deprecated and should not be used anymore.
Error:java.util.NoSuchElementException
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Failed to execute aapt
Error:com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Failed to execute aapt
Error:com.android.ide.common.process.ProcessException: Failed to execute aapt
Error:java.util.NoSuchElementException

**Comment by qalbhussain** [comment]
This error only occurs whenever i run the project on actual device. Don't know how to resolve this issue.

**Comment by dtoledos** [comment]
For me, These error appears when try run the project in any device with android studio 3.

**Comment by gnomex909** [comment]
I had the same error, after updating plugins and Studio to 3.1. Turning off instant run fixed it

**Comment by dtoledos** [comment]
Good idea, i can turn off instant run and see if is working for me, thanks

**Comment by dtoledos** [comment]
Have the all reason when the instant run is in off, this source code is running in any device, thanks a lot

**Comment by menny** [comment]
great! Thanks for sharing the solution.

**Comment by addappcn** [comment]
升级新版 android studio 错误记录
报错 java.util.nosuchelementexception  
两种解决办法
1关闭instant run

2android.enableAapt2=false 改成true  然后会报找不到 @android:windowExitAnimation  把前面的@去掉就 ok了

**Comment by XuqingLiu** [comment]
@menny 
just translation:
error records after update the new version of android studio
error: java.util.nosuchelementexception
two solutions:
1. turning off instant run
2.change android.enableAapt2=false to android.enableAapt2=true, if an error "@android:windowExitAnimation" occurs, just removing @ is okay
