### ISSUE TITLE
Long press selection on FR-Azerty keyboard for U and .

### ISSUE THREAD

**Issue by Valeryan24** [AnySoftKeyboard/AnySoftKeyboard#1296]
Hi,

There is a small bug on FR-Azerty keyboard : all letters of the first line (AZERTYUIOP), when you long press them, automatically select and write the number (1 2 3 4 5...), except for the U : instead of the "7", it writes the ü.

Also a small suggestion : for the . key on the bottom line, would it be please possible to moove the "..." at the right and make it default long press selection  (currently it is ; ) or at least put it near the ":" ?

Thanks :)

**Comment by Valeryan24** [comment]
Issue still present, only on U...

**Comment by Joppla** [comment]
Please open, it is still actual, not only on the Azerty keyboard, but also on my standard qwerty.

**Comment by Valeryan24** [comment]
Bot asked me to comment to avoid closing, and it closes anyway without resolving the bug... Same for issue 1297 !
