### ISSUE TITLE
Replace duplicates - and ' on FR Azery by left / right navigation keys

### ISSUE THREAD

**Issue by Valeryan24** [AnySoftKeyboard/AnySoftKeyboard#1297]
Hi, first congratulations and thanks for your hard work on Anysoft Keyboard !

I use the FR-Azerty with dark theme and big keys.

On the penultimate line, right to letters WXCVBN there are - and ' keys.

There are (and some of the long press selection associated) duplicates with the . and ' keys just below on the bottom line.

Would it be possible to replace - and ' after the wxcvbn by the left and right navigation arrows ?

I often need them (mainly these ones, not the up and down) because with my fingers I often miss the exact place to correct a word. I know we can put the navigation on the top line, but here I prefer to have the numbers directly available...

Thanks in advance !

**Comment by BoFFire** [comment]
Hi,
Like this ?
https://mastodon.social/@ButterflyOfFire/99752137246658652 ?

**Comment by Valeryan24** [comment]
Sorry, I never saw Ghost message and thought issue has got no answer - and now Mastodon message is not available anymore, but problem is still the same.
