### ISSUE TITLE
No vibration when typing (Android 7.0, Samsung Galaxy S7)

### ISSUE THREAD

**Issue by pieqq** [AnySoftKeyboard/AnySoftKeyboard#1301]
First of all, thanks for this great open source alternative keyboard!

### Steps to reproduce
1. Install latest version of AnySoftKeyboard from F-Droid
2. Go to `Options` > `UI` > `Keyboard effects and experience` > `Vibrate on key-press`
3. Select either `Light`, `Medium` or `Strong`

### Expected behaviour
When typing, I should feel a vibration for every key typed.

### Actual behaviour
No vibration at all.

**Android OS version:**
7.0
Kernel 3.18.14-12365438

**Device manufacturer and model:**
Samsung Galaxy S7 Edge (SM-G935FD)

**List of installed add-ons (like languages, or themes):**
AnySoftKeyboard v1.9.1117 release 3692. Installed on 1522114265852, first released installed was 3692.
Installed languages:
- English Qwerty Latin keyboard with symbols (on long-press) (default),
- French Qwerty (also via F-Droid)

**Comment by Castlemark** [comment]
I have the exact same problem, both the F-Droid and Google Play version exhibit the same behavior.

**Android OS version:**
7.0
Kernel 4.4.153

**Device manufacturer and model:**
OnePlus 5 (A5000)

**List of installed add-ons (like languages, or themes):**
AnySoftKeyboard v1.10.364. Installed languages:
- Spanish
- Catalan
