### ISSUE TITLE
Propose new logo

### ISSUE THREAD

**Issue by anaufalm** [AnySoftKeyboard/AnySoftKeyboard#1305]
Hi, I've seen your app and I think it's a lot of benefits, especially for android users who have difficulty typing in multiple languages. And here I would like to propose new logo for your app to have a good brand and become more interesting.

If you are interested and allowed me, I will make it for you, because I have an idea for this. ;)

**Comment by pieqq** [comment]
@aldatsa I'm not a member of the AnySoftKeyboard team (I'm just a happy user), but I think you can just propose your logo without asking :) Looking forward to see what you design!

**Comment by anaufalm** [comment]
Yes I know that, but maybe PO doesnt need a new logo, so I will not create it. Just make sure, you know ask before acting.

**Comment by ViXXoR** [comment]
There is an issue open for this I believe, #1125. It's in the milestones for the next release, so I would think if you have some ideas, they would be better off there.

**Comment by menny** [comment]
If you have suggestions for a new icon, or anything else, feel free to propose.
Regarding the icon, use https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1125 for proposals.
Thanks.
