### ISSUE TITLE
Language code issue

### ISSUE THREAD

**Issue by FTno** [AnySoftKeyboard/AnySoftKeyboard#1307]
In the Force Locale setting when System is selected, the app will be in english and not in norwegian (on norwegian android phone).
I believe this is because the norwegian language code used in the app is 'no' and not 'nb' as it should be.
So please change the norwegian language code to 'nb' in the app (and here at GitHub) and also at Crowdin Project Localization (as this example: https://crowdin.com/project/ublock).

Version: 1.8.1333

Android OS version: Nougat

Device manufacturer and model: Galaxy S7

List of installed add-ons (like languages, or themes): Norwegian language pack

**Comment by menny** [comment]
makes sense. I've verified it here: https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android

**Comment by menny** [comment]
I've copied the translations from `no` to `nb`. Please verify that, if possible.

**Comment by FTno** [comment]
Can confirm that translations are copied to 'nb' at Crowdin.

By the way I noticed that you had approved translations in Crowdin. Could you please remove your proofreader status for 'nb'. There are some typos and small corrections to make on already translated strings.

**Comment by menny** [comment]
how's this: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1311

**Comment by FTno** [comment]
Looks fine now, and I would presume it should work correctly in the next version when 'System' is selected in the Locale setting.

Is the pull request referenced above (Created strings.xml for nb #131) for the norwegian language pack, the right way to get the keyboard name translated?
