### ISSUE TITLE
gesture typing problem for 'is'and 'does'

### ISSUE THREAD

**Issue by sabisab** [AnySoftKeyboard/AnySoftKeyboard#1318]
Enable gesture typing. and under English, swipe the following:
1. Swipe the word "is" (from i to s). The result is "id's"
2. Swipe the word "does". The result is "doe's"
3. Swipe the word "You're". The result is "yore".
4. Swipe the word "I'll" (from I to L). The result is "Ill" (without the apostrophe).

**Comment by TimMagee** [comment]
To get words with an apostrophe, you have to swipe down to the apostrophe. I can't decide if I like that system or not.
