### ISSUE TITLE
[Feature Request] Punctuation keys should add a space automatically afterwards.

### ISSUE THREAD

**Issue by avirup** [AnySoftKeyboard/AnySoftKeyboard#1320]
### Steps to reproduce
1. Type something and press '.'

### Expected behaviour
There should be a space added after the fullstop.

### Actual behaviour
No space is added after the fullstop.

**Comment by romevi** [comment]
I would like this feature as well.

**Comment by avirup** [comment]
Can this behavior be  added? Not just for a full stop, but for other punctuation as well.
