### ISSUE TITLE
Has , Repeatedly, At Least Once Every Few Days, Switched To Hungarian Keyboard Without Me Choosing to Do So.

### ISSUE THREAD

**Issue by StevenSource** [AnySoftKeyboard/AnySoftKeyboard#1324]
### Steps to reproduce
1. I use AnySoftKeyboard.
2. When I'm doing something important, it "Co-Incidentally" (Incidences that Are Co-nnected) switches to the Hungarian Keyboard, with no easily visible user friendly way to put it back to English.

3. If you don't help resolve this issue ASAP, I will not use AnySoftKeyboard again, nor help you test it or report bugs or support it in any capacity.

### Expected behaviour
Tell us what should happen

It should stay in English mode.

### Actual behaviour
Tell us what happens instead

It switches to Hungarian Keyboard, and when I try to change it back, there is no user friendly easily visible way to put it back to English Keyboard.

Also, AnySoftKeyboard has hung/crashed/glitched/bugged out at least three times in three minutes when I try to access the Settings.

**Android OS version:**
8.0.0

**Device manufacturer and model:**
Samsung Galaxy S8+

**List of installed add-ons (like languages, or themes):**
All Languages, No Themes.

Fix it within two weeks or I will uninstall it and never come back.

Your Free Will Choice.

I AM THAT I AM.

I AM STEVEN SOURCE.

And so it is.

**Comment by LugiaDepression** [comment]
You have downloaded the Hungarian keyboard pack too (that's what I have too)? If you're a beta tester I suggest you to step out of being one, it's much trouble than worth. Otherwise I never had this issue what you described.
