### ISSUE TITLE
Suggestions bar doesn't show up in certain apps

### ISSUE THREAD

**Issue by Rising-Soul** [AnySoftKeyboard/AnySoftKeyboard#1331]
It seems to mostly affect the search/address bars in certain apps, with Simple Text Editor being the exception. Is there any way to force suggestions to always appear?

### Steps to reproduce
1. Start typing in certain apps, example: Searchbar Ex, Simple Text Editor, Yalp Store Search, Google Play Store Search, Pale Moon Browser

### Expected behaviour
Suggestions bar should appear, with suggestions

### Actual behaviour
There is no suggestions bar and no suggestions

**Android OS version:**
Android 4.3.1 (Cyanogenmod 10.2.1)

**Device manufacturer and model:**
Samsung Galaxy S4

**List of installed add-ons (like languages, or themes):**
Haven't installed any extra ones - using English and Lean Dark Option 2 as the theme. It affects all the themes I tried, but I didn't test them all.

**Comment by fridgecow** [comment]
I believe this is desired behaviour - some apps request that the text field isn't auto corrected.

**Comment by Rising-Soul** [comment]
I think the user should be allowed to decide if the behaviour is desired or not. If that's the cause of this, then I guess I'm proposing an option in the settings to override that and force auto correct to be on in all fields (except password fields). That would be nice. Maybe also a toggle gesture/button or something.

**Comment by Discostu36** [comment]
On my Samsung S5, the standard keyboard does give suggestions in all apps but AnySoftKeyboard doesn't in many. So I'm not sure that it's really desired behavior.

**Comment by ralmcruz** [comment]
> I think the user should be allowed to decide if the behaviour is desired or not. If that's the cause of this, then I guess I'm proposing an option in the settings to override that and force auto correct to be on in all fields (except password fields). That would be nice. Maybe also a toggle gesture/button or something.

An option do override this would be awesome.

**Comment by richardboegli** [comment]
I have the same issue with Bluetooth Keyboard and Mouse.

How much effort would be required for this fix?

**Comment by menny** [comment]
It could be that the app says it provides auto-complete. Browsers do that.
I can take a look

**Comment by menny** [comment]
Github Android App also does not show suggestions when writing a comment.
