### ISSUE TITLE
The French preposition « à » is not suggested by default and cannot be added to the suggestions list

### ISSUE THREAD

**Issue by pieqq** [AnySoftKeyboard/AnySoftKeyboard#1332]
In French, the preposition `à` is very often used in daily conversations. With current version of the French language pack, it is annoying to type and cannot be saved by touching it.

It should be a default suggestion or, at least, should allow the user to add it to the suggestions.

### Steps to reproduce

Theme: `Plain dark theme`
Common top generic row: `No top row`
Common bottom generic row: `Simple`

#### Test 1
1. Select `FR - Qwerty`
2. Type `a`

#### Test 2
1. Select `FR - Qwerty`
2. Long press `a`
3. Select `à`
4. Try typing the `à` that is displayed in the suggestion line (next to the `← Touch again to save`)

#### Test 1
Both `a` and `à` should be proposed by default, since `à` is such an important locution in French

#### Test 2
I should be able to press `à`, and it would be saved as a suggestion for later use.

#### Test 1
I currently have two suggestions proposed: `a` and `aller`

#### Test 2
`à` is greyed out and cannot be selected:

![keyboard-qwerty-fr](https://user-images.githubusercontent.com/512471/39414740-b7412610-4c6d-11e8-94eb-f338c54ee52e.jpg)

**Android OS version:**
7.0

**Device manufacturer and model:**
Samsung Galaxy S7 (SM-G935FD)

**List of installed add-ons (like languages, or themes):**
- ASK v1.9.1117 from F-Droid
- ASK French Language Pack v1.0.67 from F-Droid

**Comment by pieqq** [comment]
This issue is still here... can someone with appropriate rights remove the "Stale" label? Thanks.

**Comment by Yoannjap** [comment]
Hey, I found a solution to solve the 'a' or 'à' suggestion to work for French.
In Anysoftkeyboard app settings, go to 'Language' tab ('Langue' in French), Then uncheck the box called in French 'Utiliser la répétition des touches'. 

And magic! It works then
