### ISSUE TITLE
Latest version (1.9 R2) not availabe in F-Droid

### ISSUE THREAD

**Issue by CryptOwl** [AnySoftKeyboard/AnySoftKeyboard#1333]
The latest release version 1.9 R2 is not available at F-Droid. The latest version available there is 1.9.1117 (released on 2018-03-05): https://f-droid.org/repository/browse/?fdid=com.menny.android.anysoftkeyboard

F-Droid Wiki entry: https://f-droid.org/wiki/page/com.menny.android.anysoftkeyboard
Says this on the wiki page:
"**Versions** 
We have the current version of this app. (Check mode: None) (Auto-update mode: None)"

Build log:
https://f-droid.org/wiki/page/com.menny.android.anysoftkeyboard/lastbuild

It looks like F-Droid hasn't picked up the latest release for some reason (again).

**Comment by menny** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/3117

**Comment by menny** [comment]
updated to 1.9-r3 https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/
