### ISSUE TITLE
Split keyboard settings not persisted when returning from voice recognition

### ISSUE THREAD

**Issue by jhusain** [AnySoftKeyboard/AnySoftKeyboard#1334]
### Steps to reproduce
1. Use expand gesture to split the keyboard into two parts
2. Click the voice recognition button. Use voice recognition to type something.
3. Close voice recognition ime to return to  anysoftkeyboard

### Expected behaviour
Keyboard should start in Split mode

### Actual behaviour
Keyboard starts in normal mode and does not remember that it was in Split mode. Forces you to use gesture to move back to split mode again. 

**Android OS version:**
7
**Device manufacturer and model:**
Samsung Galaxy Tab 2

**List of installed add-ons (like languages, or themes):**
Only the defaults.

**Comment by kai11** [comment]
Why this is closed? This bug still exists on most recent play store version

**Comment by kai11** [comment]
Can be partially fixed in Tweaks menu (Portrait Split / Merge initial state, same for landscape), but still its not preserved.
