### ISSUE TITLE
[Feature Request] Support for Image / GIF insertion

### ISSUE THREAD

**Issue by fridgecow** [AnySoftKeyboard/AnySoftKeyboard#1335]
As in https://developer.android.com/guide/topics/text/image-keyboard

There are two ways I could see this working:
- A button on the keyboard launches the default gallery picker, and inserts the selected image into the text view on return. This is intrusive in terms of interface, but doesn't require extra permissions.
- A gallery is shown _within_ the keyboard*, and inserts the image into the text view on tap.

*from user-selected folders, as an extension

I can potentially work on this feature over the coming months, but I would like to hear if it's desirable with the overall project as is, and if so, which direction (or any other) would be best to go with.

**Comment by menny** [comment]
@fridgecow I would go with option 2. The keyboard app already has [WRITE_EXTERNAL_STORAGE](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/AndroidManifest.xml#L21) permission.
I can help out on this.

**Comment by menny** [comment]
I share this sentiment, I want a lean and quick keyboard as well. I can assure you that our implementation of GIF/media support will be light-weight and will not interfere with the main functionality of the keyboard

**Comment by menny** [comment]
https://tenor.com/gifapi

**Comment by fridgecow** [comment]
The problem with this is that ASK currently doesn't use the internet permission - so the idea was to do an offline insertion / from any app which provides an android file picker

**Comment by menny** [comment]
Of course, I paste it here so I'll remember this for the next step, which is https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1118
'

**Comment by nitrocode** [comment]
Id love to drop gboard for this app if I could send gifs. @menny any progress on this?

**Comment by fridgecow** [comment]
No, I believe if there were any progress it would be referenced in this issue. I haven't done any work on it, despite my best intentions.

**Comment by menny** [comment]
MVP is merged. Should be available in ALPHA channel in a couple of hours.

This is only initial functionality, at this time it will invoke the system's gallery-picker.

In the next commits, you will be able to use the camera or a third-party search app.

**Comment by menny** [comment]
Also, if you install https://play.google.com/store/apps/details?id=net.evendanan.lumiere you will get GIF search using this app.

An external app is required because AnySoftKeyboard does not have internet access and can not do a GIF search

**Comment by menny** [comment]
Again, this functionality is only available with the beta version of ASK.

**Comment by fridgecow** [comment]
That's amazing! Love the extensibility. As you've noted, it's a little clunky right now (choose Lumiere vs ASK and then later choose Gallery / Photos etc), but it's useful even in its current form which shows how good the feature is.

Thank you, menny!

**Comment by menny** [comment]
Yes, it's a bit weird. I just ask the OS to `Always open Lumiere` at the moment. This will directly open Lumiere when I press the MEDIA key.

**Comment by BeeeWall** [comment]
Maybe I'm blind, but I don't see the button or any setting anywhere?

**Comment by menny** [comment]
In a supporting text-field, open the emoji popup (usually, long-press the smiley key. 
On the right you'll see a Gallery icon. See attached screenshot 
![Screenshot_20190520-123808](https://user-images.githubusercontent.com/481272/58037804-3f11f700-7afc-11e9-9787-9dd2131c268c.png)

**Comment by BeeeWall** [comment]
You're right, it does. Forgot to think about whether the field might support images or not, oops.

**Comment by ndubbaka** [comment]
> https://play.google.com/store/apps/details?id=net.evendanan.lumiere

is this code open source? I don't see it in code here https://github.com/search?q=org%3AAnySoftKeyboard+giphy&type=code

**Comment by menny** [comment]
https://github.com/menny/lumiere

**Comment by crti** [comment]
On MIUI debloated I'm not able to insert from gallery-picker in Instagram: it let's select an image with ASK either from MIUI Gallery, Google Photos or File Manager, but then after selecting it just does not paste the image. On another device with crDroid this works fine and was never a problem. BTW: thx for the great App! 
So not sure if missing permissions could be responsible or some MIUI limitations/settings?

**Comment by Deanosim** [comment]
Seeing as Lumiere has been removed from the play store and is outdated.
What are people using to replace it?

**Comment by forenta** [comment]
Shouldn't this be opened again? Is there a reason why it's not on F-Droid nor at the Play Store anymore, @menny?
