### ISSUE TITLE
[Feature Request] Adding a new word

### ISSUE THREAD

**Issue by MirkVires** [AnySoftKeyboard/AnySoftKeyboard#1338]
### Steps to reproduce
1. Go to options to "Word editing".
2. Option for "add a new word" is on the right, press "add"
If you have already added a few hundred words it scrolls you waaaay down bellow.
3. Add a new word.

### Expected behaviour
The option for adding a new word should be at the top.

### Actual behaviour
Have to scrool down to the bottom to add a new word. Which is uncomfortable when you have a lot of words.

**Android OS version:**
7.0
**Device manufacturer and model:**
LG V10
**List of installed add-ons (like languages, or themes):**
English, Polish

**Comment by MisterY** [comment]
Isn't it easier to type a new word in any text box and use "Tap to add" option?

**Comment by MirkVires** [comment]
It wouldn't be such major problem if adding a new word would work properly. But it does not.
And anyway it still is a good idea to replace it from bottom to the top position.

**Comment by menny** [comment]
PR https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1340 fixes the tap-to-add functionality.

There is an "Add-word" action in the overflow menu (top right).

At some point I'll implement https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/212 and this will greatly help with this use-case
