### ISSUE TITLE
Fb messenger requires two swipe-downs to make they keyboard disappear

### ISSUE THREAD

**Issue by SassuWunnu** [AnySoftKeyboard/AnySoftKeyboard#1350]
### Steps to reproduce
1. Converse in fb messenger
2.Try to swipe down while swipe down to hide keyboard is enabled and while cursor is active in messenger text input field
3.swipe down again to make keyboard disappear because something triggers the keyboard to appear again

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by AnXh3L0** [comment]
Can you please test this again with the latest ASK and Messenger versions?

**Comment by SassuWunnu** [comment]
It's working know.

Anxhelo Lushka <notifications@github.com> ezt írta (időpont: 2019. dec. 1.,
V 16:41):

**Comment by AnXh3L0** [comment]
Great then, it must have been fixed along the way. Closing this issue.
