### ISSUE TITLE
Logo Design Update 

### ISSUE THREAD

**Issue by baranpirincal** [AnySoftKeyboard/AnySoftKeyboard#1352]
Hey! I examined your project and I saw that you have a logo design already but I think it is too generic. I can contribute on your project with making a unique logo design for AnySoftKeyboard. What do you think about that? If you interested I can show my portfolio to you. I am waiting your feedback, have a nice day!

Best Regards
Baran Pirinçal

**Comment by menny** [comment]
I would be glad for such contribution. We had a previous discussion on that here: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1125
