### ISSUE TITLE
Configuration: allow disregarding layout's top and bottom rows (and use the generic ones)

### ISSUE THREAD

**Issue by ArenaL5** [AnySoftKeyboard/AnySoftKeyboard#1361]
﻿### Steps to reproduce
This happens with the beta version of AnySoftKeyboard, too, but it's more noticeable when installing the NEO layout.

1. Install from F-Droid AnySoftKeyboard 1.9r-1, and ASK's NEO2 and Spanish layouts
2. Search for the AnySoftKeyboard application in the app drawer (or use any other method to open ASK's configuration screen).
3. Tap Language > Enable keyboard and layouts, disable default English keyboards, and enable only NEO and a Spanish layout.
4. Tap UI, and a keyboard will appear on screen.
5. Tap Tweaks and more, and choose a different Common bottom generic row. Press the Back key, and tap again the UI button.
6. The exact same keyboard appears on screen.

### Expected behaviour
There should be a way to choose which keyboard is displayed on steps 4 and 6, or it should default to the one I'm using now.

### Actual behaviour
The displayed keyboard is always NEO2.

If I install different add-ons, or enable/disable different keyboards, the keyboard in steps 4 and 6 is always the enabled keyboard in step 3 that's nearest to the top.

This is more noticeable when using NEO2's keyboard in F-Droid because the bottom row of that keyboard is fixed: it doesn't change when choosing a different common bottom generic row.

**Android OS version:** Android KitKat 4.4, Google services disabled

**Device manufacturer and model:** Vodafone Turbo 4 Smart

**List of installed add-ons (like languages, or themes):** This happens with any number of ASK's add-ons, in 1.9r-1 and the current (30 May 2018) beta version.

**Comment by p3732** [comment]
The NEO2 layout overrides the generic bottom row. Fixing this would require an option to overwrite the bottom row when a layout overrides the generic one. Or NEO2 could provide a version with the bottom row untouched. (I will try to work on the later, since this annoys me too)

**Comment by menny** [comment]
Both good suggestions
I'll change the title of this ticket to reflect the change I'm going to implement.
@p3732 can you open another ticket fie your suggestion?  "Use last used keyboard when demoing keyboard view in the settings app"

Thanks
