### ISSUE TITLE
Suggestion is adding chars on backspace

### ISSUE THREAD

**Issue by AdiZarfaty** [AnySoftKeyboard/AnySoftKeyboard#1364]
### Steps to reproduce
1. Turn suggestions on
2. Write a word
3. Press space
4. Press backspace

### Expected behaviour
Return to show suggestion for the word written just as it was when writing it.

### Actual behaviour
The first char is being dubbled. Like this
word - > wword

**Android OS version:**
6.0.1
**Device manufacturer and model:**
Samsung note 4
**List of installed add-ons (like languages, or themes):**
Hebrew. But this happens in any lang.

**Comment by 7lima** [comment]
This also happens in German. 
Nervt!

**Comment by kyak** [comment]
Happens to me as well. Very frustrating! It began after update from 1.9.1117 to 1.9.1944 (F-Droid).

**Comment by theorangepotato** [comment]
I have also experienced this issue, and can confirm that it also occurred after the same F-Droid update.

**Comment by menny** [comment]
duplicate to https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1323
Please, add your device details at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1323
