### ISSUE TITLE
Error in the question mark button

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1367]
Hello, there is an error in the question mark when you start a question in Spanish. Can you please fix it?

The correct symbol is: ¿

![unnamed_1](https://user-images.githubusercontent.com/29940632/40891223-0f2e91b2-6782-11e8-9f9e-560339010932.jpg)

**Comment by menny** [comment]
thank you for reporting

**Comment by menny** [comment]
For your information: ¿ is available in the `?` long press, when using the default generic bottom row.

**Comment by xmiseggs** [comment]
Attached is an image of how it currently appears. As you can see only the closed interrogation appears but not the open interrogation is not being shown, should it be, I understand it is. It should appear as follows: "¿?!¡" and by pressing the "" key. the cursor must display the above list and the cursor must be positioned over the closed interrogation: "?"

Please check the "?" key. which, when left pressed down, shows: "¿"

Also do the same with the "¡" key and when you leave it pressed display: "!"

Thank you very much for your great work.

Excuse my English.

![unnamed](https://user-images.githubusercontent.com/29940632/40944695-02f26d54-6856-11e8-8bfe-fb741656f32f.jpg)
