### ISSUE TITLE
Clipboard blocks keyboard if there is nothing to paste

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1371]
If we currently have nothing on the clipboard and you use the paste button in the image below, the keyboard is locked. If we have a text already copied the clipboard button works perfectly.
![unnamed](https://user-images.githubusercontent.com/29940632/40945203-06312a62-6858-11e8-80ed-242d89e550d9.jpg)

**Comment by menny** [comment]
how do you reproduce this issue?

**Comment by xmiseggs** [comment]
The only way to play it is to turn off the mobile phone, turn it on and then as there is nothing copied into memory you can try to paste it, this way the keyboard is locked. If you have something already copied into memory and pasted it works perfectly.
