### ISSUE TITLE
Add emojis key in keyboard utilities

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1373]
As you can see in the picture my keyboard does not have an icon to access the emojis, I like the way it is, it is perfect. I wanted to ask you if you can include an icon in the keyboard utilities to access the emojis.
Thank you

![unnamed](https://user-images.githubusercontent.com/29940632/41003164-5950df12-6916-11e8-8a15-c3a80abf93fc.jpg)

![unnamed2](https://user-images.githubusercontent.com/29940632/41003180-63863766-6916-11e8-81a3-4b08e77c8763.jpg)

**Comment by GoranGharib** [comment]
You can change the Bottom style in Settings -> UI -> Tweaks and more -> Common bottom generic row

**Comment by xmiseggs** [comment]
It is true that I can change the lower row, but I like the one shown in the image, so I request another place to access the emojis from.
