### ISSUE TITLE
Difference in Spanish language pack versions

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1375]
I'm not sure what the latest version of the Spanish language pack is:

- Google Play: 
https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.spain
Version: 2.1.255
Date: July 28, 2017 

- F-Droid:
https://f-droid.org/packages/com.anysoftkeyboard.languagepack.spain/
Version: Version 2.1.1 (167) 
Date: September 2, 2017

- GitHub (LanguagePack):
https://github.com/AnySoftKeyboard/LanguagePack/releases
Version: Spanish v2.1.2
Date: June 1, 2018

As you can see there are differences between dates and version numbers, also in GitHub (LanguagePack) I can not download the version in .apk format to perform the installation on my phone.

What's the latest version?

Thank you

**Comment by Solomon1732** [comment]
Spanish isn't the only language pack where the f-droid version is way behind the playstore version. Hebrew is also like this, and the main keyboard itself looks like it's a version or two behind.

**Comment by xmiseggs** [comment]
Spanish is constantly being updated. Thank you very much. You can close this query.

Actualizada 20 de marzo de 2019
Versión actual 4.0.440
