### ISSUE TITLE
When backspacing a copy of the first character is copied in beginning of the word 

### ISSUE THREAD

**Issue by NitroNils** [AnySoftKeyboard/AnySoftKeyboard#1386]
After the update to 1.9.1944 everytime I backspace after a suggestion is added and I press space (automatic space after adding suggested word is turned off) the first character is added to the beginning of the word.

If I write '_add_ ' and add a space and the backspace it ends up like '_aadd_ '.

**Comment by michaelof** [comment]
Same for me, Android 6.0, German and English. 

Found community link here: https://plus.google.com/100566113321052571340/posts/Gd9Mnx4XWdB
Hopefully reproducible now :)

**Comment by menny** [comment]
duplicate to https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1323
Please, add your device details at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1323
