### ISSUE TITLE
Setting to disable Auto word select (Auto-correct) by default

### ISSUE THREAD

**Issue by GoranGharib** [AnySoftKeyboard/AnySoftKeyboard#1393]
Hi,

Could you please add new feature to disable Auto-correction by default when you build your own keyboard app using source code the Auto corrections is no needed to that languages I created by my self i want to Inactive or disable that feature by Default for examlpe  <bool name="settings_default_auto_word_complete">false</bool>

Please I need that Dev's Help Me :(

**Comment by menny** [comment]
I don't understand exactly what you are asking. If you build the app locally on your computer, you can change the value of `settings`

**Comment by menny** [comment]
I'm not sure

**Comment by GoranGharib** [comment]
Thank you so much I means thats you're awesome master thanks again 💯

**Comment by nailinaim** [comment]
X pasti
