### ISSUE TITLE
Emoji prediction

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1394]
It would be very interesting if the list of "Next word suggestions" also shows the emoji prediction.
For example, if I say "Hello", show the suggested words such as emoji of the hand waving, etc, etc

**Comment by eadmaster** [comment]
I suggest to try a quick implementation without any sentiment analysis: simply try to match the words in the current sentence with sets of words associated to each emoticon.

Example:
👍  may match "ok", "yeah", "way to go", "yes", etc.
