### ISSUE TITLE
The currency symbol does not match the language of the keyboard

### ISSUE THREAD

**Issue by xmiseggs** [AnySoftKeyboard/AnySoftKeyboard#1403]
The currency symbol must match the selected language. My keyboard is in Spanish and in Spain the euro currency is used (€)

![unnamed](https://user-images.githubusercontent.com/29940632/41376377-5cd2e696-6f59-11e8-9623-edba47d674f8.png)

**Comment by justpilot** [comment]
The problem still remains. Would be nice if there would be an option.

**Comment by dilworks** [comment]
Go figure, my language IS Spanish, but I'm now getting the euro key after the last update at F-Droid. Except... that I'm on Venezuela, where we use (and prefer!) $, not €!

Any way to revert this?

**Comment by DanielTheGreat** [comment]
I'm currently on AnySoftKeyboard v1.12 on an Android 13 Samsung phone.
I've used this excellent keyboard for several years on different phones, but only now is it misbehaving.
My Android System Language is 'English (Australian)', and AnySoftKeyboard is set use 'System' language.  But when I open the keyboard's numeric [123!#()] pane the default currency symbol is £ when it should be $.
I know I can long-press the £ to select $, but I shouldn't have to do that.
Is this a setting issue (I can't find it) or an unfixed bug?
