### ISSUE TITLE
Auto caps and autocorrect not working in many apps

### ISSUE THREAD

**Issue by cdysthe** [AnySoftKeyboard/AnySoftKeyboard#1405]
### Steps to reproduce
For example open the DuckDuckGo Privacy search app/browser. Type in the search field. Another example is when writing an app review on Google Play. 

### Expected behaviour
First letter should be capitalized.  Auto correct and word suggestion should work. 

### Actual behaviour
No first letter caps or autocorrect. Works in other keyboards. There are other apps where the same thing happens. No first letter caps and correction . 

**Android OS version:*
8.0.0

**Device manufacturer and model:**
Moto X4

**List of installed add-ons (like languages, or themes):**
Norwegian language pack.

**Comment by menny** [comment]
I think that auto-caps does not work in search and URL related fields. Do you see auto-caps not working in other apps?

**Comment by cdysthe** [comment]
@menny Off the top of my head I remember four: The comment field in Should I Answer Personal Edition. The text editor in Total Commander and Solid Explorer. The self text field in Red Reader.
