### ISSUE TITLE
Keyboard doesn't display suggestions after upgrading to version 1.9.2055

### ISSUE THREAD

**Issue by J316** [AnySoftKeyboard/AnySoftKeyboard#1415]
### Steps to reproduce
1. Upgrade to version 1.9.2055
2. "Show suggestions" set to on

### Expected behaviour
Keyboard should show suggestions while typing

### Actual behaviour
After upgrading to version 1.9.2055 no suggestion is displayed

**Android OS version:**
Any

**Device manufacturer and model:**
Any

**List of installed add-ons (like languages, or themes):**
None

**Comment by avalx** [comment]
I have the same problem!

System: Oneplus 3, OxygenOS 5.0.4, Magisk Root, AnySoftKeyboard version 1.9.2055, Slovene Language Pack, Yochees Dark Theme

I also tried and toggle the "Show suggestions" several times without any success.

Any hope to get this solved in next release?
