### ISSUE TITLE
ASK swaps space and punctuation even when both are stroked

### ISSUE THREAD

**Issue by ArenaL5** [AnySoftKeyboard/AnySoftKeyboard#1421]
### Steps to reproduce
1. Go to Language → Tweaks and more and enable Punctuation swap
2. Type the beginning of any word, and use the suggestion bar to complete it. Make sure that a space is automatically added after this word.
3. Type any punctuation sign.
4. Now type any word manually, without using the suggestion bar (i.e. typing every letter).
5. Type any punctuation sign.

### Expected behaviour
The space and punctuation should swap places in step 3, but not in 5.

### Actual behaviour
They swap places in both steps 3 and 5.

**Android OS version:** Android 4.4.4 Kitkat

**Device manufacturer and model: Vodafone Smart 4 Turbo (rebranding of a Qualcomm/Yulong chinese model)

**List of installed add-ons (like languages, or themes):** AnySoftKeyboard **1.9.2144** (Beta from Google Play), and Spanish **2.1.255** for AnySoftKeyboard (also from Google Play)

**Comment by xmiseggs** [comment]
Just mention that in Gloogle Play the current version of the keyboard is 1.9.2055 and the Spanish language version is 2.1.255.

**Comment by ArenaL5** [comment]
That's odd. I never noticed them updating, but right now version numbers read 1.9.2144 for the main ASK app, and 2.1.255 for the Spanish keyboard.

The same bug persists, so I'll edit my initial report. Thank you.
