### ISSUE TITLE
Delete word while gesture typing

### ISSUE THREAD

**Issue by TimMagee** [AnySoftKeyboard/AnySoftKeyboard#1426]
It seems that ASK will get gesture typing soon. I'm quite excited for this upcoming feature. As gesture typing ifs not always the most accurate way to type, it is frequently necessary to remove the most recently added word. Currently that requires removing the entire word character by character. Google's implementation allows the user to instantly remove the most recent word by hitting the backspace key once. I feel this could greatly improve gesture typing speed. 
PS: this post was gesture typed using ASK.

_Sent from my Galaxy S5 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by swedneck** [comment]
This is the second most annoying part of gesture typing right now,  only beaten by gesture typing sometimes not working at all.

**Comment by xmiseggs** [comment]
In some keyboards, for example Fleksy (if I remember correctly) with the finger pressed on the backspace key and without lifting the finger is made the gesture of movement to the left and then lift the finger, this erases the last word, if we perform the same action and does not lift the finger at the end are erasing word by word until the finger is lifted or there are no more words.

**Comment by TimMagee** [comment]
@xmiseggs this seems confusing and undiscoverable.  I don't want to have to press and slide on the backspace key.

**Comment by xmiseggs** [comment]
As you indicate you can not pretend to delete an entire word just once pressed the backspace key, a press on the backspace key is deleted from a character and the action that I commented on my previous comment is done in both Fleksy, Gboard and Swiftkey.

**Comment by swedneck** [comment]
perhaps there could be an option for press and slide vs automatically switching between word deletion and character deletion?

**Comment by menny** [comment]
I'm a bit confused now. Today, if you swipe from backspace to the left, it will delete the last entered word (be via gesture-typing or old-school-typing).

Can we say this is done?

@xmiseggs @TimMagee

**Comment by xmiseggs** [comment]
@menny It's working.
For my part it's done.
Thank you.
