### ISSUE TITLE
Automatic Wordlist settings seems not work correctly

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1427]
NB. All item names are translated from the Dutch version of AnySoftKeyboard, so maybe not complete correct. The used version is the latest from F-droid. v1.9-r4

In the setting for "Special wordlists>automatic wordlist" there are three options:
"Choose learning method"

1. "after a while of use"
2. "direct after typing"
3. "Don't learn new words"

Option 2 and 3 work as option 2. There is no difference, the words will add immediately to the word-list.

Thanks.
 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by Larx** [comment]
#1376
