### ISSUE TITLE
S

### ISSUE THREAD

**Issue by qvestinf** [AnySoftKeyboard/AnySoftKeyboard#1434]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by ildar** [comment]
?

**Comment by TimMagee** [comment]
I feel this "issue" can be safely closed.

**Comment by menny** [comment]
Z
