### ISSUE TITLE
[QUESTION] Word suggestions visible with no top row

### ISSUE THREAD

**Issue by Hal47** [AnySoftKeyboard/AnySoftKeyboard#1436]
I like to have word suggestions show up on top of the keyboard without having any other keys (outside the standard keyboard) on it. 

Is it possible already in-app?

**Comment by ArenaL5** [comment]
Word suggestions are displayed on its own bar above the keyboards, no matter what layout do you choose.

I'm not sure I understand the question. If you still have an issue, could you upload a screenshot?
