### ISSUE TITLE
There's no auto space after comma . 

### ISSUE THREAD

**Issue by cdysthe** [AnySoftKeyboard/AnySoftKeyboard#1438]
### Steps to reproduce. 
Type a word and a comma. 

### Expected behaviour
An extra space should be added after comma just like it is for period. 

### Actual behaviour
No extra space is added. 

**Android OS version:*
8.1.0

**Device manufacturer and model:**
Moto X4

**List of installed add-ons (like languages, or themes):**
Norwegian language pack.

**Comment by Strubbl** [comment]
still valid

**Comment by Strubbl** [comment]
Why does the bot close this? It's still valid?

**Comment by 122800** [comment]
This issue now should probably be followed up in #2061 anyway.
