### ISSUE TITLE
[Feature Request] Workman Keyboard Layout

### ISSUE THREAD

**Issue by maverick74** [AnySoftKeyboard/AnySoftKeyboard#1440]
I recently found the Workman Keyboard Layout and while i believe there maybe a many others out there i was kind of convinced by this one.

I leave the suggestion for analysis / discussion here :)

http://workmanlayout.org/

**Comment by menny** [comment]
Also, need to update change-log

**Comment by menny** [comment]
Waiting for change-log addition

**Comment by ajgrf** [comment]
Well, I'm not sure I understand the file formats involved. This week was my first foray into Android development and it mostly just involved editing XML files.

**Comment by menny** [comment]
No worries. I'll handle that. Thank you for your contributions
