### ISSUE TITLE
Galaxy note 8 () {} [] showing wrong direction

### ISSUE THREAD

**Issue by Ds770** [AnySoftKeyboard/AnySoftKeyboard#1448]
### Steps to reproduce
1. i'm using anysoftkeyboard hebrew version
2. android 8.0.0. build number R16NW.N950FXXU3CRF4
3.

### Expected behaviour
Tell us what should happen
when i press ( or ) in hebrew, its show it wrong on certain apps like whatsapp and more. on gmail work good. i made video and here is the link: [](https://youtu.be/OBQhKyHT8ww)
in english is work fine
### Actual behaviour
Tell us what happens instead

**Android OS version:**
8.0.0
**Device manufacturer and model:**
 samsung galaxy note 8 model SM-N950F
**List of installed add-ons (like languages, or themes):**
hebrew
1. i'm not a programer, so if you guys need any more information let me know
2. english is not my native language so i have some typing mistakes

thank you

**Comment by pnehren** [comment]
How are you writing these characters? I can not find them...
