### ISSUE TITLE
AMOLED/black & white theme

### ISSUE THREAD

**Issue by swedneck** [AnySoftKeyboard/AnySoftKeyboard#1450]
There is currently a black theme that has some colors in it, so it should hopefully be easy to just copy that theme and make it completely black & white.

**Comment by uudruid74** [comment]
Why black and white? Black and red or black and green wood actually use a lot less power than white

**Comment by swedneck** [comment]
Because black and white is what most people associate with AMOLED, and looks much better than black and green/red. It's partly about saving a little extra battery, but also about looking nice.

**Comment by uudruid74** [comment]
Colorless doesn't look good at all. I would say maybe black an Amber. Or black followed by whatever the current accent color is, if that can be found programmatically

**Comment by swedneck** [comment]
You're free to prefer other aesthetics, but there are a lot of people who like white on black "AMOLED" themes.

**Comment by uudruid74** [comment]
AMOLED themes are defined by preponderance of black. I don't believe you're allowed to speak for a lot of people for your preference to White. You speak for yourself only. Everyone else can speak with their own voice

**Comment by ilovelinux** [comment]
I think that an AMOLED theme like [the Google's one](https://www.xda-developers.com/files/2016/05/amoledtheme-1024x818.png) is a must
I honestly don't like keyboards with red/green keys and the blue ones burn my eyes when I'm in the dark
Maybe I never seen a good keyboard layout with red/green keys

**Comment by menny** [comment]
In the next release, there will be "Power-Saving mode" theme. It's exactly that.

**Comment by Mikaela** [comment]
So this is hidden to power saving settings that have to be always enabled and then some disable checkboxes have to be removed?

I think ASK is getting more and more complicated whenever I search for features I am missing :(

PS. On AMOLED colours I have aquired preference to (obwiously black and) orange. See PUMPKIN for SwiftKey.

**Comment by uudruid74** [comment]
If you want it to switch when battery is low, thats under power-saving.  An always-black theme exists (I use it) in the usual place, and you can add more as you did.

**Comment by Mikaela** [comment]
Do you mean *Simple black glow* ? I missed it until reading all the names after reading your comment. However that theme uses a lot of blue and thus doesn't seem very good for late night typing.

**Comment by uudruid74** [comment]
No.  I mean Lean Dark.  It's a black theme.  Not to be confused with Lean Dark Grey

**Comment by Mikaela** [comment]
I don't know about lean dark, but the large keys version of it isn't black. I was using it until KISS Launcher update earlier today brought AMOLED Black theme and there was a noticable difference between it and ASK when something was entered to search bar.

Maybe theme descriptions should mention themes that are really black and AMOLED-friendly?

**Comment by Iizuki** [comment]
There seems to be some weird interactions between the "Power-Saving mode theme" and Night-Mode settings. Checking the "Darken keyboard theme" box brings these gray keyboxes into visibility, while without this tick it's just black (in so far as I can tell). Almost as if the "darkness" somehow overflows and starts to brighten instead..
