### ISSUE TITLE
Lack of documentation on Alt+Space language switch shortcut logic

### ISSUE THREAD

**Issue by antonok-edm** [AnySoftKeyboard/AnySoftKeyboard#1467]
This issue is in reference to the `isAltSpaceLangSwitchNotPossible` method defined [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/c7f8c2142664736ca1059a18e179468ed5ba4bb9/app/src/main/java/com/anysoftkeyboard/utils/Workarounds.java#L37) and used [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/c7f8c2142664736ca1059a18e179468ed5ba4bb9/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardHardware.java#L138).

What is the rationale behind the model check? I couldn't find anything online documenting limitations of that shortcut as it pertains to language-switching, nor any justification as to why those model strings in particular were selected.

#1465 adds a configuration option for toggling an existing Shift+Space language switch shortcut, which would be useful to add for the Alt+Space shortcut as well. It's unclear how this logic might affect the setting description, and it's preferable not to clutter extra config options on devices where they're not relevant. Ideally, it would be possible to add a comment with these details in the code as well.

**Comment by menny** [comment]
I believe this check can be safely removed.
It was introduced since Motorola Milestone devices overrode the SPACE+ALT (can't recall exactly why and how) and that broke stuff.

Feel free to remove it in your implementation of https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1465

**Comment by antonok-edm** [comment]
Awesome, I've just put that together.

I did just notice one other thing: it looks like [Alt + Right Shift](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/bb730b13fd797bb2e1033525382ddcafd97d8908/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardHardware.java#L118) is yet another shortcut for the same thing, also completely undocumented. Should I add a setting for that as well, or just remove it?

**Comment by menny** [comment]
I think it's okay to remove
