### ISSUE TITLE
Proper nouns with gesture typing in English

### ISSUE THREAD

**Issue by TimMagee** [AnySoftKeyboard/AnySoftKeyboard#1468]
Currently gesture typing does not support any proper nouns or other capitalized words. It would be nice if it did.

**Comment by menny** [comment]
@TimMagee, Can you provide some examples?

**Comment by TimMagee** [comment]
Try gesture typing the word English. It doesn't work. Also, if you press the shift key,  I would expect the next word to be capitalized. But it isn't.

**Comment by Maugrift** [comment]
The main issue brought up here (capitalizing proper nouns with gesture typing) has been fixed. However, "i" doesn't get capitalized if you gesture type a word after immediately after typing it. If you press space and then gesture type it works, but that's less ideal.

There's also the issue of being unable to capitalize a word by pressing shift and then gesture typing, which could be a really nice change. This should probably be moved to its own issue though.
