### ISSUE TITLE
Question: Delete "Emoticons" History?

### ISSUE THREAD

**Issue by 0pLuS0** [AnySoftKeyboard/AnySoftKeyboard#1477]
### Steps to reproduce
1. Begin typing in any app
2. Pick an emoticon
3. Now there is a History

### Expected behaviour
To be able to clear/delete the history

### Actual behaviour
The emoticon history is created

**Android OS version:**
Oxygen OS 5.1.5

**Device manufacturer and model:**
OnePlus 5T

**List of installed add-ons (like languages, or themes):**
English language
Yochees Dark

I have been looking around and I don't see any options.

```Can the emoticons history be deleted?```

Thanks

**Comment by 0pLuS0** [comment]
@menny thanks

Button to clear would be nice....

**Comment by l3u** [comment]
I just found this exact feature request (sadly being closed meanwhile). I would really also like to see this feature, being able to clear the smiley history without having to delete all data. Would be very nice :-)

**Comment by Steve017** [comment]
I would like to second that please.

A button would be great.

Also, as far as I can tell, no new emojis are being added to my history. Does it stop adding history when it fills up?

Even better, the ability to remove individual unwanted emojis from history...  Then we'd end up with a nice custom set.

I'll gladly settle for a clear button tho 😘

**Comment by lubenard** [comment]
Hey, i just submitted a PR that can erase recent emoji list: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2917
You cannot delete them one by one, just delete the whole list
