### ISSUE TITLE
Tiny font size for words in suggestion bar

### ISSUE THREAD

**Issue by MrPointer** [AnySoftKeyboard/AnySoftKeyboard#1482]
### Steps to reproduce
1. Simply type some chars to "ignite" the suggestion engine/bar
2. All words are barely visible

### Expected behaviour
Ordinary font size as it has been for years.

### Actual behaviour
Tiny font size, barely visible.

**Installed App Version: 1.9.2400, version code 4975**

**Android OS version: 8.0**

**Device manufacturer and model: Samsung Galaxy S8**

**List of installed add-ons (like languages, or themes): Hebrew language, Russian language**

**Comment by menny** [comment]
Could you try this version: https://3364-4063516-gh.circle-artifacts.com/0/apks/debug/app-debug.apk

You will need to uninstall the version you have right now before trying to install this one.

**Comment by MrPointer** [comment]
@menny Just checked it - Works perfectly!
When will this version will be officially out? Do you recommend to keep using it?

**Comment by menny** [comment]
I'll release later today. Should be available in a few hours.
You will need to uninstall this one before installing the production
version again
Thanks for verifying

**Comment by menny** [comment]
fix in https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1486
