### ISSUE TITLE
Sardinian (sc) does not appear in the language list - app version: 1.9.2445

### ISSUE THREAD

**Issue by asereze** [AnySoftKeyboard/AnySoftKeyboard#1488]
### Steps to reproduce
1.Opened the app
2. Opened the "Tweaks" option menu and the "Force language" option
3. Searched for the language in the list

### Expected behaviour
I though I would find Sardinian (sc) in the list.

### Actual behaviour
It's not there.

Android OS version:
Android 8.1 (lineage OS 15.1)

Device manufacturer and model:
Xiaomi Redmi Note 4X

List of installed add-ons (like languages, or themes):
No themes, four languages (Italian, English, Portuguese and the Sardinian one I created)

**Comment by asereze** [comment]
I did it about a year ago, the app has been translated for a while.

**Comment by asereze** [comment]
The problem is still there. Sardinian was available in the list of one of the beta versions from the beta program in Google Play, but it's still not available in the stable one.

**Comment by asereze** [comment]
Why was this closed? I commented on it.

**Comment by AnXh3L0** [comment]
@asereze the bot has some issues, reopening.

**Comment by asereze** [comment]
Closed by https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3188
