### ISSUE TITLE
Simple bottom row makes using single quotes difficult

### ISSUE THREAD

**Issue by pudup** [AnySoftKeyboard/AnySoftKeyboard#1493]
### Steps to reproduce
1. Use simple bottom row or something similar
2. The symbols area has no single quote.

### Expected behaviour
Symbols panel has a single quote button

### Actual behaviour
Single quote is only found by long pressing the comma on the bottom row

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by headglitch** [comment]
Why hasn't this been fixed nearly two years later?
