### ISSUE TITLE
Strange backspace behaviour in Firefox 

### ISSUE THREAD

**Issue by JohnVeness** [AnySoftKeyboard/AnySoftKeyboard#1495]
### Steps to reproduce
1. Open Firefox
2. Find a web form (e.g. a Github new issue form)
3. Type a word, e g. "hello" followed by space
4. Type another word, e.g. "world" followed by space
5. Press backspace

### Expected behaviour
Should see "hello world" in the form.

### Actual behaviour
See "helloworld" in the form.

**Android OS version:**
6.0
**Device manufacturer and model:**
Sony Xperia Z5 Compact
**List of installed add-ons (like languages, or themes):**
English language, no themes.

**Comment by AnXh3L0** [comment]
Hello @JohnVeness ,
Thank you for opening this issue.

I managed to reproduce the bug on my device too, and also noticed it doesn't happen only on Firefox form boxes, but also in many other cases.

I'm going to investigate. Will let you know soon.

**Comment by marmistrz** [comment]
I'm also affected by this bug.

**Comment by MicroBeast** [comment]
Seem related to suggestions. Turning off Show suggestions in AnySoft settings "solve" this.
Well, it brought another issue if we want the suggestion to show up.
