### ISSUE TITLE
Preferences title font size

### ISSUE THREAD

**Issue by FTno** [AnySoftKeyboard/AnySoftKeyboard#1496]
The font size in settings (tweaks) is very large (too large) and the text is thus shortened several places, as seen in the example screenshot below.
The size is bigger than in the section headings and even the main title at the top.

![screenshot](https://user-images.githubusercontent.com/16176811/47227981-62d55900-d3c4-11e8-86ea-7118eed46cf8.png)

The font size is also substantially larger than what is common in my other apps.

Version 1.9.2445 (5020) F-Droid
Samsung Galaxy S7 Nougat

**Comment by menny** [comment]
yeah... I'll figure out a different theme for preferences.
