### ISSUE TITLE
Autocorrect doesn't keep casing

### ISSUE THREAD

**Issue by hoshsadiq** [AnySoftKeyboard/AnySoftKeyboard#1505]
### Steps to reproduce
1. Type "Theyll"
2. Notice word prediction favours "they'll" over "They'll"
3. Press [Space] to autocomplete

### Expected behaviour
Due to the casing, it should predict and autocomplete "They'll" over "they'll", conversely, if the original word was "they'll", it should predict "they'll".

### Actual behaviour
It autocompletes "they'll"

**Android OS version:**
Android 8

**Device manufacturer and model:**
Sony Xperia Z3 Compact

**List of installed add-ons (like languages, or themes):**
None, using keyboard: English Latin keyboard with symbols (on long press)

**Comment by Strubbl** [comment]
still valid issue.

**Comment by Strubbl** [comment]
Why does the bot close this? It's still valid?
