### ISSUE TITLE
Have to press Space Bar mutliple times before Space Character gets entered

### ISSUE THREAD

**Issue by sikaiser** [AnySoftKeyboard/AnySoftKeyboard#1506]
### Steps to reproduce
1. Press Space Bar (Classic no mic bottom row)
2. Note: haptic and visual feedback (visual = button changes color)
3. Note: no space character was entered

### Expected behaviour
Space Character should be entered every time

### Actual behaviour
No Space Character is entered

**Android OS version:**
7.0

**Device manufacturer and model:**
Umi Super
IMPORTANT: This phone has touch screen issues and I believe I also notice sometimes in other apps that I get haptic and visual feedback but the touch doesn't really get processed further.
But: In other Keyboards (notably Gboard) I do not have this problem, even though the Space Bar is in the same spot on the screen. This is why I decided to report it as an issue here.

**List of installed add-ons (like languages, or themes):**
German Language
Swiss Language

**Comment by AnXh3L0** [comment]
Hi @sikaiser

Thanks for opening this issue.

Unfortunately I couldn't reproduce this bug on my devices. As you mentioned, the device has touch issues so I wouldn't trust it to work reliably.
