### ISSUE TITLE
The graphic accent

### ISSUE THREAD

**Issue by OsvaldoMorinigo** [AnySoftKeyboard/AnySoftKeyboard#1509]
### Steps to reproduce
1.Open the keyboard
2.Hold any vocal (aeiou)
3.The first character is a à, in spanish this is wrong, because the right way is á, and this is not comfortable, specially when you try to type fast.

### Expected behaviour
Tell us what should happen
When you hold a vocal the first character should be á
### Actual behaviour
Tell us what happens instead
The keyboard shows an à
**Android OS version:**
6.1
**Device manufacturer and model:**
Samsung J2 Prime
**List of installed add-ons (like languages, or themes):**
Spanish pack

**Comment by AnXh3L0** [comment]
Hello @OsvaldoMorinigo, does this still happen with the latest ASK version for you?
