### ISSUE TITLE
Power Saving keyboard theme improvements

### ISSUE THREAD

**Issue by Maccer1** [AnySoftKeyboard/AnySoftKeyboard#1510]
Right now this is the power saving keyboard in v1.9-r6:

![20181027_172342](https://user-images.githubusercontent.com/8525464/47605969-84aa8d80-da0d-11e8-9c61-863f98994ba0.png)

I think it would look better (and save more battery life with AMOLED displays) if the bottom bar buttons had the same color as the rest of the keyboard. Something like this:

![20181027_172342](https://user-images.githubusercontent.com/8525464/47606056-1f579c00-da0f-11e8-84e0-5ac8b4398fdf.png)

The main changes are the background color of the key and the color of some symbols that go from white to gray (emoji, erase and shift symbols).

By the way, is it possible to hide the bottom bar with the icons? I'd like to do it to have more vertical space on my screen :)

More info:
* OS: Nougat 7.0
* AnySoftKeyboard v1.9.2481 release 5056, first release installed was 5020.
* Keyboard theme: Lean Dark - Large
* Language: Spanish

**Comment by swedneck** [comment]
This would be lovely, as well as making this keyboard available as a separate theme instead of power saving option!

One thing though, maybe the enter key should also be greyscale?

**Comment by menny** [comment]
makes sense
