### ISSUE TITLE
Spanish layout lacks ü

### ISSUE THREAD

**Issue by Undigon** [AnySoftKeyboard/AnySoftKeyboard#1514]
### Steps to reproduce
1. Install AnySoft Keyboard
2. Select Spanish layout
3. While writing, long press **u**

### Expected behaviour
Letters ú and ü should appear as options to be selected

### Actual behaviour
Letter ú appears as the only option.

**Android OS version:** 8.1.0

**Device manufacturer and model:** Nokia 6.1 _TA-1045_

**List of installed add-ons (like languages, or themes):** AnySoftKeyboard: Spanish

All downloaded through F-Droid.
That letter is important to write some words like _pingüino_ and _ungüento_.

**Comment by ArenaL5** [comment]
It's already added on master.

@menny is currently speaking with F-Droid to update the app.

**Comment by AnXh3L0** [comment]
Closed as fixed.
