### ISSUE TITLE
Suggestion: Add an even lower vibration mode

### ISSUE THREAD

**Issue by sophie-glk** [AnySoftKeyboard/AnySoftKeyboard#1515]
This is the one thing that annoys me the most. The lowest setting is still way to high. The way Swift Key for example has implemented it, is in my opinion just perfect.

Device:
Galaxy s9+
AnySoftKeyboard v1.9.2445
OS: Oreo 8.0

**Comment by ilovelinux** [comment]
Instead, the lowest setting on my smartphone is so low that I can't feel the vibration. I can feel the medium vibration only if I pay attention to it. I actually had to set vibration to high

AnySoftKeyboard v1.9.2445
Android Nougat 7.0

**Comment by tt7753** [comment]
Seems to be very device specific, on my one plus 3 and my moto g it was fine. So my new/updated suggestion would be to add a slider, with which we can set the strength continuously.

**Comment by ilovelinux** [comment]
Is there a way to know the maximum vibration supported by the device?

**Comment by matsest** [comment]
On my Huawei Mate 9 Pro it is also way to high, so I'm currently keeping it turned off. Agreed that input as vibration length (in ms) as SwiftKey has would be perfect.

AnySoftKeyboard 1.9.2445, version-code 5020
Android: 8.0.0 (EMUI LON-L29 8.0.0.378(C432))

**Comment by matsest** [comment]
FYI this also works as a fix. Could it be implemented to choose this value manually in the application? 

https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/698#issuecomment-423795917
