### ISSUE TITLE
[Feature request] behavior of Ctrl like on a PC 

### ISSUE THREAD

**Issue by bkqtnte10** [AnySoftKeyboard/AnySoftKeyboard#1516]
it would be nice to have Ctrl-c as copy,  ctrl-a as "select all" and so on. I have seen it implemented in BeHe keyboard: https://github.com/VladThodo/behe-keyboard/

**Comment by jstsmthrgk** [comment]
This would create problems for certain apps (e.g. SSH clients) because these key combinations mean something else there.
