### ISSUE TITLE
Allow to choose two (or more?) dictionaries for word correction or guess in which language are you typing and use that language's dictionary

### ISSUE THREAD

**Issue by ilovelinux** [AnySoftKeyboard/AnySoftKeyboard#1517]
Hi guys,
I often switch between two languages and it's a bit annoying to have to change keyboard layout every time just for word correction because chars are almost the same.
It would be awesome if you add something to suggest words of both dictionaries language like lots of keyboards already do

**Comment by maverick74** [comment]
Please see if this is what you want:

When ready to type, long press "enter" key and then choose "overide active dictionary" and mark the ones you want.

This way the keyboard layout you use will make use of the dictionaries you marked...

Was it this you were looking for?

**Comment by ilovelinux** [comment]
Yes, I didn't know it! Thank you!
