### ISSUE TITLE
Contributing my src code to repository

### ISSUE THREAD

**Issue by VitaliPom** [AnySoftKeyboard/AnySoftKeyboard#1526]
Hi,
I apologies if this is a wrong place to ask, I know I made a separate keyboard but it is indeed separate and hey, it's free so you can download it if it fits your needs. I do however work on my separate repository on my Pc with some cool, very nice mockups fir Anysoftkeyboard. The good news are that the two work great together, like you don't have to uninstall one to use another, but each have different combination of options instead and I just switch between one another to use each set of features every time, very cool.
#  I wanted to ask. Maybe can someone please help me commit the changes? I'm really struggling with this on my own.
Many thanks,
Vitali

**Comment by menny** [comment]
@VitaliPom sure, let's get your features into AnySoftKeyboard. Can you provide a list of features you want to merge into ASK?

**Comment by VitaliPom** [comment]
gosh thanks, I'm so happy I will have a chance to contribute to
Anysoftkeyboard and to github as well :D
This is really a great chance for me,
Maybe we can set up a code review for two of us both later on? I need to
explain of what I did and there are plenty of features over there, but
truthfully very nice.

**Comment by VitaliPom** [comment]
Closed the issue, Menny helped me and Jopper said to close my non-open opened issues :)
