### ISSUE TITLE
Any manual how to customize keyboard layout?

### ISSUE THREAD

**Issue by vvch** [AnySoftKeyboard/AnySoftKeyboard#1529]
Is there any manual how to build my own customized keyboard layout (XML file AFAIU) and make the program to use it? Tried to find one but did not succeed.

**Comment by reaysawa** [comment]
I'm also interested. Currently following this [PR](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1449/files) as a base for how to go about this.

I think it would be possible to register new resources for a custom layout the same way plugins do it, however I do not know how to setup this. I think one of the places to look at would be [AddOnsFactory.java](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/java/com/anysoftkeyboard/addons/AddOnsFactory.java).

If you have root access to your device, you can go to the [data directory](https://android.stackexchange.com/questions/47924/where-android-apps-store-data) and follow that PR as a guide to modify the files.

**Comment by select** [comment]
I just read https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1581#issuecomment-454597290 maybe this helps
