### ISSUE TITLE
Back-word feature should remove some previous whitespace and room for improvements.

### ISSUE THREAD

**Issue by titoBouzout** [AnySoftKeyboard/AnySoftKeyboard#153]
I'm currently creating a custom layout for my language, and the key "delete" defaults to delete "backword" (because I prefer this way). like this:

```
<Key android:codes="-7" android:isRepeatable="true" android:keyEdgeFlags="right" ask:hintLabel=" " android:popupCharacters="" android:keyIcon="@drawable/sym_keyboard_delete"  android:keyWidth="15%p"  ask:isFunctional="true"/>
```

I think this function(delete back-word) can be improved to provide what it seems a useful  behaviour. Currently it seems, it only delete the previous word, and non-words are deleted char by char.

Suggestions:

**1.**
When the previous characters are just "whitepspace" remove all the whitespaces till the first non-whitespace char.

For example this: 

```
and some words.    |
```

 will become this:

`and some words.|`

**1.1** 
An exception when there is newline characters:

```
and something.
        |
```

will become

```
and something.
|
```

**2** 
First hit to delete "back-word" should remove just the previous char. _this allow corrections of the last typed char(when we notice we made an spelling)_. Next hits should remove whole words.
For example:

```
and I made a typi|
```

will become 

```
and I made a typ|
```

then, if I hit delete again(or If I keep pressed the "delete" key), should become:

```
and I made a |
```

**3** 

A timeout, to allow _char by char_ deletion. similar to previous suggestion, if I hit "delete backword", then wait a little bit (good idea to have it configurable via preferences, such 120ms), the next hit to "delete backword" will delete just 1 char.

For example:

```
and some text|
```

will become

```
and some tex|
```

wait 190ms, hit again "delete backword" will become

```
and some te|
```

etc..

I run out of imagination with this function.. for now :)

**Comment by menny** [comment]
I've made some improvements
