### ISSUE TITLE
Can you add symbols like "{}<>_" and other, please

### ISSUE THREAD

**Issue by Gidross** [AnySoftKeyboard/AnySoftKeyboard#1538]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by pnehren** [comment]
+1 

I was shocked that many characters are missing. Also [] are not available. Is it possible to add them?

**Comment by ArenaL5** [comment]
All those characters are on the second page of symbol characters. To open that second page of symbols, click on 123!#(), then on {}_

Those symbols are there on the current package on F-Droid, so this issue is already fixed.
