### ISSUE TITLE
Blank "Key preview" for some keys 

### ISSUE THREAD

**Issue by titoBouzout** [AnySoftKeyboard/AnySoftKeyboard#154]
Currently, the "Key preview", of some characters are just "blank". Not sure if I'm doing something wrong.

For example arrows ↑  and ↓ correctly show ↑  and ↓ as "key preview", respectively, when long-pressed and repeatable = true, like this:

```
<Key android:keyHeight="@integer/key_short_height" android:keyWidth="12.5%p" ask:isFunctional="true" android:codes="@integer/key_code_arrow_up" android:isRepeatable="true" android:keyEdgeFlags="left" ask:hintLabel=" " android:popupCharacters=""/>
        <Key android:keyHeight="@integer/key_short_height" android:keyWidth="12.5%p" ask:isFunctional="true" android:codes="@integer/key_code_arrow_down" android:isRepeatable="true" android:popupCharacters="" ask:hintLabel=" "/>
```

but with the same configuration, with keys  ← and →, it shows a completely black "key preview". Sometimes, the "key preview" shows correct for some ms, but these get black quickly.

```
<Key android:keyHeight="@integer/key_short_height" android:keyWidth="12.5%p" ask:isFunctional="true" android:codes="@integer/key_code_arrow_left" android:isRepeatable="true" android:popupCharacters="" ask:hintLabel=" "/>
        <Key android:keyHeight="@integer/key_short_height" android:keyWidth="12.5%p" ask:isFunctional="true" android:codes="@integer/key_code_arrow_right" android:isRepeatable="true" android:popupCharacters="" ask:hintLabel=""/>
```

Something similar happens with some other keys, such ",.?!", when you hit these quickly. ( I have some vague suspicious that this happens, when a hit of these keys cause a change of caps(visual change caps in all the keyboard), for example, moving the cursor(with right and left arrows) inside this text: " . . . . . . . . . ")

**Comment by AnXh3L0** [comment]
Closing this, same with issue https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/176
