### ISSUE TITLE
Show typed letters in gesture-typing

### ISSUE THREAD

**Issue by leafcutterant** [AnySoftKeyboard/AnySoftKeyboard#1546]
(aka. swipe/swiping/swype/swyping)

### Steps to reproduce
1. Try to gesture-type something.

### Expected behaviour
ASK should show which letters have been input so far (show the "progress"), so that I know if I'm getting it right.

### Actual behaviour
I only see the end result, and I have to wait until the word is finished to see that I've made a mistake.

**Comment by leafcutterant** [comment]
Not stale. Bad bot.

**Comment by leafcutterant** [comment]
Does the close mean this will be implemented?

**Comment by Masqueey** [comment]
Try manually closing/opening it, or open new issue referencing this one
