### ISSUE TITLE
Allow gesture-typing without autocorrect

### ISSUE THREAD

**Issue by leafcutterant** [AnySoftKeyboard/AnySoftKeyboard#1547]
(aka. swipe/swiping/swype/swyping)

### Steps to reproduce
1. Try to gesture-type something.

### Expected behaviour
The letters I've gesture-typed will be entered.
If I want ASK to try to guess what I'm trying to gesture-type, I can set that in the settings.

### Actual behaviour
ASK tries to guess what I'm trying to gesture-type based on its own dictionary and inserts that word.
I have no way of disabling this.

**Comment by menny** [comment]
I don't think I understand the issue. Can you give more details?

**Comment by leafcutterant** [comment]
Sorry, I meant autocorrect, not autocomplete. Title corrected.

The issue is that with gesture-typing you can only input words that are contained in the dictionary.

Let's assume I want to gesture-type "[Toulon](https://en.wikipedia.org/wiki/Toulon)". I can't; it will autocorrect to "typhoon". I wanted to gesture-type "wahahaha" but got "earthquake".

The built-on dictionary will never be able to cover everything people want to write. For those who are proficient at gesture-typing and want to utilize its speed for every word, there should be an option to disable autocorrect for gesture-typing and enter only the characters that were registered by the keyboard.

**Comment by menny** [comment]
when swiping "wahahah" you are swiping over "wasdfghgfdsasdfghgfdsasdfgh"
Even if we'll only take letters that are at corners many words could not be created. For example, "typo" is "tyuiopo"

**Comment by leafcutterant** [comment]
Gesture-typing, as far as I understand, only takes letters you stop over, thus my proposal. (Or am I wrong?)

**Comment by PhilippLoewen** [comment]
@leafcutterant as far as I understand gesture typing takes all letters you pass over into account. The word "top" for example only requires me to move my finger from "t" to "p". I don't have to stop on "o".

**Comment by leafcutterant** [comment]
@PhilippLoewen If I slide from "t" to "p", I get "to". And if it would work like you described (all letters taken into account), that would be pretty bad. Imagine typing "avocado" -- you pass over hell of a lot of letters that are not in that word. (And I can type "avocado" like that.)

**Comment by Samgarr** [comment]
I was used to gesture typing even with disable autocorrect with SwiftKey Keyboard. With AnySoftKeyboard with disabled autorcorrect gesture typing not working at all - characters are not typed. It would be nice to use gesture typing without autocorrect.

**Comment by leafcutterant** [comment]
Not stale.

**Comment by leafcutterant** [comment]
I repeat: not stale. Requesting re-opening.
