### ISSUE TITLE
After word selection convert two spaces to period+space

### ISSUE THREAD

**Issue by Strubbl** [AnySoftKeyboard/AnySoftKeyboard#1549]
### Steps to reproduce
1. Go to Language --> Tweaks
2. Activate option that double space key inserts a period
3. Go to more settings and activate also the option to add a space after a word selection/completion
4. Go to an app with an input field
5. enter a word and use the word completion. Now the word incl. a space is in the input field, e.g. `Test `
6. Press space key, now you have two spaces after the word instead of a period

### Expected behaviour
With the above settings, it would be convenient, if two spaces after a word completion were converted to period+space. E.g. `Test. `

### Actual behaviour
I have two spaces after the word and no period is inserted. E.g. `Test  `

**Android OS version:** Lineage 14.1 (Android 7.1.2)

**Device manufacturer and model:** Sony Xperia Z5 compact

**List of installed add-ons (like languages, or themes):** German language

**Comment by Strubbl** [comment]
I think this issue is related to #1433

**Comment by ArenaL5** [comment]
It does seem like a duplicate.

Thank you for your report, anyways. Two spaces should convert to period & space, and it should be possible for that conversion to be canceled with a backspace in case of accidental conversion.

Please check if there's some progress at the original #1433.
