### ISSUE TITLE
'undo deleted'

### ISSUE THREAD

**Issue by titoBouzout** [AnySoftKeyboard/AnySoftKeyboard#155]
Yep!

I imagine to have an "undo" command.. but, something _very simple_ as: 
- If the last pushed key was "delete"(the command)
- the keyboard can have _somewhere_, the deleted text.
- then, a command "undo delete" is available, 
- if the user presses "undo deleted", the text is restored.
- if instead, the user presses any other key after deleting, the undo history is just trashed.

Just an idea, which _looks like_ simple and useful

**Comment by tympan** [comment]
The absence of an Undo key or gesture on mobile devices has been discussed on a usability mailing list I subscribe to. The consensus seems to be it would be very welcome. Wouldn't it be nice if AnySoftKeyboard was the first to provide this?

**Comment by menny** [comment]
@tympan , can you point me to the mailing list thread?

**Comment by tympan** [comment]
It's a private mailing list in the Usability profession but I'll ask the 
posters for permission to send you the thread. Couple of days.

///Peter

**Comment by menny** [comment]
Closing for now

**Comment by tympan** [comment]
On 05/13/2015 02:49 AM, Menny Even Danan wrote:
> @tympan <https://github.com/tympan> , can you point me to the mailing
> list thread?

The authors have agreed, but not for publication on the list.
If you can mail me your personal address I can send it there.

///Peter

**Comment by menny** [comment]
You can find my email address at https://github.com/menny
