### ISSUE TITLE
[Feature] Support switching to other keyboard app easily 

### ISSUE THREAD

**Issue by Tikotik** [AnySoftKeyboard/AnySoftKeyboard#1552]
As of now, switching to other keyboard app takes multiple steps :  utility keyboard-> settings -> change input method -> another kbd app.

I hope those can be shortened by adding option to switch kbd app in gestures, or by long pressing on space bar like other apps do.
One example where it is useful is password keyboards to switch temporarily and frequently like : https://github.com/Kunzisoft/KeePassDX

**Comment by TheVirtualMachine** [comment]
Looks like #1388 explains how to do this. It's easy to switch, although not very intuitive.

**Comment by Tikotik** [comment]
Yes! Switching kbd is implemented, but adding a gesture or shortcut for a specific layout would be very useful, instead of 1388.
