### ISSUE TITLE
A settings model more friendly for new users

### ISSUE THREAD

**Issue by Maccer1** [AnySoftKeyboard/AnySoftKeyboard#1554]
Hey. I've been using your keyboard for a while and I've found that it has lot of options and that can be a bit confusing at first. It took me some time to adapt. That's why I decided to create a new settings model with the aim of making it easier for the end user while still having the same settings available.

Since this is a bit long to post here, I've created a [google docs](https://docs.google.com/document/d/1cvMYS--7Q3xpDMPVRickWqUcC1caPp-aW2ZjXt9EE44/edit?usp=sharing) with the model I propose.

It's a work in progress, meaning that some things are not perfect yet but also meaning that everyone can contribute to it. Right now the link just lets people comment because it could be a mess if I let everybody edit it, but I'm open to allow some people edit it directly or I can edit it myself as well if you tell me what to change.

I wanted to know what you think and if you think this is possible to implement. Thanks! :smiley:

**Comment by menny** [comment]
Thank you for your feedback. I agree that our settings app is a mess. I'll try to incorporate this.

**Comment by Maccer1** [comment]
If you want I can create a list of the changes so it's a bit easier to do. But it will take some time to make, I'm kinda busy atm
