### ISSUE TITLE
Request: Gboard/AOSP Like Theme

### ISSUE THREAD

**Issue by 0pLuS0** [AnySoftKeyboard/AnySoftKeyboard#1557]
Great app, but this really needs a Gboard/AOSP Keyboard like theme. Even SimpleKeyboard is themed like this!

I see someone asking the same thing, and not word about this?

https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1235

So how about it?

THANKS

**Comment by menny** [comment]
Dark and light themes
Bold text
Hints

**Comment by menny** [comment]
Actually, it seems that adding this theme to AnySoftKeyboard will adding quite some size to APK. I'm going to work on this as an external theme: https://github.com/AnySoftKeyboard/LanguagePack/issues/260

**Comment by 0pLuS0** [comment]
Thanks, that really looks a lot better IMHO!

I really don't like the Themes in AnySoftKeyboard...
