### ISSUE TITLE
Can't scroll down to click tweaks in UI section with a top row selected

### ISSUE THREAD

**Issue by PopeRigby** [AnySoftKeyboard/AnySoftKeyboard#1580]
### Steps to reproduce
1. Go to UI section in settings
2. Click on "tweaks and more"
3. Click on "top generic row"
4. Click on anything besides "no top row"
5. Go back to main UI menu page
6. Realize you cant click on tweaks

### Expected behaviour
Should be able to scroll down and click tweaks. 

### Actual behaviou
You can't 

**Android OS version:**
8.1

**Device manufacturer and model:**
Moto G5 Plus

**List of installed add-ons (like languages, or themes):**
None

**Screenshot**
https://photos.app.goo.gl/7gX424HMwfQkiM7W9

**Comment by ArenaL5** [comment]
Screenshot of the bug, courtesy of @santa-klaus (uploaded to issue #1842).

 ![image](https://user-images.githubusercontent.com/10899463/64858758-90547200-d628-11e9-8baf-4ee98ecededf.png)

This should be easy to fix, but there are a lot of bugs open and the next release will take time. Please be patient.

For the moment, turn your phone. The keyboard should disappear in horizontal screen mode, and there should be more than enough space for all three buttons.

**Comment by menny** [comment]
I think that is fixed for the next release. And available now in the alpha channel. See https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1812
