### ISSUE TITLE
T9 keyboard theme for round smartwatch

### ISSUE THREAD

**Issue by luisreche** [AnySoftKeyboard/AnySoftKeyboard#1582]
I use the T9 keyboard with Portuguese Brazilian spelling checker on Zeblaze Thor 4 Plus smartwatch, AMOLED screen 1.4 inches, 400 x 400 pixels, and it works great. Only a few keys do not appear fully.
I would just suggest a theme for round smartwatch of this T9 keyboard.

**Comment by maverick74** [comment]
T9?! 

We don't have a funcional T9 yet!
see #1412
