### ISSUE TITLE
Latest version (1.9 R6) is not available in F-Droid

### ISSUE THREAD

**Issue by 0rganite** [AnySoftKeyboard/AnySoftKeyboard#1586]
The last version available in F-Droid is the 1.9 R5 (1.9.2445) and not the 1.9 R6.
https://f-droid.org/wiki/page/com.menny.android.anysoftkeyboard

I cannot simply update the ASK with the apk from github or playstore because it is not the same signature key.
I cannot simply delete the app because it is install as a system app.

Thank you for the update in F-Droid

**Comment by 0rganite** [comment]
I finally succeed to uninstall ASK with Titanium backup and reinstall the last version from play store.

**Comment by menny** [comment]
updated: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.menny.android.anysoftkeyboard.txt#L285

**Comment by Joppla** [comment]
Hello,
Thanks for updating F-Droid. But how long will it take that the uypdate is visible in F-Droid? Till now it isn't published.

Thanks for any reaction
