### ISSUE TITLE
[FEATURE REQUEST] Keyboard layout independent of language

### ISSUE THREAD

**Issue by waltherm** [AnySoftKeyboard/AnySoftKeyboard#1590]
Keyboard selection is bound to the langauge. I would like to use a keyboard independent from the autocomplete langauge.

**Comment by select** [comment]
Hi there I would also like to know if there is an option to have a keyboard that autopredicts German and English at the same time.

**Comment by waltherm** [comment]
@select: I like your suggestion, but I was initially referring to something else than mulitple languages for autoprediction. I would like to see the keyboard layout to be independent from the autoprediction language; I am fine with selecting a language currently, but constantly mess up z and y when writing in English.

**Comment by woj-tek** [comment]
Yes, please. Currently #908 got implemented (and a bunch of others in #909) but still - while layout mostly stay the same, language selection can alter is slightly - for example Spanish would add `ñ` to main keyboard, and alt-keys are completely different (which hinders muscle memory).

Ideally layout should keep completely fixed, adding language would only add accented characters to alt-keys (and there shouldn't be a need to switch languages manually)...

**Comment by matt-snider** [comment]
I also would really appreciate this functionality. As a second language speaker of German, I've always found the QWERTY layout with umlauted characters via long press much easier than switching to QWERTZ.

**Comment by regagain** [comment]
I'm switching between languages a lot and changing between qwerty/qwertz/azerty is painful. This would be very useful.

**Comment by maverick74** [comment]
See also #1094 and #1341

**Comment by Blauschirm** [comment]
I also would love to type english with the QWERTZ layout.

**Comment by woj-tek** [comment]
Yesterday I ran into https://github.com/pemistahl/lingua - I'm not exactly sure if this would be of any help (given the nature of fuzzy-matching prediction first) but maybe it could be of use somehow?

Unfortunately lack of this future stops me from using ASK on a daily basis (using regularly 3 languages - switching between them is kinda annoying…)

**Comment by ArenaL5** [comment]
@woj-tek, please try the comment Blauschirm posted:

> [...] the way to do that is to "override the default dictionary"
> Long press ENTER key and pick that option.

ASK is aware of this option being difficult to find: #1794. But this issue should be closed.

**Comment by woj-tek** [comment]
@ArenaL5 and @Blauschirm - yes, this option works so one can type in multiple languages using single layout but it's not perfect - there are no language diacritics when adding dictionaries (it seems that those only affects autocomplete/suggestions). For example after selecting: English, Polish and Spanish (and opting for Polish layout) I can't type `ñ` character (long-press on `n`).

@menny - I'm not sure whether this issue should be closed.

**Comment by matt-snider** [comment]
It would be great to be able to configure multiple layout-language pairings. For example, I might have (1) QWERTY-English and name it "English", but then also have (2) QWERTY-German and call that "German". (2) being because I want to type in German but don't like to use QWERTZ.

As @woj-tek has commented, some characters might still be missing from the key's long press menu. Maybe these can come from the configured dictionaries?

Just an idea, I understand that a change like that would be a lot of work.

**Comment by ArenaL5** [comment]
Okay, I understand the problem, and fortunately, we were already working on it.

AnySoftKeyboard already has an in-built list of default accented letters, but it's currently only used when the current layout doesn't define any. If #1921 is merged, AnySoftKeyboard Beta will allow you to add this list to the characters defined by your layout, so you'd be able to type `ñ` by holding `n`, even if it's not explicitly defined in your keyboard layout.

In the meanwhile, you can either compile your APKs directly from AnySoftKeyboard/LanguagePack if you know how, or install a language pack that has all of your desired letters.

For selecting a single language, you can use the Enter key to choose what dictionaries do you want to use. I admit that it can become quickly annoying, and some change should be made, but it seems the most flexible way to cater to every user. It would be useful to read more opinions about this.

**Comment by woj-tek** [comment]
OH, that sounds awesome! Thanks :-)
