### ISSUE TITLE
[FEATURE REQUEST] Insert punctuation after space should remove space 

### ISSUE THREAD

**Issue by waltherm** [AnySoftKeyboard/AnySoftKeyboard#1591]
When I autocomplete a word by selecting it from the list on top of the keyboard, it is possible to add a space automatically to continue writing. However, when I would like to add any punctuation (excluding hyphens), the previously added space should be removed automatically when the punctuation is added. 

If I select the word from the list, remove the space, the autocorrection is reversed.

**Comment by neolovich** [comment]
When i make a point the function works. I choose a word from the list on top of the keyboard (the space is automatically added) and when i set a point, the point is directly behind the word.
But as far as i can see, it is the only punctuation where this works. For the interrogation mark or the brackets the helpful "feature" would be nice (at least for all punctuations, as it is mentioned in the title).
