### ISSUE TITLE
Differences in languages

### ISSUE THREAD

**Issue by PapaSocrates** [AnySoftKeyboard/AnySoftKeyboard#1595]
1. On English the top row has every graphic accent and numbers, in Spanish it only has one type of accents and no numbers.

2. Almost every letter on the English one has diverse functions on hold, on Spanish only vowels.

3. Changing between languages is a chore, the spacebar is too small and the keyboard layout changes with language.

Nonetheless the keyboard is great and I will continue to use it, but as trilingual person it has some inconveniences

**Comment by Joppla** [comment]
3. I agree, and also the language change without any choose sometimes back to English
