### ISSUE TITLE
ASK still not visible in F-Droid, see also #1586

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1598]
About 6 days, see #1586, ago ASK 1.9 R6 is added to F-droid, but still not visible. How long will it take usually?

Thanks for a reaction,

**Comment by AnXh3L0** [comment]
Hi there @Joppla,

F-Droid follows a First One First Out process for building the apps. They go over each and every one and build them themselves, then the apps go through an airgapped machine (offline) that holds the signing keys to sign the apps. After that, the apps are pushed to the repos. 

Usually this process takes about a week or more, depending on high up or down the list an app is at the moment.

**Comment by Joppla** [comment]
Thanks for your reaction! For me it is clear.
