### ISSUE TITLE
Fix Record text over voice to be like the working version from v108-v123

### ISSUE THREAD

**Issue by VitaliPom** [AnySoftKeyboard/AnySoftKeyboard#1602]
Current voice record version for dictation is not working, broken and uses new Google API. Needs to revert it back, since on my older version [I checked] and it working perfectly.

**Comment by VitaliPom** [comment]
Priority 666 999

**Comment by avently** [comment]
Hey, @VitaliPom . I must say to you that you have so many issues here. And all of them looks like a private notes. They are useless to people who can read it (except you, probably). Such notes takes time to read and contributors just waste their time. So maybe, just maybe, you can close  the issues without useful content to people around this repo. I can suggest to you some apps for note taking if you want. 
Big number of issues which are not decreasing over time can make development process harder than developer wants it to be. If you want to get help or to help, make issues more detailed. It will help to understand your idea and a proposed solution.

**Comment by VitaliPom** [comment]
I'm working on those ''notes'', write me a personal message if you want to
talk.
