### ISSUE TITLE
Make new COMFORTABLE bottom row default

### ISSUE THREAD

**Issue by VitaliPom** [AnySoftKeyboard/AnySoftKeyboard#1603]

**Comment by VitaliPom** [comment]
Priority 1
--Make new branch for that one, Menny might think it's weird.

**Comment by VitaliPom** [comment]
Dexamol
META

**Comment by Joppla** [comment]
Duplicate of #1600

**Comment by VitaliPom** [comment]
@Joppla Intention was not similar, but yes they are duplicate.

**Comment by VitaliPom** [comment]
Mean that, if you want you can close my duplicates, I just feel it more comfortable to search meanwhile and anyways I think I complete them and close all next week ^^ Sorry for spam, I'm thinking more than I writing.

**Comment by Joppla** [comment]
For me it doesn't matter much, but **I think** it should be better to have all thoughts and ideas about the same problem in one dread and not in several. I m always surprised that there are more than 300 open issues in a project, but maybe you are able to solve a lot of them to make the list at the end much shorter  ;-)

**Comment by VitaliPom** [comment]
No need to make it default, I was learning and rumping up. Spammed too much in here.
