### ISSUE TITLE
Spontanious changing of language and lay-out

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1605]
Hello,

Maybe it is only a question of settings, but I have the experience that the language of my keyboard is changing automatic when a app or website is started. Standard I like to use the Dutch keyboard, but sometimes I needed to change to Polish, German, French, English or terminal. This keyboards I have pre-selected. 

Many times I start to type a message and find out that the key-board is in English in stead of the suspected Dutch. 
Is this a bug or can I change the settings in a way that the keyboard is changed t another layout only if I use the button upper-right on the keyboard.

Thanks for reaction.

### Steps to reproduce
1. It is in my opinion a spontaneity change, I don't see how to reproduce
2.
3.

### Expected behaviour
Tell us what should happen
Should stay in the chosen lay-out and language

### Actual behaviour
Tell us what happens instead
Spontaneity change of lay-out

**Android OS version:**
9, but it was also in 7 and 8 before

**Device manufacturer and model:**
Samsung S9 (but earlier I had the same problem with my S7

**List of installed add-ons (like languages, or themes):**
Dutch, Polish, Terminal

**Comment by Joppla** [comment]
Is there somebody who can answer this?

**Comment by michaelof** [comment]
@Joppla: Found your issue as an already existing issue for exactly the question I want to ask :)

Found out that you can rearrange the activated and available languages in settings / languages, simply by long clicking on a language and move / drag and drop to the desired new position.

So I moved German in my case before English. But to be honest I have no clue if there's a relation between this language sort order in settings and the way ASK "assigns" a language to a specific typing situation.

**Comment by Joppla** [comment]
@michaelof : Thanks for the advice, I will check it if the problem is solved.

**Comment by Joppla** [comment]
@all: Maybe there can make a note in the helpfiles if this is the solution?
