### ISSUE TITLE
Add option disable the annoying popup on keypress

### ISSUE THREAD

**Issue by VitaliPom** [AnySoftKeyboard/AnySoftKeyboard#1608]
The popup is really annoying, the effect of flying letters is so much better! Make it default.

**Comment by VitaliPom** [comment]
priority 1

**Comment by VitaliPom** [comment]
CODE 
Dexamol

**Comment by ArenaL5** [comment]
There are ways to disable this.

In the main configuration (AnySoftKeyboard app), go to the UI tab, then set "Animations" to "None" and "Select pop-text type" to "On any key".

**Comment by AnXh3L0** [comment]
Since this is already possible to disable, I am closing this issue as solved. Specifically, a new Settings UI would fix this for future possible bug tickets.
