### ISSUE TITLE
Make the new Popup Animation for keys as Default instead of the old Tooltip effect. 

### ISSUE THREAD

**Issue by VitaliPom** [AnySoftKeyboard/AnySoftKeyboard#1609]
There are cool animations of letters flying around inside the keyboard, I don't understand why people keep suffering with the old disturbing effect.

**Comment by VitaliPom** [comment]
priority 1 

It's impossible to type;

**Comment by VitaliPom** [comment]
CODE NAME
Dexamol

**Comment by VitaliPom** [comment]
FIXED

**Comment by Joppla** [comment]
@VitaliPom : why don't you close the item if it is fixed?

**Comment by VitaliPom** [comment]
I don't know how.
Trying to close now

**Comment by Joppla** [comment]
If I look at my own issues there is a button [Close Issue] near the [Comment] button:
![afbeelding](https://user-images.githubusercontent.com/25467829/51977268-46e35800-2487-11e9-81dc-5ce380734403.png)

**Comment by VitaliPom** [comment]
I cannot push the changes, I've got this: 
`Permission to AnySoftKeyboard/AnySoftKeyboard.git denied to VitaliPom`

**Comment by VitaliPom** [comment]
Do I need to ask Permissions? From who, from Menny? Is there someone else who can grant me//?

**Comment by Joppla** [comment]
I think you can make a pull request with the changes you made and the issue you can close. If the developer agree with the changes he will accept the pull request.

**Comment by VitaliPom** [comment]
Tried to hack it, push only the branch. Same error.... @menny  Could you get involved?

**Comment by Joppla** [comment]
so? this can be closed?

**Comment by VitaliPom** [comment]
That no, only the duplicates. Because I believe we 1st need to complete the PR and see the changes, meanwhile the PR is created but not yet committed. Is it fine for you> is it just the way you work and it's okay?

**Comment by VitaliPom** [comment]
Whatever is common. Tell me and I will do...

**Comment by VitaliPom** [comment]
Irrelevant - refering to Visibility of This Very Feature issue https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1627
