### ISSUE TITLE
Keyboard fails to open

### ISSUE THREAD

**Issue by shawn1thompson** [AnySoftKeyboard/AnySoftKeyboard#1615]
### Steps to reproduce
1. Try to type something
2. Keyboard fails to appear, but there is a place where it should appear
3. Force stop

### Expected behaviour
Tell us what should happen
I should be able to type something

### Actual behaviour
Tell us what happens instead
The keyboard fails to appear

**Android OS version:**
8.0.0

**Device manufacturer and model:**
moto g6

**List of installed add-ons (like languages, or themes):**
None

**Comment by VitaliPom** [comment]
Are you working on developers version with the source code or you downloaded from store?

**Comment by shawn1thompson** [comment]
Downloaded from F-Droid

**Comment by VitaliPom** [comment]
Not familiar with F-Droid but you could just to make sure try and download from google play, I don't which problems might be caused in F-Droid but permissions problem and versioning bug migth be enough just to try. IF not, I'll be curious to find out what's wrong as well.

**Comment by shawn1thompson** [comment]
@VitaliPom I try not to use the Play Store whenever possible, though, if necessary, I will.

@menny I have, several times

**Comment by VitaliPom** [comment]
Try to use that once for me please. I'll try to help you, though don't know why and how yet. That Store settings block my head from thoughts on other possible bugs currently.

**Comment by shawn1thompson** [comment]
The Play Store version doesn't seem to suffer from the same problem.

**Comment by menny** [comment]
I guess an update to the fdroid version is needed
