### ISSUE TITLE
Turkish F layout

### ISSUE THREAD

**Issue by paledega** [AnySoftKeyboard/AnySoftKeyboard#1618]
I created unoffical turkish F layout.
https://gitlab.com/droidtr/anysoft-languagepack-turkish-f

Turkish has two different layout.(Trq and Trf)
Anysoft turkish language pack has trq but doesnt have trf.

**Comment by paledega** [comment]
![img_20190204_093951_822](https://user-images.githubusercontent.com/38860643/52193571-bb334800-2847-11e9-81d4-5404a362ced9.jpg)

**Comment by menny** [comment]
that's cool. Do you want to donate that to the official pack?

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/LanguagePack/tree/master/languages/ossturkish

**Comment by paledega** [comment]
Ok no problem.You can use

**Comment by paledega** [comment]
When you merge trf layout

**Comment by menny** [comment]
@paledega did you open a PR to fix my Turkish pack as well?
