### ISSUE TITLE
[Wishlist / feature request] Customizable top row

### ISSUE THREAD

**Issue by kbs1** [AnySoftKeyboard/AnySoftKeyboard#1632]
Dear all,

it would be great if users could define their own top row. This keyboard doesn't need anything else and will then be perfect :)

The top row contents could be edited using a simple text area. For example if the user would enter ":-*/)(_" then those keys would be always displayed in the top row.

Furthermore, special letters LRUDACXV should be recognised and those would render arrows (LRUD) and copy-paste functions (all, copy, cut, paste). When holding on the arrow keys, the cursor should constantly move (key-repeat only on those keys).

These features are directly inspired by dodol Keyboard. That app no longer works on Pie as it tries to override final requestShowSelf. I can't find any other keyboard project (at all) that has anything like customisable top row (always present) - with arrow keys at least. I think this feature is very useful to many users. Terminal users can add special characters for example. 

Thank you! :)

**Comment by stardomains2** [comment]
I second this. Attached is the ASK I made custom for me. The cut paste select all undo copy and cursor control is fantastic. Would love if it was an option in the main ASK so I could get the new updates. The custom look is mine too. The custom look is mine too.

(https://i.imgur.com/sRry8aY.png)
