### ISSUE TITLE
F-droid update please

### ISSUE THREAD

**Issue by paledega** [AnySoftKeyboard/AnySoftKeyboard#1637]
Last days I created pull request and @menny fixed turkish character bug. But f-droid versiyon didnt update yet. When we publish  on f-droid

**Comment by AnXh3L0** [comment]
Hello there @paledega, the F-Droid builds are usually late because of how F-D works, and they are triggered only after a release on GitHub afaik.

**Comment by menny** [comment]
This is correct. We have an easier way to generate the required metadata change for fdroid releases, so it might be easier in the future.

I'll mark this issue for the next milestone so we'll remember to also publish to fdroid

**Comment by chohner** [comment]
Looks like this is the last issue for `v1.10-r3` - So all thats left is closing this and making a github release, right?

**Comment by menny** [comment]
Pretty much

**Comment by menny** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/6170

**Comment by menny** [comment]
merged
