### ISSUE TITLE
Switching from 'Terminal' to 'English' causes developer warning toast

### ISSUE THREAD

**Issue by Rixon-gh** [AnySoftKeyboard/AnySoftKeyboard#1639]
### Steps to reproduce
1. View Terminal layout
2. Switch to English
3. ???
4. Profit!

### Expected behaviour
None

### Actual behaviour
Toast: `Developer warning for package "com.menny.android.anysoftkeyboard"
Failed to post notification on channel "null"
See log for more details`

**Android OS version:**
8.1.0 Oreo (I think notification handling changed in 7+?)

**Device manufacturer and model:**
Nexus 6P

**List of installed add-ons (like languages, or themes):**
None

**Comment by Rixon-gh** [comment]
(It might be worth noting that I installed from fdroid)

**Comment by menny** [comment]
I can't seem to reproduce this... how do you switch from Terminal to English?
