### ISSUE TITLE
Use more subtle color red chosen from Material Design in keyboard

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#1648]
### Steps to reproduce
1. Install keyboard
2. Let battery of device run low to show red icon in bottom right of keyboard

### Expected behaviour
The color red that should be used in the keyboard and must not conflict with the Material Design style of Android.

### Actual behaviour
The color red used on the black keyboard does this at the moment. Please, choose a red color from Material Design that better matches the black background of the keyboard.

**Android OS version:**
9

**Device manufacturer and model:**
n/a

**List of installed add-ons (like languages, or themes):**
n/a

**Comment by menny** [comment]
gladly! do you have a recommendation?

**Comment by PanderMusubi** [comment]
Red `#f44336`from https://www.materialui.co/colors

**Comment by PanderMusubi** [comment]
Can this be reopened please?
