### ISSUE TITLE
Feature: display word autocorrect suggestion upon moving cursor on word

### ISSUE THREAD

**Issue by edo0** [AnySoftKeyboard/AnySoftKeyboard#1649]
As per the title, I think it would be useful to enable the autocorrector suggestions also when tapping and moving the cursor within a previously written word, so as to have the similar alternative words you might have meant to be writing.

Current behaviour: no suggestion is displayed

**Comment by menny** [comment]
this is already possible!
go to the  `Languages` section in the Settings app and under `Tweaks` pick `Suggestions restart`

**Comment by DougTy** [comment]
This isn't working, tapping a previously written word doesn't show any suggestions with `Suggestions restart` turned on.
