### ISSUE TITLE
We can change navbar color

### ISSUE THREAD

**Issue by paledega** [AnySoftKeyboard/AnySoftKeyboard#1652]
//We should add into InputMethodService class onWindowShown function

if(Build.VERSION.SDK_INT > 20){//is kitkat+
    Window w = getWindow().getWindow();
    if(read.getBoolean("activedraw",true)){//is feature enabled?
    w.setNavigationBarColor(read.getInt("color",Color.parseColor("#1a252f")));//find color from database or other way
    }else{
        w.setNavigationBarColor(Color.parseColor("#1a252f")); //static color
     }
}

**Comment by paledega** [comment]
![screenshot_20190224-114929_lawnchair](https://user-images.githubusercontent.com/38860643/53297119-1cc85000-3811-11e9-9745-0d8e5ed7d41a.png)

**Comment by paledega** [comment]
I dont know how to add this feature in anysoft keyboard.
@menny Can you help me

**Comment by menny** [comment]
really?!! you can do that? This is amazing.

**Comment by matsest** [comment]
This would be a nice option to expose in the settings menu.

**Comment by menny** [comment]
this was done with: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1773
