### ISSUE TITLE
Large dark space above keyboard

### ISSUE THREAD

**Issue by ondrejj** [AnySoftKeyboard/AnySoftKeyboard#1653]
### Steps to reproduce
Not sure, how to reproduce. Look at screenshot, happens always for me.
Trying also different themes, still same problem. Unable to find any setting, which can help.
Look like it's space for suggestions, but suggestions are turned off and space is still here.
I use mostly connectbot, which don't need suggestions, but same problem is in other apps too.

Unable to upload screenshot, here is a link:
![](http://www.salstar.sk/temp/Screenshot_20190224-153639.png)

**Android OS version:**
Android Pie 9, latest updates for my phone

**Device manufacturer and model:**
Sony Xperia XZ1 compact

**List of installed add-ons (like languages, or themes):**
ssh for anysoftkeyboard

**Comment by menny** [comment]
This is the future home of Actions-Strip (and suggestions).
It will be hidden in the next beta if you disable Suggestions.
