### ISSUE TITLE
Keyboard with higher keys?

### ISSUE THREAD

**Issue by poet-man** [AnySoftKeyboard/AnySoftKeyboard#1664]
I use German keyboard and tried all designs within ask on my galaxy S4 tablet.
All designs seem to have keys, that are too small in hight, because I tend to hit the key below the one, I want (i.e. "." instead "m").
Anybody know a 'higher' design to download and can tell me, which one to try?
Thanks
Axel

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by VitaliPom** [comment]
hi, Vitali is here. Working on that, soon will update. Though not currently ready

**Comment by menny** [comment]
@poet-man you can change the height of the keyboard by changing the "factor" value.
Go to Themses->Tweaks (the gear icon at the top) and change the value of "Portrait Height Factor" to something larger than 1.
