### ISSUE TITLE
I can't find english keyboard in source

### ISSUE THREAD

**Issue by MassiminoilTrace** [AnySoftKeyboard/AnySoftKeyboard#1669]
Hi!
I can't find in the source where the default English keyboard and dictionary are.
I am trying to build my version with a dialect language next to the Italian, so that people could download a version with these already pre-packed languages.
For old people, finding where the language pack installer is and downloading the languages of interest could be difficult.

Thank you in advance

**Comment by menny** [comment]
here you go:
https://github.com/AnySoftKeyboard/LanguagePack/tree/master/languages/english

**Comment by MassiminoilTrace** [comment]
Sorry for reopening.
I saw from your answer that these languages are synced from a remote repo, because the main keyboard and the language packs are in different repos.
How I could access the single language packs in other repos or in other forks?

**Comment by menny** [comment]
@MassiminoilTrace I'm not sure I understand the question
