### ISSUE TITLE
Does AnySoftKeyboard send my typings to cloud or external server?

### ISSUE THREAD

**Issue by lluke777** [AnySoftKeyboard/AnySoftKeyboard#1673]
Does AnySoftKeyboard send my typings to cloud or external server?
Does Incognito mode store any marks of my typing?

**Comment by menny** [comment]
AnySoftkeyboard DOES NOT send any data out of your device. Furthermore, the app does not even have permissions to access the network!

Saying that, it does store, locally, statistical data on your typing so it can learn how to correct typing better. This data never leaves your phone and is stored in private storage which (should) be only available to AnySoftKeyboard.

When _Incognito Mode_ is enabled, AnySoftKeyboard will stop storing data locally.

**Comment by lluke777** [comment]
OK. Thank You for clarifying.
