### ISSUE TITLE
latest version on fdroid

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1674]
Hello,

I see on PlayStore a new version published on 22nd of March. Is it also published on fdroid yet?

Thanks,
Jop

**Comment by menny** [comment]
I've requested: https://gitlab.com/fdroid/fdroiddata/merge_requests/4653

**Comment by Joppla** [comment]
Thanks!
-- 
Met vriendelijke groet,
Jop

Menny Even Danan <notifications@github.com> schreef op 25 maart 2019 18:21:56 CET:
