### ISSUE TITLE
Override Power Savings

### ISSUE THREAD

**Issue by jgonyea** [AnySoftKeyboard/AnySoftKeyboard#1677]
Could there be an option to disable/ override the auto-power saver? I appreciate the power consumption feature, but there are times when I still want the auto corrections.

Thanks either way.

**Comment by menny** [comment]
Yes! You can customize (or completely disable) Power-Saving:

* Start the AnySoftKeyboard Settings app.
* Click UI section (at the bottom).
* And then "Keyboard effects and experience".

You'll find there options for controlling Power-Saving (and other things).
