### ISSUE TITLE
Enable night mode.

### ISSUE THREAD

**Issue by Szelephimba** [AnySoftKeyboard/AnySoftKeyboard#1679]
The app does not follow the night mode setting of Oneplus 5T

### Steps to reproduce
By setting to "never" & "always" be in dark mode: it works properly.
The "follow system" does not work. 

### Actual behaviour
Remains in 'day mode' 

**Android OS version:** "9"

**Device manufacturer and model:** OnePlus 5 T

**List of installed add-ons (like languages, or themes):
Hungarian
Qwerty 4 lines

**Comment by menny** [comment]
how do you set automatic night-mode on you device?

**Comment by Szelephimba** [comment]
Menny Even Danan <notifications@github.com> ezt írta (időpont: 2019. ápr.
3., Sze 23:22):

**Comment by apszowski** [comment]
I see the exact same behavior on my OnePlus 6T. Night Mode trigger in AnySoftKeyboard set to "Follow system".  Night mode on the phone is in default setting so "from sunset to sunrise". Even manually switching between Night mode on the phone doesn't seem to register in AnySoftKeyboard.
