### ISSUE TITLE
Key preview 

### ISSUE THREAD

**Issue by dangerchitthu** [AnySoftKeyboard/AnySoftKeyboard#1687]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by frytkisasmaczne** [comment]
this is very helpful indeed

**Comment by menny** [comment]
Please open an issue with the required details.
