### ISSUE TITLE
Emojis not visible or usable

### ISSUE THREAD

**Issue by Penaz91** [AnySoftKeyboard/AnySoftKeyboard#1688]
Steps to reproduce:
1. Open any app that requires typing text
2. Keep the emoji button pressed to open the emoji submenu
3. No emojis are shown (besides some basic ones and the ones in the "most recently used" section)
Expected behaviour:
Most or all the emojis should show

Actual behaviour
Almost no emojis are shown

Android OS version:
Android 5.0

Device manufacturer and model: Asus Zenfone 2 (Z00AD)

List of installed add-ons (like languages, or themes):
Italian Extension

EDIT: I just found the issue template, so I'll update the comment to reflect it, sorry

Thanks for your work

**Comment by Penaz91** [comment]
I attach some screenshot, hopefully they help.
![Screenshot_2019-04-04-22-36-00](https://user-images.githubusercontent.com/6682630/55587119-f4dedd00-572a-11e9-876b-4aefd2736857.jpg)
![Screenshot_2019-04-04-22-36-09](https://user-images.githubusercontent.com/6682630/55587140-ff997200-572a-11e9-952c-67369c44fb30.jpg)
![Screenshot_2019-04-04-22-38-23](https://user-images.githubusercontent.com/6682630/55587141-00320880-572b-11e9-9085-c2fe641dbf6e.jpg)

**Comment by patrick-conley** [comment]
I'm having the same issue. The emoji that do appear are the same ones shown in Penaz91's screenshots. The issue started on or before 2019-03-13.

**Android OS version:**
Android 4.4.2

**Device manufacturer and model:**
Samsung Galaxy S3

**List of installed add-ons (like languages, or themes):**
French
One-Handed Dvorak (from an apk I found on a forum somewhere)

**Comment by sk197876** [comment]
I am having the same issue.

OS: Android 5.0
Device: BQ Aquaris E5

**Comment by GoranGharib** [comment]
That's a Android OS Issues NOT ASK the  Color Emoji's is Support on Kitkat 4.4 and Above....

**Comment by github-tomster** [comment]
@all the users having this issue:
downgrade to 1.9.2629
it works as it should work, and on top of that, as it worked before the update to 1.10.364 .... (what a miracle)

@those-who-code
i am also on 4.4.2 and i hope you know what you have altered as 1.9.2629 works and 1.10.364 not!

@Penaz91 
ty for the post here, who knows if one cares at all

@GoranGharib 
1.9.2629 works
1.10.364 fails
now you...

**Comment by Penaz91** [comment]
I can confirm that downgrading to ASK version 1.9.2629 fixes the issue.

I'm not an android developer, but I heard google changed their emojis recently and put up a utility to port them to older android versions (API 19+) called "EmojiCompat" or something, here's the link: https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat

Just putting it out there hoping to help.

Also thanks to @github-tomster for the suggestion to downgrade.

**Comment by github-tomster** [comment]
1.10.606 still fails...

**Comment by moritzboth** [comment]
I have the exact same problem on Samsung galaxy s4, android 5.0.1.

**Comment by github-tomster** [comment]
@whoevercares
one could say, all versions after 1.9.2629 fail, hence these issues here.
so maybe, if it is not possible to fix that, a BUG label can be added here?
or create a known issues point?

**Comment by patrick-conley** [comment]
I have some free time next week. I'll take a stab at fixing it then.

**Comment by azzamsa** [comment]
I have the same issue: Asus Zenfone Max ZC550KL, Android 5.0.2, AnySoftKeyboard v1.10-r2

**Comment by menny** [comment]
The issue is `aapt2`. Until version 1.10 we used `aapt` version 1, but in order to support newer build-tools we moved to `aapt2`.
This is the commit that introduced `aapt2`: https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/e9774282b057bc8199a804c0f6eea6633d7079be#diff-503f218d646c10f484fdc9d6315bf2e3

**Comment by menny** [comment]
One option would be to go back to `aapt` v1 release something that is stable and then stop supporting any device before api 24.. or so.
Another, is to go back to ask google to fix `aapt2`.

**Comment by menny** [comment]
hmmmm. I may have found the issue. And it's not `aapt`'s fault. I think I didn't convert the emoji-lists for devices prior to API21 correctly...

Verifying.

**Comment by menny** [comment]
I've verified on an emulator that this fix works.
A BETA release will be available later today.
