### ISSUE TITLE
[Feature Request] Yochees Light Theme

### ISSUE THREAD

**Issue by theweavrs** [AnySoftKeyboard/AnySoftKeyboard#1689]
Hi, I just installed AnySoftKeyboard from Google Play and played around with it for a while. I have noticed there is no "light" theme for Yochees and I would like it very much if it was added (or I can add it if possible). It's (in my opinion) the best theme currently for the keyboard.

**Comment by menny** [comment]
@yochees, thoughts?

**Comment by theweavrs** [comment]
@menny I don't think it should be very hard to create a light theme as everything is already implemented in the dark theme; we just have to change a few colors and do some testing.

**Comment by GoranGharib** [comment]
@theweavrs  I have been use in my private keyboard that build from ASK if want email me i will send you the Light version of Yochees Theme  :) 

gorran90@gmail.com

**Comment by GoranGharib** [comment]
@theweavrs  I have been used in my private keyboard that build from ASK source code if wanted mail me i will send you the Light version of Yochees Theme :)

gorran90@gmail.com

![Screenshot_2019-04-15-05-23-42-1646515806_EDIT_1](https://user-images.githubusercontent.com/3160786/56104116-14ea7980-5f3f-11e9-95c0-ed00c3a7cc47.png)

**Comment by theweavrs** [comment]
@GoranGharib Sent you an email

**Comment by menny** [comment]
![Screenshot_20190426-201127](https://user-images.githubusercontent.com/481272/56842027-973c3d00-685f-11e9-92b0-decc69e0245c.png)

**Comment by menny** [comment]
Will be available in the next release

**Comment by theweavrs** [comment]
@menny  thanks a lot. Looking forward to using this keyboard as my daily! : ) Keep up the wonderful work!

**Comment by yochees** [comment]
Guys, sorry for chimming in half a year later :)
I completely missed what is happening here. However I've updated both themes - dark and light. @menny - if you or someone else is going to code this thing to life - I can commit couple hours a week - for further tweaks.

<img width="360" alt="Dark lowercase" src="https://user-images.githubusercontent.com/24437104/70726024-16ef1d00-1d06-11ea-8f83-f134ebdcea7c.png">
<img width="360" alt="Light" src="https://user-images.githubusercontent.com/24437104/70726025-16ef1d00-1d06-11ea-9ea8-6943a7c2e520.png">
<img width="360" alt="Dark Caps" src="https://user-images.githubusercontent.com/24437104/70726027-1787b380-1d06-11ea-82a1-a803f6528b17.png">

**Comment by menny** [comment]
that would be wonderful @yochees 
Please add the assets to https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1911

We can target this for the r4 release (we are releasing r3 in a couple of weeks)

**Comment by AnXh3L0** [comment]
@yochees wow these are wonderful, I love them 💯
