### ISSUE TITLE
Issue causing whole phone to crash and restart loop

### ISSUE THREAD

**Issue by Ajt8000** [AnySoftKeyboard/AnySoftKeyboard#1691]
### Steps to reproduce
1. Install AnySoftKeyboard on a Samsung A3(2016)
2. To test see if the phone will let you access the battery portion of 'Device Maintenance', or will boot 'Apps' in the settings menu without crashing.
3. Try and restart or shutdown phone

### Expected behaviour
The phone and keyboard should function as intended.

### Actual behaviour
The keyboard functions with no issue, but it seems to cause an issue with everything else. I first noticed something was wrong when I couldn't enter the battery portion of the phones built in device maintenance app, later I was locked out of the apps part of the settings. Eventually the phone started getting slower and the launcher (the standard Samsung touchwiz launcher) would begin to crash.

To attempt to fix it I restarted my phone, which caused the phone to get stuck in a restart loop where it would reboot, show the login screen for a second or two then reboot again. During this the phone became quite hot and the battery would go down and down faster than normal. I had to plug the phone into the charger and let it get this out of its system before it would turn on and stay on. It also did this in safe mode.

In total the phone was put into the restart loop 4 times over the course of a week.

I had a suspicion it was the keyboard due to this behaviour only starting after the update to version 1.10.364. I was able to disable the keyboard through the launcher by holding the icon down and putting it to sleep, from there I was able to change the keyboard, enter device maintenance and put all of the other programs which were open to sleep and uninstall the keyboard.

**Android OS version:** 7.0

**Device manufacturer and model:** Samsung Galaxy A3 (SM-A310F)

**List of installed add-ons (like languages, or themes):** English

**Comment by menny** [comment]
After uninstalling the keyboard everything was back to normal?

**Comment by Ajt8000** [comment]
> 
> 
> After uninstalling the keyboard everything was back to normal?

Yes, the phone has behaved itself just fine since uninstalling it. I am hoping to reinstall the keyboard once a new version is rolled out.

**Comment by kadfd** [comment]
I had a similar issue where "system-ui" crashed everytime i open the keyboard. This resulted in my screen going black and all i could do was restart or shutdown my phone. So I had to uninstall it.
