### ISSUE TITLE
Stuck in t9

### ISSUE THREAD

**Issue by silenthog** [AnySoftKeyboard/AnySoftKeyboard#1698]
### Steps to reproduce
1. set up anysoft including t9 as a keyboard 
2. could not turn off t9 and revert to LG/Google keyboard
3. turned off anysoft and not LG/Google keyboard defaults to t9 keyboard
4.  turned on anysoft again and cannot select or deselect t9 as a keyboard
5.  turned off anysoft again and cannot utilize full QWERTY keyboard in LG/Gboard, only QWERTY for anysoft regardless of whether anysoft keyboard is toggled OFF for 'on-screen' or 'physical' or 'managed'

### Expected behaviour
should be able to toggle usable keyboards, whether within the anysoft library or revert to default keyboards

### Actual behaviour
im stuck in the 1990's with t9 and cannot get a full QWERTY again from my default keyboards that also have the benefits of swype.  anysoft broke my default keyboards and will be deleted if i cannot fix this critical bug.

**Android OS version:**
8.1.0
**Device manufacturer and model:**
LG v40 5ua10e
**List of installed add-ons (like languages, or themes):**
had system spanish turned on, then noticed these keyboards wouldnt switch.  disabled native spanish keyboards, then installed anysofts spanish keyboard and went from not being able to toggle back to LG keyboard to being stuck with t9 or anysoft-only QWERTY

**Comment by maverick74** [comment]
?! ASK does not have T9 (see #1412) - you must be referring to the 16 keys layout...

Now, if you remove ASK does it solve the problem?

After removing you should be able to go back to gboard without any problems.

If you don't intent to use t9, then I would recommend re-installing ask after, as it is a great qwerty keyboard!
