### ISSUE TITLE
Sir who to fix

### ISSUE THREAD

**Issue by dangerchitthu** [AnySoftKeyboard/AnySoftKeyboard#1714]
2019-05-04 12:06:37.175 4116-4310/com.menny.android.anysoftkeyboard A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7dc05903ff in tid 4310 (RxCachedThreadS)

**Comment by oldosfan** [comment]
Please post the entire logcat

**Comment by ArenaL5** [comment]
There's no question, logcat, or enough information here. @dangerchitthu isn't likely to return and the other issue they posted was similiarly empty.

@dangerchitthu, if you do return, please feel free to open a new issue with more information.

Until then, there's no point in keeping this issue open, I guess.

**Comment by AnXh3L0** [comment]
Closing the issue for lack of information.
