### ISSUE TITLE
Bug report v1.10.606

### ISSUE THREAD

**Issue by darvinya** [AnySoftKeyboard/AnySoftKeyboard#1715]
Stayed the all bugs were in v1.10.573. https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1711

**Comment by ArenaL5** [comment]
Please don't report the same bug twice. Comment on the original issue if you must.

Opening duplicate tickets only makes it harder for maintainers and volunteers to improve the app.

**Comment by AnXh3L0** [comment]
Closing down this issue as a duplicate.
