### ISSUE TITLE
Where is serbian cyrilic keyboard?

### ISSUE THREAD

**Issue by Bucov** [AnySoftKeyboard/AnySoftKeyboard#1723]
Hi,

Long time user here. I just got new phone today, LG g7 and I cannot find serbian keyboard layout, what happened? I have it on 2 other phones, but I cannot seem to find it on play store.

Really need this, is it possible to add this using just the apk?

**Comment by stefan-krle** [comment]
Hi, pull request made to add the Serbian language pack, waiting on feedback/merge, https://github.com/AnySoftKeyboard/LanguagePack/pull/270

**Comment by Bucov** [comment]
Thanks. When it will be available in the app? I'm using beta

**Comment by Bucov** [comment]
I have extracted apk for serbian keyboard, from old phone. I can upload it here, but I'm not owner of that code
