### ISSUE TITLE
Underline each word containing spelling mistakes

### ISSUE THREAD

**Issue by YuGiOhJCJ** [AnySoftKeyboard/AnySoftKeyboard#1725]
### Steps to reproduce
1. Get a Xiaomi Redmi 6A smartphone
2. Download and install AnySoftKeyboard from apkpure.com (AnySoftKeyboard_v1.10.606_apkpure.com.apk)
3. Download and install French for AnySoftKeyboard from apkpure.com (AnySoftKeyboard_v4.0.516_apkpure.com.apk)
4. Run the Messaging app
5. Write a message in French with words containing spelling mistakes

### Expected behaviour
Each word containing spelling mistakes should be underlined

### Actual behaviour
Only the word currently written is underlined

**Android OS version: 8.1.0 (and MIUI Global 10.0)**

**Device manufacturer and model: Xiaomi Redmi 6A**

**List of installed add-ons (like languages, or themes): French for AnySoftKeyboard**

Details: I like to check my spell after writing a message and not while I am typing. So, I would like to keep a trace of which word contains spelling mistakes. Maybe you should add an option "Underline words" in "AnySoftKeyboard" > "Language" > "Configure correction behavior and other dictionaries." to let the user enable or disable this feature.

Thanks.
Best regards.

**Comment by YuGiOhJCJ** [comment]
How to remove the stale label please?

**Comment by mirfatif** [comment]
This would be a great addition.
