### ISSUE TITLE
[Feature Request] Option to mix current dictionaries

### ISSUE THREAD

**Issue by moshpirit** [AnySoftKeyboard/AnySoftKeyboard#1727]
I used Swiftkey for a while and this is a feature I miss from then: not needing to switch from dictionaries because I have all words for me. This is very cool for me since I'm used to write in English and Spanish, so I'm constantly changing the language and I prefer this way. 

Maybe there could be an option that mixed the enabled dictionaries, so you can have all these 3 to change: `English`, `Spanish` and `Mixed`. After that, I can just select the default dictionary as `Mixed`. This way I use the mixed dictionaries as my default option but if I'm getting a lot of English suggestions and I know I'm going to write a lot in Spanish, I can just quickly switch to `Spanish`.

IDK if this is hard to implement, but I think it is a worth feature.

**Comment by fgibaux** [comment]
I come from Swiftkey as well and liked the all dictionaries at once, I found how to do it: 
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/832#issuecomment-298328943

> long press on enter key and choose "override the default dictionary", and select any dictionary you want for the current keyboard layout

Hope this helps

**Comment by moshpirit** [comment]
This is just great, thank you so much! 😊

**Comment by ArenaL5** [comment]
Related to #1794. (This issue is technically closed, but the option should exist in the main settings screen. For the moment it doesn't.)

Duplicate at #1918.

**Comment by AnXh3L0** [comment]
The feature is available but should become visible in the main settings screen. Closing this issue as solved and adding it to the list for the UI redesign.
