### ISSUE TITLE
Deliver official layout packs as AppBundle features

### ISSUE THREAD

**Issue by rimas-kudelis** [AnySoftKeyboard/AnySoftKeyboard#1739]
I'm under impression that the main source of bad ratings for layout packs on Play Store is the fact that often people download a layout pack without downloading the base keyboard first. As a result, they are unable to find their new keyboard anywhere, get frustrated that it "does not work" and leave a negative rating/review. I've seen this more than once with the [Lithuanian layout pack](https://play.google.com/store/apps/details?id=org.herrlado.ask.languagepack.lithuanian).

While looking into how this issue could be solved, I stumbled upon a relatively new feature of the Android Platform called [Android App Bundle](https://developer.android.com/platform/technology/app-bundle/index.html), which allows building modular Android packages where only "main" features of the app are installed initially, and other (less used/less stable/less important etc.) features can be installed when demanded at runtime. I think it would be nice if ASK layout packs could be turned into such features installable on demand from within the app itself. Assuming this would work, separate layout packs could then be hidden from Play Store for Android versions which support the App Bundle mechanism, thus (hopefully) reducing user's confusion.

**Comment by ArenaL5** [comment]
Good insight, and thanks a lot for your effort! I can tell you that @menny has at some point looked into this, as evidenced by his self-reminder at #1353. I'm not sure if he has any concrete plans in mind.

Your post will be very useful if someone decides to write a pull request. :smile:

**Comment by rimas-kudelis** [comment]
Ah, thanks for the pointer!
