### ISSUE TITLE
Theme preview in UI Settings may take up too much space

### ISSUE THREAD

**Issue by rimas-kudelis** [AnySoftKeyboard/AnySoftKeyboard#1740]
Theme preview is rendered seemingly without any size constraints in the settings. This may result in some options being almost hidden in UI settings and in the theme chooser looking awkward in the theme list.

See the screenshots below:

UI settings
![paveikslas](https://user-images.githubusercontent.com/2812673/59155914-704a6b00-8a9b-11e9-9e95-63ab88d13ece.png)

Theme chooser
![paveikslas](https://user-images.githubusercontent.com/2812673/59155916-74768880-8a9b-11e9-9fdd-11ada33c1070.png)

**Comment by AnXh3L0** [comment]
Hello there @rimas-kudelis, we are aware of this issue and are working towards improving the settings UI/UX in the near future. Thanks for opening this issue.

**Comment by menny** [comment]
@ArenaL5 is this the issue you fixed?

**Comment by ArenaL5** [comment]
It isn't. You closed a similar issue at #1842, but I didn't touch those.

I only fixed the spacing in the bottom row itself, not on the menus.

**Comment by menny** [comment]
I think your fix should also fix this... Or, I hope.
The demo-keyboard view is using the same mechanism.
