### ISSUE TITLE
Do not leave an unnecessary empty space before a dot

### ISSUE THREAD

**Issue by Massedil** [AnySoftKeyboard/AnySoftKeyboard#1748]
### Expected behaviour

If a word is added by the suggestion and a "double space press" is made then add the automatic dot after the word (do not leave an unnecessary empty space).

If you select the word "word" from the suggestion bar and double tap on space, you expect to have "word. " inserted.

### Actual behaviour

If you select the word "word" from the suggestion bar and double tap on space, you will have "word . " inserted.

---
Version: 1.10.606 F-droid
Android OS version: LineageOS 16.0
Device manufacturer and model: Samsung Galaxy S5 (kltedv)
List of installed add-ons (like languages, or themes): French language pack

**Comment by AnXh3L0** [comment]
I couldn't manage to reproduce this bug, please provide more information on your settings.

**Comment by Massedil** [comment]
> I couldn't manage to reproduce this bug, please provide more information on your settings.

Sorry, I retried, but I can't reproduce the issue, me neither. Since June, I remember that I have changed the aggressiveness of the corrector and some spaces option after correction and the repetition time to "very quick". I surely changed something else. I can't find what.
