### ISSUE TITLE
Backspace after swiping a word should delete the whole word

### ISSUE THREAD

**Issue by Shadow53** [AnySoftKeyboard/AnySoftKeyboard#1755]
### Steps to reproduce
1. Install ASK 1.10.606 from F-Droid.
2. Make sure gesture-typing is enabled.
3. Swipe-type a word and then hit backspace.

### Expected behaviour
The assumption is that the word was not the one the user meant to type, delete the whole word and let them try again.

### Actual behaviour
Backspace deletes one character at a time, making it take longer to delete the word before trying again.

**Android OS version:** 9.0.0 (LineageOS for microG)

**Device manufacturer and model:** OnePlus 5

**List of installed add-ons (like languages, or themes):** None, using QWERTY with symbols on long press.

**Comment by amgatx** [comment]
Has this really been left uncorrected for three years?   This is the only reason I find this keyboard hard to use, everything else is good.  Can we please get a setting for this function?

**Comment by menny** [comment]
This has been fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2353
It is available right now in the BETA channel
