### ISSUE TITLE
(question) about cut copy paste

### ISSUE THREAD

**Issue by soilentgreen** [AnySoftKeyboard/AnySoftKeyboard#1758]
Hey,

There is any way to mark a text, and cut copy paste it with the keyboared?

**Comment by IronJunkie** [comment]
Yes, from utility keyboard (eg swipe up from space key or change assigned key in gestures settings for other swipe to "show utility keyboard")

**Comment by soilentgreen** [comment]
Thanks

**Comment by jwsp1** [comment]
please close this issue as your question has been answered.

**Comment by AnXh3L0** [comment]
Closing issue as solved.
