### ISSUE TITLE
Allow option to hide app icon in the app dock

### ISSUE THREAD

**Issue by jaredsburrows** [AnySoftKeyboard/AnySoftKeyboard#1760]

**Comment by AnXh3L0** [comment]
Can you please provide some more information on what you want to achieve? If you mean hiding the app icon from the launcher, that is already possible.

**Comment by jaredsburrows** [comment]
@AnXh3L0 Does this exist in the "Settings" menu?

**Comment by menny** [comment]
In the "Hello" section, click the overflow button at the top-left. Pick "tweaks". In the new page, disable "settings app"
