### ISSUE TITLE
some settings are hard to find

### ISSUE THREAD

**Issue by 532910** [AnySoftKeyboard/AnySoftKeyboard#1766]
This menu is really hard to find:
![image](https://user-images.githubusercontent.com/14617699/61165492-e70ad600-a529-11e9-92e9-7f867ebc6656.png)

Please move it from the `Select theme` screen
![image](https://user-images.githubusercontent.com/14617699/61165484-bb87eb80-a529-11e9-8ee0-78a97b2c609c.png)

Under `UI: Tweaks and more`:
![image](https://user-images.githubusercontent.com/14617699/61165501-1ae5fb80-a52a-11e9-970a-f26ee09ce0cb.png)

**Comment by Mikaela** [comment]
Related: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1341

**Comment by Soundtoxin** [comment]
It would be nice to have all settings on one screen, and/or a search.

**Comment by AnXh3L0** [comment]
Related to #1341 and many others, closing down for now to reduce the number of open issues (will be updated once we have a better UI).
