### ISSUE TITLE
settings dark theme

### ISSUE THREAD

**Issue by 532910** [AnySoftKeyboard/AnySoftKeyboard#1768]
Please add support for dark theme for the settings.

![image](https://user-images.githubusercontent.com/14617699/61165925-84b4d400-a52f-11e9-887e-e8a97bc54cb8.png)

**Comment by Mm2PL** [comment]
It is already there in `Keyboard effects and expierence. -> Night-Mode settings -> Darken Settings App UI`. You just have to enable that setting and set `Enable Night-Mode` to `Always`

**Comment by 532910** [comment]
This issue is about setting dark theme only. Night-Mode settings has nothing common with it.

**Comment by menny** [comment]
I'm not sure I understand the requirement. @532910 can you explain this again?

**Comment by 532910** [comment]
I'm talking about dark theme for settings UI, without `Night-Mode`.

**Comment by Jonta** [comment]
UI -> Keyboard effects and experience -> Night-Mode settings -> Enable Night-Mode

(Clarifying what @Mm2PL wrote)

Mine was set to "Never"

@menny Why isn't it "Follow system" by default? =)

**Comment by menny** [comment]
Since, when implemented, it was not working well on all devices I decided to have it opt-in. I'll try that again and maybe change the default

Thanks for reminding me about this
