### ISSUE TITLE
make capitalization optional

### ISSUE THREAD

**Issue by michaelkonecny** [AnySoftKeyboard/AnySoftKeyboard#1777]
It would be great if on could opt out of auto capitalization somewhere in the settings.

This used to be a feature I used to love in the now discontinued Swype keyboard. Small caps just somehow look way cooler in casual chats, plus not everyone has to be able to tell if you're on a PC or on mobile.

**Comment by IronJunkie** [comment]
You can, go to settings> language>configure>auto cap

**Comment by michaelkonecny** [comment]
Gees, how did I miss that? Thanks!
