### ISSUE TITLE
[Request] Backup and restore

### ISSUE THREAD

**Issue by smnthermes** [AnySoftKeyboard/AnySoftKeyboard#1780]
I use more than one Android device, so it would be useful to be able to restore from a file outside of the default location, and without overriding the existing database.

**Comment by menny** [comment]
makes sense

**Comment by jwsp1** [comment]
Just created a backup, reinstalled the app and saw that my backup was deleted too. Now all settings, private dictionary, etc, are gone forever. Very disappointed as it was a lot of work to add hundreds of additional words into the database...

Please make a big note/warning on this backup-restore feature until saving directory can be changed manually.

**Comment by lubenard** [comment]
Hey ! I am currently coding that feature ! 

It will work that way: 

If your smartphone is kitkat (android 4.4) or above, it will use the defaut android file selector, allowing, i hope, backup and restore on/from your google drive.

If you want more info about it, look on [this](https://developer.android.com/guide/topics/providers/document-provider) side.

If you are under Android 4.4, a intern file selector will be used, to ensure full compatibility with older devices. It will not be able to backup to google drive.

If you have any suggestions or questions about it, i'll be glad to hear them

**Comment by menny** [comment]
hey @lubenard any progress with this?

**Comment by lubenard** [comment]
Almost finished ! Writing unit tests, running them, and make a pull request

**Comment by menny** [comment]
nice! Then I'll wait for this before releasing the new IME.

**Comment by lubenard** [comment]
Here are a few screenshot of the file explorer. 
Version >= 4.4 will use Android Intent.

Backup 
![Screenshot_1593962342](https://user-images.githubusercontent.com/42534397/86608481-e83ed980-bfaa-11ea-8c4a-2b62a60cbd3b.png)

Restore
![Screenshot_1593962332](https://user-images.githubusercontent.com/42534397/86608470-e6751600-bfaa-11ea-96f6-afe99c970fc0.png)

**Comment by menny** [comment]
wonderful
