### ISSUE TITLE
Freeze when using domain long key on spanish layout

### ISSUE THREAD

**Issue by worg** [AnySoftKeyboard/AnySoftKeyboard#1781]
### Steps to reproduce
1. Open a browser and focus the url bar
2. Select spanish as layout
3. Type something and long press the [.com] key to get the domains popup

### Expected behaviour
Domain suggestion popup shows

### Actual behaviour
Keyboard freezes and stays on screen even when switching apps 

**Android OS version:**
9
**Device manufacturer and model:**
Xiaomi Mi A1
**List of installed add-ons (like languages, or themes):**
Spanish language pack

** Note: when using english the popup behaves correctly **

### Screenshot of the issue
![image](https://user-images.githubusercontent.com/675355/61478515-45371f00-a957-11e9-874d-c6b59c1085b6.png)

**Comment by menny** [comment]
thanks for reporting

**Comment by worg** [comment]
Thank you for all the work on ASK
