### ISSUE TITLE
Cannot copy version on version screen

### ISSUE THREAD

**Issue by timthelion** [AnySoftKeyboard/AnySoftKeyboard#1795]
### Steps to reproduce
1. Open the anysoft keyboard software

2. Press on the home button
3. Press the questionmark
4. long touch the version
![Screenshot_20190729-221909_AnySoftKeyboard](https://user-images.githubusercontent.com/1391608/62080854-f59f0000-b240-11e9-92be-8923968e3624.png)

### Expected behaviour
Context menu appears and user can copy version to clipboard

### Actual behaviour
Version cannot be coppied

**Android OS version:**
Lineage OS 16
**Device manufacturer and model:**
OnePlus 3t
**List of installed add-ons (like languages, or themes):**
None?

**Comment by menny** [comment]
that's a pretty good idea.
