### ISSUE TITLE
[Gesture typing] reset word mode on cursor move/positioning

### ISSUE THREAD

**Issue by ildar** [AnySoftKeyboard/AnySoftKeyboard#1798]
### Steps to reproduce
1. Gesture type aword 
2. Tap in the middle of the typed word to move and position the cursor 
3. Preform anything, e.g. tap ‘a‘ to insert a letter
4. See insertion failed adding new letter after the word

### Actual behaviour
See the word underlined. It brings a lot of weird effects, especially in interference with neighbour words

**Comment by menny** [comment]
@ArenaL5 can you take a look at this?

**Comment by ArenaL5** [comment]
I'm testing on current master (commit cad0bdb35fe4eeea260bdff1f4a8cb67e3a05914). The only weird effect I see is that the inserted letter is pushed away:

1. The predicted word is committed.
2. A space is inserted. The cursor is put after that space.
3. The letter you tapped is inserted. 
4. The cursor moves like normal, and ends up after that letter, ending with (for example) "testing a".

It doesn't matter if I use the cursor keys or tap directly in middle of the word.

Of course it's still wrong behaviour, but it seems different from what @ildar is describing. (That's to be expected, as this report is from months ago.)

Could somebody verify from current master?

**Comment by ildar** [comment]
I would be happy if anything was fixed. Then I'd test and report further
problems if remain
🤗
(As i already wrote I'm still on Gboard because of the annoying bugs that's
why I'm annoying )))

**Comment by menny** [comment]
I see the behavior @ildar is describing on the latest _master_

1. Swipe a word (say, "what")
1. Click the middle of the word to move the cursor to after the "a"
1. Type another "a".

Expected to see "whaat", but I get “what a".

@ArenaL5 do you see a different behavior? @ildar is that the issue you see?

**Comment by ildar** [comment]
Exactly. My version is 1.10.606 from
https://f-droid.org/app/com.menny.android.anysoftkeyboard

**Comment by ArenaL5** [comment]
We're all seeing the same issue, then.

I'll look into it.

**Comment by ildar** [comment]
I'm testing it and like it very much! Thanks a lot!
