### ISSUE TITLE
Update README.md and web-site to include new features

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#1800]
* Gesture-typing
* Dark-mode
* power-saving
* app-specific-theme-tinting.

**Comment by AnXh3L0** [comment]
Hey @menny, want me to update both of these?

**Comment by menny** [comment]
Please do @AnXh3L0

**Comment by AnXh3L0** [comment]
Okay, working on it, closing this for now as the updated descriptions should be up today.
