### ISSUE TITLE
[Request] add new top keyboard layout for text editing

### ISSUE THREAD

**Issue by puresinevgen** [AnySoftKeyboard/AnySoftKeyboard#1813]
I think it'll be nice to have the new text editing top keyboard layout, which will let better text navigation and editing.
Something like this.
![Screenshot_20190809-203639_](https://user-images.githubusercontent.com/46336966/62800680-a08aa600-baec-11e9-86ff-4f67b48cf095.png)

And this is the codes for the keys.

    <Row android:keyWidth="12.5%p" android:keyHeight="@integer/key_short_height" android:rowEdgeFlags="top">
        <Key android:codes="@integer/key_code_arrow_left" android:isRepeatable="true" />
        <Key android:codes="@integer/key_code_arrow_up" ask:longPressCode="@integer/key_code_move_home" />
        <Key android:codes="9" />
        <Key android:codes="@integer/key_code_clipboard_copy" ask:longPressCode="@integer/key_code_clipboard_cut" />
        <Key android:codes="@integer/key_code_clipboard_select" ask:longPressCode="@integer/key_code_clipboard_select_all" />
        <Key android:codes="@integer/key_code_clipboard_paste" ask:longPressCode="@integer/key_code_clipboard_paste_popup" />
        <Key android:codes="@integer/key_code_arrow_down" ask:longPressCode="@integer/key_code_move_end" />
        <Key android:codes="@integer/key_code_arrow_right" android:isRepeatable="true" />
    </Row>

My english is bad sorry for it.

**Comment by menny** [comment]
thanks a lot.
Don't you prefer to open a PR for this and get the credit?

**Comment by puresinevgen** [comment]
PR is good, but this top string is always within a touch, especially when you type a lot or edit many texts.

**Comment by ArenaL5** [comment]
> PR is good, but this top string is always within a touch, especially when you type a lot or edit many texts.

?

I think there's been a misunderstanding here. @menny meant a Pull Request, as in program it yourself and upload the code to GitHub so he'll be able to include it.

@puresinevgen, if you're interested in doing that and don't know how, I can guide you through it.

**Comment by puresinevgen** [comment]
> 
> 
> > PR is good, but this top string is always within a touch, especially when you type a lot or edit many texts.
> 
> ?
> 
> I think there's been a misunderstanding here. @menny meant a Pull Request, as in program it yourself and upload the code to GitHub so he'll be able to include it.
> 
> @puresinevgen, if you're interested in doing that and don't know how, I can guide you through it.

I'm not a programmer. Please explain me how to do that, i'll do everything i can.

**Comment by ArenaL5** [comment]
Sorry for the late reply, I needed to test a couple things.

I've noticed you already forked this project (you already have a puresinevgen/AnySoftKeyboard). Before you prepare your PR, you'll need to sync your fork with the original.

I assume you know how to use the command line; if not, tell me. Take your time, this is not difficult, but there a lot of steps, especially the first time.

So:

1. **[Install `git`](https://git-scm.com/downloads).** The only way to sync your fork is through `git`. (Or deleting and remaking your fork, but that's not an option if you already uploaded any work of yours.)
2. **Clone your fork (not the original)**. This means downloading the entire history of your project to your computer. Create a folder wherever you want, navigate there from your command line, and run
`git clone https://github.com/puresinevgen/AnySoftKeyboard.git`. Then wait a bit.
3. **Enter the newly created folder** with `cd AnySoftKeyboard`
4. **Download the newest changes from AnySoftKeyboard/AnySoftKeyboard**. Your fork is now pretty much a copy of AnySoftKeyboard/AnySoftKeyboard, so just run `git pull https://github.com/AnySoftKeyboard/AnySoftKeyboard`. This should be much quicker than step 2.
5. **Upload those changes.** You don't really _need_ to do it now, but it's a nice way to check if everything's working okay. Run `git push`. It will ask you for the username and password you use at GitHub. Type them, and then check [puresinevgen/AnySoftKeyboard](https://github.com/puresinevgen/AnySoftKeyboard).

If everything's okay, your fork should be up-to-date with the original, and you should be able to read "This branch is even with AnySoftKeyboard:master" (maybe translated to another language.)

6. **Create a new _branch_.** Again, it's not absolutely necessary, but it will make things _so much easier_ if you ever need to sync your repository again. Run `git checkout -b textedit` to create a new branch called `textedit` (you can choose any other name).
7. **Add your keyboard row to the project**. Your code's almost complete; you only needed to add a couple tags. Create a blank file at `ime/app/src/main/res/xml/`, open it in a text editor, and paste this content:

```xml
<?xml version="1.0" encoding="utf-8"?>

<Keyboard
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:ask="http://schemas.android.com/apk/res-auto">
<Row android:keyWidth="12.5%p" android:keyHeight="@integer/key_short_height" android:rowEdgeFlags="top">
    <Key android:codes="@integer/key_code_arrow_left" android:isRepeatable="true" />
    <Key android:codes="@integer/key_code_arrow_up" ask:longPressCode="@integer/key_code_move_home" />
    <Key android:codes="@integer/key_code_tab" />
    <Key android:codes="@integer/key_code_clipboard_copy" ask:longPressCode="@integer/key_code_clipboard_cut" />
    <Key android:codes="@integer/key_code_clipboard_select" ask:longPressCode="@integer/key_code_clipboard_select_all" />
    <Key android:codes="@integer/key_code_clipboard_paste" ask:longPressCode="@integer/key_code_clipboard_paste_popup" />
    <Key android:codes="@integer/key_code_arrow_down" ask:longPressCode="@integer/key_code_move_end" />
    <Key android:codes="@integer/key_code_arrow_right" android:isRepeatable="true" />
</Row>
</Keyboard>
```

(I only added four lines, indentation, and changed `9` for `@integer/key_code_tab`.)
Use a sensible name that fits in with the other names in the folder: in my examples I'm using `ext_kbd_top_row_text_editing.xml`

8. **Link to your code in the manifest.** AnySoftKeyboard doesn't automatically detect keyboards in that folder: you need to add it to the list. Navigate to this file _in your computer_:

https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/54b4c2f1a35adb6f699360b8e2095f24fa98770d/ime/app/src/main/res/xml/extension_keyboards.xml#L60-L69

and paste this code before the blank line:

```xml
    <ExtensionKeyboard
        id="16bbcd88-5532-4fd6-92ff-db57977dd815"
        nameResId="@string/extension_kbd_top_text_editing"
        extensionKeyboardResId="@xml/ext_kbd_top_row_text_editing"
        extensionKeyboardType="@integer/extension_keyboard_type_top_row"
        description=""
        index="9"
        />
```

Where:
* `id` is a random 128-bit number formatted like a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), I got it by searching `generate random uuid` on the web. You can use any UUID as long as it doesn't match exactly any other in the project.
* `index` is what it looks like: 1 for the 1st row, 2 for the 2nd row...
* `extensionKeyboardResID` *must* be `@xml/` plus the exact filename you chose in step 7, omitting `.xml`.
* `nameResId` *must* start with `@string/`. You can change the name after, but you'll need to remember for the next step.
9. **Name your keyboard.** The `nameResId` line above actually looks for a name in English in this file:

https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/54b4c2f1a35adb6f699360b8e2095f24fa98770d/ime/app/src/main/res/values/strings.xml#L542-L551

The code also includes translations for other languages, but those are managed via [Crowdin](https://crowdin.com/project/anysoftkeyboard) and @menny will have to set it up himself. So don't worry about it for this PR.

Add a line like this (again, in your computer) before the blank line:
```xml
    <string name="extension_kbd_top_text_editing">Quick text editing</string>
```
taking care that the name in quotes matches `nameResId` in step 8, and replacing `Quick text editing` for a better name if you have any.

From this point forward, Git will guide you through some steps. Now we'll do a final check-up before actually sending the changes.

10. **Double-check your changes.** Run `git status` and you should see a message like this, in red and white (the file paths are relative to the folder you run `git status` on):
```
On branch textedit
Changes not staged for commit:
  (use "git add ..." to update what will be committed)
  (use "git checkout -- ..." to discard changes in working directory)

        modified:     ime/app/src/main/res/values/strings.xml
        modified:     ime/app/src/main/res/xml/extension_keyboards.xml

Untracked files:
  (use "git add ..." to include in what will be committed)

        ime/app/src/main/res/xml/ext_kbd_top_row_text_editing.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

Now run `git diff` and you should see something like this:
``` diff
diff --git a/ime/app/src/main/res/values/strings.xml b/ime/app/src/main/res/values/strings.xml
index 044772c8d..88de9f5f7 100644
--- a/ime/app/src/main/res/values/strings.xml
+++ b/ime/app/src/main/res/values/strings.xml
@@ -548,6 +548,7 @@
     <string name="extension_kbd_top_nav">Navigation keys</string>
     <string name="extension_kbd_top_numbers_simple">Simple, numbers only</string>
     <string name="extension_kbd_top_terminal">Terminal</string>
+    <string name="extension_kbd_top_text_editing">Quick text editing</string>
 
     <string name="extension_kbd_bottom_regular_with_voice">Regular</string>
     <string name="extension_kbd_bottom_regular">Classic (no mic)</string>
diff --git a/ime/app/src/main/res/xml/extension_keyboards.xml b/ime/app/src/main/res/xml/extension_keyboards.xml
index de41d6f6f..1671cc45b 100644
--- a/ime/app/src/main/res/xml/extension_keyboards.xml
+++ b/ime/app/src/main/res/xml/extension_keyboards.xml
@@ -65,6 +65,14 @@
         description=""
         index="8"
         />
+    <ExtensionKeyboard
+        id="16bbcd88-5532-4fd6-92ff-db57977dd815"
+        nameResId="@string/extension_kbd_top_text_editing"
+        extensionKeyboardResId="@xml/ext_kbd_top_row_text_editing"
+        extensionKeyboardType="@integer/extension_keyboard_type_top_row"
+        description=""
+        index="9"
+        />
 
     <!-- bottom rows -->
     <ExtensionKeyboard
@@ -149,4 +157,4 @@
             description=""
             index="2"
             />
-</ExtensionKeyboards>
\ No newline at end of file
+</ExtensionKeyboards>
```

11. **(Finally!) Prepare your changeset.** (called "commit" in Git). Remember the instructions you got in step 10 when running `git status`? Follow them:
```
git add ime/app/src/main/res/values/strings.xml
git add ime/app/src/main/res/xml/extension_keyboards.xml
git add ime/app/src/main/res/xml/ext_kbd_top_row_text_editing.xml
```
and run `git status` again to double-check if you missed anything. Every file in red should be green now:
```
On branch textedit
Changes to be committed:
  (use "git reset HEAD ..." to unstage)

        modified:     ime/app/src/main/res/values/strings.xml
        new file:     ime/app/src/main/res/xml/ext_kbd_top_row_text_editing.xml
        modified:     ime/app/src/main/res/xml/extension_keyboards.xml

```
Create a commit with `git commit -m "Summary"`, replacing `Summary` with an actual summary. Git won't let you create a commit with no summary at all; write something sensible.

Git will then print a message about your author information. **Read this message carefully;** older versions of Git will set your author information automatically, based on the username and hostname on your PC. Newer versions of Git will outright refuse to work until you set up an author name and an author email.

12. **Upload your commit, and create a remote branch in the process.** Branches on your PC don't need to match branches on your Git repo, but this is already confusing enough so we'll force it to be.

Assuming you named your local branch `textedit`, run `git push origin textedit:textedit`, type your username and password when Git asks you for them, and... congratulations! You're done with Git for today!

13. **Create a pull request.** In your web browser, go to ]your repo](https://github.com/puresinevgen/AnySoftKeyboard). You should see a yellow box reading something like:

"Your recently pushed branches: **textedit** (lest than a minute ago). **Compare and pull request**"

Push that button and follow the instructions, and you're set!
