### ISSUE TITLE
[Feature request] Theme the navbar based upon the app

### ISSUE THREAD

**Issue by IOI-655321** [AnySoftKeyboard/AnySoftKeyboard#1824]
Can the navbar colour be themed based upon the app? Other keyboards such as Swiftkey do this and it makes for a nice experience, especially when using a dark theme.  Im not sure if the setting for this comes from the app or the keyboard but ive noticed in apps such as signal with dark mode on Swiftkey shows the nav button background dark but ASK shows a light button background.

**Comment by AnXh3L0** [comment]
Hi,

This feature has been implemented in the latest alpha, should be available in the next stable release on F-Droid/Play Store.

**Comment by IOI-655321** [comment]
Excellent thanks will look forward to that.
