### ISSUE TITLE
English symbols-There's no semicolon

### ISSUE THREAD

**Issue by whichwaywaswest** [AnySoftKeyboard/AnySoftKeyboard#1837]
### Steps to reproduce
1.Use Symbols key (123)
2.Use  Top Extension 
3. Checked all symbols layouts

### Expected behaviour
You would imagine there would be a semicolon somewhere in the symbols layout, but there isn't one on any screen that I can see. 

### Actual behaviour 
Missing semicolon

**Android OS version:**
7.1.1
**Device manufacturer and model:**
Motorola Moto e4
**List of installed add-ons (like languages, or themes):**
English and Lean Dark Grey

**Comment by whichwaywaswest** [comment]
Like I'm not going crazy right? I've had this keyboard for a month or so now, and I guess I've just never had to use one up until now, but I searched through all the layouts and popups,  and can't for the life of me find it.

**Comment by santa-klaus** [comment]
In my layout the semicolon appears on long-press on `.` in the english layout, or on long-press on `:` in the first symbols layout. I can't see it anywhere as a key, though.

**Comment by ArenaL5** [comment]
The bottom row and the symbols page are universal. They are the same for every language pack.

Semicolons certainly haven't a dedicated key because two pages of symbols are already enough. Long-pressing on colon or comma seems appropriate for a relatively uncommon sign.
