### ISSUE TITLE
AOSP Light theme has wrong font color in long-press keys

### ISSUE THREAD

**Issue by santa-klaus** [AnySoftKeyboard/AnySoftKeyboard#1839]
### Steps to reproduce
1. Set your theme to AOSP Light
2. Long-press a key.

### Expected behaviour
The keys that appear on long-press should have the same font color as the normal keys.

### Actual behaviour
The font color is white, making it nearly impossible to distinguish the keys.

**Android OS version:**
Android 7.1.2 (Fairphone Open OS 19.08.1)

**Device manufacturer and model:**
Fairphone 2

**List of installed add-ons (like languages, or themes):**
German, Spanish, Swedish, NEO2

**Comment by AnXh3L0** [comment]
Thank you for opening this issue @santa-klaus, I managed to reproduce the bug. Will check and try to fix it.

**Comment by santa-klaus** [comment]
that would be really great, thank you!

**Comment by AnXh3L0** [comment]
@ArenaL5 can you assist me with this please?
