### ISSUE TITLE
UI settings panel clipped and non-scrollable

### ISSUE THREAD

**Issue by santa-klaus** [AnySoftKeyboard/AnySoftKeyboard#1842]
### Steps to reproduce
1. Go to the settings and press the palette to access UI settings.
2. Try to read the last menu entry or to scroll down to read it.

### Expected behaviour
No menu entry should be clipped. If the whole menu doesn't fit the screen it should be scrollable.

### Actual behaviour
The last entry ('User Interface') is clipped, and you can't scroll down to read it.

![image](https://user-images.githubusercontent.com/10899463/64858758-90547200-d628-11e9-8baf-4ee98ecededf.png)

**Android OS version:**
Android 7.1.2 (Fairphone Open OS 19.08.1)

**Device manufacturer and model:**
Fairphone 2

**List of installed add-ons (like languages, or themes):**
German, Spanish, Swedish, NEO2

**Comment by ArenaL5** [comment]
Duplicate of #1580. Thank you for the screenshot, it helps a lot.

This should be easy to fix, but there are a lot of bugs open and the next release will take time. Please be patient.

For the moment, turn your phone. The keyboard should disappear in horizontal screen mode, and there should be more than enough space for all three buttons.

**Comment by santa-klaus** [comment]
Sorry for not finding the duplicate! I will be patient, really like the app and would love to see it get better :)

**Comment by menny** [comment]
I think that this issue is fixed for the next release, and already available in the alpha.
See https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1812
