### ISSUE TITLE
[Feature Request] Google Keyboard Layout

### ISSUE THREAD

**Issue by baarkerlounger** [AnySoftKeyboard/AnySoftKeyboard#1844]
Is there a configuration option (or could there be) for the button layout to be the same as that of the standard Google keyboard.

Mainly the bottom row making the space bar wider and/or moving it further to the right and only having one punctuation mark next to it rather than two as shown below:

![image](https://user-images.githubusercontent.com/5101747/68140874-70ed0d80-ff24-11e9-8a03-c0c4bef812e2.png)

**Comment by jwsp1** [comment]
Please add a screenshot to show what you mean. It makes it easier for the dev to understand what you mean.

**Comment by dan26dlp** [comment]
Anysoftkey app>UI>Common bottom generic row>Simple

This will essentially be identical to your screenshot here.

**Comment by dan26dlp** [comment]
I do wish there was a layout with the period on the other side of the space key since I tend to hit the period key on accident, but I think this is the best I can get

**Comment by baarkerlounger** [comment]
@dan26dlp that's the exact reason I wanted this but I think you're right, the simple UI is actually close enough.
