### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by userkilled** [AnySoftKeyboard/AnySoftKeyboard#1846]
Sorry, but there will be a development for ios, really want to see your beautiful keyboard in the app store?

**Comment by jwsp1** [comment]
I doubt that the @menny has capacity to build an iOS version. 

I think this issue can be closed, as well as a lot of other open issues here. Hope @menny will find some time to take care of those issues which won't be fixed/realized. 476 open issues look just too messy in my eyes, especially when realizing that 50% are issues/feature requests that most likely won't be worked on.

**Comment by AnXh3L0** [comment]
Hello there, for the moment there is no plan for an iOS version as the Android version still needs a lot of polishing. Closing this for now.
