### ISSUE TITLE
[bug] not possible to add one letter word 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [AnySoftKeyboard/AnySoftKeyboard#1849]
It's not possible to add one letter word directly by double taping on it. Still possible in option, edit dictionary.

**Comment by jwsp1** [comment]
This is the same behavior as when trying to add a word while incognito mode is enabled. It also doesn't work then, regardless how many characters.

Referring #1738

**Comment by ArenaL5** [comment]
Duplicate of #1747.
