### ISSUE TITLE
No Paragraph Sign § (German)

### ISSUE THREAD

**Issue by SubSi** [AnySoftKeyboard/AnySoftKeyboard#1853]
### Steps to reproduce
1. No § sign (paragraph Sign)
2.
3.

### Expected behaviour
Tell us what should happen
Sign should be there

### Actual behaviour
Tell us what happens instead
It doesnt excist

**Android OS version:**
9
**Device manufacturer and model:**
Huawei
**List of installed add-ons (like languages, or themes):**
German language

**Comment by s99h** [comment]
In release 1.10-r3 it's shows in numedic mode after a long press on the asterisc.
Maybe it was there in older releases too.

**Comment by menny** [comment]
It's also long-press on `s`
