### ISSUE TITLE
White bar below the keyboard

### ISSUE THREAD

**Issue by attuo** [AnySoftKeyboard/AnySoftKeyboard#1857]
### The problem
* After updating OnePlus 7 from Android 9 (Oxygen OS 9.5.11) to Android 10 (Oxygen OS 10.0) the white rectangle appears below the keyboard every time using the keyboard.
* Might not be related to the updating though.

Image demonstrating the problem, white rectangle below the keyboard:
![keyboard_bug](https://user-images.githubusercontent.com/13207859/66221984-a30a1600-e6bf-11e9-817c-1b2ba7292b5e.jpg)

**Android OS version:** 
* Oxygen OS 10.0

**Device manufacturer and model:**
* OnePlus 7

**List of installed add-ons (like languages, or themes):**
* Finnish for AnySoftKeyboard (installed)

* Lean Dark theme (native, not installed)

**Comment by praveenchandranpk** [comment]
Same issue here. Oneplus 5t android 9.

**Comment by attuo** [comment]
So if you have the same problem on Android 9, the problem is not related to the Android 10 then.

**Comment by Monti94** [comment]
Same here, Huawei P10 lite, Amdroid 8.0

**Comment by menny** [comment]
I've added an option in the settings app to disable nav-bar colorizing.

**Comment by menny** [comment]
will be in the beta channel in a couple of hours.
