### ISSUE TITLE
Emoji not show

### ISSUE THREAD

**Issue by dickyharper** [AnySoftKeyboard/AnySoftKeyboard#1874]
![Screenshot_2019-11-10-15-05-38](https://user-images.githubusercontent.com/50758669/68588315-3b9f6d00-049a-11ea-91bd-fcb48ac28187.png)

### Steps to reproduce
1.If I choose emoji
2.Not show anything.

### Expected behaviour
I hope this an issue.  I love your app.

Samsung s4 gt-i9500
5.0.1 lollipop.

**List of installed add-ons (like languages, or themes):**

Turkish language addon.

**Comment by dickyharper** [comment]
Some of the punctuation marks have the same problem.

**Comment by menny** [comment]
This is fixed for the next release.
This is duplicate of https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1688
