### ISSUE TITLE
Incorrect display of the sizes of the letters Ш and Щ in Russian keyboard

### ISSUE THREAD

**Issue by ediowar** [AnySoftKeyboard/AnySoftKeyboard#1892]
### Steps to reproduce
1. Update to latest beta version
2. Start input
3. Place your smartphone vertically
4. Tap on shift

### Expected behaviour
All letters must be resized

### Actual behaviour
The size of the letters Ш and Щ almost does not change
[Screenrecorder-2019-12-01-23-13-54-360.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/3908682/Screenrecorder-2019-12-01-23-13-54-360.zip)

**Android OS version:**
9 PKQ1.190319.001
**Device manufacturer and model:**
Xiaomi Redmi 7A
**List of installed add-ons (like languages, or themes):** 
Russian keyboard

**Comment by ArenaL5** [comment]
I can confirm this bug on an old phone, but it only affects the labelling of the keys. The keys correctly output lowercase ш, щ and uppercase Ш, Щ as usual.

This is almost certainly a consequence of #1539; see that for details.
