### ISSUE TITLE
[Feature Request] Option to swap numbers with special characters while holding shift

### ISSUE THREAD

**Issue by udit** [AnySoftKeyboard/AnySoftKeyboard#1894]
Holding shift only changes the letters to capital. It would be nice if it changes the numbers in the top row to their respective special characters (1 to !, 2 to @ etc).

This will be useful in typing passwords with several common special characters. As of now it requires switching back and forth between main keyboard and special characters or long pressing numbers which takes more time.

**Comment by menny** [comment]
This was missed.

Right now, if you do not have a generic-top-row (that is, generic-top-row is set to None) when you type in a password field, we'll automatically include a _numbers top row_ that will show the special characters when holding the shift key.

**Comment by ArenaL5** [comment]
I can confirm. The number keys on password fields already change as @udit requests __unless__ they have set their top row to "Number keys".

This is inconsistent behaviour and will be fixed.
