### ISSUE TITLE
[Feature Request] Disable bottom row below space that hold the icons

### ISSUE THREAD

**Issue by rockavoldy** [AnySoftKeyboard/AnySoftKeyboard#1895]
I need option to disable bottom row that hold the icons like battery, it's really anoying cause the key sometimes not pressed, I always hit the bottom row below space, i had using another theme, but like it's not the theme itself.. please add this feature

**Android OS version:**
LineageOS 16.0 (Android 9 Pie)

**Device manufacturer and model:**
Redmi 5A (riva)

**List of installed add-ons (like languages, or themes):**
no installed add-ons

**Comment by Mersadon** [comment]
I would also like to ask the devs to include the option to adjust or disable the spacing between the bottom row and screen edge. I am also quite often hitting the spacing below spacebar.
Thanks
