### ISSUE TITLE
No backspace in first symbols keyboard

### ISSUE THREAD

**Issue by ashirviskas** [AnySoftKeyboard/AnySoftKeyboard#1898]
### Steps to reproduce
1. Click on "123!#()" button while in keyboard

### Expected behaviour
I see all the symbols and a backspace button

### Actual behaviour
I don't see the backspace button, just an empty space in its place.

**Android OS version:**
9.0
**Device manufacturer and model:**
Oneplus 6
**List of installed add-ons (like languages, or themes):**
Lithuanian and Russian keyboards. Nothing else.

![Screenshot_20191204-222921__01](https://user-images.githubusercontent.com/11985242/70178978-d9770800-16e5-11ea-8ac8-1a2b1acbf9c5.jpg)

**Comment by ashirviskas** [comment]
Version 1.10.1064, version-code 6234

**Comment by menny** [comment]
Thank you for reporting

**Comment by ArenaL5** [comment]
I was hoping that no one would notice until I fixed it... that one was a typo I made. I accidentally disabled that key. Sorry.

I've made a fix (040c74d8daa3eee8d96880cb1ba37299b399ca22), and we'll merge it very soon, along with simple fixes for other bugs.
