### ISSUE TITLE
feature request: simultaneous multiple languages

### ISSUE THREAD

**Issue by Rik44444** [AnySoftKeyboard/AnySoftKeyboard#1918]
Hi ASK, thank you for all your work on this great keyboard! 
i have a feature request: to make it possible to use multiple languages simultaneously, so that you do not have to switch between languages when typing. Swiftkey has this feature, which is why i always used their keyboard in the past. I'm trying your keyboard now, because i'm a big fan of open source, and this would be a great addition!

**Comment by ArenaL5** [comment]
This option already exists, but the configuration screen is glitched and doesn't display it (#1794).

Hold the Enter key, then tap "Override default dictionary" and select which languages you want. Dictionaries are bundled with language packs.

**Comment by Rik44444** [comment]
amazing!! this definitely deserves to get more attention in the ASK app, i know that specifically for this reason many people use Switfkey. If more people knew this was possible they might switch to ASK!

**Comment by ArenaL5** [comment]
Good to know! I'll add a line to the README in my next pull request. :smile:

**Comment by Rik44444** [comment]
i would do more than add a line to the Readme, i would advertise this as a function! i know only 1 other keyboard that offers this, and it's a big +!

**Comment by ArenaL5** [comment]
I... hadn't noticed. I only mostly type in one language on my phone, and half the time I type everything manually.

@AnXh3L0, you're mostly in charge of https://anysoftkeyboard.github.io/, right? What do you think?

**Comment by jwsp1** [comment]
Wow! Missed that feature as well, and just discovered it. Thank you for describing your workaround! #1794 should be fixed soon in order to allow others to enable this awesome feature

**Comment by AnXh3L0** [comment]
@ArenaL5 yeah, I'm in charge of the website, I will update it to include this feature too.

**Comment by NeoScaler** [comment]
Searched for two days, because I read it on the homepage but did not find it in the settings.

**Comment by menny** [comment]
@AnXh3L0 I was wondering if it will be helpful to include a section in the website with guide about some features (how to set up, and how it looks in real life). Maybe a set of gifs?

**Comment by AnXh3L0** [comment]
@menny sure, that could work.

**Comment by Rik44444** [comment]
> 
> 
> Searched for two days, because I read it on the homepage but did not find it in the settings.

do i understand you've not been able to enable multiple languages...? this is the way to do it: Hold the Enter key, then tap "Override default dictionary" and select which languages you want. Dictionaries are bundled with language packs.
