### ISSUE TITLE
Unicode Combining Characters Interpreted as End-of-Word Character

### ISSUE THREAD

**Issue by martholomew** [AnySoftKeyboard/AnySoftKeyboard#1919]
While I was trying to [make a Sinhala language pack](https://github.com/AnySoftKeyboard/LanguagePack/issues/277), I realized that [unicode combining characters](https://en.wikipedia.org/wiki/Combining_character) are interpreted as an end-of-word character (like a space character would be), resulting in the suggestions dictionary picking the word it thinks is closest at that point, as it would if you were to hit space.

I tried looking through the code, but I couldn't find the offending line. I know you've been working on code near this problem @ArenaL5 , have any ideas?

**Comment by ArenaL5** [comment]
I would try tracking this function through all the Java code:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/849c13a13125c0955139727112e420c2c88a477e/app/src/main/java/com/anysoftkeyboard/dictionaries/TextEntryState.java#L73

`isSeparator` decides if it is an end-of-word character or not. Most of the calls to that function are done from https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/849c13a13125c0955139727112e420c2c88a477e/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java but it's hard to follow.
