### ISSUE TITLE
Issue:White strap at the bottom of the keyboard, after OS upgrade

### ISSUE THREAD

**Issue by ronvalensi** [AnySoftKeyboard/AnySoftKeyboard#1928]
Hello team,

I have Samsung Galaxy Note 10 plus.
I had a software upgrade to the OS last week and since then, I have a white strap at the bottom of the keyboard.

### Steps to reproduce
1. Enter any Text window in the phone (Browser search, Whatsapp, etc.)
2. Anysoft keyboard will pop out, with a white strap gap at the bottom.

### Expected behaviour
AnysoftKeyboard will be anchored to the bottom of the phone.

### Actual behaviour
AnysoftKeyboard pops out, but there is a white strap at the bottom.
(see screen shot)
[https://ibb.co/sRr3z1k](url)

**Android OS version:**
10

**Device manufacturer and model:**
Samsung Galaxy Note 10 Plus

**List of installed add-ons (like languages, or themes):**
Anysoft board + The Herbew add-on.

**Comment by brunofontes** [comment]
I have exactly the same issue in a Moto G5 Plus with Brazilian Portuguese Language Pack in Android 8.1.0

But when I try to use the numbers or change the keyboard language, it just freezes.

**Comment by ronvalensi** [comment]
Hello Bruno, what do you mean by uninstall from Google Apps and install on F-Droid?
Sorry for the ignorance :)

**Comment by brunofontes** [comment]
Oh, I just uninstalled it from my phone (it had been previously installed from play.google.com) and I installed it again using F-Droid: https://f-droid.org/packages/com.menny.android.anysoftkeyboard/

I hope I could make myself clear this time!  :)

**Comment by menny** [comment]
Please provide screenshots of the issue. And specify which OS you are using. Also, if you can, provide a screenshot of the previous state.

**Comment by menny** [comment]
Can you check to see how "Draw behind the navigation-bar" setting affects this?
(settings app -> UI-> Effects)
<img width="469" alt="Screen Shot 2020-01-04 at 8 00 31 PM" src="https://user-images.githubusercontent.com/481272/71773553-e5e0c180-2f2c-11ea-9d64-335f0bfbc174.png">

**Comment by janslav** [comment]
> Can you check to see how "Draw behind the navigation-bar" setting affects this?
> (settings app -> UI-> Effects)
It does affect it for me. Disabling the option fixes the problem for me. Thanks for the tip.

**Comment by menny** [comment]
can you send screenshots with the check on and off?
And which device/OS you are using

Thanks

**Comment by ronvalensi** [comment]
Any idea why I don't have those option under "Effects"?
<a href="https://ibb.co/NmbLR8V"><img src="https://i.ibb.co/QCt602b/effects.jpg" alt="effects" border="0"></a>

**Comment by menny** [comment]
@ronvalensi which version of the app are you using?

**Comment by ronvalensi** [comment]
1.10.606, may 4, 2019. That's the latest one I have in the Play Store.

**Comment by menny** [comment]
This feature is in the next release. I've increased the rollout so you should see this update soon.
