### ISSUE TITLE
Words were automatically saved with manual lerning method

### ISSUE THREAD

**Issue by LeSnake04** [AnySoftKeyboard/AnySoftKeyboard#1929]
I set the save save words setting to manual, but ASK save often word automatically.

(Maybe you forgot, that arrays start on 0. Thats often the problem.)

Version: 1.10-r2

**Comment by ArenaL5** [comment]
If I understood you correctly, your bug is already fixed with PRs #1887 and #1893 in AnySoftKeyboard Beta, but this correction wasn't released to F-Droid or Google Play yet.

To see this bug fixed, you'll need to either compile the beta APK from `master` branch, or wait for a new release.
