### ISSUE TITLE
Feature request: Fast possiblility to switch on/off num line (gesture?)

### ISSUE THREAD

**Issue by knutii** [AnySoftKeyboard/AnySoftKeyboard#1937]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by AnXh3L0** [comment]
Can you please complete this issue @knutii?

**Comment by knutii** [comment]
For example: Add toggle num line to gesture action list?

**Comment by knutii** [comment]
I do not want to switch on the num line all the time because it takes away space from the screen, but sometimes it would be nice to have it available for some time. Switching it on and off in a simple and fast way would be nice.

**Comment by menny** [comment]
when I need to enter a digit or two I use the Top-Extension keyboard (swipe up over the keyboard top edge).

If you need it to be sticky (keep open until BACK is pressed), you can set it so in the UI->Effects->Tweaks

Does that solve your issue?

**Comment by knutii** [comment]
Great, exactly what I was looking for!
Still learning how to use all the included features, best keyboard I ever had!

**Comment by nicoursi** [comment]
In my case it closes when I press any key out of the Top extension keyboard. Not only when BACK is pressed. 
This way it's not easy to write an alphanumeric code without getting the extension bar closed at the first letter typed.

Is this a bug, or it's intended behaviour?
