### ISSUE TITLE
[Issue] fixing previous words replaces them by whitespace

### ISSUE THREAD

**Issue by janslav** [AnySoftKeyboard/AnySoftKeyboard#1940]
### Steps to reproduce
1. Write "one two three"
2. Touch "two" to move the cursor there to change it.
3. Make any modification (backspace to delete 'o' or add a new char or anything)
4. the word gets replaced by whitespace. The whitespace needs to be deleted, otherwise it usually breaks the text (so it probably isn't simple spaces but some invisible/unprintable characters etc.)

### Expected behaviour
Should be possible to edit anything, not just the current (last) word in a text.

### Actual behaviour
As seen in step 4, the text gets broken. Editing the last word works ok.

**Android OS version:**
9 (gonna update to 10 now, will report if problem persists)
AnySoftKeyboard version 1.10.1079, code 6249

**Device manufacturer and model:**
Samsung Galaxy S10e

**List of installed add-ons (like languages, or themes):**
"Czech for AnySoftKeyboard"

**Comment by menny** [comment]
This issue was fixed a couple of days ago and should be available as updated version 1.10.1089. See https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1900

**Comment by janslav** [comment]
Thanks, problem gone.
