### ISSUE TITLE
F-Droid Summary

### ISSUE THREAD

**Issue by uniqx** [AnySoftKeyboard/AnySoftKeyboard#1962]
F-Droid will update how we display summary text in our next app release. Summary text will now always be highlighted and prepended to the long app description.

Your long description text starts with the same text you've got in your summary. This will look redundant. I recommend to remove the summary text from your long description.

here are more infos/screenshots about this update: [fdroidclient!855](https://gitlab.com/fdroid/fdroidclient/merge_requests/855)

**Comment by menny** [comment]
@uniqx  makes sense. It's been a while since I made changes to fdroid, can you point me to the location of the summary details? Or are you taking that from Play Store?

**Comment by menny** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6319

**Comment by menny** [comment]
merged.
