### ISSUE TITLE
ASK is very out of date on F-Droid

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AnySoftKeyboard/AnySoftKeyboard#1983]
The AnySoftKeyboard application is one update behind the current version on F-Droid. On Google Play, it's perfectly up to date.

AnySoftKeyboard - German Language Pack is about 2 years behind the current update on F-Droid.

**Comment by menny** [comment]
we have an ongoing attempt to update fdroid: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1637
