### ISSUE TITLE
update at fdroid

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#1992]
Hi,

I saw there is a new version on play store. When will it be at fdroid?

Thanks

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by Glitchy-Tozier** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1983#issuecomment-578154279

**Comment by AnXh3L0** [comment]
The new version has been merged on F-Droid and will be available soon.

**Comment by Joppla** [comment]
Thanks
