### ISSUE TITLE
Allow editing the "Quick Fixes" dictionary

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#202]
Any word from the dictionary pack should be marked as Read-Only.
User can define new ones.

**Comment by stephenrubio94** [comment]
Is this working as of the Oct 11, 2018 build?  I'm using that on Android 9, and added abbreviations are not being replaced or suggested.
![screenshot_20181211-155805](https://user-images.githubusercontent.com/7660517/49838097-e4f75380-fd5d-11e8-9d8b-f456f18cf868.png)
![screenshot_20181211-155823](https://user-images.githubusercontent.com/7660517/49838098-e4f75380-fd5d-11e8-90eb-a8b6e147b6b3.png)
