### ISSUE TITLE
customize vibration

### ISSUE THREAD

**Issue by Monirzadeh** [AnySoftKeyboard/AnySoftKeyboard#2024]
Please add an option to customize vibration feedback
Current vibration option get a sense of vibration whole phone
In other keyboard like Gboard it is so better
So if I can control vibration time and power of that, I can simulated exact feedback that I like

**Comment by menny** [comment]
This should be possible. Check the vibration settings in UI
![Screenshot_20200207-073214](https://user-images.githubusercontent.com/481272/74030054-1a0c2f80-497c-11ea-8865-0ff023dfbc22.png)

**Comment by Monirzadeh** [comment]
I don't have this option only (none light medium strong)
I install that from fdroid

**Comment by menny** [comment]
There should be a new version on fdroid that has this setting

**Comment by Monirzadeh** [comment]
Last update is for 8 months ago
How should I install newer version there?
