### ISSUE TITLE
Meta: anysoftkeyboard-bot is closing stale issues incorrectly

### ISSUE THREAD

**Issue by papb** [AnySoftKeyboard/AnySoftKeyboard#2066]
The bot closed issue #1390 even though comments were made to prevent the stale condition... It should have removed the label but did not.

**Comment by menny** [comment]
Agree. I realized that the message was incorrect, and the actual action required is to remove the label. I updated the bot's message.

**Comment by papb** [comment]
@menny Thanks! I believe issue #1233 has the same problem
