### ISSUE TITLE
[Button Change] [Spanish Layout] Change "¿" and "¡" characters in symbols keyboard [Low priority]

### ISSUE THREAD

**Issue by LukasThyWalls** [AnySoftKeyboard/AnySoftKeyboard#2074]
This is a small change in the Spanish layout because in Spanish the characters "¿" and "¡" are more used than other more easily accesed with the actual layout.

This are the actual layout
![ASK_Spa_SymbolsOriginal](https://user-images.githubusercontent.com/1467366/75100903-8de14580-55d4-11ea-8dad-c3af3af5d8c9.jpg)

And this is what make more sense in Spanish
![ASK_Spa_SymbolsFixed](https://user-images.githubusercontent.com/1467366/75100910-9e91bb80-55d4-11ea-921a-0719e67995cb.jpg)

I know you can access all these characters in the "letters" keyboard pressing the "." button, but it's a detail to make more sense with the keyboard.

**Comment by menny** [comment]
You're suggesting that we switch the order of the popups for Spanish locales?

**Comment by LukasThyWalls** [comment]
Basically, the popus of "!" and "?" buttons looks now like the first image, and i would be better like the second image (more logical and usable for spanish language, of course).
