### ISSUE TITLE
"Activate ASK"-Screen can't be Skipped.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AnySoftKeyboard/AnySoftKeyboard#2087]
### Steps to reproduce
Every time the app is opened while the Keyboard is disabled in the Android-Keyboard-Settings, the "Activate AnySoftKeyboard"-screen pops up. (the one with the big OFF-icon)

### Expected behaviour
Users should be able to skip this screen and go into the AnySoftKeyboard-settings even though it's not enabled.

### Actual behaviour
They can't. There is no "skip"-button.

**Android OS version:**
10
**Device manufacturer and model:**
Samsung Galaxy S9
**List of installed add-ons (like languages, or themes):**
German

**Comment by menny** [comment]
good point
