### ISSUE TITLE
"shiftedOutputText" and "outputText" Reset Word Prediction

### ISSUE THREAD

**Issue by martholomew** [AnySoftKeyboard/AnySoftKeyboard#2096]
This behavior can be observed on the "shiftedOutputText" keys on the Sinhala Inscript keyboard. On being pressed, the word predictions are reset.

This is because it uses the onText function which is supposed to have this behavior.

There are three solutions:

- Change the onText function's behavior, which will inadvertantly change quickText behavior.

- Make a new function that the outputText keys will use.

- Get rid of shiftedOutputText and switch the keycodes to using a 2d array so that all the keys can have multi-character outputs, each comma'd off from the other.

The second solution will be the easiest immediately, while the third makes more sense in the long run.

**Comment by menny** [comment]
Another option is to only abort predictions if the text ends with a space, or other word terminator.

Or more generally, have `onText` feed each character into the `onKey` function

**Comment by martholomew** [comment]
Oh that will be much easier. Will do.

**Comment by menny** [comment]
I realize that it will make more sense to have another API method `onTyping`. The difference is that `onText` will commit the entire text directly to the input-box and will stop prediction, what `onTyping` will stimulate typing.

`onText` will be used for emojis, clipboard, etc.
`onTyping` will be used when multiple code-points need to be output as part of the word.
