### ISSUE TITLE
Disable autocorrection, not suggestions

### ISSUE THREAD

**Issue by LukasThyWalls** [AnySoftKeyboard/AnySoftKeyboard#2135]
Hi

There is a way to disable autocorrection (auto change words) without disabling the word suggestions?

I tried disabling "Fast Corrections and abbreviations" (Spanish -> English translation) option, i see that here in other issue, but ASK is still changing words while i'm writing.

I want to do this first because i don't like the auto change words, but also because ASK is doing very bad suggesting and changing words when i am using two dictionaries together (Spanish and English), but that's another issue.

**Comment by entfernt** [comment]
yes i need suggestion but no autocorrection too. I font find a Setting for it.

**Comment by decadent** [comment]
In settings → Language → Correction behavior, set ‘Auto-select suggestion aggressiveness’ to ‘off’.

**Comment by menny** [comment]
what @decadent said.

**Comment by decadent** [comment]
Frankly this option is not very intuitive: I too disabled suggestions at first and wasn't sure that what I want instead is possible.
