### ISSUE TITLE
[bug] adding a word to one dictionary,  erases it from the other

### ISSUE THREAD

**Issue by nicoursi** [AnySoftKeyboard/AnySoftKeyboard#2139]
### Steps to reproduce
Add the following words to the word editor for the English language 
1. `I`
2. `a`
3. `A`
Now change language to italian and add them there too
1. `I`
2. `a`
3. `A`

### Expected behaviour
Both dictionaries (Italian and English) should have `I`, `a` and `A` in their dictionaries.

### Actual behaviour
If the word you're adding to a dictionary already exists in another dictionary,  it will be removed from the former one.
So, in the example above, `I`, `a` and `A` will be erased from the English dictionary. If you add them back to the English dictionary,  they will be automatically removed from the Italian one. This happens with both, Android's global built in User-dictionary and private user dictionary storage.

Setting minimum word lenght suggestion to 1 and  adding these letters to both, Italian and English dictionaries works as a work around for bug [1730](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1730)

**Android OS version:**
9.0
**Device manufacturer and model:**
Xiaomi Redmi Note 7
**List of installed add-ons (like languages, or themes):**
Italian, English
Yockeys  Dark option dark theme

**Comment by georgikoemdzhiev** [comment]
I noticed that too

**Comment by maximilianovermeyer** [comment]
Should be the same problem like in #2033 .

**Comment by nicoursi** [comment]
Duplicate of #2033
