### ISSUE TITLE
Gesture typing does not support other languages

### ISSUE THREAD

**Issue by 12people** [AnySoftKeyboard/AnySoftKeyboard#2162]
### Steps to reproduce
1. Switch to the Czech ASK language.
2. Try to gesture type (= swipe)

### Expected behaviour
Standard gesture typing functionality

### Actual behaviour
Gesture typing does not work

**Android OS version:**
Oreo

**Device manufacturer and model:**
Fairphone 3

**List of installed add-ons (like languages, or themes):**
Czech for AnySoftKeyboard

**Comment by tobiasBora** [comment]
I can confirm a bug in the way gesture typing picks its dictionary: when I long press Enter and select another dictionnary (for example English dictionary on a French Bépo layout), the gesture typing sill uses the french dictionnary.

**Comment by MisterY** [comment]
Also, when multiple dictionaries are used, the gesture-typing only uses the one that is assigned to the current layout .
Example : I'm using Dvorak layout with three languages. When glide-typing, only English suggestions will be displayed, ignoring the other two languages.

**Comment by tobiasBora** [comment]
Also, it has some troubles with the punctuation. Like in french, you find ' a lot in between two words like j'aime, j'oublie, il m'oblige... and it's not properly handled

**Comment by tobiasBora** [comment]
@menny thanks a lot! Is this supposed to solve the issues with ponctuation or not?

**Comment by menny** [comment]
I'll need more info and examples for that.

**Comment by tobiasBora** [comment]
So for instance if I swype and don't get the correct word, I'll clic on the word in the proposition bar above the keyboard. This will insert the good word, together with a space. If I continue to swype, the next word will be inserted with a space in front, leading to two spaces like `my  words`. Also, when I swype a word containing the char `'`, like `je m'assure` (in french), the word is usually not found. Note that I've the feeling that the words I often use are found, so it may be possible that the default french dictionnary is lacking all words with a `'` char, but that when I type them manually they end up in my own dictionnary (now, I can type ` aujourd'hui` while when I got my phone I could not). However, it may be possible to avoid adding many entries to the dictionnary by just allowing verbs starting with a voyel to be prepended with m/s/t followed by an appostrophe (there may be other letters, but I can't find other exemples without m/s/t). Of course, only for french.

**Comment by ferromint** [comment]
> [...] you find ' a lot in between two words like j'aime, j'oublie, il m'oblige [...]

@menny, it seems to me as if the second topic about the single quote character being used in French e.g. for reflexive verbs (actually separate from the original issue's topic) @tobiasBora brought up, relates either more to #2163, not in a grammatical sense but a conceptual way, or should be a completely separate topic.

Both topics are about leaving out letters and contracting two words into one using a single quote character (but in different languages with different grammatical rules).

e.g. English:
do not (correct) -> don't (also correct)
vs
e.g. French:
je aime (incorrect) -> j'aime (correct)

**Comment by ferromint** [comment]
@tobiasBora, in the <a href="https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3250#issuecomment-1383688728">comment of a different issue</a> (actually dealing with hyphenation) @LoukaOctave reported that gesture typing of words with apostrophes in French works (at least for a few examples/attempts).

Do you have the latest version of ASK installed?
If yes, can you verify if at least the problematic examples <a href="https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2162#issuecomment-1065827206">you previously reported</a> still pose a problem or are they working now even after removing them from your personal dictionary?
