### ISSUE TITLE
Would it be possible to add a messagease layout to the keyboard? 

### ISSUE THREAD

**Issue by Kommynct** [AnySoftKeyboard/AnySoftKeyboard#2164]
Messagease makes typing on an Android keyboard SO MUCH BETTER, but I can't stand the actual messagease keyboard it's so outdated and terrible, would adding a layout like that be possible with this keyboard? 

I'd gladly do the work myself if given instructions on how to achieve this, I'm not really a programmer but I'm totally willing to try

**Comment by menny** [comment]
I don't think we can implement that, I'm guessing they have a copyright on that design and method.

Have you tried Gesture-Typing?
