### ISSUE TITLE
Build Failed - AndroidX is not Enabled

### ISSUE THREAD

**Issue by or-git** [AnySoftKeyboard/AnySoftKeyboard#2214]
1. I ensured that I have the required setup - Java 10, API 28, NDK 14b, local.properties file well-configured, etc. I have Android Studio 3.6.2 installed on my computer (which runs Ubuntu 18.04).
2. When I try to build the project by using Android Studio or by running `./gradlew build`, the compilation failed with the following error:
```
ERROR: This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.test:monitor:1.2.0, androidx.test:core:1.2.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.annotation:annotation:1.0.0
Affected Modules: app, base-test, dictionaries, fileprovider, ime-addons, ime-base, nextword, overlay, pixel, prefs, remote
ERROR: This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.test:monitor:1.2.0, androidx.annotation:annotation:1.0.0
Affected Modules: api
```

I tried to fix that by adding the following lines to `gradle.properties` file:
```
android.enableJetifier=true
android.useAndroidX=true
```
but they lead to other problems, and I'm quite sure that if I had to add those lines by myself then there is something wrong in my process.

I would like to get some help here,
Thanks.

**Comment by lubenard** [comment]
Hello, does it throw an error if you add them ?

**Comment by menny** [comment]
I don't get any of those errors. And on CI we use Ubuntu.

What happens when you run `./gradlew ime:app:assembleDebug`?

**Comment by lubenard** [comment]
Weird stuff just append. 

Android Studio was working fine, then throw me the same error. 

Just did Gradle update before it happen. I will inverstigate to see if coming back to older version can solve the problem.

I am using Arch Linux

Running ```./gradlew ime:app:assembleDebug``` just run fine and is successful

**Comment by menny** [comment]
oh, yes, you should not use any version other than `3.5.3`. That's the last version that works with the required NDK version we need.

We will move forward to a newer NDK once the correct release is out.

BTW, You should be able to use Android Studio 3.6 and even 4.0, but make sure the Android Gradle Plugin is `3.5.3`.
