### ISSUE TITLE
"remove suggestions" button is always present, even on empty textfields.

### ISSUE THREAD

**Issue by kartik918** [AnySoftKeyboard/AnySoftKeyboard#2220]
### Steps to reproduce
1. Open keyboard on any text field.
2. Observe suggestions bar.

### Expected behaviour
Suggestions bar should be hidden or have no button when nothing is typed.

### Actual behaviour
The close button is always present, also suggesting to remove suggestions where none are present.

### Screenshots:

![photo_2020-04-12_19-46-17](https://user-images.githubusercontent.com/48270786/79073609-278bc000-7d05-11ea-9eed-228cb2e4a128.jpg)

![photo_2020-04-12_19-46-48](https://user-images.githubusercontent.com/48270786/79073611-2a86b080-7d05-11ea-93ef-0164c8301310.jpg)

**Android OS version:** Android 9

**Comment by menny** [comment]
Interesting UX. Let me think about this.

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2311
