### ISSUE TITLE
Missing 'ü'-key on german layout since last update

### ISSUE THREAD

**Issue by alohadan** [AnySoftKeyboard/AnySoftKeyboard#2224]
### Steps to reproduce
1. Write a message
2. Key is disapeared

**Android OS version:**
10

**Device manufacturer and model:**
Xiaomi Fermi 3s

**List of installed add-ons (like languages, or themes):**
No add-ons.
Disapeared on Evers theme.

**Comment by menny** [comment]
@martholomew can you verify this?

**Comment by alohadan** [comment]
I'm on AnySoftKeyboard-Beta.
On the screenshot you can see the special characters on the right side without ü. So i have to longpress the u-letter…



Am 16. April 2020 17:29:41 MESZ schrieb Menny Even Danan <notifications@github.com>:
>@martholomew can you verify this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2224#issuecomment-614724441

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by menny** [comment]
I also see this in the Play Store reviews:
Rated 4 out of 5 by Mariam Chilingarova.

Where from the layout disappeared ü ????? I put this package only so as not to do long-press! If this option remains, then I will delete it so that it does not take up memory, I will use English ....

https://play.google.com/apps/publish?account=9112598064186436167#ReviewDetailsPlace:p=com.anysoftkeyboard.languagepack.german&reviewid=gp:AOqpTOEv19PpIQAnBYAH0WDIqdIOVO7HEgribdlSSnJ-s2UMjSWOjWgFNgIQmv-frx2JvBdL56YWSkTAxAxUZ-8

**Comment by alohadan** [comment]
The 'ü' was right from the letter 'p'.

Gamba Zamba has the same proplem after updating the german translation:

https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.german

Am 16. April 2020 19:37:27 MESZ schrieb Menny Even Danan <notifications@github.com>:
>I also see this in the Play Store reviews:>
>Rated 4 out of 5 by Mariam Chilingarova.>
>>
>Where from the layout disappeared ü ????? I put this package only so as
>not to do long-press! If this option remains, then I will delete it so
>that it does not take up memory, I will use English ....>
>>
>https://play.google.com/apps/publish?account=9112598064186436167#ReviewDetailsPlace:p=com.anysoftkeyboard.languagepack.german&reviewid=gp:AOqpTOEv19PpIQAnBYAH0WDIqdIOVO7HEgribdlSSnJ-s2UMjSWOjWgFNgIQmv-frx2JvBdL56YWSkTAxAxUZ-8>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2224#issuecomment-614794054

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by DerXteMensch** [comment]
Same here (Android 7) after updating the German language pack

**Comment by menny** [comment]
which layout is missing the ü? i see that in the latest release it was there: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/release-branch-addons-v4.0-r1/addons/languages/german/pack/src/main/res/xml/de_qwertz.xml#L18

**Comment by menny** [comment]
oh! I see the issue now! the ü is drawn off screen

**Comment by kegelkugel** [comment]
Same problem (missing letter ü) on Android 8, ASK v1.10-r3, layout "Deutsch Created with tudor and Claude Philipona".

**Comment by menny** [comment]
here is the fix: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2231

**Comment by menny** [comment]
once this is passed, I can release a new version of the German pack to Play-Store

**Comment by menny** [comment]
New release is rolling out
