### ISSUE TITLE
Hide Keyboard on physical key not working

### ISSUE THREAD

**Issue by mindo** [AnySoftKeyboard/AnySoftKeyboard#225]
This option is not working - with either enable or disable when a keyboard is attached the soft keyboard is never displayed.
Tested with Nexus 7 (2012) with an OTG usb cable, a Xperia Ray with a mini usb male to usb A female adapter and an Accuative VIP 5000 (it has an USB port).
If you don't have a tablet with a usb port or adapters for it you can test this by installing a VNC server (droid server for instance), it will add a "physical" keyboard.

**Comment by gotwig** [comment]
I realy need this feature. I use a gamepad, which is always recognized as a keyboard and its so anoying :/ can you help me how to implement this? I can maybe fix it with some help

**Comment by menny** [comment]
The next release has a few fixes related to physical keyboard.
I'll release a beta version in the upcoming days. You will want to signup to the beta: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard
