### ISSUE TITLE
[feature request] ordinal symbols in PT-PT

### ISSUE THREAD

**Issue by 1000283** [AnySoftKeyboard/AnySoftKeyboard#2252]
Physical pt-pt keyboards and most virtual keyboards have male and female [ordinal symbols](https://en.wikipedia.org/wiki/Ordinal_indicator).
They have a dedicated key on physical keyboards or are usually on the alternative characters for A and O letters.
It would be neat if these were added to pt-pt as they are quite common.

**Comment by maverick74** [comment]
Indeed they are very used!!!
