### ISSUE TITLE
Feature Request: Long-press on backspace should delete word after word instead of individual characters

### ISSUE THREAD

**Issue by jwiesel** [AnySoftKeyboard/AnySoftKeyboard#2255]
Hi there, first of all great open source keyboard!

I just moved away from SwiftKey keyboard and really miss one "simple" feature.
If I want to remove a few words from my sentence, I can simply hold the backspace key and see word by word disappear (slowly). In AnySoftKeyboard character by character disappears (quickly)

### Steps to reproduce
1. Type a few words
2. Try to exactly remove the last two words by holding backspace
3. Continue typing without the need to press backspace again, entering last characters of a word again and entering a space/blank again.

### Expected behaviour
On longpress of key backspace, word by word should be removed instead of character by character. To avoid deleting too much the pause in between should be a bit longer than with the character-by-character deletion in AnySoftKeyboard. 

### Actual behaviour
Character by character is deleted. You might delete too little or too much and need to fix the text accordingly.

**Android OS version:**
* Android 9

**Device manufacturer and model:**
* Huawei

**List of installed add-ons (like languages, or themes):**
* German Language pack

**Comment by PrSunflower** [comment]
Hi! I am a user of AnySoftKeyboard and as I understand your feature request I have to say it would annoy me. I like it when a long press on backspace deletes the characters one by one.

If the developers choose to implement this feature I would appreciate letting the users choose between deleting characters one-by-one or word-by-word.

For the moment what I can suggest is activating **Back-word support: "Shift + Backspace will delete the last word"**. You can find it in ASK Settings > Language > Tweaks and more > Tweaks > Back-word support.

**Comment by jgentil** [comment]
This would be amazing!!   Definitely the only feature I miss from Swiftkey.

**Comment by jgentil** [comment]
> For the moment what I can suggest is activating **Back-word support: "Shift + Backspace will delete the last word"**. You can find it in ASK Settings > Language > Tweaks and more > Tweaks > Back-word support.

I don't see that option.  :(

**Comment by PrSunflower** [comment]
@jgentil  
> I don't see that option. :(

1. ASK Settings > Language

![Screenshot_20200531-015755](https://user-images.githubusercontent.com/59576952/83341455-00547680-a2e4-11ea-864d-ba555d70fbf0.png)

2. Tweaks and more

![Screenshot_20200531-015806](https://user-images.githubusercontent.com/59576952/83341460-18c49100-a2e4-11ea-9acf-c6adb150f277.png)

3. Tweaks

![Screenshot_20200531-015812](https://user-images.githubusercontent.com/59576952/83341464-211ccc00-a2e4-11ea-8ff3-e677cc3e361f.png)

4. Enable Back-word support

![Screenshot_20200531-015828](https://user-images.githubusercontent.com/59576952/83341467-28dc7080-a2e4-11ea-81f3-79eaeef33f47.png)

**Comment by PrSunflower** [comment]
@jwiesel 

Just want to know 😄, did the Shifted Backspace solve your problem?

**Comment by Masqueey** [comment]
@PrSunflower I love how clear you made it to find the correct setting. Definitely lol'd there.

I was looking through some issue requests as I don't get this feature to work... I use swipe (s̶o̶ ̶m̶a̶y̶b̶e̶ ̶t̶h̶a̶t̶ ̶i̶s̶ ̶c̶a̶u̶s̶i̶n̶g̶ ̶i̶t̶ _just checked, it's not_) but I can't get the shift+backspace to work.

**Update** (while writing this reply): I just figured out how to get it to work; you need to hold both at the same time. I kept using shift and then backspace, which just removed the last letter. I probably need to make a feature request rather than a bug report.

**Comment by PrSunflower** [comment]
@Masqueey  Haha! I am not really into coding so if I can help people by only posting screenshots I'm happy!

Oh wow. I knew where to find the setting but I've never used the shifted backspace myself. Didn't know you had to hold both.

The new feature request you want to write is about not having to hold these keys?

**Comment by PrSunflower** [comment]
Well this issue is getting old and inactive...

**Comment by jwiesel** [comment]
Hi all, thanks for your help, the screenshots and the clarification using both buttons (shift + backspace) at the same time. I got used to ASK in the meantime and will try to use the existing feature to delete entire words. I'll close the issue accordingly.

**Comment by PrSunflower** [comment]
Glad to see that you're still here @jwiesel  😄

Great! May everyone have a nice time typing with ASK 😉
