### ISSUE TITLE
Number row not hide if filed AnySoftKeyboard be in number mode

### ISSUE THREAD

**Issue by Monirzadeh** [AnySoftKeyboard/AnySoftKeyboard#2265]
### Steps to reproduce
1. active number row for AnySoftKeyboard
2. go to a field that just get number (AnySoftKeyboard show numpad)

### Expected behaviour
hide number row if keyboard open in numpad mode
### Actual behaviour
you see an unnecessary number row on top of numpad

**Android OS version: 10**

**Device manufacturer and model: poco**

**List of installed add-ons (like languages, or themes): just Persian layout**

**Screenshot**
![f3e727b5-f875-4e61-a572-3947a430e66d](https://user-images.githubusercontent.com/25131576/81501171-132ee900-92ec-11ea-9e31-0623eef8b5cf.png)

**Comment by O-DoC** [comment]
Hello,

I have the same behavior for input type field  = `phone`

But it's hide, _and it's ok like that_, for the input type = `number` .
