### ISSUE TITLE
Gesture typing doesnt work if battery saver is on

### ISSUE THREAD

**Issue by talk2g** [AnySoftKeyboard/AnySoftKeyboard#2270]
Even when the app isnt restricted by battery usage

**Comment by talk2g** [comment]
Just saw the options in setting.

**Comment by bertolinocastro** [comment]
It took a while for me to find these settings... I think they make not that much sense being inside "Effects", inside "UI". Simply because they're general power-saving settings, which take care of disabling features that do not relate entirely with UI/Effects
