### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by jbrepogmailcom** [AnySoftKeyboard/AnySoftKeyboard#2274]
Hello. I understand that any Android keyboard passes keystrokes to the operating system over some API, where it is then picked up by target application over another API. Does that mean that on level of OS any software keyboard can be eavesdropped? Thank you for comment. Jan

**Comment by menny** [comment]
If i understand your concern correctly, then yes. If your OS is compromised (that is, some code can hook/intercept OS API calls) then it is possible to record all your key presses.
