### ISSUE TITLE
[Bug][android 10] show back button even when gesture navigation is on

### ISSUE THREAD

**Issue by ghasemiHussein** [AnySoftKeyboard/AnySoftKeyboard#2278]
After enabeling gesture navigation in android 10, there should be no button in bottom of screen. but when using ASK it shows a button for hidding keyboard which is unnecessary.
![Screenshot_20200519-125811](https://user-images.githubusercontent.com/64186121/82303709-94633b80-99d0-11ea-823d-2683eb3aa3cf.png)

**Comment by menny** [comment]
I realize now that I can not change that: that button is controlled by the OS
