### ISSUE TITLE
[Bug] Autocorrect cutting off las letter of th type words

### ISSUE THREAD

**Issue by najodleglejszy** [AnySoftKeyboard/AnySoftKeyboard#2279]
Device: Sony Xperia XZ2 Compact running Android 10
Languages: English, Polish (merged)
Version: 1.10.1454

After updating the keyboard today, ASK's autocorrect has been cutting off some letters when typing; sometimes it's just one letter, other times it's multiple. 
Examples:
"called" being corrected to "calle" (which isn't a valid word in any of my dictionaries
"we" to "w"
"some" to "so"
"word" to "WOR"
"just" to "jus"
"set" to "se"

I have my Auto-select suggestion aggressiveness set ("se") to "Extreme" and it's been working fine for forever, but ("bu") something seems ("seem") to have broken now ("no").

**Comment by menny** [comment]
Thanks for reporting. What causes that auto correct? Is it that you type part of the word and press space? Or is it that you had a typo that was auto corrected upon space?
Can you check what is your "Restart suggestions" setting?

**Comment by najodleglejszy** [comment]
it actually happens when I type out the entire word with no typos and then press space. my "Suggestions restart" is disabled (the box is unchecked).

**Comment by menny** [comment]
will release later tonight.

**Comment by najodleglejszy** [comment]
yup, today's update did fix it for me. thanks a lot, that was really painful to deal with!

**Comment by menny** [comment]
Thanks for reporting. It's much easier to fix a beta than a production release
