### ISSUE TITLE
(Bug - BETA) Keyboard hangs (and crashes) after a few minutes of use

### ISSUE THREAD

**Issue by Pat3375** [AnySoftKeyboard/AnySoftKeyboard#2280]
### Steps to reproduce
1. Tras la última actualización se ha bloqueado el teclado y el teléfono haciendo necesario reiniciar el teléfono.
2. Después de reiniciar el teléfono el teclado funciona durante unos segundos hasta que se vuelve a bloquear.
3. 
### Expected behaviour
Tell us what should happen

### Actual behaviour
He tenido que desactivar el teclado y sustituirlo por otro.

**Android OS version:**
8.1.0

**Device manufacturer and model:**
Umidigi OnePro

**List of installed add-ons (like languages, or themes):**
KeyBoard Theme Dusk Black
Spanish for AnySoftKeyboard

**Comment by menny** [comment]
thanks for reporting. I'm trying to locate the cause.
