### ISSUE TITLE
Add option to disable auto dark mode

### ISSUE THREAD

**Issue by Athoss9** [AnySoftKeyboard/AnySoftKeyboard#2284]
If the battery percantage is low or I switch on energy saving mode the keyboard automatically swithes to dark theme. I suppose it is for energy saving purposes but since I use an IPS screen, not amoled, there's no difference in energy usage, it just makes the buttons much less visible.

**Comment by RDRXS** [comment]
![2](https://user-images.githubusercontent.com/54729767/82637933-5dba3a80-9bf5-11ea-848d-5b353f7d5046.png)

Even with this unchecked? 😕

**Comment by Athoss9** [comment]
Thank you for the suggestion, it works fine now. The keyboard has so many options that sometimes it is difficult to find the correct one :)
