### ISSUE TITLE
[Feature Request] Ability to resize keyboard

### ISSUE THREAD

**Issue by Flam3z** [AnySoftKeyboard/AnySoftKeyboard#2292]
The keyboard seems a bit too big fir my screen and a feature to adjust that would be very useful.

**Comment by Invisigon** [comment]
You can already adjust the keyboard size. Follow the screenshots.
![Screenshot_20200523-145741](https://user-images.githubusercontent.com/57682953/82741353-f63fe000-9d05-11ea-8cd2-c23e4f753ad5.png)
 

![Screenshot_20200523-145813](https://user-images.githubusercontent.com/57682953/82741356-fa6bfd80-9d05-11ea-8427-1f144a529489.png)

![Screenshot_20200523-145828](https://user-images.githubusercontent.com/57682953/82741374-0fe12780-9d06-11ea-81e3-5d61a613b1eb.png)

**Comment by Flam3z** [comment]
thank you so much.

**Comment by aubrielee** [comment]
Very neat. How about width factor? For example, moving the keyboard to the left side of the screen, for easier left-handed gesture typing.

**Comment by Invisigon** [comment]
@menny

**Comment by menny** [comment]
It is possible to condense the keyboard to the left or right (or split it in half). Open the utility popup to do that (swipe up from the space bar)
