### ISSUE TITLE
Enhancement: allow changing size of key 'subtext' ( alternative characters)

### ISSUE THREAD

**Issue by Jackalaq** [AnySoftKeyboard/AnySoftKeyboard#2296]
### Steps to reproduce
1. Get into your 40's
2. Find that you can't read ASK keys' alternative characters without reading spectacles manufactured by NASA
3. Find no theme that solves this problem

### Expected behaviour
It would be great to able to see the keys. The layouts are hard to learn/ guess.

### Actual behaviour
Spend ages guessing where punctuation might be lurking. Some folk will give up and leave.

**Android OS version:**
7.1.2 /e/OS
**Device manufacturer and model:**
OnePlus 3t
**List of installed add-ons (like languages, or themes):**
None

**Comment by menny** [comment]
Something like this? https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2317
