### ISSUE TITLE
Double press space bar

### ISSUE THREAD

**Issue by Eichhof** [AnySoftKeyboard/AnySoftKeyboard#2299]
Hello everybody

I like the feature that double press the space bar inserts a dot and a white space. Where is this feature implemented in AnySoftKeyboard? I would like to use this specific feature in my own keyboard.

**Comment by YohananDiamond** [comment]
It seems like this feature is already present. I found it in Language Tab -> Tweaks and more -> Double space to period.

**Comment by Eichhof** [comment]
Yes, this feature is present in AnySoftKeyboard. But I would like to use this feature in my own keyboard. That's why I'm interested to know how it is implemented in AnySoftKeyboard so that I can reuse the implementation.

**Comment by YohananDiamond** [comment]
Oh, sorry for the misunderstanding :P

**Comment by menny** [comment]
@Eichhof see https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java#L777
