### ISSUE TITLE
Feature Suggestion: Clipboard Icon

### ISSUE THREAD

**Issue by Flam3z** [AnySoftKeyboard/AnySoftKeyboard#2300]
I recently switched from the default galaxy keyboard and been having a greater experience using this new keyboard of its really only missing a keyboard icon for use, the only way to open the clip board is a long-press on the text field.

**Comment by menny** [comment]
In the next release, the keyboard will suggest the last entry in the clipboard when you enter a textbox.

Right now, you can swipe up from the space-bar to open the utility-box which has a few clipboard related actions.
