### ISSUE TITLE
auto-scroll (setSelected) clipboard strip-action

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2313]

**Comment by lubenard** [comment]
Hey !

Little return:

setSelected does not seems to work here. I am investigating why the text is not scrolling at all.

Even [android:ellipsize="end"](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/ime/app/src/main/res/layout/clipboard_suggestion_action.xml#L17) in ``` clipboard_suggestion_action.xml``` does not seem to have en effect. 

In fact, the line above should add 3 dots to the string.

I'm looking on the side of ```CandidateView``` in ```main_keyboard_layout.xml```

If you have any Idea, I'd be happy to discuss about it.

**Comment by menny** [comment]
yeah, I couldn't figure that out either.
I tried setting `ems`, or `focusable`, etc 
nothing worked.

It could be an incorrect measuring flow in `KeyboardViewContainerView`.

**Comment by lubenard** [comment]
Just found out. 

Apparently, setInputType for clipoboard is breaking ellipsize.

See my commit: [here](https://github.com/lubenard/AnySoftKeyboard/commit/8a6e2f457d5c30c837dd3e26fcec62e1cf5c7ee2)


What do you think about it. I will see if there is a way to bypass it, and make it work anyway

**Comment by menny** [comment]
Amazing! Good catch.
I would still like to hide passwords. Maybe set the text in the TextView to dots?

**Comment by lubenard** [comment]
Yes, good idea ! I'll do that, and keep you update !

**Comment by lubenard** [comment]
What do you think of [this](https://github.com/lubenard/AnySoftKeyboard/commit/64bf5e7f9dab5c055d8fac32a880d0d4e919a4d1) commit ? Feel free to test it and return modifications you want before i make a PR

**Comment by menny** [comment]
yes, this is what I had in mind. I left a couple of comments on the commit.

**Comment by lubenard** [comment]
Fixed everything [here](https://github.com/lubenard/AnySoftKeyboard/commit/f7557dd79ed5cbf74927b8e4c320b8bf28c0cbfc) !

**Comment by menny** [comment]
great! Open a PR?
