### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by Stenafo** [AnySoftKeyboard/AnySoftKeyboard#2315]
It would be nice to have a keyboard with a more modern and especially smaller look, in fact there is no way to choose the size of the keyboard, in fact it now occupies almost half of my screen, while other keyboards occupy a third.
At the bottom there is an empty band that does nothing but make the keyboard even longer.
Another problem is the size of the space bar, too small, you could join the (,) and (.) Keys to save space, and maybe even incorporate the (?) Key.

**Android OS version:7

**Device manufacturer and model: Samsung galaxy s6

**List of installed add-ons (like languages, or themes): Italian language

**Comment by lubenard** [comment]
Hello, you can change the size of the keyboard under

Interface -> Choose and configure keyboard theme -> the gear in the upper right -> Keys height factor in portrait mode. 

The default value is 1.0, but if you want it smaller, you can set it to 0.8 or 0.9.

For the space bar problem, you can the bottom row layout under 

Interface -> Tweaks -> Bottom Row.

**Comment by menny** [comment]
@Stenafo, did @lubenard suggestion work for you
