### ISSUE TITLE
Missing Swiss French layout

### ISSUE THREAD

**Issue by jlemonde** [AnySoftKeyboard/AnySoftKeyboard#2345]
I am missing a Swiss French keyboard. That is a QWERTZ keyboard with ÈÉÀ to the right, basically the exact same as the existing Canadian French keyboard but with Y and Z swapped.

Since it is only about swapping two letters, could this please be added to the French language pack? The spellcheck dictionary for Swiss French is basically the same as for Standard French (minor exceptions that could be learnt from usage).

PS: the Swiss French layout is not included in the Swiss language pack (which is a pity) but IMHO it does not really matter whether the Swiss French keyboard is added to the Swiss Pack or to the French Pack.

Would someone be so kind to have a look into it?

**Comment by Porrumentzio** [comment]
I'm a bit busy working on other languages, but it would be really easy to make what you say. Do you know anything about programing?
I could help

**Comment by jlemonde** [comment]
Hi! I know a bit about programming,and I had a look into this project but I did not understand the structure of the project.

The Swiss French layout is currently being added to the Swiss language pack by its maintainer, so this issue may be closed.
