### ISSUE TITLE
parser.py character literal and unmappable character problem

### ISSUE THREAD

**Issue by subwayeetfresh** [AnySoftKeyboard/AnySoftKeyboard#2347]
![Screenshot (60)](https://user-images.githubusercontent.com/61372350/85259859-65d0f880-b487-11ea-8d84-09df3f6251f8.png)

C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:171: error: unmappable character (0x9D) for encoding windows-1252
            case '�?':
                    ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:169: error: unclosed character literal
            case '’':
                 ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:169: error: illegal character: '\u2122'
            case '’':
                    ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:169: error: not a statement
            case '’':
                   ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:169: error: unclosed character literal
            case '’':
                     ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:171: error: unclosed character literal
            case '�?':
                 ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:171: error: illegal character: '\ufffd'
            case '�?':
                    ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:171: error: not a statement
            case '�?':
                   ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:171: error: unclosed character literal
            case '�?':
                     ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:172: error: unclosed character literal
            case '“':
                 ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:172: error: unclosed character literal
            case '“':
                     ^
C:\Users\athar\AndroidStudioProjects\AnySoftKeyboard\buildSrc\src\main\java\Parser.java:172: error: not a statement
            case '“':
                   ^

**Comment by subwayeetfresh** [comment]
if you guys are having the same problem, just replace this:
 
`    private char fixup(int intChar) {
        switch (intChar) {
            case '\u2019':
                return '\'';
            case '\u201d':
            case '\u201c':
                return '\"';
            default:
                return (char) intChar;
        }
    }
`

**Comment by subwayeetfresh** [comment]
private char fixup(int intChar) {
        switch (intChar) {
            case '\u2019':
                return '\'';
            case '\u201d':
            case '\u201c':
                return '\"';
            default:
                return (char) intChar;
        }
    }

**Comment by menny** [comment]
Do you want to create a PR for this? It will be helpful.
