### ISSUE TITLE
[Feature request] Gesture typing: backspace should delete entire word

### ISSUE THREAD

**Issue by Christian-Git01** [AnySoftKeyboard/AnySoftKeyboard#2353]
When gesture typing is used and swyping results in the wrong word, it is more helpful to delete the entire word at once, but only the last character. Default AOSP keyboard has this feature.

**Comment by PrSunflower** [comment]
Hi! I agree with you but I found an older duplicate issue here : #1755

I think it's the same thing so it's better to leave a like on the older issue and close that one.

**Comment by Christian-Git01** [comment]
@PrSunflower Thanks. Isseu closed, because it is a duplicate of: #1775

**Comment by Christian-Git01** [comment]
@PrSunflower Thanks. Isseu closed, because it is a duplicate of: #1775
