### ISSUE TITLE
Unable to use ./gradlew on Android Studio (Linux)

### ISSUE THREAD

**Issue by Porrumentzio** [AnySoftKeyboard/AnySoftKeyboard#2358]
I'm making a language package and when trying to use:
> ./gradlew :addons:languages:esperanto:pack:makeDictionary

I get this error:

> 
> [porru@matejaro AnySoftKeyboard]$ ./gradlew :addons:languages:esperanto:pack:makeDictionary
> 
> > Task :buildSrc:compileJava FAILED
> /home/porru/Sorkuntza/GNU/AnySoftKeyboard/ASK-eo/AnySoftKeyboard/buildSrc/src/main/java/github/RestRequestPerformer.java:37: error: no suitable constructor found for Scanner(InputStream,Charset)
>                         new Scanner(httpResponse.getEntity().getContent(), StandardCharsets.UTF_8)
>                         ^
>     constructor Scanner.Scanner(Readable,Pattern) is not applicable
>       (argument mismatch; InputStream cannot be converted to Readable)
>     constructor Scanner.Scanner(InputStream,String) is not applicable
>       (argument mismatch; Charset cannot be converted to String)
>     constructor Scanner.Scanner(File,String) is not applicable
>       (argument mismatch; InputStream cannot be converted to File)
>     constructor Scanner.Scanner(File,CharsetDecoder) is not applicable
>       (argument mismatch; InputStream cannot be converted to File)
>     constructor Scanner.Scanner(Path,String) is not applicable
>       (argument mismatch; InputStream cannot be converted to Path)
>     constructor Scanner.Scanner(Path,Charset) is not applicable
>       (argument mismatch; InputStream cannot be converted to Path)
>     constructor Scanner.Scanner(ReadableByteChannel,String) is not applicable
>       (argument mismatch; InputStream cannot be converted to ReadableByteChannel)
> Note: /home/porru/Sorkuntza/GNU/AnySoftKeyboard/ASK-eo/AnySoftKeyboard/buildSrc/src/main/java/BuildLogger.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':buildSrc:compileJava'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 663ms
> 
> 
> 

I followed the instructions in https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1909#issuecomment-578385234 and installed `OpenJDK-10.0.2` on `/opt` and pointed to it on` Project Structure > SDK Location > JDK location`

But the same error happens.

Also I get an error when AndStudio tries to build the project:
![irudia](https://user-images.githubusercontent.com/61913683/86258161-cb756100-bbba-11ea-8a56-f19fe7bd6c42.png)

Some help? I'm not programmer and I don't understand what could the problem be

**Comment by menny** [comment]
Ensure you have Java11 installed and set as in the PATH and as the default JVM.

I use [jenv](https://www.jenv.be/) to manage my Java environment. This repo has a `.java-version` that will tell `jenv` to switch to the right version.

Also, ensure that the JVM used by Android-Studio is Java11.

**Comment by menny** [comment]
See https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/CONTRIBUTING.md for a bit more details.
