### ISSUE TITLE
Portrait Split mode settings dialog typo

### ISSUE THREAD

**Issue by JagdishKumar1970** [AnySoftKeyboard/AnySoftKeyboard#2376]
### Steps to reproduce
1.Open Launcher Icon.

2.Enter 'UI' Section from bottom bar.

3.Enter 'Tweaks and more', then 'Tweaks'.

4.Tap on "Portrait Split/Merge initial State".

5.Heading of the dialog box still says Landscape.

### Expected behaviour: 
Refer to: '5.'

**Android OS version:**
7.1.2
(LineageOS 14.1)
**Device manufacturer and model:**
z2_plus(Specs: 4,64,SD820): 
https://en.m.wikipedia.org/wiki/Lenovo_Z2_Plus
**List of installed add-ons (like languages, or themes):**
none.

**Comment by menny** [comment]
thanks for reporting
