### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by rosesandtea** [AnySoftKeyboard/AnySoftKeyboard#2383]
The spacebar is way too thin. This slows down typing considerably.

**Comment by lubenard** [comment]
Hello, if you are speaking about the length of the space bar, have you tried to change your bottom layout ?

You can do it in the app under ````Interface -> Tweaks and more -> Common bottom generic row````

If you are speaking about the height, have you tried to increase the size of your keyboard ?

You can change this under ````Interface -> Choose and configure keyboard theme -> the gear in the upper right -> Keys height factor in portrait mode````

**Comment by Jonta** [comment]
Closing as uninformative

Author has no GitHub-activity for at least 365 days
