### ISSUE TITLE
Cursor lagging behind when typing

### ISSUE THREAD

**Issue by crdpa** [AnySoftKeyboard/AnySoftKeyboard#2390]
### Steps to reproduce
1. Type long sentences 

### Expected behaviour
The cursor should stay in the end of the sentence so i can continue typing normally

### Actual behaviour
Right now i was typing "Alguns movimentos bruscos". When typing it, the cursor should stay at the end.

What happens is the cursor falls behind one or two letters. It suddenly stays here:

"Alguns movimentos bru|s"

So when i continue typing the sentence is:

"Alguns movimentos brucoss"

I cleaned cache and data and the problem went away for two or three days, but it's back.

**Android OS version:**
Android 10 (MIUI 11)

**Device manufacturer and model:**
Xiaomi Mi 9 Lite

**List of installed add-ons (like languages, or themes):**
PT-BR language

**Comment by PrSunflower** [comment]
Hi, I am having the same issue but we are not the only ones. Issue #1875 already discusses of this.

@crdpa  I think it would be better if you thumbs up #1875 and close this issue.

**Comment by crdpa** [comment]
@PrSunflower thanks! Didn't saw that one. I'm closing this one.

Closed because it's a duplicate of [#1875](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1875)
