### ISSUE TITLE
(feature request) floating keyboard and clipboard which can view all copied text 

### ISSUE THREAD

**Issue by shelra** [AnySoftKeyboard/AnySoftKeyboard#2402]
Floating mode makes a lot of sense when using device in landscape mode, and clipboard which can remember multiple text is very useful

**Comment by Jonta** [comment]
"clipboard which can view all copied text" seems to be implemented now:
1. Swipe up from spacebar (might take a few tries)
2. Press and hold clipboard-icon

**Comment by Jonta** [comment]
Closing as fixed
