### ISSUE TITLE
No uppercase when swiping

### ISSUE THREAD

**Issue by Grahack** [AnySoftKeyboard/AnySoftKeyboard#2424]
### Steps to reproduce
1. Click Shift
2. Type with the gesture feature on (swipe)

### Expected behaviour
The word "typed" should have its first letter uppercase.

### Actual behaviour
The first letter is lowercase.

**Android OS version: 9**

**Device manufacturer and model: Huawei P Smart**

**List of installed add-ons (like languages, or themes): FR lang pack**

**Comment by Jonta** [comment]
Occurs in English too

Android 10

**Comment by Jonta** [comment]
Related:
- https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1769
- https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2288
- https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1953
- https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1322
- https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/706

**Comment by menny** [comment]
Haha, that's a lot of "related" 😂

**Comment by Jonta** [comment]
Closed as duplicate
