### ISSUE TITLE
Keyboard theming issue when Quick-text editing top row is enabled

### ISSUE THREAD

**Issue by nihal697** [AnySoftKeyboard/AnySoftKeyboard#2439]
### Steps to reproduce
1. Set theme to yochees light 

### Expected behaviour
Top row should be visible

### Actual behaviour
Its not visible clearly because the text colour also is white.

**Android OS version:**
Android Q

**Device manufacturer and model:**
Xiaomi redmi note 7
**List of installed add-ons (like languages, or themes):**
None
![Screenshot_20200822-150722_KISS_launcher](https://user-images.githubusercontent.com/47318989/90953569-0349a800-e48a-11ea-8b56-cd545ff86306.png)

Note : Almost similar issue in 
Plain Light theme.

**Comment by Porrumentzio** [comment]
Happens the same with second "numbers and sings" view:

![IMG_20201011_230520](https://user-images.githubusercontent.com/61913683/95690249-8e3b5900-0c16-11eb-98ba-751af6fca8bc.jpg)

The moving sings are white and therefore they're almost invisible

**Comment by Porrumentzio** [comment]
Also happens something similar with number-screen:
![IMG_20201016_232725](https://user-images.githubusercontent.com/61913683/96310234-3ed69d80-1007-11eb-9497-078f4bc27277.jpg)

**Comment by LunarEclipse363** [comment]
Seems to be missing light-theme versions of icons for the Yochees theme and it just using the dark theme icons.

https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/256d939fc3c7d896ef7567b632b98914418dfd3d/ime/app/src/main/res/values/styles_yochees_keyboard_theme.xml
