### ISSUE TITLE
[Feature request] allow removing the little globe icon for multiple language

### ISSUE THREAD

**Issue by dreth** [AnySoftKeyboard/AnySoftKeyboard#2443]
Please! allow removing the little globe icon for multiple language keyboards, it's unnecessary for me (for example) since i use swipe on spacebar to change language.

if this is possible please show me how!

**Comment by nicoursi** [comment]
There are plenty of bottom rows available. Not all of them have the icon you are talking about. Just pick a different one!

**Comment by O-DoC** [comment]
There's an option in  _(not sure about the correct label)_ `interface /  advanced option / show language button` with an `on-off` checkbox.
This do the work for me !

**Comment by menny** [comment]
what @O-DoC said :)
I use that too.
