### ISSUE TITLE
Does AnySoftKeyboard Support new autofill method ?

### ISSUE THREAD

**Issue by Moxville** [AnySoftKeyboard/AnySoftKeyboard#2467]
Hi,

Does AnySoftKeyboard Support this new feature ?

**Android 11's new autofill method that integrates with keyboard**
https://www.androidpolice.com/2020/08/10/android-11-will-make-password-autofill-much-better-thanks-to-keyboard-integration/
https://developer.android.com/preview/features/ime-autofill#configure-provider

Thanks

**Comment by menny** [comment]
this is great! we will support this.

**Comment by Taknok** [comment]
Documentation: https://developer.android.com/guide/topics/text/ime-autofill
(Link in 1st post is broken since it is not a preview anymore)

**Comment by menny** [comment]
This was implemented. Version 1.11-r1 is rolling out with the implementation

**Comment by Taknok** [comment]
Ok, thank you !
It is implemented in #2920 for the reference.
