### ISSUE TITLE
App title in F-droid android app

### ISSUE THREAD

**Issue by GertVerhoek** [AnySoftKeyboard/AnySoftKeyboard#2469]
### Steps to reproduce
1. Open F-Droid android **app**
2. Search for AnySoftKeyboard

### Expected behaviour
App should just be called AnySoftKeyboard

### Actual behaviour
App is called Indonesian for AnySoftKeyboard
Weirdly it's named correctly on the F-Droid website, only the android app is wrong (and yes repositories were updated first)
EDIT:
Apparently this changes randomly, it's (at the time of writing) named as Afrikaans for AnySoftKeyboard.

![image](https://user-images.githubusercontent.com/52334480/92746914-f7178300-f383-11ea-9747-ab0c813160e6.png)
![image](https://user-images.githubusercontent.com/52334480/92746940-fbdc3700-f383-11ea-952f-103b057eb033.png)

*Probably not useful stuff:*
**Android OS version:**
9

**Device manufacturer and model:**
Nokia 8 (TA-1004)

**List of installed add-ons (like languages, or themes):**
Dutch Language pack

**Comment by grravity** [comment]
Yup reporded this many eons ago and still hasn't been fixed :/

**Comment by dragonmaus** [comment]
I'm seeing it as "Afrikaans for AnySoftKeyboard" in FoxyDroid.

**Comment by grravity** [comment]
@dragonmaus it constantly changes

**Comment by feluxe** [comment]
I'm currently trying to install it via f-droid. Can anyone tell me how to find the right one?

**Comment by GertVerhoek** [comment]
> I'm currently trying to install it via f-droid. Can anyone tell me how to find the right one?

Get the one with "We live in a world full of languages. Why not use a multi-lingual keyboard?" as the first line in the description, it's likely the top one.
The language packs have "Language pack for AnySoftKeyboard" as the first line.

**Comment by feluxe** [comment]
@GertVerhoek The one with "We live in a world full of languages. Why not use a multi-lingual keyboard?" doesn't appear when I search the F-Droid app. It only appears when I use the F-Droid Browser UI, currently [listed](https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/) as afrikaans.

**Comment by GertVerhoek** [comment]
So search for "afrikaans for anysoftkeyboard" on the app, or just open the link you just used yourself but on your phone.
https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/

**Comment by feluxe** [comment]
> So search for "afrikaans for anysoftkeyboard" on the app,

The right one doesn't appear within the smartphone app, even if I search for *afrikaans*.

>  or just open the link you just used yourself but on your phone.

I have that link opened within the browser on my phone, but I cannot find a way to use that website to install it via F-Droid.

**Comment by dragonmaus** [comment]
If you have the "Open Link With..." app installed (also on Fdroid), you can "share" that page from your browser to "Open With..." and select the Fdroid app.

**Comment by feluxe** [comment]
@GertVerhoek  @dragonmaus Ah, thanks! I didn't know I can install the apk from the website via f-droid. I have it installed now. Thanks for your help!

**Comment by markwmuller** [comment]
FWIW, this is also broken on the f-droid website's search function -- https://search.f-droid.org/?q=anysoft%20keyboard&page=2&lang=en

Once I find the right link to click, it does have the correct title though https://f-droid.org/en/packages/com.menny.android.anysoftkeyboard/

**Comment by giorgiga** [comment]
Just setup a new device and the label is now "ICS Theme for AnySoftKeyboard"

**Comment by ourichermath** [comment]
Currently, in my F-Droid app, it's showing up at the top of the list as "Thai for AnySoftKeyboard We live in a world full of languages.  Why not use a multi-lingual keyboard?

If I install with that and it hops to a different language pack, will my installation end up turning into an actual Thai language pack?  Will it continue to update itself via F-Droid?

**Comment by deutrino** [comment]
This has been broken for a very long time.

See also: https://gitlab.com/fdroid/fdroiddata/-/issues/2014

**Comment by Jonta** [comment]
Closing as duplicate
