### ISSUE TITLE
[Feature Request] Export User-Directory to import on new phone

### ISSUE THREAD

**Issue by lcewcb8l6xe1jxr0zxdj** [AnySoftKeyboard/AnySoftKeyboard#2479]
I found the option to import a user-dictionary via the wordeditor, where a xml is expected to reside on my phone. 

I cannot find how to export a user-dictionary on my old phone. 
"Use private User-Dictionary storage" is selected on my old phone. 

Is it possible to have the custom wordlist exported when using "private storage"?

**Comment by maximilianovermeyer** [comment]
You can export your dictionary via the backup function. You get there by pressing the three dots in the upper right corner. The option is called 'user words'. Is this what you are looking for?

**Comment by menny** [comment]
@lcewcb8l6xe1jxr0zxdj did that help you?
