### ISSUE TITLE
Add dvorak layout for Danish

### ISSUE THREAD

**Issue by snkfxx** [AnySoftKeyboard/AnySoftKeyboard#2480]
As a Danish dvorak user I would greatly appreciate having that keyboard layout available in the Danish language pack. Unfortunately, I have no experience in android dev and am unable to contribute it myself.

But I have made the keyboard xml file containing the Danish dvorak layout (using the Danish qwerty and the English dvorak layouts as templates). I am hoping that someone else could complete the job with this file already done (I hope it's not too much work).

Thanks! Please let me know if there is something missing in the file.

https://pastebin.com/WQEv3kq7

(the unusual placement of the backspace button is to make the keys line up vertically in the proper way)

**Comment by snkfxx** [comment]
Thanks, ArenaL5! Looking forward to see it in a release.

**Comment by menny** [comment]
@ArenaL5 are you going to open a PR for this?

**Comment by ArenaL5** [comment]
[Now I am.](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2597) (Sorry, I found several easy targets and tried to bundle them all in a single PR. As last time.)
