### ISSUE TITLE
Catalan keyboards are not comfortable

### ISSUE THREAD

**Issue by idrilirdi** [AnySoftKeyboard/AnySoftKeyboard#2493]
The catalan language uses apostrophes quite extensively, so why are both catalan keyboards missing this key? The popup keys are also useless greek letters, or accented versions of letters that are not present in catalan, instead of punctuation marks and symbols that are used in everyday typing. As it is now, the keyboard is too unflexible in things like these for me to use comfortably everyday. I suggest uncoupling keyboards to languages and allow us to use whatever combinations work best for us instead of tying them together

**Comment by ArenaL5** [comment]
This can already be done, at least using the debug builds. (Hold the hyphen key to the right of the P key on the default keyboard.) Maybe that wasn't the case when you wrote your report.

Uncoupling keyboards and languages was already possible, but it's difficult to find. Press and hold the Enter key on your desired layout and select “Replace default dictionary”. Then uncheck everything but the Catalan dictionary.

You can also select a lower row (the key row that contains the spacebar) that has the apostrophe key.
