### ISSUE TITLE
Twemojis as ASK emojis

### ISSUE THREAD

**Issue by Porrumentzio** [AnySoftKeyboard/AnySoftKeyboard#2498]
I would like to have Twemoji as default ASK emojis, because they are more comprensible.

They're open source and their repo is this: https://github.com/twitter/twemoji

**Comment by realpixelcode** [comment]
Yes, this would be so great! I don't really like the current emoji set 😕

**Comment by kurdikeyboard** [comment]
No, I prefer the original Android emoji's they much better than twemoji

**Comment by realpixelcode** [comment]
🙁💔

**Comment by Jonta** [comment]
Sounds like something to make a setting

**Comment by menny** [comment]
I don't think I will be able to support this:
* the library requires network access to retrieve the emoji images
* the library only provides local encoding and rendering, it does not send to the other party that rendering. In other words, it is a cosmetic feature.
