### ISSUE TITLE
Allow removing items from the clipboard manager

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2512]
Open the clipboard manager, there should be a "Trash Can" icon next to each item so it can be removed from the list.

**Comment by menny** [comment]
Use case: for example, one of the items is a password.

**Comment by Invisible3ck** [comment]
Working on latest ASK beta.

**Comment by menny** [comment]
You got this on your device? So quickly?

**Comment by Invisible3ck** [comment]
> You got this on your device? So quickly?

Yes, however the icon on the right is an x instead of a trash can. 
![Screenshot_20201103-200751583 (1)](https://user-images.githubusercontent.com/63332039/98068265-6fdd0d80-1e10-11eb-8cdb-80f9abc99d04.jpg)

**Comment by menny** [comment]
good point
