### ISSUE TITLE
Cursor jumps within written word

### ISSUE THREAD

**Issue by Krzmbrzl** [AnySoftKeyboard/AnySoftKeyboard#2515]
### Steps to reproduce
1. Type a word (rather fast)
2. Sometimes the cursor seems to jump back within the word so that instead of appending letters to the currently written word, they get inserted somewhere in the middle

It only happens every once in a while though...

### Expected behaviour
All letters typed should be appended to the current word

### Actual behaviour
They get inserted somewhere within the current word 

**Android OS version:** 8.0.0

**Device manufacturer and model:** Shift, Shiftphone 6m

**List of installed add-ons (like languages, or themes):** where can I find this? I definitely do have installed a German keyboard layout. Other than that I don't think I have installed anything extra 🤔

**Comment by Massedil** [comment]
I can confirm this. If you need help to reproduce put the phone in eco-mode (less processor used) and type as fast as possible : the problem occurs more often.

**Comment by menny** [comment]
Would you mind trying this build: https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257
It includes some fixes around that area.

**Comment by Krzmbrzl** [comment]
Can I simply download the linked archive to my phone, install the APK and check it out that way?

And if I want to revert to the version I am currently using, is that going to work as well (without wiping my settings)? :thinking:

**Comment by menny** [comment]
To be able to go back to the latest stable version:

1. Backup settings in AnySoftKeyboard
2. uninstall
3. download, unzip and install the APK from the link
4. follow the setup process
5. restore from the previously saved backup file.
6. Verify that everything is good.

**Note:** Keeping this version will not allow auto-updates from Google Play Store.

if you want to go back to the previous stable version:
1. Uninstall the test version
2. Install AnySoftKeyboard from Play Store
3. Follow the setup process.
4. restore from the previously saved backup file

**Comment by menny** [comment]
Seems to be fixed: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2320
