### ISSUE TITLE
AnySoftKeyboard deletes a char when adding a comma ","

### ISSUE THREAD

**Issue by Massedil** [AnySoftKeyboard/AnySoftKeyboard#2526]
### Steps to reproduce

- Add a dot (.) by double pressing space
- Move you cursor to the end of another word before in the text
- Add a comma (,) to the end of this word

### Expected behaviour

The comma is added at the end of the word and no char disapear.

### Actual behaviour

The last char of the word is deleted and the comma is added.

Android 9 - LineageOS 16.0 - Samsung Galaxy - G900F - Version 1.10.1109 (6279) F-Droid

**Comment by Massedil** [comment]
Here is a video of the bug and XML configuration :

[1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5506528/1.zip)

**Comment by menny** [comment]
Amazing find! Thank you

**Comment by menny** [comment]
Is this the latest code? Alpha? Beta? Production?

**Comment by Massedil** [comment]
> Is this the latest code? Alpha? Beta? Production?

I updated my first post : "Version 1.10.1109 (6279) F-Droid"

**Comment by menny** [comment]
I would appreciate if you can verify that the fix works for you: https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257

**Comment by Massedil** [comment]
> I would appreciate if you can verify that the fix works for you: https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257

I got a 404 error with your link. Is it also your case or I do something wrong ?

EDIT : It works now because I'm connected to my github account. I will test.

**Comment by Massedil** [comment]
Problem of deleted char solved by the new version. 

I'm surprised to see a COVID-19 alert from the keyboard. Why ?

I will continue to use this version and let you know if something else strange happens.

Thanks !
