### ISSUE TITLE
Restart suggestions does work when using backspace 

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2532]
On latest code

**Comment by Massedil** [comment]
Thanks ! How can I have a test build with this fix?

**Comment by menny** [comment]
you can grab a fixed version here: https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1506540992/artifacts/26396712

**Comment by menny** [comment]
Thanks for testing. Let me know if you find any issues.

**Comment by Massedil** [comment]
Thanks. I have updated and suggestions work as expected for now !

The only annoying thing is the covid message that comes back often. Is it possible to do something about this ?

**Comment by Massedil** [comment]
1/2. Impossible to reproduce but sometimes suggestions disappear. When putting the cursor on a past written word, it is not underlined as usual and suggestion is empty.

![Screenshot_20201117-174857_Fennec_F-Droid](https://user-images.githubusercontent.com/20357783/99420632-bd23a980-28fd-11eb-9d21-d1be99fdc0e0.png)

![Screenshot_20201117-174853_Fennec_F-Droid](https://user-images.githubusercontent.com/20357783/99420667-c6ad1180-28fd-11eb-9dce-91ed4f51a242.png)

2/2. Sometimes the corrector only takes a part of the word. It seems that it is after that bug that point 1 occurs.

![Screenshot_20201117-174843_Fennec_F-Droid](https://user-images.githubusercontent.com/20357783/99420807-f3f9bf80-28fd-11eb-9ccb-cd8d6a657b06.png)

**Comment by PrSunflower** [comment]
Hi, I have downloaded and installed this APK (Testing build 1.10.1651, version code 6821) but the error is still here.

I have been using it for several days, here are some screenshots:

### Example 1

![Screenshot_20201119-154408](https://user-images.githubusercontent.com/59576952/99975844-ff883300-2da2-11eb-9138-d93bd185e3f6.png)

![Screenshot_20201119-154415](https://user-images.githubusercontent.com/59576952/99975868-07e06e00-2da3-11eb-9af9-09f0c20659b3.png)

### Example 2

![Screenshot_20201119-155133](https://user-images.githubusercontent.com/59576952/99975935-1f1f5b80-2da3-11eb-89f5-6479c1e816f5.png)

![Screenshot_20201119-155137](https://user-images.githubusercontent.com/59576952/99975944-221a4c00-2da3-11eb-8c61-239981bd3710.png)


### Example 3

![Screenshot_20201120-132919](https://user-images.githubusercontent.com/59576952/99975956-247ca600-2da3-11eb-8dca-82571cbfaf54.png)

![Screenshot_20201120-132930](https://user-images.githubusercontent.com/59576952/99975967-27779680-2da3-11eb-8f84-f6a54b1d8e76.png)


### Example 4

![Screenshot_20201123-095126](https://user-images.githubusercontent.com/59576952/99975984-2b0b1d80-2da3-11eb-8f05-ff0b2b870a1e.png)

![Screenshot_20201123-095130](https://user-images.githubusercontent.com/59576952/99975991-2d6d7780-2da3-11eb-8f0a-62a2c92bc7b5.png)


### Example 5, other languages are affected too

![Screenshot_20201117-020416](https://user-images.githubusercontent.com/59576952/99976000-2fcfd180-2da3-11eb-84c9-dc2b42709bbc.png)

<br>

<br>

Were these errors supposed to be fixed? Are you working on it?
