### ISSUE TITLE
please fix

### ISSUE THREAD

**Issue by duergrim** [AnySoftKeyboard/AnySoftKeyboard#2568]
I know this is weird, but when I'm long press the emoji, and use the heart, it shows a perfect good heart emoji ❤️ but when I use the other heart by going to the {}_ thing ♥ - see the difference? Please fix this, I want the first heart to be replaced with the "wrong" heart.

Btw let me change the emoji I use when short pressing the emoji icon, to the right heart for example, instead of the ugly smile emoji.

![Screenshot_20201128-155007__01__01](https://user-images.githubusercontent.com/44030905/1005186
![Screenshot_20201128-160202__01](https://user-images.githubusercontent.com/44030905/100518687-4c00b380-3193-11eb-830b-50691f1f21af.jpg)
11-dac10080-3192-11eb-988d-7ce72bc1144b.jpg)

### Steps to reproduce
1. Press 123!#()
2. Press {}_
3. Use the heart

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**
10
**Device manufacturer and model:**
Oneplus 6
**List of installed add-ons (like languages, or themes):**
Danish

**Comment by duergrim** [comment]
![Screenshot_20201128-155007__01__01](https://user-images.githubusercontent.com/44030905/100518724-96823000-3193-11eb-85da-1df5c1815d72.jpg)

**Comment by menny** [comment]
Those are, actually, two different hearts on purpose.
The emoji heart ❤️ is love kind of emoji. While the symbols heart ♥ is part of the cards deck set ♦♣♠

Regarding your second request, you can override the default emoji in the emoji settings page under the settings button (top right gear icon)
