### ISSUE TITLE
Spelling error(?) "Codvid"

### ISSUE THREAD

**Issue by Jonta** [AnySoftKeyboard/AnySoftKeyboard#2588]
### Steps to reproduce
Search: https://github.com/AnySoftKeyboard/AnySoftKeyboard/search?p=1&q=codvid

### Expected behaviour
0 results. "Covid" instead

### Actual behaviour
22 results

"Covid" currently has 6bn Google-results. "Codvid" has 330k (>18kx difference)

Searchability

**Comment by menny** [comment]
embarrassing.
Fortunately, this is a string identifier and not something users see.
Unfortunately, this ID is already heavily used in translations and changing it will revert many translations.

I'm going to keep this typo for convenience. In any case, Covid will go away in a few months (hopefully) at which point any covid related code and strings will be removed.

Thanks for finding this!
