### ISSUE TITLE
Accidentally pressing mic

### ISSUE THREAD

**Issue by duergrim** [AnySoftKeyboard/AnySoftKeyboard#2607]
Please let me get rid of the microphone in the keyboard. I accidentally press it like 15-20 times a day![Screenshot_20201224-013741.jpg](https://user-images.githubusercontent.com/44030905/103046556-fac4c380-4588-11eb-813e-6d127faf13f5.jpg)

**Comment by fontanon** [comment]
![Screenshot_20201229-170530](https://user-images.githubusercontent.com/113024/103297261-3b449700-49f8-11eb-8b4d-620099c12a1b.png)

I guess you could just personalise the common bottom bar to remove the mic icon. It is under theme settings. Have a look at the image.

**Comment by duergrim** [comment]
How did you get that keyboard? I can't find it

**Comment by matheuswillder** [comment]
Go to **UI**>**Other settings**>**Generic bottom line** (I'm using the Portuguese translation so the English may not be exactly that). I also had the same problem. ASK is very customizable but the settings are not very easy or intuitive.

**Comment by duergrim** [comment]
> Go to **UI**>**Tweaks and more**>**Common bottom generic row** (I'm using the Portuguese translation so the English may not be exactly that). I also had the same problem. ASK is very customizable but the settings are not very easy or intuitive.
> 
> Edit: correction of options in English.

Thank you!!!!❤️
