### ISSUE TITLE
ASK doesn't recognize words from user dictionary while gesture typing.

### ISSUE THREAD

**Issue by x-enigma** [AnySoftKeyboard/AnySoftKeyboard#2613]
### Steps to reproduce
1.Add a custom word to dictionary( example "asdfgh" or "awsed" for easy gesture  ).
2.Draw the gesture for "asdfgh" or "awsed".

### Expected behaviour
AnySoftKeyboard should recognize my gesture as the new word from the dictionary.

### Actual behaviour
It does not recognize the word and instead gives words from the default English dictionary.

**Android OS version:**
Andriod 10

**Device manufacturer and model:**
Nokia 5.1 Plus

**List of installed add-ons (like languages, or themes):** None

**Comment by free5lot** [comment]
I have this issue too.

**Comment by Apflkuacha** [comment]
This issue has already been posted here, hopefully it's fixed soon: [https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1933](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1933)

**Comment by Jonta** [comment]
Closing as duplicate
