### ISSUE TITLE
Dvorak variants for czech and other languages

### ISSUE THREAD

**Issue by WesterWest** [AnySoftKeyboard/AnySoftKeyboard#2625]
I am a dvorak user and I really enjoy AnySoft keyboard, but it only comes in english layout, that means that I only have english autosuggestions, but I use more languages (especially czech) day to day. Is there perhaps a way to make more general layouts possible, or just making czech layout (plus maybe german) dvorak?

**Comment by khlsvr** [comment]
Same here, but I want finnish suggestions.

Also for the finnish dvorak I am fine without having ä and ö on the board, but I would wish that a long press on `a` would autoselect `ä` at first and not `à` as that seems to be the autoselect option in the finnish qwerty keyboard aswell as in the english dvorak keyboard. So using long press with `a`, you would need to move your finger to the furthest most option to pick up the `ä`.

**Comment by menny** [comment]
Thank you @khlsvr for answering.
If there is a special variant of Dvorak for Czech, we can create that in the Czech pack, otherwise, @khlsvr solution is good.

**Comment by WesterWest** [comment]
> Thank you @khlsvr for answering.
> If there is a special variant of Dvorak for Czech, we can create that in the Czech pack, otherwise, @khlsvr solution is good. 

no there isn't, it's just a simple us dvorak with accented letters, I'm glad there's a solution to this
