### ISSUE TITLE
[Feature Request] Add Option to Disable Key Popup for Password Fields

### ISSUE THREAD

**Issue by hbchai** [AnySoftKeyboard/AnySoftKeyboard#2630]
The keyboard currently pops up the pressed key on all fields, including password fields. This makes it easier for an onlooker to steal a password.

This request is to add an option to avoid popping up the pressed key on password fields.

**Comment by menny** [comment]
this is a good suggestion. I'll try to get this done for r4, but may need to push it to r5.
