### ISSUE TITLE
Suggestions do not restarted if deleting past the second word

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2632]
Type "hello hello hello " in WhatsApp 
Now, back space back to the first hello.
Should restart that word, but doesn't

**Comment by menny** [comment]
This might have been fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2696

**Comment by avently** [comment]
Hello, Menny. I'm using ASK many years and after updating to the latest version from f droid i found a different unexpected behavior. Tried to find related issues and looks like this one describes similar problem. Is it the same problem or a new one? Should i create a new issue?

On this video you see that for some reason ASK tries to suggest words even if there is no space before the cursor. It makes so hard to edit previous text in case i what to change it. Is it expected or not?

https://user-images.githubusercontent.com/7953703/118422816-9a1b5c00-b6cc-11eb-85fe-3c17dd1f71c2.mp4

**Comment by PrSunflower** [comment]
Hi @avently , wow how lucky was I to find your video recording!

We already have an issue [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2578) discussing of this problem. It also annoys me.

**Comment by avently** [comment]
@PrSunflower yep, so lucky. Thanks for mentioning, will be watching this issue too!
