### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by yoge67855** [AnySoftKeyboard/AnySoftKeyboard#2675]
1. translator
2. when i click emoji i would want to open emoji panel
3. giphs
4. stickers
5. layout more like in Gboard (edit)

**Comment by yoge67855** [comment]
oh and
quick search with duckduckgo, startpage, qwant, searx etc.

**Comment by Jonta** [comment]
I suggest splitting this up into 6 issues, with better titles

And of course searching for them first, to reduce duplicates

Perhaps [a Discussion](https://github.com/AnySoftKeyboard/AnySoftKeyboard/discussions) would be more appropriate =)

**Comment by menny** [comment]
@yoge67855 , as @Jonta suggested, please start with discussions on those topics and we'll take it from there.
