### ISSUE TITLE
Gesture typing feature stopped working

### ISSUE THREAD

**Issue by Publius1788** [AnySoftKeyboard/AnySoftKeyboard#2683]
This morning, gesture typing was not working though it was enabled in settings. Had to reboot device to work again.

GrapheneOS on pixel 4a

The battery level was very low, perhaps connected?

**Comment by menny** [comment]
gesture-typing stops when the battery is low. You can change this behavior in the settings app: UI->Keyboard effects and experince->Power-saving mode

**Comment by rustyjarz** [comment]
I have the same problem, but battery level is fine! I have to open Anysoft settings to have gesture (swipe) typing to work again. Very annoying.
