### ISSUE TITLE
[FR] add apks upload to github actions

### ISSUE THREAD

**Issue by ildar** [AnySoftKeyboard/AnySoftKeyboard#2687]
Everytime full build produces apks but only logs are downloadable.

### Expected behaviour
Github actions make built apks available.

### Actual behaviour
Only logs available: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/.github/workflows/checks.yml#L237

Thanks.

**Comment by menny** [comment]
APKs are built and archived on every deployment to production: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/.github/workflows/deploy.yml#L54

For example: https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/510293967

**Comment by ildar** [comment]
right.
Actually I wanted apks for
https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/543373229/workflow
.
So fixing subject to "+ WIP PRs" i.e. for new pushes to a PR that is WIP.
Please?

**Comment by menny** [comment]
In checks we only build the debug variant without a proper signing. This is equivalent to you building on your machine. Only after merge to master (when it is safe to use the secret signing) we build a release and properly sign.

**Comment by ildar** [comment]
building on your machine.
>
 yes, again :(
That's why asking "$SUBJECT"

**Comment by menny** [comment]
What is the use-case here? Are you creating PRs so something will build an APK for you?

**Comment by ildar** [comment]
Just  wanted to test the latest commits from
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1870/ . Compiling
myself will require a little more efforts.
