### ISSUE TITLE
PR #2696 create issue where cursor position is not updated and erase/type somewhere else

### ISSUE THREAD

**Issue by joe540** [AnySoftKeyboard/AnySoftKeyboard#2704]
~~I will try to get that on recording~~ (See at the bottom of this post), but the PR #2696 seems to create an issue where the cursor position is not updated.
I will try to get logcat with a debug build also

### Steps to reproduce
1. Write a long text
2. Move the cursor by touching somewhere in the text 
3. Try to correct/erase/type there. It will sometimes remove/add characters at the wrong place

### Expected behaviour
Cursor position should be moved along the cursor

### Actual behaviour
Sometimes, the cursor position is not updated when it is moved by touching somewhere in the text, so you type/erase at the wrong place in the text

**Android OS version:**
Android 10 
**Device manufacturer and model:**
OnePlus 6T
**List of installed add-ons (like languages, or themes):**
French language pack

Here's a recording slowed down 6 times:

https://user-images.githubusercontent.com/22401071/107902876-afd68500-6f15-11eb-8ef4-8c2a09edb515.mp4

**Comment by menny** [comment]
oh.. that's annoying. Please get me a logcat, annotated in someway if you can.

**Comment by joe540** [comment]
OK, that was due to my previous modifications (that I commented out) that where messed up when doing `git stash` and `git stash pop` after pulling the latest change. The following line was missing:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/9ab232e28fe5091ca2bb96479ea14b026c0f63fe/ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java#L475

Nevermind this issue, I was probably the only affected user :stuck_out_tongue: I'm closing it. Thanks again for your time, support and great app!


~~I figure out that this happen when you move the cursor inside de same word~~

~~For example, if you type "abcdef" (without space, so the cursor is after the f: "abcdef|") then move the cursor somewhere else in the same word (for example: "abc|def"), it seems to not update the cursor at all. I was able to reproduce it everytime I did it~~


~~I write "Abcdef",~~
~~Logcat when I move the cursor to position 3~~
```
02-15 14:53:19.886 29054 29054 D ASK     : shift updateShiftStateNow inputSaysCaps=false
02-15 14:53:19.886 29054 29054 D ASK     : shift Setting UI active:false, locked: false
02-15 14:53:19.886 29054 29054 D ASK     : onUpdateSelection: oss=6, ose=6, nss=3, nse=3, cs=0, ce=6
02-15 14:53:19.887 29054 29054 V ASK     : onUpdateSelection: word 'Abcdef', position 6.
02-15 14:53:19.887 29054 29054 D ASK     : onUpdateSelection: ok, let's see what can be done
02-15 14:53:19.887 29054 29054 D ASK     : onUpdateSelection: inside the currently typed word to location 3. <-- That's the correct position of my cursor
```

~~Then I press backspace~~
```
02-15 14:53:22.560 29054 29054 D ASK     : onFunctionKey -5
02-15 14:53:22.581 29054 29054 D ASK     : shift updateShiftStateNow inputSaysCaps=false
02-15 14:53:22.581 29054 29054 D ASK     : shift Setting UI active:false, locked: false
02-15 14:53:22.581 29054 29054 D ASK     : onUpdateSelection: oss=3, ose=3, nss=5, nse=5, cs=0, ce=5 <-- Should be "oss=3, ose=3, nss=2, nse=2, cs=0, ce=5"
02-15 14:53:22.581 29054 29054 V ASK     : onUpdateSelection: word 'Abcde', position 5. <-- Should be "word 'Abdef', position 2."
02-15 14:53:22.581 29054 29054 V ASK     : onUpdateSelection: Expected event. Discarding.
```

**Comment by menny** [comment]
That's a relief. I was worried that I introduced a bug with my change, and it's going to be another hard one to fix (as was the previous one you analyzed for us)
