### ISSUE TITLE
Suggestion: 4 sea-life-emoji in animal-category, in addition to their current food-category (🦀, 🦞, 🦐 & 🦑)

### ISSUE THREAD

**Issue by Jonta** [AnySoftKeyboard/AnySoftKeyboard#2716]
🐙 Octopus is already in it https://emojipedia.org/octopus/

Emojipedia's descriptions do mention food, but not exclusively
|Emoji|Link|Snippet from Emojipedia|
|:-|:-|:-|
| 🦀 | https://emojipedia.org/crab/    | May be used to represent crab as food or metaphorical senses of crab (e.g., crabby).                                            |
| 🦞 | https://emojipedia.org/lobster/ | Often used to represent lobster as food as well as in connection to the US state of Maine.                                      |
| 🦐 | https://emojipedia.org/shrimp/  | May be consumed in the form of 🍤 Fried Shrimp or 🥘 Shallow Pan of Food. Often used to represent seafood.                      |
| 🦑 | https://emojipedia.org/squid/   | Occasionally used to represent squid as a food item. Not to be confused with 🐙 Octopus, though their applications may overlap. |

Octopus is mentioned explicitly as something not to confuse with squid

I'm reporting this because I predicted I'd find one of these under "Nature", but instead found it under "Food"

I think having them in 2 different categories is fine: People think about things differently, tags are more useful, and they look very much alive on my device

**Comment by menny** [comment]
yes, you are right. I opted for unicode.org top-level [grouping](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/emojis/emoji-test.txt#L3456). But this can be changed.

Do you want to submit a PR for that? Add the food-marine group to https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/buildSrc/src/main/java/emoji/EmojiCollector.java#L73 and regenerate the emoji layouts (`./gradlew :makeEmojiKeyboards`)

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2910
