### ISSUE TITLE
Unexpected enrollment in beta program

### ISSUE THREAD

**Issue by RonKaminsky** [AnySoftKeyboard/AnySoftKeyboard#2749]
### Steps to reproduce
1. Install latest update from Google Play Store without actively joining beta program

### Expected behaviour
Version of ASK should not be a testers' version.

### Actual behaviour
Version of ASK is a testers' version.

**Android OS version:**
6.0.1

**Device manufacturer and model:**
OnePlus X (ONE E1001)

**List of installed add-ons (like languages, or themes):**
English + Hebrew

**Comment by menny** [comment]
When did you install? And which version do you see (check AnySoftKeyboard settings app, not anywhere else)

**Comment by RonKaminsky** [comment]
Update installed a bit before 2021-03-06 17:09 UTC.

I don't know if it is significant but before pressing the install button in the Play Store, I pressed on the name of the application, and then on the bullet list which started with "Keep safe! ...", and then on the "Details" screen I copied the link to the milestone in Github and visited it in a browser, where I also looked at the closed issues.

**Comment by jotaf98** [comment]
Same, installing from Play Store gets you ASK Canary currently.

**Comment by lajby95** [comment]
Having same issue, I probably got it in the last 2 weeks. Version 1.10.1786, version-code 6956.

**Comment by IggyTechLab** [comment]
Same here. App last updated on March 2nd via Play Store. Android 10.

![IMG_20210307_144419.jpg](https://user-images.githubusercontent.com/77900218/110242000-2f270980-7f54-11eb-8db4-853df66a255f.jpg)

![IMG_20210307_144906.jpg](https://user-images.githubusercontent.com/77900218/110242017-49f97e00-7f54-11eb-98a1-df9cda4b1c2c.jpg)

Also, I have noticed a small fire icon in the bottom right of the keyboard. Does it have something to do with this version or is it another setting I have unintentionally enabled?

![IMG_20210307_142512.jpg](https://user-images.githubusercontent.com/77900218/110241988-233b4780-7f54-11eb-8d19-6e1f3db2d023.jpg)

**Comment by DrTexx** [comment]
Can confirm that I'm also
- Haven't opted into any non-stable builds, but have been updated to a canary build
- Can see the fire icon mentioned above, but don't recall seeing it before.

Only noticed because I became paranoid when I saw a random coronavirus icon to the left of the (x) button in the auto-complete bar.
<img src="https://user-images.githubusercontent.com/23412100/110260871-dda76a80-7fa5-11eb-9790-7cabbbf5c749.jpg" width=50%></img>

**Comment by Roozter2** [comment]
New install from Play Store followed by notice to update which is the Canary build.

**Comment by RonKaminsky** [comment]
Finally figured out where the version is:

Version 1.10.1786, version-code 6956

**Comment by lajby95** [comment]
Latest update from Google Play seems to have fixed it for me. Version 1.10.1794, version-code 6964.

**Comment by RonKaminsky** [comment]
> Latest update from Google Play seems to have fixed it for me. Version 1.10.1794, version-code 6964.

Fixed for me also, same version. Should I close this? Or should a specific commit be cited?

**Comment by Jonta** [comment]
Since nobody's commented since March, closing now
