### ISSUE TITLE
Little orange symbol in corner

### ISSUE THREAD

**Issue by herut18** [AnySoftKeyboard/AnySoftKeyboard#2751]
### Steps to reproduce
1. Just opened my android xiaomi mi max2
2.
3.

### Expected behavior
Expected to use ASK keyboard as always

### Actual behaviour
Tell us what happens instead
Little orange symbol in lower right corner was never there before
**Android OS version:**
7.1.1 nmf26f

**Device manufacturer and model:**
Xiaomi mi max 2
**List of installed add-ons (like languages, or themes):**
Hebrew

**Comment by menny** [comment]
It's a bug in our release process. It will be fixed soon.
