### ISSUE TITLE
Tap area for whitespace is cut off when "draw behind navigation bar" is enabled

### ISSUE THREAD

**Issue by alchemiker** [AnySoftKeyboard/AnySoftKeyboard#2771]
### Steps to reproduce
1. Open the keyboard.
2. Enable the setting "draw behind navigation bar" (or whatever it is called in the english app version).
3. Try to tap on the whitespace, "switch language", punctuation or whatever your current layout has in the lowest key-row.

### Expected behaviour
The tap should be registered wherever you tap on a key.

### Actual behaviour
The tap will be only registered if you tap above the space where the navigation bar would have been.

**Android OS version:** 10

**Device manufacturer and model:** Nokia 6.2

**List of installed add-ons (like languages, or themes):** German Language Pack ("Deutsches Sprachpaket"), Russian Language Pack ("Russian for AnySoftKeyboard"). 
I am also enrolled it the beta-testing although it is not shown in the app itself. Version 1.10.1794, version-code 6964

In the attachments are two screenshots of the keyboard in WhatsApp (it happens in other apps too)
 with the options "show layout boundaries" and "show finger tipps" activated in developer mode, which should hopefully explain the problem.

![Screenshot_20210310-153405 1](https://user-images.githubusercontent.com/63516327/110646319-12d6d700-81b7-11eb-8cb1-60fe8d79f9cc.png)

![Screenshot_20210310-153359 1](https://user-images.githubusercontent.com/63516327/110646775-85e04d80-81b7-11eb-8392-85382b585d3e.png)

**Comment by alchemiker** [comment]
Was fixed with the last major update.

**Comment by menny** [comment]
Thanks for reporting back
