### ISSUE TITLE
privacy policy link is wrong on android playstore

### ISSUE THREAD

**Issue by lkelemen** [AnySoftKeyboard/AnySoftKeyboard#2779]
### Steps to reproduce
1. click privacy policy link at the bottom of the page https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard&hl=en&gl=US
2. It wants to open http://anysoftkeyboard.github.io/privacy_policy.html which doesn't exist

### Expected behaviour
It should go to https://anysoftkeyboard.github.io/privacy-policy/

### Actual behaviour
It goes to http://anysoftkeyboard.github.io/privacy_policy.html which doesn't exist

**Comment by menny** [comment]
Thank you!

**Comment by Jonta** [comment]
@menny Problem persists

Don't want legal problems. =)

**Comment by menny** [comment]
done
