### ISSUE TITLE
Qwerz keyboard with english dictionary?

### ISSUE THREAD

**Issue by Mannshoch** [AnySoftKeyboard/AnySoftKeyboard#2781]
How do I setup an English keyboard with Qwerz layout instead QWERTY?
At moment I have two keyboards. One with Qwerz for German and one with QWERTY for English.

**Comment by snkfxx** [comment]
This is not really an 'issue's with the app, but here goes:

1. Enable both the German and English keyboards
2. Go to the keyboard layout you want to use (qwerz)
3. Press and hold the enter key
4. Press 'override default dictionary'
5. Select only English from the list, or a combination of languages

**Comment by Mannshoch** [comment]
Thank you really much!
Over the last years I several times Installed this App and uninstalled it again because of this Problem.  Now Im Happy. I have the Perfect Keyboard!

**Comment by snkfxx** [comment]
You're welcome!

You should close this issue then.

**Comment by Mannshoch** [comment]
I'm not sure. Isn't it a design problem if user do not find that settings? In my opinion most user choose one keyboard but wish using it with different language?

**Comment by snkfxx** [comment]
I guess you should probably submit a feature request then.

I do agree that it's a shame the override default dictionary option, which is very useful, is almost impossible to find if you don't know where to look.
