### ISSUE TITLE
will 1.10-r4 be also on Fdroid soon?

### ISSUE THREAD

**Issue by Joppla** [AnySoftKeyboard/AnySoftKeyboard#2798]
Great to read that release 1.10-r4 is available in spite of your lack of time. But will it be also on fdroid soon?

**Comment by maximilianovermeyer** [comment]
@Joppla It seems like this should be resolved now ( not by me) .

**Comment by Joppla** [comment]
I ve seen it. 

Met vriendelijke groet,

Jop
(Vanaf mijn mobiel verzonden, dus waarschijnlijk te kort en te bondig)


19 mei 2021 19:02:35 maximilianovermeyer ***@***.***>:

**Comment by Jonta** [comment]
@Joppla I suggest fixing your email signature. =)

Closing as I get the impression that this is resolved
