### ISSUE TITLE
Punctuation and spaces: ( open parenthesis or bracket), " speech marks" and @ symbol.org

### ISSUE THREAD

**Issue by Jackalaq** [AnySoftKeyboard/AnySoftKeyboard#2813]
### Steps to reproduce
1. Type (
2. Gesture a word... e.g. Example
3. Type )

### Expected behaviour
(Example)

### Actual behaviour
( Example)

**Android OS version:**
Nougat

**ASK version**
1.10.r3 ( awaiting on FDroid)

**Device manufacturer and model:**
OnePlus 3T

**List of installed add-ons (like languages, or themes):**

**Comment by hakaishi** [comment]
I also have this problem. 
Also when typing a quotation mark etc.

**Comment by Jackalaq** [comment]
Also, @ symbol should probably not have a space after it. I'll amend the title of this thread.
