### ISSUE TITLE
Backup failes due to missing directory

### ISSUE THREAD

**Issue by toolstack** [AnySoftKeyboard/AnySoftKeyboard#2815]
### Steps to reproduce
1. Start ASK
2. Select three dot menu
3. Select Backup
4. Click Backup

### Expected behaviour
Backup file should be created in /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files.

### Actual behaviour
Error message is displayed: Failed! Failed to backup your data due to Failed to of storage folder /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files

This is because the "com.menny.android.anysoftkeyboard" directory does not yet exist in /storage/emulated/0/Android/data.  If I manually create it, the backup works correctly.

Taking a quick look at the source code it looks like line 133 of AnyApplication.java is the likely culprit:
```
new File(externalFolder, "/Android/data/" + BuildConfig.APPLICATION_ID + "/files/"),
```
As it looks like it assumes all paths already exist above "files".

I'm not a java programmer, but doing a quick search, perhaps something like:
```
new File(externalFolder, "/Android/data/" + BuildConfig.APPLICATION_ID + "/files/").mkdirs(),
```
would solve the issue?

**Android OS version:**
LineageOS 17.1 or 18.1, no GAPPS or microG.

**Device manufacturer and model:**
Muliptle: OnePlus 5,7,8t, Pixel 4, Samsung Galaxy Tab s5e

**List of installed add-ons (like languages, or themes):**
None

**Comment by Flnch** [comment]
For me it is the same error on Android 11 with AnySoftKeyboard version `1.10.1109` from F-Droid.

> This is because the "com.menny.android.anysoftkeyboard" directory does not yet exist in /storage/emulated/0/Android/data. If I manually create it, the backup works correctly.

Interesting that manually creating the folder works for you. For me, this does not work. Even exporting the settings after a fresh installation of AnySoftKeyboard does not work (and yes, the file permission was granted). Maybe this has to do with a different file access mechanism on Android 11?

Btw, exporting the settings to custom paths is an already implemented feature, according to pull request #2365 and issue #2728. Then it may work. But I did not test the GitHub release of AnySoftKeyboard and this feature is not available on F-Droid yet, as the most recent F-Droid build is still back from 2020-02-12.

**Comment by toolstack** [comment]
>Maybe this has to do with a different file access mechanism on Android 11?

LineageOS 18.1 is Android 11 so it has the same result on it.  Note that I did have to use ADB to create the folder, as I found no file manager that would let me do it.

> But I did not test the GitHub release of AnySoftKeyboard and this feature is not available on F-Droid yet, as the most recent F-Droid build is still back from 2020-02-12.

I'm using the f-droid release as well.

**Comment by Flnch** [comment]
> Note that I did have to use ADB to create the folder, as I found no file manager that would let me do it.

My file manager also did not work. But I managed to create the folder with the onboard "File" app.

**Comment by landry314** [comment]
i think it is because the permission the app has is "allow access to media only". BUT, all apps should have read/write access to their own folders in /Android. This is also an issue for me on LineageOS 18.1

**Comment by bugith** [comment]
Met this issue in Android 13 on Nothing Phone (1) Nothing OS 1.5.2 when I want to use Save settings "To custom location" with v1.11.7137 from F-Droid.

**Comment by xeruf** [comment]
so on an unrooted phone I cannot extract a backup? yikes...

**Comment by toolstack** [comment]
@xeruf you can still extract the backup, you do need a file explorer that properly asks for the permissions though when you navigate to the folder.
