### ISSUE TITLE
Please Give Option to turn off Covid-19 Icon

### ISSUE THREAD

**Issue by rwg83** [AnySoftKeyboard/AnySoftKeyboard#2850]
Please give an option to turn off the new Covid-19 icon/link.

Thanks.

**Comment by WilliamShockleyfake** [comment]
Yes that shit is annoying. We don't care

**Comment by maximilianovermeyer** [comment]
Linked to #2803

**Comment by EdaNano** [comment]
Also make it turned off by default. Or even better, remove this feature, this has nothing to do with a keyboard app ;) Can you imagine life with all apps doing this ?

**Comment by aaaawwWWWwwwwWWW** [comment]
exactly why you thought it was good... we need a keyboard not covid

**Comment by STPKITT** [comment]
This should've been fixed in no time, but instead developers didn't even give a remotely reasonable explanation about wth this "feature" has a place in a *keyboard* app!?!

**Comment by menny** [comment]
This will be removed in the next release, which is delayed due to lack of bandwidth. Sorry.

**Comment by STPKITT** [comment]
Thank you very much for that statement! I'm looking forward to the next release.

**Comment by evanz000** [comment]
Hey guys, another option is to downgrade to the previous version https://github.com/AnySoftKeyboard/AnySoftKeyboard/releases/tag/1.10-r3
