### ISSUE TITLE
Why hindi version  addon for AnySoftKeyboard cannot be installed? 

### ISSUE THREAD

**Issue by Premjit-Developer** [AnySoftKeyboard/AnySoftKeyboard#2865]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by Jonta** [comment]
@Premjit-Chowdhury Details? =)
