### ISSUE TITLE
ime:app:debugRuntimeClasspath? ime:app:minifyCanaryWithR8?

### ISSUE THREAD

**Issue by matthewmorrone** [AnySoftKeyboard/AnySoftKeyboard#2871]
Hello, 

After cloning the repo with a fresh install of Android Studio, I keep getting the following trying to build:

Could not resolve all dependencies for configuration ':ime:app:debugRuntimeClasspath'.
Could not create task ':ime:app:minifyCanaryWithR8'.
Cannot query the value of this provider because it has no value available.

Found this on StackOverflow but the SDK manager doesn't show up under the tools menu:
https://stackoverflow.com/questions/64549203/could-not-resolve-all-dependencies-for-configuration-app-debug-runtime-classpa

Any ideas?

**Comment by menny** [comment]
What was the issue? Or are you still seeing the issue?

**Comment by matthewmorrone** [comment]
I'm honestly not sure. I didn't change anything, but the sixth try seemed to do the trick.
