### ISSUE TITLE
Swipe-Down gesture doesn't work for hiding keyboard 

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2883]
This is only when Gesture Typing is enabled.

**Comment by andyxo-xo** [comment]
Can confirm.... swiping down on alphabet keyboard didn't hide it for me either

**Comment by jviki** [comment]
Same issue.

**Comment by RhysSpellbinder** [comment]
Can confirm on Android 11 Redmi 9 pro Stock

**Comment by menny** [comment]
I will enable this gesture when the finger swipes all the way out through the bottom of the keyboard (in gesture-typing enabled mode)
