### ISSUE TITLE
Keyboard change gesture (swipe left/right on keyboard) too sensitive

### ISSUE THREAD

**Issue by gbakeman** [AnySoftKeyboard/AnySoftKeyboard#2902]
### Steps to reproduce
1. Use keyboard while normally typing

### Expected behaviour
Key inputs continue to behave normally, i.e. typing text.

### Actual behaviour
The keyboard reads a "keyboard switch" gesture on the spacebar and switches keyboards (Console for me).

**Android OS version: 9 Pie (OxygenOS)**

**Device manufacturer and model: OnePlus 6T**

**List of installed add-ons (like languages, or themes): None that I'm aware of.**

As of version 1786, it seems like the keyboard gesture swipe has suddenly become more sensitive without me changing any settings. I like being able to swap keyboards with the space bar, but I think it's reading my spacebar taps and swipes more often than it should.

**Comment by richaardvark** [comment]
Will someone please do something about this??! I am using a OnePlus 8 on OxygenOS 12 (Android 12) and this is still an issue.

**Comment by khimaros** [comment]
i believe this is a duplicate of https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2902

**Comment by gbakeman** [comment]
@khimaros Right you are, I'll close this issue.
