### ISSUE TITLE
COVID link

### ISSUE THREAD

**Issue by BluhmJA** [AnySoftKeyboard/AnySoftKeyboard#2914]
@### Steps to reproduce
1. None. Keyboard opened.

### Expected behaviour
Blank suggestion bar

### Actual behaviour
Red COVID icon with hyperlink to WHO COVID site is displayed with no option to disable.
This "feature" is a bug and has no place in this app. I causes the suggestion bar to stay up all the time and takes up valuable screen real estate. More importantly, the developers have no right to push any kind of agenda on their users. COVID info is only a few clicks away via any browser anywhere in the world on any device for anyone interested. This needs to be removed NOW. And I don't mean provide an option to disable it, or make it disappear after the first click. It needs to be entirely removed immediately, and no "features" like this should ever be implemented in the future.

**Android OS version:**
All

**Device manufacturer and model:**
All

**List of installed add-ons (like languages, or themes):**
Inconsequential

**Comment by menny** [comment]
First, the COVID message will be removed in the next release as COVID becomes less of an issue (with vaccination going up).
Secod, this message is shown a handful of times before being removed completely.
Third, the developers of this app have the right to do whatever they wish with the app as long as it is legal. I can promise you that in the future we will show similar messages if such extraordinary events - like worldwide pandemic - occur.

**Comment by Nutomic** [comment]
How often is "a handful times"? I must have opened the keyboard dozens of times since installing the update, and I'm still seeing the icon. I dont mind warnings about important events, but in this case its pretty useless as the pandemif has been going on for over a year, so everyone already knows about it. Why dont you simply hide the icon after the first time it has been clicked?

**Comment by jherazob** [comment]
>  Secod, this message is shown a handful of times before being removed completely.

Incorrect, for me it has been shown every single time, without exception, since the plague started. And i must have accidentally clicked it a hundred times already. It's very annoying and cannot be disabled.

>  Third, the developers of this app have the right to do whatever they wish with the app as long as it is legal. I can promise you that in the future we will show similar messages if such extraordinary events - like worldwide pandemic - occur.

And the users have the right to avoid the app if it becomes a nagging mom, with no option to disable the nagging

**Comment by daffydock** [comment]
Found this through a link from Reddit. 

They are right, it is their app to do as they wish. However, I do not install a keyboard app to get info or get reminders about info that I can easily get anywhere else. 

It is unfortunate, but for now, the best fix is to remove this keyboard and switch to another one with less feature creep.

**Comment by helllamer** [comment]
Quick fix/workaround, works perfectly:
```
adb uninstall com.menny.android.anysoftkeyboard
```

**Comment by deutrino** [comment]
I use my phone **a lot,** every day, and I type on it **a lot,** every day, and the message has not disappeared.

**Comment by deutrino** [comment]
2 months later, this still appears every single time I open the keyboard. Every time. I must have clicked it by accident five times in a week.

Not appropriate.

**Comment by fuck-shithub** [comment]
Political propaganda does not belong in software.
Does anyone know of any free-software Android keyboard that does not pull this kind of shit? Or perhaps someone should fork ASK to remove this kind of shit.

**Comment by 5lttrz** [comment]
Strange. I have seen in only around 6-7 times in the 10 months i have been using ASKeyboard

Have you tried reinstalling? (With all data backed up of course)

**Comment by aceryz** [comment]
What a joke. I just switched off recommended words altogether. To get rid of the idiotic "feature" I had to turn off an actual, helpful feature. I'm waiting for some more skilled people to make a fork without this nonsense, I'd gladly pay for it, too.

Doesn't matter what it is about, a keyboard app is not a place for reminders and links of any sort.

**Comment by menny** [comment]
This has been removed for several months now. Are you sure you're using the latest version?

**Comment by aceryz** [comment]
The newest from F-Droid, for some reson the red icon appeared this week. I haven't seen it before.

**Comment by menny** [comment]
I'm trying to get f-droid to update to the latest version of ASK. Once that happens, the COVID notice will be removed.

**Comment by aceryz** [comment]
Great, thank you - it's much appreciated. I love the keyboard! Cheers.

-------- Oryginalna wiadomość --------
‎ 10.01.2022, 18:56, Menny Even Danan napisał(a):
