### ISSUE TITLE
Option for changing the size of the keyboard

### ISSUE THREAD

**Issue by salmanpy444** [AnySoftKeyboard/AnySoftKeyboard#2930]
Changing keyboard height/size

**Comment by glemco** [comment]
Hidden but somewhat possible, go to the UI tab, select and configure themes and then press the gear (settings) icon on the top right side in the titlebar.
In the menu that appears you can select the height of keys for both landscape and portrait mode (kind of what you want, I guess)

**Comment by Jonta** [comment]
@salmanpy444 Looks to me like what @glemco said answered your question. =)

Keyword: Keys height factor in portrait mode / Keys height factor in landscape mode

**Comment by pesokpesok** [comment]
Thank you - exactly what i was looking for!
