### ISSUE TITLE
FKeyboard in Play Store uses ASK's source code without disclosing it

### ISSUE THREAD

**Issue by najodleglejszy** [AnySoftKeyboard/AnySoftKeyboard#2944]
https://play.google.com/store/apps/details?id=com.vitali.pom.effectedkeyboard2

you can tell from the screenshots that at least some parts of the keyboard are lifted from ASK - the panel you get when swiping up from the space bar, the X button in the suggestions bar, even the placement of the beta icon in the bottom right corner of the kesyboard. the description doesn't mention anywhere that it's based on AnySoftKeyboard, nor does it share the keyboard's source code anywhere.

edit: apparently it mentions that it's based on AnySoftKeyboard in the app itself, and the Apache license doesn't require them to release a derivative under the same license. disregard, I guess.

**Comment by menny** [comment]
@VitaliPom , I assume that the app has a licenses page and AnySoftKeyboard is mentioned there (there is no need to mention in the Play Store description, just in the in-app licenses page)

**Comment by najodleglejszy** [comment]
yup, I can confirm that it does have an About section which mentions ASK and the licenses.
