### ISSUE TITLE
give the option to disable/remove COVID information icon

### ISSUE THREAD

**Issue by flisboac** [AnySoftKeyboard/AnySoftKeyboard#2975]
### Steps to reproduce
1. Open any app with text input
2. Highlight the text input. Any soft keyboard opens
3. Coronavirus information icon and text instantly gets in the way, and stays in the way for quite a while.

For short messages, like in messaging apps, I can’t really use autocomplete, because the covid overlay text does not disappear in time. I have to wait some seconds before being able to click on the autocomplete option.

I also don't see the need for such functionality. It's been detrimental to my experience. At least, let me disable it.

![Screenshot_20210903-125435](https://user-images.githubusercontent.com/1124212/132034548-65a25c1e-6954-46e2-a947-82d25675836b.png)

### Expected behaviour
I expect to be able to disable this COVID whatever it is.

### Actual behaviour
I see no option to disable the COVID information icon/message.

**Android OS version:**
Android 9

**Device manufacturer and model:**
Moto Z3 Play

**List of installed add-ons (like languages, or themes):**
Portuguese (Brazil)

**Comment by voldemarz** [comment]
Yes. This is annoying. There is already enough covid related info everywhere, don't need one constantly in my face.

**Comment by k-at-e** [comment]
When I write something on a web page I often touch it inadvertently and it opens a gov. page on my browser, it drives me crazy because I loose the page I was on. I love this keyboard but it became unusable for me. 😟

**Comment by vukasin-nikodijevic** [comment]
Please, remove it or give option to disable.
It is ridiculous to have something like that as part of the keyboard.

**Comment by cyanne-git** [comment]
Adding political messaging to your software is intrusive.

**Comment by Frans-Github** [comment]
Yes, please give option to remove or even better, just remove it. Totally agree with voldemarz, there is more than enough info anywhere else. Thanks

**Comment by menny** [comment]
First, covid is not a political message, it's a public safety issue.
Second, this message is already removed in the latest ALPHA release and will be in BETA soon, and stable in a bit.
