### ISSUE TITLE
GitHub: Update to new version of issue template workflow

### ISSUE THREAD

**Issue by Jonta** [AnySoftKeyboard/AnySoftKeyboard#2976]
### Steps to reproduce
1. https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/3b27dd10c78013850d832e3922faefed6213a66d/issue_template.md
2. Try to edit it

### Expected behaviour
Lets me edit (resulting in a fork and pull request)

### Actual behaviour
Refreshes page

**Comment by menny** [comment]
Since the change requires an update to a file in the git repository, a pull request must be involved. This is how GitHub works.

Just make it, and I'll approve and merge.

**Comment by Jonta** [comment]
My mistake

The fix:
- Click [3b27dd10c7] top left
- Select [master]

Pull request made: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2991
