### ISSUE TITLE
Backspace does not delete a word at a time

### ISSUE THREAD

**Issue by crogonint** [AnySoftKeyboard/AnySoftKeyboard#2985]
Feature request:

First off, I am SO happy the type with gesture feature is working, why is it still in beta?

The one thing I'm getting hung up on is that AnySoftKeyboard doesn't erase a word at a time when I ft finger a word, so I end up making things a mess and have to backspace to the mistake when I notice it.

**Comment by menny** [comment]
This is as design. If you wish to delete the entire word, you can use SHIFT+DELETE.

**Comment by crogonint** [comment]
Shift delete, on a phone?? First off, I think you meant shift+backspace..

Second off.. dude, the industry standard has changed, change the features
around.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
