### ISSUE TITLE
Weird order of secondary options on C key for Portuguese

### ISSUE THREAD

**Issue by robsonsobral** [AnySoftKeyboard/AnySoftKeyboard#2987]
I tried to do a pull request, but I know nothing about Android and couldn't find my way around. Sorry!

### Steps to reproduce
1. switch layout to Portuguese
2. hold C key

### Expected behaviour
The closest option should be `ç`, as it's the most used one

### Actual behaviour
The closest option is `'`

**Android OS version:**
11

**Device manufacturer and model:**
motorola one vision

**List of installed add-ons (like languages, or themes):**
- Portuguses (Brazil) QWERTY
- English (United States) QWERTY

**Comment by menny** [comment]
which version of the poruguese add-on do you have? In the code I see that it is correct

**Comment by robsonsobral** [comment]
I guess I'm doing something wrong. Please, how can I check the version?!🤔

![image](https://user-images.githubusercontent.com/931642/133704165-7c76d1c8-31e4-4a1c-aaa1-41ca7b4ad21a.png)

**Comment by robsonsobral** [comment]
Forgive me! I messed up things!
