### ISSUE TITLE
Unknown host CPU architecture: arm64 M1 MacBook Pro 2020

### ISSUE THREAD

**Issue by muhammadatifarif** [AnySoftKeyboard/AnySoftKeyboard#3025]
### Steps to reproduce
1. I've got a project that is working fine in windows OS but when I switched my laptop and opened an existing project in MacBook Pro M1. I'm unable to run an existing android project.
2.  I'm using anysoft keyboard  SDK in my project that is using this below line.
android {
    externalNativeBuild {
        ndkBuild {
           path 'Android.mk'
        }
    }
    ndkVersion '21.4.7075529'

}

that is causing issue mentioned below

# [CXX1405] error when building with ndkBuild using /Users/mac/Desktop/Consumer-Android/ime/dictionaries/jnidictionaryv2/Android.mk: Build command failed. Error while executing process /Users/mac/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/mac/Desktop/Consumer-Android/ime/dictionaries/jnidictionaryv2/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/mac/Desktop/Consumer-Android/ime/dictionaries/jnidictionaryv2/build/intermediates/cxx/Debug/4k4s2lc6/obj NDK_LIBS_OUT=/Users/mac/Desktop/Consumer-Android/ime/dictionaries/jnidictionaryv2/build/intermediates/cxx/Debug/4k4s2lc6/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n} ERROR: Unknown host CPU architecture: arm64

please visit below link for more details.

https://stackoverflow.com/questions/69541831/unknown-host-cpu-architecture-arm64-android-ndk-siliconm1-apple-macbook-pro

**Comment by menny** [comment]
https://github.com/android/ndk/issues/1299#issuecomment-752734755 should solve the issue (until NDK has official support).

I do not have an M1 machine to verify the solution
