### ISSUE TITLE
Very few kaomojis available to use

### ISSUE THREAD

**Issue by Netherquark** [AnySoftKeyboard/AnySoftKeyboard#3031]
### Steps to reproduce
1. Open competing keyboard (eg GBoard)
2. Check Kaomoji section
3. Can be observed to have more kaomojis than AnySoftKeyboard.  

### Expected behaviour
All of [these](https://photos.google.com/share/AF1QipOFUiRc_A4RxyVMNAmeQE8fJR7nbkumoC1NfitJzQxfpIU95dFsn5v2wC3bTJfaXw?key=Y3BZSEFXcUttTGszVno3Tndodm9neEFmYUhxMXpR) emojis are available to the user.

### Actual behaviour
A selective few kaomojis are available

**Android OS version:**
Android 11 R

**Device manufacturer and model:**
Xiaomi Redmi Note 9 Pro (curtana/miatoll)

**List of installed add-ons (like languages, or themes):**
Language: Only English
Theme: AOSP Dark
That's it? stock apart from that

**Comment by yagueto** [comment]
+1 for this, would like to see more as well.

It could be great to allow users to add their own kaomoji as well (without recompiling the app)

**Comment by Netherquark** [comment]
[This](https://www.androidpolice.com/2019/01/15/gboard-v7-9-prepares-new-emoticons-adds-many-new-languages-and-more-apk-teardown/) might be relevant. Apart from that, a quick search leads to many kaomoji websites such as [this](http://kaomoji.ru/en/), [this](https://kaomojihub.com/), and more.

**Comment by christofjs** [comment]
I can work on this. I'll try to get a pull request up in the next couple days. Let me know if there's any more input before I start (e.g. is there such thing as too many). I'll organize the xml by emotion/creature via comments, but add them all to the current kaomoji tab for now.

**Comment by Netherquark** [comment]
that's awesome, just adding them to the current kaomoji tab should be a good initial start imo

**Comment by Netherquark** [comment]
Sooo @christofjs is this fixed?

**Comment by christofjs** [comment]
Yes and no @Netherquark ... got them all added and have a pull request in, but the build is failing for an unknown and I would have to imagine an unrelated reason. Just asked Menny to take a look, but I can't think of anything more that I can do.

**Comment by Netherquark** [comment]
Thats great!

**Comment by menny** [comment]
This is merged and will be available in the next release. Thank you all
