### ISSUE TITLE
Does not save new words in android 10

### ISSUE THREAD

**Issue by RootedNewbie** [AnySoftKeyboard/AnySoftKeyboard#3052]
### Steps to reproduce
1.type new word
2.click on new word in suggestion bar
3.Prompt appears 'touch again to save'
4.does not save and  'touch again to save' remains unchanged.

### Actual behaviour

**Android OS version:**
Stock android 10 rooted with Magisk

**Device manufacturer and model:**
Moto G7

**List of installed add-ons (like languages, or themes):**
ASK French and Spanish dictionaries

**Comment by RootedNewbie** [comment]
The latest update to ASK canary now saves new words correctly. 
So far everything else also seems to work correctly in canary.

**Comment by menny** [comment]
Thank you for updating.
A new stable release is rolling out
