### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#3064]

**Comment by PrSunflower** [comment]
Ah yeah I had read an article about that from GitHub in Sep 2020 😄

I think it will be nice.

**Comment by menny** [comment]
[](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)[](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)[Why GitHub renamed its master branch to main](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)[](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)[](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)
[Regarding Git and Branch Naming](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3273
