### ISSUE TITLE
Setting to disable Corona Safety Icon is missing

### ISSUE THREAD

**Issue by STNBRT** [AnySoftKeyboard/AnySoftKeyboard#3068]
### Steps to reproduce
1. Start the keyboard by launching any app that requires you to type something :)
2. See the Corona Safety Icon
3. Open up the AnysoftKeyboard Settings and search them all for an option to disable the Icon

### Expected behaviour
There should be a setting disabling the Corona Notificaton Virus Icon.

### Actual behaviour
There seems to be no such setting.

**Comment by RoestVrijStaal** [comment]
@STBRT which version do you use and from where (e.g. F-Droid, Google Play Store, the Releases page of this GitHub repo) did you install & update it?

**Comment by STNBRT** [comment]
@RoestVrijStaal I'm using version 1.10.1795 on Android 11 (Samsung Galaxy). Installed via Google Play Store.

**Comment by gkubed** [comment]
I am also experiencing this on 1.10.1794.

**Comment by menny** [comment]
the next release, 1.11-r1, will have it removed completely. v1.11 is rolling out right now

**Comment by RoestVrijStaal** [comment]
@menny Thanks. Did you already informed those guys at F-Droid about it?

They are Slowpokes when it comes about releasing new versions.

**Comment by menny** [comment]
@RoestVrijStaal I have not, yet. Will do that later this week
