### ISSUE TITLE
Android/data permission denied

### ISSUE THREAD

**Issue by JeFormes** [AnySoftKeyboard/AnySoftKeyboard#3091]
Hello, 
With Anysoftkeyboard, I created my dictionary and exported in the folder but when I want to copy that in my drive I can't. It is not easy when you must change or lose your phone you will do all again....

Android 12 - Google Pixel 5 - French
Anysoftkeyboard version 1.11.181

**Comment by domportera** [comment]
I had problems with backup , but found if you dont specify a backup location and just use the default location it works. only problem is you need a special app to access that hidden folder  (Total Commander works for me)
