### ISSUE TITLE
Vibration

### ISSUE THREAD

**Issue by Setuneh** [AnySoftKeyboard/AnySoftKeyboard#3097]
### Steps to reproduce
1. No vibration when typing
2.
3.

### Expected behaviour
stop vibration when typing

### Actual behaviour
ita vibrating when i type with ask

**Android OS version:**11

**Device manufacturer and model:**galaxy s10+

**List of installed add-ons (like languages, or themes):**

**Comment by Ghostbird** [comment]
Seems like a duplicate of #3096

**Comment by menny** [comment]
@Setuneh , sis you try to disable vibration as @Ghostbird suggested?

**Comment by Setuneh** [comment]
Yes, thank you!

Menny Even Danan ***@***.***> ezt írta (időpont: 2022. jan.
2., Vas 15:16):
