### ISSUE TITLE
[Bug] Backup to specified folder fails

### ISSUE THREAD

**Issue by domportera** [AnySoftKeyboard/AnySoftKeyboard#3121]
### Steps to reproduce
1. Anysoft Canary
2. press Backup
3. choose a custom path (I used A: storage/emulated/0/Backups | B: Downloads folder)

### Expected behaviour
backup would save to specified folder

### Actual behaviour
In both cases it creates a correctly named empty (0B) file at the specified path 

A:
<img src="https://user-images.githubusercontent.com/6530600/147391253-3d896ad0-b61a-4f1e-a323-53c383a6f818.png" alt="Screenshot_20211225-131916" width="300"/>

B:
<img src="https://user-images.githubusercontent.com/6530600/147391254-19610daf-7179-49bc-ad8f-d2c42bbfae3a.png" alt="Screenshot_20211225-131950" width="300"/>

**Android OS version:**
11, Pixel 2

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by WebworkrNet** [comment]
I can confirm this.

**Comment by domportera** [comment]
also, i was unable to use any backups I actually made to restore any settings - it failed too

**Comment by mlpd** [comment]
This might have to do with the latest Android updates where apps can only access folders that they have created.
This is a huge bug though. If you back up to the default anysoft folder and then you uninstall the app that folder will be removed and your backup will be lost.

**Comment by loziniak** [comment]
I had same problem, so I'll post a solution that worked for me in this thread, because there are no app updates for many years and it's not possible to get updates without Google Play beta channel.

You can get backup files from default location through `adb`, because system file explorer displays *Android/data* as an empty folder. The files are actually there though, but hidden:

```
$ adb shell
a41:/ $ ls /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files
AnySoftKeyboardPrefs.xml
a41:/ $ exit                                                                                       
$ adb pull /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files/AnySoftKeyboardPrefs.xml ./
/storage/emulated/0/Android/data/com.menny.andro..., 0 skipped. 13.9 MB/s (1776573 bytes in 0.122s)
```
