### ISSUE TITLE
ETA for 1.11

### ISSUE THREAD

**Issue by opk12** [AnySoftKeyboard/AnySoftKeyboard#3145]
Hello, is there an expected date for the release of 1.11? f-droid is at 1.10 and tag `1.11-r1` dates back to November. Thanks

**Comment by menny** [comment]
the push to FDroid was done a few days ago: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10344
I guess they haven't published it yet.

**Comment by opk12** [comment]
Published. Thanks :)
