### ISSUE TITLE
Backup lost after uninstall

### ISSUE THREAD

**Issue by mlpd** [AnySoftKeyboard/AnySoftKeyboard#3181]
### Steps to reproduce
1. From the app, use the backup function
2. Uninstall app
3. Reinstall app
4. From the app, try to restore

### Expected behaviour
App settings get restored

### Actual behaviour
App States it Cannot find backup file
This in some ways relates to bug #3121 

Workaround: use a file manager to copy the backup to a different folder (you cannot directly back up the settings anywhere else because of bug #3121). After uninstalling and reinstalling the app you can move the backup file back to be any soft default backup folder. This will allow the settings to be restored

**Android OS version:12

**Device manufacturer and model:**
Samsng S21

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
I will only allow using the system's file picker for backup and restores. This seems what Android wants.
https://developer.android.com/training/data-storage/shared/documents-files#java
