### ISSUE TITLE
Is there an hability to send a line feed without triggering an action?

### ISSUE THREAD

**Issue by rimugu** [AnySoftKeyboard/AnySoftKeyboard#3210]
### Steps to reproduce
1. Open twitter client
2. Start writing, try to enter a line feed
3. Note is sent before finishing composing

### Expected behaviour

A way to just send the line feed without triggering an action launch

### Actual behaviour

Enters triggers and action launch

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**
Android 10
Twitter client AndStatus 2021-09-30  v.59.05 (latest from f-droid)
AnySoftKeyboard v 1.11.7197, version-code 7137 (latest from f-droid)

**Comment by menny** [comment]
This can be achieved by pressing SHIFT+ENTER

**Comment by rimugu** [comment]
Thanks for the information, that works for me.
