### ISSUE TITLE
Several languages suggestions for Gesture Typing

### ISSUE THREAD

**Issue by voidplayer** [AnySoftKeyboard/AnySoftKeyboard#3227]
### Steps to reproduce
0. have > 2 languages configured
1. type a word in a language
2. type a second word

### Expected behaviour
make the second suggestions based on the language of the first word

### Actual behaviour
suggested words are actually based on the current language selected

I dont know what trick google keyboard uses, but they suggest correct words even typing in 3 different languages and you dont need to switch language

Auto correction become more annoying because most often than not, you dont have the correct language selected and its not that you misspelled something

Thanks for this amazing keyboard!!

**Comment by menny** [comment]
You can get something similar: long-press ENTER, and select `Override default dictionary`. Then, in the new window, check all the languages you want to be associated with them current keyboard layout

**Comment by voidplayer** [comment]
It doesnt work for prediction or gesture typing, but i guess autocorrects will be less often now!

Thanks!
