### ISSUE TITLE
In the last few weeks, someone messed up the Arabic keyboard's Alef-Hamza default consonant

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [AnySoftKeyboard/AnySoftKeyboard#3243]
### Steps to reproduce
1. In the keyboard, hold the Alef letter in Arabic. Instead of getting the previous default, equivalent to consonant `a`, we get `e` (default was Hamza above Alef, now below)... how was that change done? 
 
Using the keyboard has become very annoying. A few of my friends have noted the same issue and this has slowed people down a lot, because the new default is rarely the case in Arabic.

### Expected behaviour

**Android OS version: 12**

**Device manufacturer and model: SM-N975F/DS and SM-950F, both at about the same time after an update**

**List of installed add-ons (like languages, or themes): English, Arabic and German QWERTY slim + Youchees Light theme + Plain light theme. I don't think any of that matters though**

**Comment by menny** [comment]
This is the change? https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/4e899080d30b3469c845c0f07e1946dba449f2b1

**Comment by menny** [comment]
You are saying "أ" should be the first in the list? Can you explain why? (I want to have the reason documented, I'm not an Arabic speaker)

**Comment by TheQuantumPhysicist** [comment]
Thank you for the fast response.

> This is the change? [4e89908](https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/4e899080d30b3469c845c0f07e1946dba449f2b1)

The timeframe seems consistent. It's probably the change that caused the issue. I also see the new order in my keyboard.

> You are saying "أ" should be the first in the list? Can you explain why? (I want to have the reason documented, I'm not an Arabic speaker)

First or last doesn't really matter. But what matters is that when I hold Alef, I'd get "أ" instead of "إ" by default (hence if I hold for a long time then release), because "أ" is the most used variation in the language, and others are kind of the exception.

From the looks of it, it seems that if you exchange
ٱاٰآأإء
with
ٱاٰآإأء
and do nothing else, it would solve the problem, because it seems that the second letter in this array is the default one. 

If there's another way to change the default one selected when holding Alef and set it to "أ" (regardless of the order), then that's probably a better solution.

**Comment by TheQuantumPhysicist** [comment]
Yes! Thank you very much!
