### ISSUE TITLE
Remove Goto Short Link from Welcome section

### ISSUE THREAD

**Issue by not-AMM** [AnySoftKeyboard/AnySoftKeyboard#3270]
Goto Short Links have been shut down since february 10 of 2022. People wanting to contribute could feel confused by being misguided to the Google Support website. It should be replaced by other link shortening solution or by the original link.

Currently using AnySoftKeyboard **Canary 1.11-r2** (1,11,373 version-code 7333).

**Comment by menny** [comment]
Thanks for pointing this out.
I fixed some places, where do you see such links?

**Comment by not-AMM** [comment]
In the Welcome/Home Section:
![imagen](https://user-images.githubusercontent.com/43765089/157725454-7139d566-13c7-4c8e-bad3-81201ccad0ef.png)

The first link (evendanan) redirects to the Google Support Page 👀

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3272
