### ISSUE TITLE
Firefox passwords don't get shown

### ISSUE THREAD

**Issue by twoexem** [AnySoftKeyboard/AnySoftKeyboard#3287]
### Steps to reproduce
1. Install Firefox and enable password autofill
2. Save password of service (e.g. Twitch) in Firefox password storage
3. Install and open services app (e.g. Twitch app) and click on the login fields for eMail and password

### Expected behaviour

Pressing the "search firefox" button should show saved passwords

### Actual behaviour

Nothing

**Android OS version:** Android 11

**Device manufacturer and model:** Fairphone FP4

**List of installed add-ons (like languages, or themes):** German keyboard

(This issue could also be caused by Firefox.)

**Comment by alchemiker** [comment]
I would be very astonished if this ever should work, a third-party-app (in your example the Twitch App) shouldn't have access to data from another app (Firefox), especially as sensitive as passwords. Imagine if every app on your phone could grab your passwords from Firefox.
For me autofill in Firefox itself works, and the banner for autofill ("Vorgeschlagene Zugangsdaten") is displayed by Firefox itself, even if it appears just above the keyboard and could evoke the impression that it were from the keyboard.

**Comment by twoexem** [comment]
I don't know if it's by the keyboard or browser, only thing I know that it has worked in the past but now the button doesn't do much.
Also, it asked for my password (in this case fingerprint) to access passwords, so I suppose the passwords are safe.

**Comment by Regina-v** [comment]
I can confirm that there was a time point when it indeed has worked and that it has stopped working. However, it's also not working with another keyboard so I would blame Firefox and not AnySoftKeyboard.

**Comment by twoexem** [comment]
Alright, good to know. I'll see if I can notify FF devs somehow, thanks for the nice reply and have a good Tuesday!
