### ISSUE TITLE
Unable to completely disable autocorrect for space removal

### ISSUE THREAD

**Issue by drelephant** [AnySoftKeyboard/AnySoftKeyboard#3293]
### Steps to reproduce
1. Try to type anything including a period, eg "cd .."

### Expected behaviour

When I press these keys:
c
d
-space-
.
.

It should type "cd .."

"Show Suggestions" is set to on, but under "Auto-select suggestion aggressiveness" I have it set to "Aggressiveness level: off".

Under "Tweaks", "Double space to period" is off.

### Actual behaviour

It autocorrects the space before the first period and types "cd. ."

Also any time you use arrows to go back to correct a command (when I'm navigating the CLI history), it will remove spaces.

This is super annoying when trying to use ssh...

**Android OS version:**

Android OS 10, ASK version 1.11.177

**Device manufacturer and model:**

Samsung S10 5G

**List of installed add-ons (like languages, or themes):**

Dvorak (Created with Stephen Paul Weber), Lean Dark theme.

**Comment by drelephant** [comment]
I changed back to version v1.9-r5 and it did not have the problem, and then I went back to the latest and it also didn't have the problem!!

Seems something got messed up in my settings but uninstalling/reinstalling fixed it.

**Comment by drelephant** [comment]
Very odd, now it has started doing it again, even without me changing any settings at all.

**Comment by 122800** [comment]
Hi @drelephant, from the behaviour you describe, it sounds like you have this setting activated:

> Language - > Tweaks and more > Swap punctuation and space

You could try toggling that off and see if it solves your problem.

See also #2431, which is related to the topic, but actually aims to improve this setting to perform the exact opposite of what you want (e.g, you'd end up with `cd.. ` instead of `cd. .` or `cd ..`.

Hope this helps!

**Comment by drelephant** [comment]
Thanks @122800, I think that fixed it!

It's odd that after reinstalling before, it wasn't doing that and then it seemingly changed by itself though. Anyway it was broken just then and after changing that setting it works fine now. Hopefully it stays that way!
