### ISSUE TITLE
lol 

### ISSUE THREAD

**Issue by RainyThatsMe** [AnySoftKeyboard/AnySoftKeyboard#3317]
Why can't we add lol as a word? Very tired of it being changing it to mol and it's not even a word either.

**Comment by menny** [comment]
wow.. I haven't notice this before. Let me check that out

**Comment by RainyThatsMe** [comment]
And you don't link to GIFs and stickers in my Verizon messages app. Bitmoji would be nice too eventually. Didn't realize because in FB the links are on their app so you don't need them on the key board. Just noticed that yesterday.
________________________________

**Comment by wilmhit** [comment]
this should be a language agnostic if possible

**Comment by eggbeater98** [comment]
I still have this issue, despite adding "lol" specifically to my dictionary. I'm on the latest Canary version: 1.12.572

**Comment by hairlesshobo** [comment]
Jumping in here to say that this is something I'm dealing with constantly too. I use "lol" a lot but despite how many hundreds of times I've selected "lol" instead of "mol" on the suggestions list, ASK insists that I meant "mol". I've tried removing mol from the dictionary but it refuses to go away.

**Comment by menny** [comment]
`lol` is in the dictionary. It has a frequency of `1`, which is extremely low.
It should return as the first option when typing "lol", but it doesn't. I'll try to figure out why.

**Comment by menny** [comment]
Okay... I got it. Since the word "lol" has such a low frequency it gets sorted  out from the list of suggestions.
I'll give complete typed words much higher frequency.
I'll also increase the frequency of `lol` and `LOL` as these are common words.
