### ISSUE TITLE
Settings import fails, if filepath is selected manually.

### ISSUE THREAD

**Issue by castilma** [AnySoftKeyboard/AnySoftKeyboard#3326]
### Steps to reproduce
1. On my galaxy S8+ with ASK 1.11.7137 I saved all settings etc.
2. transfer the xml file to Fairphone 2 via bluetooth and same ASK version.
3. Try to import the file, choosing the filepath by myself. I choose the file in the bluetooth directory.

### Expected behaviour

The import should work.

### Actual behaviour

I got a (rather unintelligible) error message, which seems to not be able to find the file. 
![anysoft](https://user-images.githubusercontent.com/17392981/164912860-b40152ff-964e-41fc-ac81-322f99049ad0.png)

**Android OS version:**
9

**Device manufacturer and model:**
Fairphone 2

**List of installed add-ons (like languages, or themes):**
Neo2 Layout

**Comment by castilma** [comment]
Moving the file into 'files' inside ASK data dir it works.
ASK probably is just missing the permission to open the file from other paths. It should ask for permission in that case, imho.

**Comment by menny** [comment]
We revamped this in the upcoming release. If you try out the beta version you should get better results.

**Comment by castilma** [comment]
I won't have time to test it. I'm trusting you.
