### ISSUE TITLE
Keyboard doesn't work on Android 13 beta 1

### ISSUE THREAD

**Issue by balalev** [AnySoftKeyboard/AnySoftKeyboard#3335]
### Steps to reproduce
1. Open keyboard like tap to a text box
2. You can tap anywhere, nothing will happen

### Expected behaviour

You should be able to type

### Actual behaviour

You can't able to type anything

**Android OS version:**
13 beta 1

**Device manufacturer and model:**
Google Pixel 5

**List of installed add-ons (like languages, or themes):**
Magyar AnySoftKeyboard (Hungarian language pack)

**Comment by menny** [comment]
Can you provide a logcat?

**Comment by balalev** [comment]
Hi! Here is a LogCat snippet for AnySoftKeyboard Canary (com.menny.android.anysoftkeyboard) v1.11.447 release 7407. Installed on 1651073658328, first release installed was 6266.
BRAND:google
DEVICE:redfin
Build ID:TPB1.220310.029
changelist number:TPB1.220310.029
MODEL:Pixel 5
PRODUCT:redfin
TAGS:release-keys
VERSION.INCREMENTAL:8473704
VERSION.RELEASE:12
VERSION.SDK_INT:32
Locale:hu_HU
configuration:{1.0 216mcc30mnc [hu_HU] ldltr sw392dp w392dp h785dp 440dpi nrml long hdr widecg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 136 - 1080, 2296) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} as.7 s.1 fontWeightAdjustment=0}
That's all I know.
Log contains 0 lines:

**Comment by balalev** [comment]
Beta 2 solved the problem.
