### ISSUE TITLE
Ignoring language and layout

### ISSUE THREAD

**Issue by not-AMM** [AnySoftKeyboard/AnySoftKeyboard#3339]
### Steps to reproduce
1. Restart your phone (can also happen at random times). 
2. Sometimes, the keyboard stops recognizing the language and layout.
3. Enter the settings and there's no (at least) Spanish language nor layout.

### Expected behaviour

AnySoftKeyboard works as it should, with the two layouts being present and the language/layout should apppear in this settings area.

### Actual behaviour
Spanish language/layout disappears and appears after some time (I can't calculate this because it's almost random). Also, there are no error warnings. Only english language/layout is available.

**AnySoftKeyboard Version**
AnySoftKeyboard Canary. Version 1.11.447, version-code 7407.
**Android OS version:**
Android 10.
**Device manufacturer and model:**
Umidigi F2.
**List of installed add-ons (like languages, or themes):**
- Spanish for AnySoftKeyboard.

**Comment by sslaia** [comment]
Does this occur only with Spanish? I've installed English, Indonesian, German, Nias and they are still there after restart.

**Comment by not-AMM** [comment]
I only speak english and spanish, so I don't know if this affects other languages. What happens is that I can't select the language as if it wasn't installed. This only happens if the app closes unexpectedly, like if I restart my phone forcefully. It just updated, so I'll check if this still happens.

**Comment by not-AMM** [comment]
Hey! I haven't had this problem in weeks, so I guess it has been solved. 

I'm not marking it as closed because I don't know if you want more information. If not, this now has been solved. Thank you!:)
