### ISSUE TITLE
I am new user and have a little problem :)

### ISSUE THREAD

**Issue by mfascioglu** [AnySoftKeyboard/AnySoftKeyboard#3341]
Hi, Turkish QWERTY keyboard is looking like this (right). But it is wrong.
![_20220504_165933.JPG](https://user-images.githubusercontent.com/104912991/166703083-e75be6c0-1341-49c4-bd67-f08292d85805.JPG)

Its must be like this. Can you fix this problem?
![_20220504_172358.JPG](https://user-images.githubusercontent.com/104912991/166703825-3074cc37-67e0-477c-a276-3ac665e3e8c0.JPG)

Thanks :)

**Comment by alchemiker** [comment]
You can set in the settings your language for suggestions and autocorrect to Turkish and the layout to English, then you should get what you want.

**Comment by mfascioglu** [comment]
> You can set in the settings your language for suggestions and autocorrect to Turkish and the layout to English, then you should get what you want.

Yes im using already but, English keyboard does not have caped letters(ğ, ş, ı). This is big problem for Turkish users.

**Comment by menny** [comment]
oh.. that's a weird bug. Let me try to locate that issue

**Comment by menny** [comment]
I think [this](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3351) will fix the issue. But, how will we test this? Can you install a testing version?

**Comment by mfascioglu** [comment]
> I think [this](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3351) will fix the issue. But, how will we test this? Can you install a testing version?

Sorry for late. Thanks, i can try but i do not know where is the test version? Im only user, do not developer :)

**Comment by Kiyoshime** [comment]
I solved it. I used Apkeditor and changed xml codes of turkish_withoutaccented.xml file to default QWERTY keyboard and added the turkish words to pop-ups.(ö,ü,ı,ş,ğ)

**Comment by menny** [comment]
Thanks for verifying
