### ISSUE TITLE
Space in the middle of the keyboard

### ISSUE THREAD

**Issue by febishine** [AnySoftKeyboard/AnySoftKeyboard#3347]
### Steps to reproduce
1.There's a space between letters in the middle of the keyboard 

### Expected behaviour
 Keys should be nearby in the keyboard 

### Actual behaviour
<!--
The keys in the middle are separated by a void

**Android OS version: 11

**Device manufacturer and model: Xiaomi, Redmi Note 9

**List of installed add-ons (like languages, or themes): None

**Comment by sslaia** [comment]
I still don't understand what exactly is the problem. But I guess, the xml layout file is somehow messed up. So it's worth to check that source code of the keyboard layout.
With which language layout does this occur?
