### ISSUE TITLE
AnySoftKeyboard build error in Android studio!

### ISSUE THREAD

**Issue by alenappo** [AnySoftKeyboard/AnySoftKeyboard#3354]
### Discussed in https://github.com/AnySoftKeyboard/AnySoftKeyboard/discussions/2603

<div type='discussions-op-text'>

<sup>Originally posted by **GoRaN909** December 21, 2020</sup>
Hello, 

How to fix this error in Parser.java when trying to build the project in Android Studio the master code is not import in latest version of Android studio and Java 11, Please help me how to fix that Error.

[![Screenshot-2020-12-21-185522.png](https://i.postimg.cc/y8KvxCgd/Screenshot-2020-12-21-185522.png)](https://postimg.cc/kBjxYZy3)</div>

**Comment by menny** [comment]
This should be fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3356
