### ISSUE TITLE
Battery Saver (Feature Request/help)

### ISSUE THREAD

**Issue by Disaster2life** [AnySoftKeyboard/AnySoftKeyboard#3367]
Hey I recently started using the keyboard, and I love it, but I have one really big issue with it, I always use my phone with the power saving mode on to preserve my battery life, but the software sees that and even though my actual battery level might be 70% it still turns off the auto correct feature, which I heavily rely on due to my typing skills being trash with a touchscreen, I tried finding how to change this behavior in the app but I couldn't find anything, any help? I really don't want to switch away from ASK but it really is a make or break thing for me

**Comment by meatspinner** [comment]
Adding to this, whenever the phone battery gets low (15% in my case) the auto-correct gets turned off. I think an option to disable this behavior should be included.

**Comment by menny** [comment]
You can config Power Saving in the settings app.
UI->Effects and experience->Power Saving settings


 ![Screenshot_20220520-202223_AnySoftKeyboard Dev.png](https://user-images.githubusercontent.com/481272/169626838-a7150720-f346-474e-8734-e48afdd7fc4e.png)

**Comment by meatspinner** [comment]
Damn, I don't know how I never noticed that option. Thanks.

**Comment by Disaster2life** [comment]
Apologies, didnt see that option

**Comment by menny** [comment]
Well... the settings app is a mess at the moment, i can see how one misses it

**Comment by ph1248** [comment]
Hello,

I'm sorry, but I cant find this setting in the app. Is it still availavle in the newest release?
