### ISSUE TITLE
Import backup to restore

### ISSUE THREAD

**Issue by jswetzen** [AnySoftKeyboard/AnySoftKeyboard#3403]
### Steps to reproduce
1. Restore backup -> choose custom path
2. Select any backup file outside of Android/data/com.menny.anysoftkeyboard/files

### Expected behaviour
Import succeeds

### Actual behaviour
Import fails, no such file. It seems I can see the file but AnySoftKeyboard has no right to read it. 

**Android OS version:**
/e/OS, based on Android 11

**Device manufacturer and model:**
Fairphone 4

**List of installed add-ons (like languages, or themes):**
Swedish language addon

**Comment by jswetzen** [comment]
Version 1.11.7137
-------- Originalmeddelande --------
På 13 juni 2022 19:27, Menny Even Danan skrev:

**Comment by menny** [comment]
I don't think we released "Version 1.11.7137" yet.
We have `1.11.177` in production and `1.11.521` in alpha/beta channels.

**Comment by menny** [comment]
This issue was solved with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3276
It will be available in the next release.

**Comment by rubaboo** [comment]
Sorry but when's the next release? I cannot import my settings.

**Comment by nazar-pc** [comment]
@menny is it you or someone else who is releasing on F-Droid? I hit the same issue and the version on F-Droid is over 1 year old.

**Comment by menny** [comment]
Anyone can set up a new release in fdroid. The process is pretty simple over there

**Comment by nazar-pc** [comment]
I'm personally very far from Android development. Will you have time to do that in the nearest future?

**Comment by doodhout** [comment]
Current workaround:

1. in anysoftkeyboard, make a backup to the default path (i.e. not a custom path), it will show you where the backup file is saved
2. use a file manager to locate this file
3. replace this newly created backup file with the backup you want to restore (even the filename has to be identical!)

**Comment by xeruf** [comment]
except I cannot access this path as my phone is unrooted atm... still waiting on the F-Droid update, come on why do you prioritise big tech?

**Comment by doodhout** [comment]
No, this path is available on unrooted phones. Try it, I just did and it works.

**Comment by xeruf** [comment]
I tried it on my phone which is on Android 10 and could not figure it out.
Just saw there has not been any release in almost two years?
Is this project dying?
