### ISSUE TITLE
Add þ to default english layout

### ISSUE THREAD

**Issue by KSPAtlas** [AnySoftKeyboard/AnySoftKeyboard#3406]
The default English layout is useful as a generic Latin/Greek keyboard, but it is missing þ. Þ is actually sometimes used in English by people who want to revive the letter.

**Comment by menny** [comment]
Okay, sure. Where should it be positioned?

**Comment by KSPAtlas** [comment]
Either on T or on P (Altgr-P produces thorn on many computer keyboards)

**Comment by sslaia** [comment]
Alternatively put it as a popup character to either p or s on the layout.

**Comment by KSPAtlas** [comment]
Thats what I was saying.

**Comment by menny** [comment]
@sslaia would you mind creating a PR that adds that to the P popup?

**Comment by sslaia** [comment]
> @sslaia would you mind creating a PR that adds that to the P popup?

Done. PR submitted.

**Comment by menny** [comment]
Fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3408
