### ISSUE TITLE
Switch keyboard (Feature Request/help)

### ISSUE THREAD

**Issue by Extroonie** [AnySoftKeyboard/AnySoftKeyboard#3424]
### Steps to reproduce
1. Activate AnySoftKeyboard from languages and input and a few additional keyboards (like Gboard).
2.  Switch active keyboard to AnySoftKeyboard (from the app).
3. Long press the space bar on AnySoftKeyboard.

### Expected behaviour
 It should show other available keyboards so you can switch between them easily.

### Actual behaviour
 Nothing happens.

**Android OS version:**
11
**Device manufacturer and model:**
Vivo Y21
**List of installed add-ons (like languages, or themes):**
None

**Comment by glemco** [comment]
Late reply, but maybe someone is still wondering this. I don't think ASK can do that from the space bar, however you can get to that menu long pressing enter and tapping on _change input method_. Alternatively most android navbars show a button just for this (on mine it's visible on the bottom right corner when the keyboard is active).

**Comment by domportera** [comment]
@extroonie AnySoftKeyboard actually can do this! how you access this sub menu depends on your keyboard layout, but i recorded this video to demonstrate how it works

https://youtube.com/shorts/_EHmF9drp9g

To access this menu with ease, you can attach it to a keyboard gesture in the Gestures settings. The particular menu is called the "utility keyboard"

**Comment by stephan-dev** [comment]
@domportera Wow, thanks for the video, the item I had to tap was right under my eyes (like we say in french, meaning in plain sight), but I thought I had tried everything, and that this item was not available for me. It was!
