### ISSUE TITLE
Providing updated dictionaries

### ISSUE THREAD

**Issue by smarquespt** [AnySoftKeyboard/AnySoftKeyboard#343]
Hi menny,

I´m using anysoftkeyboard as my main keyboard app but I notice that langpack for Portuguese is extremely outdated. I´ve already read your wiki in googlecode but the way to create a language pack is out of my skills. But I can provide you the sources for an updated package. Are you interested?

**Comment by smarquespt** [comment]
No answer since april 30 so I guess that there is no interest in updated dictionaries.

**Comment by menny** [comment]
@smarquespt , I'm really sorry, I completely drop the ball here.

I can update the package, but what is the sources you can provide?

**Comment by smarquespt** [comment]
Hi,

You can grab any one you want in here: http://natura.di.uminho.pt/wiki/doku.php?id=dicionarios:main

**Comment by menny** [comment]
What about frequencies (or word popularity)?

**Comment by smarquespt** [comment]
What do you mean? I don´t understand.

**Comment by homersimpsons** [comment]
@smarquespt next word function need words frequencies to provide a better suggestion, then if you haven't got frequency, dictonary can't be update.
