### ISSUE TITLE
UK currency symbol missing

### ISSUE THREAD

**Issue by Cool4catz** [AnySoftKeyboard/AnySoftKeyboard#3463]
Hi all,
I have downloaded and installed AnySoftKeyboard for the English language on my phone, but there isn't a UK currency 'pound'' symbol.
Please could someone tell me if there is a version of AnySoftKeyboard including the UK currency symbol?
Thanks.

**Comment by WPettersson** [comment]
I'm not sure I'll have time to check this myself, so if I don't, I think the solution is to create `ime/app/src/main/res/values-en-rgb/currency_data.xml` with UK (Great Britain) specific currency data. Hopefully I can test this in the next few days, once I have access to my android development suite again.
