### ISSUE TITLE
Auto correct turns 'I' into 'IN'

### ISSUE THREAD

**Issue by deeeseee** [AnySoftKeyboard/AnySoftKeyboard#3465]
### Steps to reproduce
1. While typing, I try to type the word "I".
2. Auto-correct auto-selects the word "IN" unless I manually select "I" from the list of options above the keyboard.
3. My "Next word aggresiveness" is set to Minimal, and I've even tried to "Clear next-word data".

### Expected behaviour
When I type "I", it should leave it as it is.

### Actual behaviour
ASK auto-correct auto-selects the word "IN" unless I manually select "I" from the list of options above the keyboard.

**Android OS version:** Android 11, One UI version 3.1

**Device manufacturer and model:** Samsung Galaxy S10e

**List of installed add-ons (like languages, or themes):** None

**Comment by deeeseee** [comment]
Any tips or advice to fix this? Is there a way to manually delete certain words from the built-in dictionary?

**Comment by Noitarud** [comment]
Did it begin working well? Perhaps you could reinstall…

**Comment by menny** [comment]
@deeeseee , can you provide more information about this? I can not seem to reproduce this bug.
