### ISSUE TITLE
Beta / Canary version 1.11.582 crashes when set as default keyboard

### ISSUE THREAD

**Issue by voldemarz** [AnySoftKeyboard/AnySoftKeyboard#3472]
### Steps to reproduce
1. Set AnySoftKeyboard as default in Android settings

### Expected behaviour
Becomes default keyboard

### Actual behaviour
"Oops, didn't see that coming" notification appears. 

It appears that this started after an earlier crash due to some other reason.

**Android OS version:**
Android 12

**Device manufacturer and model:**
Samsung Galaxy s10e

**List of installed add-ons (like languages, or themes):**
Latvian language

Crash report here [https://pastebin.com/KnX9RFu2](https://pastebin.com/KnX9RFu2)

**Comment by menny** [comment]
Can you attach the crash log?

**Comment by voldemarz** [comment]
> Can you attach the crash log?

Where can I get it?

**Comment by menny** [comment]
When you get that crash notification you have an option to send it. Maybe email that or save to your device first and then attach to this ticket

**Comment by voldemarz** [comment]
I already added that, was linked in the first post. This https://pastebin.com/KnX9RFu2[https://pastebin.com/KnX9RFu2](https://pastebin.com/KnX9RFu2)

**Comment by menny** [comment]
Unfortunately, the provided logs do not give meaningful information about this crash. If I understand correctly, I don't think the app can provide any such details.

I've bumped a few stuff with the code and there is a new canary available (shortly). Please make sure you have version 1.11.598 atleast.

**Comment by voldemarz** [comment]
I reinstalled the app and now keyboard works fine. I have 1.11.582, don't have update offered in the Play Store.

**Comment by menny** [comment]
Okay. I'll close this for now, and please report back if you see this crash with the new version
