### ISSUE TITLE
get rid of automatic  word corrections 

### ISSUE THREAD

**Issue by skyerjoe** [AnySoftKeyboard/AnySoftKeyboard#3482]
### Steps to reproduce
1. Get rid of automatic word correction
2. Just typing this Text Here
3.

### Expected behaviour
 just type word and See word Suggestions in the upper line but no automatic correction from the words if ure typing 

### Actual behaviour

**Android OS version:**
MUI Global 12.5.1 |11 RKQ1.200826.002
**Device manufacturer and model:**
mi9t pro 

**List of installed add-ons (like languages, or themes):**
German, English , Keyboard: Terminal

**Comment by menny** [comment]
which settings have you set to disable "automatic word correction"?

**Comment by Noitarud** [comment]
I agree. I just had enough of it too (suggestions still okay). My peeves are that I can notice the wrong correction after two-plus characters pressed (space and first character of next word; sometimes it insists on a significant change too which is only sometimes from extending a word). I do not know what kind of interface will help for longer times to notice, maybe word change history?

As for reconciliation, I would like the keyboard to change shade to indicate it will change and a more intense change if it was going to completely change the word. A possible alternative to that (for right-aligned kb only) is to list the results from right to left so the green one will appear (if it appears, #3364) above the keyboard (this is a tablet issue).

I couldn't find any option to disable other than to increase minimum word length.

**Comment by skyerjoe** [comment]
> which settings have you set to disable "automatic word correction"?

Everything which possible but its not gone , suprisingly if i use the terminal design i had almost no corrections so far. 

best regards

**Comment by Noitarud** [comment]
You can set it to not suggest, but you cannot set it to not correct.

**Comment by skyerjoe** [comment]
I have to correct myself i u deactivate every Autoselection and Helpers, u can type almost without any autocorrection but then the app brings no benefit and i'll stick with an other one. 

best regards
