### ISSUE TITLE
Cant create Backup in own folder

### ISSUE THREAD

**Issue by neodata83** [AnySoftKeyboard/AnySoftKeyboard#3505]
### Steps to reproduce
1. Select your own folder for backup
2.
3.

### Expected behaviour

I can choose a backup folder

### Actual behaviour

The Programm create a file with 0 Byte and gives and error. "Failure to access storage" The normal backup works but i cant get the file because android blocks the access to the folder by default

**Android OS version:**

13

**Device manufacturer and model:**

pixel 4a

**List of installed add-ons (like languages, or themes):**

german

**Comment by RhysSpellbinder** [comment]
I have the same problem. It is not possible to read or to write in the own order. Error Message:
**"...open failed: ENOENT (no such file or directory)"**"...open failed: ENOENT (no such file or directory)"

So I can not get my preferences from another phone because in this phone I can not write to android/data/...

Is it possible to request the access to file write/read from android?

Android 13, Google Pixel 6 pro

**Comment by menny** [comment]
This is already fixed in the BETA version. Unfortunately, it is not available in FDroid.

I'm not sure when I'll be able to release a new version as I am hunting down a typing bug

**Comment by RhysSpellbinder** [comment]
Thank you for fixing this bug. 
Is it possible to download the APK from you Homepage?

**Comment by menny** [comment]
I can point you to an APK, but since you have installed from Fdroid the
signature will mismatch. I do not have the signature file they use over
there.
Basically, this means you can not install over the fdroid APK with anything
other than theirs

**Comment by RhysSpellbinder** [comment]
A link to the APK would be nice. I can uninstall the F-Droid version before.

**Comment by menny** [comment]
You can take the latest APK from the latest "imeMain_alpha_100" action. For example, this: https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/3249386928
There is an `apks` archive in the _Atrifacts_ section on that page.

**Comment by menny** [comment]
Please note, you might lose your backup if you uninstall the app!

**Comment by menny** [comment]
It is, sometimes, possible to retrieve the file from the app's private data folder using `adb pull` or even an advanced file browser app
