### ISSUE TITLE
[Feature Request] Include the Masculine (º) and Feminine (ª) Ordinal Indicator

### ISSUE THREAD

**Issue by hugoxrosa** [AnySoftKeyboard/AnySoftKeyboard#3507]
Could you add the diacritics Masculine (º) and Feminine (ª) Ordinal Indicator?

They are used in Portuguese to writing ordinal numbers, I think they are also used in Spanish and Italian (not sure).
The English 1st, 2nd and 3rd in Portuguese are written as 1.º, 2.º and 3.º (masc.) and also 1.ª, 2.ª and 3.ª (fem.).

The Unicode for they are:
 - U+00AA - Feminine Ordinal Indicator - ª
 - U+00BA - Masculine Ordinal Indicator - º
 
Others keyboard place those symbols in the submenu of letters a and o.
But, I think it maybe better placed on the numeric keyboard, like de ° (Degree Sign) that is placed on 0 (zero) submenu, because they are used to write numbers and not words.

**Comment by menny** [comment]
I'll those to all `a` and `o` long-press options.
Regarding the second option you mentioned, should both ª and º be in the long-press options of `0`?

**Comment by moshpirit** [comment]
I can confirm that they exist in the Spanish keyboard already. You can access to them by pressing A and O .

**Comment by menny** [comment]
I can confirm these are set up for:
- [Portuguese with symbols](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/addons/languages/portuguese/pack/src/main/res/xml/qwerty_with_symbols.xml#L36)
- [Brazilian](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/addons/languages/brazilian/pack/src/main/res/xml/brazilian_qwerty_with_symbols.xml#L21)
- [Spanish[(https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/addons/languages/spain/pack/src/main/res/xml/es_qwerty.xml#L19)
- and a few more

I'll add those characters to:
- Spanish with symbols (two layouts)
- all English layouts (10 layouts)

**Comment by menny** [comment]
what about adding those to the symbols layout? @hugoxrosa you mentioned that it makes sense to have them in the numbers submenu (popup). On which keys?

**Comment by menny** [comment]
So far, this is where I am with the change: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3515/files
Let me know if this makes sense
