### ISSUE TITLE
Merge Belarusian layout

### ISSUE THREAD

**Issue by andrewshadura** [AnySoftKeyboard/AnySoftKeyboard#351]
Please add Belarusian layouts (Cyrillic and Latin) from [alex73's repository](/alex73/AnySoftKeyboardLanguagePackBelarusian). They currently lack a dictionary, but it can be generated from `hunspell-be` package (the following is for Debian):

``` sh
apt-get install hunspell-be hunspell-tools
unmunch /usr/share/hunspell/be_BY.dic /usr/share/hunspell/be_BY.aff > be_BY.wordlist
```

**Comment by AnXh3L0** [comment]
The Belarusian language pack (and layout) are now in ASK. Closing this issue.
