### ISSUE TITLE
No space swap on punctuation coming from popup

### ISSUE THREAD

**Issue by aprunai** [AnySoftKeyboard/AnySoftKeyboard#3525]
Hello, first of all I'd like to say 'thanks' for this wonderful keyboard! Its levels of usefulness and customization are unmatched by any other, and I cannot wait to see what new features and improvements are coming in the future! ('Space' and 'Delete' swiping to move/delete, wink wink nudge nudge ;) )

Anyways I found this strange behaviour which might be a bug: punctuation chosen by moving within period popup menu, such as colon, semicolon, comma, exclamation mark - but NOT question mark, which is already selected when the popup opens - doesn't swap with space. Comma key on the left side of space key works fine.
It's as if moving within the popup menu was seen by the software as 'breaking' the automatic space swap sequence.

### Steps to reproduce
1. Type the beginning of a word and choose ASK's suggestion, e.g. buil -> building(automatic space)
2. Long press period key and choose any from the following: colon, semicolon, comma, exclamation mark.

### Expected behaviour

All punctuation symbols, included those from popup menus, should be swapped with automatic space.

### Actual behaviour

Punctuation which requires opening the period popup menu and choosing a symbol won't be swapped.

**Android OS version:** 8.0.0

**Device manufacturer and model:** Huawei P10 Lite

**List of installed add-ons (like languages, or themes):** Languages: Italian, English; keyboards chosen: Italian QWERTY with symbols, English QWERTY with symbols

**Comment by menny** [comment]
thanks for reporting

**Comment by aprunai** [comment]
Thanks to you for your work!
