### ISSUE TITLE
decouple keyboard layout and language

### ISSUE THREAD

**Issue by monfortm** [AnySoftKeyboard/AnySoftKeyboard#3528]
Hello,

Thanks for the great keyboard!

It's not so much of an issue and more of a question/request:

Is it possible to decouple the keyboard layout from the language+autocorrect?

I am very happy with the QWERTY layout - and I want to keep it at all times - but would like to benefit from different language specific (auto)correction, depending on the language I'm writing in.

Currently, to change the language, I need to change the layout.

Is decoupling already possible but I overlooked the appropriate configuration? Or it's not possible, then I would like to hear how we can make it happen.

Cheers,
M

**Comment by menny** [comment]
it is possible to _attach_ different dictionaries to a layout: long-press the ENTER key and select `Override default dictionary` in the popup options menu. Here you can attach any of the dictionaries currently installed on your device. Does this work for you?

**Comment by monfortm** [comment]
Thanks I could indeed do this! Never knew before. I will use the feature and come back if this does not work but I think this is exactly what I needed! Cheers!
