### ISSUE TITLE
Random red flashing on main build?

### ISSUE THREAD

**Issue by ipkpjersi** [AnySoftKeyboard/AnySoftKeyboard#3554]
## Steps to reproduce
Option 1:
1. Build then install an APK from the main branch.
1. Start typing something then type like a 5 or a %, a red flash around the border of the screen occurs.

Option 2:
1. Build then install an APK from the main branch.
2. Open AnySoftKeyboard Dev settings.
3. Click Gestures, a red flash around the border of the screen occurs.

### Expected behaviour
No red flashing border

### Actual behaviour
Red flashing border

**Android OS version:**
Android 11 (OxygenOS 11)

**Device manufacturer and model:**
OnePlus 7 Pro

**List of installed add-ons (like languages, or themes):** 
None

Here's a video of the flashing: https://streamable.com/r6waau

What could be causing this? Could it be capturing a debug log or screenshot or logging an error or something similar? I can't seem to find any mention anywhere what the red flashing could be.

Tagging @menny for visibility

**Comment by menny** [comment]
This happening only in dev builds. It is used to notify the developer that something is running where it shouldn't. It is harmless, at the moment.
See https://developer.android.com/reference/android/os/StrictMode

**Comment by ipkpjersi** [comment]
Ah that's good to know, looks like here is how to disable the fairly annoying red flash as well: https://www.droidviews.com/how-to-fix-the-red-frameborder-around-the-screen-of-android-devices/

Cheers.
