### ISSUE TITLE
Telegram, black suggestion bar in landscape

### ISSUE THREAD

**Issue by manolollr** [AnySoftKeyboard/AnySoftKeyboard#356]
Sorry for my English.

Telegram with ASK in portrait works well:

![screenshot_2014-07-07-13-35-20](https://cloud.githubusercontent.com/assets/8089376/3494713/6347450e-05cb-11e4-9882-b260f737f0dc.png)

But in landscape there is a black bar instead suggestion bar.

![screenshot_2014-07-07-13-35-41](https://cloud.githubusercontent.com/assets/8089376/3494733/d4d43d62-05cb-11e4-8a6c-fa38fc4d709a.png)

This only fails with Telegram. Is there any workaround? Where is the problem, with Telegram or with ASK?

Thank you.

**Comment by menny** [comment]
@manolollr , sorry for the late reply.
Does this happen only with Telegram?

**Comment by manolollr** [comment]
Yes.

**Comment by menny** [comment]
Got it.
