### ISSUE TITLE
Czech layout is missing on F-Droid

### ISSUE THREAD

**Issue by jkufner** [AnySoftKeyboard/AnySoftKeyboard#359]
Hello,
I cannot find Czech layout on F-Droid for this totally awesome keyboard, could you please make sure it is there together with other language packs? I found it only at https://play.google.com/store/apps/details?id=org.herrlado.ask.languagepack.czech

Thank you!

**Comment by homersimpsons** [comment]
That is normal, it is not menny that published it on play store.
This ticket could be close
It would be better for you to send an email to the original author of this layout

**Comment by ArenaL5** [comment]
Please close this issue, Czech keyboard has been long on F-Droid (even if we're waiting for it to update it again).

**Comment by AnXh3L0** [comment]
Closing this issue as the pack is on F-Droid.
