### ISSUE TITLE
DavidBowieEasterEgg() now points to a dead link

### ISSUE THREAD

**Issue by Andy3153** [AnySoftKeyboard/AnySoftKeyboard#3599]
### Steps to reproduce
1. Get the easter egg
2. Try to click the 'play button'

### Expected behaviour
A Spotify playlist opens.

### Actual behaviour
The button points to a dead link.

### My note
This was pretty cool to find. In my 2-3 years of using this keyboard, I've never stumbled across either of the two easter eggs. But when I did, and I realised the link was dead, I rushed here to find the code that did it. If I knew what playlist the link was pointed at, this would've been a pull request fixing it. I love easter eggs.

**Comment by menny** [comment]
Oh, man!
Thanks for reporting.
It should have directed you to https://open.spotify.com/playlist/37i9dQZF1DZ06evO0auErC?si=23d2eb833d8048c3
