### ISSUE TITLE
Punctuation swapped with space while autocorrect features disabled

### ISSUE THREAD

**Issue by Soundtoxin** [AnySoftKeyboard/AnySoftKeyboard#3600]
### Steps to reproduce
1. Write some words, make a space, add a symbol
2. "words words !" 
3. becomes "words words! "

### Expected behaviour

keep what I wrote 
### Actual behaviour

becomes "words words! "

**Android OS version:**
12
**Device manufacturer and model:**
OnePlus 8T with LineageOS
**List of installed add-ons (like languages, or themes):**

This is very annoying, I want raw inputs for things like terminal commands, irc chatting, ddg searches with bangs. I disabled all the smart stuff I could, as far as I know.

**Comment by alchemiker** [comment]
Hi @Soundtoxin , it looks like one smart stuff escaped your notice, for there is indeed a setting for that : ) 

I also hate this particular autocorrect feature (look at the way I write smileys in the line above and you will see why)
Go to: 🌐 Language > 🎚️ Optimization and more > 4th option:  swap punctuation and space. Un-check this option, and you will have peace from this feature.

**Comment by Soundtoxin** [comment]
You're right! Thank you very much ! ! !
