### ISSUE TITLE
Hide smiley key

### ISSUE THREAD

**Issue by rosshadden** [AnySoftKeyboard/AnySoftKeyboard#364]
As far as I can tell, there is not an option to hide the smiley key. For those of us who do not use this or other "quick texts", this key is annoying and taking up precious real estate. Can there be a setting added for he bottom bar that removes this?

**Comment by AnXh3L0** [comment]
Many layouts have been added and it's now possible to use a  layout that doesn't have the smiley. Closing the issue.
