### ISSUE TITLE
[Feature request] disable top line

### ISSUE THREAD

**Issue by FadeFx** [AnySoftKeyboard/AnySoftKeyboard#3650]
As I and probably also many other people have all options available in the top row available in other ways, it would be nice if we could disable that row and get higher keys instead.
![Screenshot_20230226-174353](https://user-images.githubusercontent.com/41125748/221424108-1a7010e4-5995-4c53-895c-4f6177edde7d.png)

**Comment by alchemiker** [comment]
Hello @FadeFx this behaviour can be turned off via the settings: 🎨 > Optimization and more > Top row (might be called different on your device, mine isn't english). I have the "no top row" option selected. 

If you want to change the height of the keyboard in general, you can change it from 🎨 > ⌨️ choose and configure keyboard layouts > ⚙️ (in the upper right corner) > and there the last two setting in the list, to change the height of the keyboard in vertical and horizontal layout. I have set the value `1.25` for vertical layout.

**Comment by FadeFx** [comment]
Thanks, I found erverything now, its a bit confusing to find all the settings in the beginning...
