### ISSUE TITLE
Build language pack, icon generation build error (Windows)

### ISSUE THREAD

**Issue by Cyberman-tM** [AnySoftKeyboard/AnySoftKeyboard#3709]
I'm trying to build a new language pack, according to https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/addons/CONTRIBUTING.md .
So far it worked, but when I want to generate the icons from the svg file, I get errors:

>F:\AnySoftKeyboard-main\AnySoftKeyboard-main>gradlew :addons:languages:klingon:pack:generateLanguagePackIcons :addons:languages:klingon:apk:generateStoreLogoIcon
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Could not determine the dependencies of null.
>> Could not resolve all task dependencies for configuration ':buildSrc:buildScriptClasspath'.
>   > Could not resolve project :buildSrc.
>     Required by:
>         project :buildSrc
>      > No matching variant of project :buildSrc was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1.1' but:
>          - Variant 'apiElements' capability :buildSrc:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
>              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 8
>              - Other compatible attribute:
>                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
>          - Variant 'mainSourceElements' capability :buildSrc:unspecified declares a component, and its dependencies declared externally:
>              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
>              - Other compatible attributes:
>                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
>                  - Doesn't say anything about its elements (required them packaged as a jar)
>                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
>                  - Doesn't say anything about its usage (required runtime)
>          - Variant 'runtimeElements' capability :buildSrc:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
>              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 8
>              - Other compatible attribute:
>                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
>          - Variant 'testResultsElementsForTest' capability :buildSrc:unspecified:
>              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
>              - Other compatible attributes:
>                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
>                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
>                  - Doesn't say anything about its elements (required them packaged as a jar)
>                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.1.1')
>                  - Doesn't say anything about its usage (required runtime)
>
>* Try:
>> Run with --stacktrace option to get the stack trace.
>> Run with --info or --debug option to get more log output.
>> Run with --scan to get full insights.
>
>* Get more help at https://help.gradle.org
>
>BUILD FAILED in 1s

and I'm not sure what the actual problem is - is it really a difference in java version? Or did I miss some step and accidently broke something?

Working on Windows, I installed ImageMagick

**Comment by menny** [comment]
Seems like a java version issue. You'll need Java 17 installed and set as the jdk for this project

**Comment by Cyberman-tM** [comment]
Indeed, that was the issue. I was convinced I had the right java version installed, but probably not the JDK.

Thank you!
