### ISSUE TITLE
Add space to numbers keypad

### ISSUE THREAD

**Issue by breversa** [AnySoftKeyboard/AnySoftKeyboard#372]
Hi,

Thanks for adding dot to the numbers keypad (very usefull to input IP addresses !), but it'd be even better to be able to input space as well, wich comes in very handy when inputting phone numbers, for instance (e.g. +33 1 23 45 67 89)

Maybe as a pop-up on the dot key ?

That space should however ignore the "space gets back to the letters keyboard" option though. Otherwise, it'd be of little value.

**Comment by breversa** [comment]
It's most useful when I need to text a phone number to someone : the format
I most often use is "01 23 45 67 89" (= national french format).

To do so, I have to input 01, then switch back to the letters/symbols
layout to input space, then switch to the symbols or numbers layout again…
five times, which is tedious.
(Note : I have the "space switches back to letters layout" option activated)

I'd love to be able to switch once to the numbers layout, type the numbers
AND spaces, then switch back to the letters layout to resume my message.

Is that clearer ?

2014-12-31 21:26 GMT+01:00 Menny Even Danan <notifications@github.com>:

**Comment by menny** [comment]
Try this out: https://drive.google.com/open?id=0B_4L3UCZ8dDyNjhtYkRRTjJyOWM&authuser=0

**Comment by breversa** [comment]
I gave it a try and it's indeed very useful !

However, I had to disable "space brings back letters layout" for it to be
really useable. Would it be possible that space on the numbers layout (and
only there) ignores that option even if it is activated ?

2015-01-13 4:07 GMT+01:00 Menny Even Danan <notifications@github.com>:
