### ISSUE TITLE
Vertically shrinking keyboard (bug or feature?)

### ISSUE THREAD

**Issue by Criseum** [AnySoftKeyboard/AnySoftKeyboard#3786]
### Steps to reproduce

Not sure how to reproduce issue

### Expected behaviour
Normal keyboard height is roughly 9/20 screen space at a 1.1 portrait height factor

### Actual behaviour
Keyboard shrunk vertically to 1/3 screen space, keys are now square and square instead of horizontal and are more typo-prone

**Android OS version:**
MIUI Global 14.0.14
**Device manufacturer and model:**
Xiaomi 12 Pro (zeus)
**List of installed add-ons (like languages, or themes):**
Using Yochees Dark, English Qwerty Latin

**Comment by twoexem** [comment]
I have this issue too. Same theme, running Fairphone OS (almost stock Android 13)

**Comment by menny** [comment]
I've seen this, too. But, I can not reproduce it. Not really sure where is its source. Whenever you encounter this, please report any info you can.

**Comment by twoexem** [comment]
Switching between two keyboards seems to temporarily fix this issue.

**Comment by twoexem** [comment]
Also, this bug only appeared when my Fairphone FP4 got updated to Android 13.

**Comment by menny** [comment]
Yes, I noticed the same. But, I still have not found the cause

**Comment by SC1040-TS2** [comment]
> Yes, I noticed the same. But, I still have not found the cause

https://developer.android.com/about/versions/13/summary
Here is a summary of all known changes that affect developers regarding Android 13 and SDKVersion 33, if that helps in understanding what about layout rendering was broken.

I have yet to replicate it as of recently, save for one thing: DoorDash app notification handling is notorious for breaking the UI in Android 13 if enabled. Keyboard layout sometimes included. So it is turned off for that app.

Current 1.12 Beta builds of AnySoftKeyboard otherwise have yet to show this problem again, but I have made note of how its own notification service is likely broken due to missing some features in implementation. See my prior issue for a reply alluding to that, but I may also elaborate on it further with a new issue on how to Unbreak the Notifications permission service.

**Comment by twoexem** [comment]
It seems to me that this bug occurs sometimes when the phone screen changes orientation while the keyboard is on-screen.

**Comment by menny** [comment]
I think you found something here!

**Comment by menny** [comment]
Can others verify this on their devices?

**Comment by ferromint** [comment]
@twoexem
> It seems to me that this bug occurs sometimes when the phone screen changes orientation while the keyboard is on-screen.

@menny
> Can others verify this on their devices?

Yes, I can confirm this behavior, with an emphasis on the word _sometimes_.

Rotating the phone by 90 degrees from portrait into landscape and back again with the keyboard being visible, sometimes changes its height. It becomes smaller more often than larger.

I tried rotating it a couple of times and the behavior seems quite random:

| i | orientation | height |-| i  | orientation | height |-| i  | orientation | height |
| - | ----------- | ------ |-| -- | ----------- | ------ |-| -- | ----------- | ------ |
| 0 | portrait    | normal |-| 10 | portrait    | normal |-| 20 | portrait    | small  |
| 1 | landscape   | normal |-| 11 | landscape   | normal |-| 21 | landscape   | small  |
| 2 | portrait    | normal |-| 12 | portrait    | normal |-| 22 | portrait    | normal |
| 3 | landscape   | large  |-| 13 | landscape   | normal |-| 23 | landscape   | normal |
| 4 | portrait    | normal |-| 14 | portrait    | normal |-| 24 | portrait    | normal |
| 5 | landscape   | normal |-| 15 | landscape   | normal |-| 25 | landscape   | large  |
| 6 | portrait    | normal |-| 16 | portrait    | small  |-| 26 | portrait    | small  |
| 7 | landscape   | normal |-| 17 | landscape   | normal |-| 27 | landscape   | normal |
| 8 | portrait    | normal |-| 18 | portrait    | normal |-| 28 | portrait    | small  |
| 9 | landscape   | normal |-| 19 | landscape   | small  |-| 29 | landscape   | normal |

**Comment by AeonTicker** [comment]
> It seems to me that this bug occurs sometimes when the phone screen changes orientation while the keyboard is on-screen.

works now, thanks man
