### ISSUE TITLE
Play store version not downloadable

### ISSUE THREAD

**Issue by HenrikPoulsen** [AnySoftKeyboard/AnySoftKeyboard#3799]
### Steps to reproduce
1. Go to https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard
2.
3.

### Expected behaviour
Should be possible to download

### Actual behaviour
Cannot download due to being too old.
See screenshot
![Screenshot_20230929-153038](https://github.com/AnySoftKeyboard/AnySoftKeyboard/assets/472627/2e58b562-e74a-4dfe-8754-6613271b5303)

**Android OS version:** 13

**Device manufacturer and model:** Google Pixel 7a

**List of installed add-ons (like languages, or themes):** N/A

**Comment by DiWa51** [comment]
FTR, I've just installed it on Android 13 using F Droid (_actually this is the way I got to know this keyboard_)

**Comment by HenrikPoulsen** [comment]
As i noticed [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3683#issuecomment-1742925522) it's not installable for good reasons.
The app does not function correctly in at least android 13

**Comment by SC1040-TS2** [comment]
> As i noticed [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3683#issuecomment-1742925522) it's not installable for good reasons. The app does not function correctly in at least android 13

Are you able to corroborate this on the current 1.12 Beta version? Its manifest reports that it does in fact have a TargetSDKVersion of 33, corresponding to Android 13. It may not fully support Android 13, but is a start in confirming if that version mitigates this problem.

**Comment by HenrikPoulsen** [comment]
I can confirm that the 1.12 beta works. I managed to install it (had to do it from a computer and install it remotely for some reason, because it did not let me still on the phone, but it worked).
And that version resolves my comment in #3683 as well so I didn't get that warning anymore when enabling the keyboard

**Comment by SC1040-TS2** [comment]
> Great to hear.

Indeed. Though, obviously, much more work will need to be done to fully account for the newer TargetSDKVersion as well as the just-released Version 34 (Android 14), but that is what the Beta build version is for. Being bleeding edge and responding to things as they happen.

**Comment by menny** [comment]
Please keep reporting issues as you find them.

**Comment by Bar7788** [comment]
I am trying to install the anysoftKeyboard on Samsung S21 Ultra (Android 14) and I cannot find the app on google play...
Is there a way of using the Hebrew anysoftKeyboard on Android 14?

**Comment by pdimens** [comment]
![Screenshot_20240216-104003](https://github.com/AnySoftKeyboard/AnySoftKeyboard/assets/19176506/bd932a16-5501-4735-99d4-116a3b2f573f)
