### ISSUE TITLE
Support email still reports google bug reporting

### ISSUE THREAD

**Issue by ondrejj** [AnySoftKeyboard/AnySoftKeyboard#380]
A message from ask(at)evendanan.net still reports link to google bug reporting instead of github and is ignored. Please fix. Thank you.

**Comment by menny** [comment]
Fixed. Thanks for letting me know.
Please try the new automatic response

**Comment by ondrejj** [comment]
OK, link removed, but there is no link in new message. It was nice to have it.
Can you at least add direct link to bugtracking to http://anysoftkeyboard.github.io/ ?

**Comment by menny** [comment]
I have, didn't I? The automatic reply should look like this:
```
If you are having issues with installing and enabling AnySoftKeyboard, run the AnySoftKeyboard Settings app, or read our WiKi.

If you see boxes instead of letters, this is an Android bug, read here for details.

For general help, go to our support community.

If you want to report a bug, either reply to this email and describe the bug, or open an issue at our bug tracking web page.

Thanks.

http://anysoftkeyboard.github.io/
Donate if you like: http://s.evendanan.net/ask_donate

Thanks.
```

**Comment by ondrejj** [comment]
I don't see any direct link to bugtracking. There was one in previous message, but not in current.

**Comment by menny** [comment]
Ho, sorry, the HTML was striped. The real reply has "our bug tracking web page" as a link directing to Github's issues page.

**Comment by ondrejj** [comment]
I still use a terminal email clien named mutt, which prefer non-html messages, but if it's as you say, then it's OK.

**Comment by menny** [comment]
Plaintext-Hardcore, ah?
