### ISSUE TITLE
How to account for Granular Storage in Android 13+.

### ISSUE THREAD

**Issue by SC1040-TS2** [AnySoftKeyboard/AnySoftKeyboard#3808]
### Steps to reproduce
1. Known issue affecting 1.11. Was patched out in current 1.12 Beta versions until further notice.

### Expected behaviour
The Keyboard originally used the Global Storage permission to access files in the clipboard.

### Actual behaviour
As of Android 13, this behavior is broken and cannot be set with ease in AnySoftKeyboard version 1.11.x. The 1.12 Beta currently has this removed as a mitigation, but I am passing on official documentation for this as good measure, in the event it can be reimplemented alongside the Read Clipboard permission.
https://developer.android.com/about/versions/13/behavior-changes-13
Clipboard Behavior things: https://developer.android.com/develop/ui/views/touch-and-input/copy-paste
**Android OS version:**
Android 13.
**Device manufacturer and model:**
Sony Xperia 1 IV.
**List of installed add-ons (like languages, or themes):**
None beyond the default. Workman Keyboard layout and Yochees Dark theming are in use.

### Additional Notes.
This Issue may comprise redundant information that the developer is already well aware of. The intent of this Issue is to provide quick and direct reference to Google's documentation relative to these matters.

**Comment by menny** [comment]
This is great! thank you

**Comment by SC1040-TS2** [comment]
> This is great! thank you

Appreciated. Now you know.

Also, to make use of the Notifications permission correctly (also broken on newer devices), you will likely need to call Run Foreground Services to leverage it again.
https://developer.android.com/guide/components/foreground-services

**Comment by SC1040-TS2** [comment]
Additional note for @menny : To account for Scoped Storage precedents beginning in Android 11 (SDKVersion 30), the Write External Storage permission in the manifest must be replaced with Read External Storage.

Alternatively, using the Storage Access Framework or MediaStore API is advised by Google.

**Comment by menny** [comment]
Fixed in latest beta
