### ISSUE TITLE
add reverse cycle through alphabet keyboards

### ISSUE THREAD

**Issue by jensMF** [AnySoftKeyboard/AnySoftKeyboard#381]
I would realy appreciate to have the option to reverse cycle through alphaber keyboards. There is an option for next alphabet keyboard but not the other way round… Thanks for this great app!

**Comment by homersimpsons** [comment]
It is a good idea when you have got a lot of keyboards but is a lobby click on the button to switch keyboard would be OK or too long ?

**Comment by jensMF** [comment]
Excuse me, but I don't know what a lobby click is. But if zou mean the change keyboard button I have to say than I do not use it. So I would prefer to have it as an option for swiping. At the moment I change keyboards with swiping the spacebar right. And I would love to go back with swiping the spacebar left.

**Comment by homersimpsons** [comment]
Sorry, keyboard  correction, it was long click
