### ISSUE TITLE
key combination for emoticon

### ISSUE THREAD

**Issue by clo10** [AnySoftKeyboard/AnySoftKeyboard#382]
Hi, 
I am looking for the key combination corresponding for the emoticon displayed when you only type on the "emoticon-key". I entered this symbol in the screenlock password but when restarting my android, anysoftkeyboard has been uninstalled or someone made a bad joke. 
I have now only the standard keyboard available and are unable to enter the password unless I know the key-combination for this emoticon, something like ";-)" 

Hopefully is my message clear and someone can help me.
Claude
![ask_first_emoticon](https://cloud.githubusercontent.com/assets/10469353/5687773/91b587ee-9850-11e4-95aa-6be2cd22a0c2.PNG)

**Comment by menny** [comment]
Ho! That's terrible.
there isn't a 'key combination' for this kind of emoji.
It's a specific Unicode character, and if the keyboard does not include it, I don't know how you could enter it.

**Comment by clo10** [comment]
Hi,

thanks a lot for your answer.
It seems to be the character combination (in ascii) 0xF0 0x9F 0x98 0x93 (not printable, unfortunately)
I could read this sequence when sending a email from another smartphone featured with anysoftsoftkeyboard. In this email, I put the sequence with the standard letter and the emoji inside. Then I read this email with an old outlook express. In the message source, I could see in base64 coded the standard letter and the sequence of the emoji.

I am now trying to know if some special caracters in a "standard" keyboard could correspond with these character codes. But I fear there is no escape.

Claude
je suis charlie
  ----- Original Message -----
