### ISSUE TITLE
Restore function not working

### ISSUE THREAD

**Issue by nihal697** [AnySoftKeyboard/AnySoftKeyboard#3833]
### Steps to reproduce
Install ASK fresh and try to restore the backup.

### Actual behaviour

**Android OS version: android 13 lineage os**

**Device manufacturer and model: redmi note 11**

**List of installed add-ons (like languages, or themes): ASK app version 1.12.365 from play store, no addons**
I think the issue is probably that the app is not asking for storage.

**Comment by returntrip** [comment]
I would add to this issue that the backup function is also affected

**Comment by menny** [comment]
fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3854
