### ISSUE TITLE
ASK crashing if typing bobachodabobach

### ISSUE THREAD

**Issue by nihal697** [AnySoftKeyboard/AnySoftKeyboard#3834]
### Steps to reproduce
type the word bobachodabobach

### Actual behaviour

**Android OS version: android 13 lineageos**

**Device manufacturer and model: redmi note 11**

**List of installed add-ons (like languages, or themes):ASK version 1.12.365 from play store, no addons**
attaching the crashlog
[crash_report_details_1699935547225.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/13344427/crash_report_details_1699935547225.txt)

**Comment by menny** [comment]
wow. this is a crazy find. thank you so much

**Comment by nihal697** [comment]
ikr 🤣
