### ISSUE TITLE
"FrankenRobot cannot be resolved to a type"

### ISSUE THREAD

**Issue by maddy04** [AnySoftKeyboard/AnySoftKeyboard#389]
Hi,
   Thank you very much for this great effort. ITs greate contribution in open source community. I am looking for simmilar solution keyboard, I have imported your poroject and added mainAPI as library project. I am getting error like 
  "FrankenRobot cannot be resolved to a type".
I could not fine where the package "net.evendanan.frankenrobot" is?
 Please help me.
Thanks.

**Comment by menny** [comment]
AnySoftKeyboard only supports the _Gradle_ build system.
See https://github.com/AnySoftKeyboard/AnySoftKeyboard/wiki/How-to-Build-AnySoftKeyboard

**Comment by maddy04** [comment]
Hi Menny,
              Thanks for your reply. I am running it on eclipse not in android studio, may be that causes some issue with BuildConfig file, but now I have run AnySoftKeyboard  somehow. There are some new problems :) . The keyboard open only once and after that it started getting crash when i try to input. I could not find any error or exception on logcat.

**Comment by menny** [comment]
It most likely related to build issues. Please try it out Gradle
