### ISSUE TITLE
Gitter link is broken

### ISSUE THREAD

**Issue by naoliv** [AnySoftKeyboard/AnySoftKeyboard#3964]
The chat address (https://gitter.im/AnySoftKeyboard/) on the initial github page (https://github.com/AnySoftKeyboard/AnySoftKeyboard), AnySoftKeyboard's homepage (https://anysoftkeyboard.github.io/) and Mastodon (https://hachyderm.io/@anysoftkeyboard) is broken, giving a 404 Not Found error.

**Comment by menny** [comment]
I'll remove the links to gitter. I am not monitoring that.

I think people should use `Discussions` or go Mastodon.

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard.github.io/commit/97ee42c904405c14e94e0e2cabf78d8e3f8ceff5
