### ISSUE TITLE
Missing apostrophe character

### ISSUE THREAD

**Issue by enricocirene** [AnySoftKeyboard/AnySoftKeyboard#4043]
### Actual behaviour

The apostrophe character ' is missing from the keyboard. The only one that's similar and is present is `, which is not usable in Italian.
I've also noticed that, with the English keyboard, the apostrophe is part of the suggestions, so, even though the character is not present, it can still be accessed; in the Italian keyboard is not present in the suggestions, so maybe, besides adding the character, it becomes necessary to integrate it in the Italian keyboard suggestion engine.

**AnySoftKeyboard version:** 1.11.177

**Android OS version:** EMUI 12.0.0

**Device manufacturer and model:** Huawei Mate 20 Pro

**List of installed add-ons (like languages, or themes):** Italian for AnySoftKeyboard

**Comment by ferromint** [comment]
What happens when you long-press the double quotes `"` button in the special characters section on the keyboard?

**Comment by enricocirene** [comment]
It does appear that way but I believe it was a mistake on my part while tinkering with the top/bottom row customization. The Italian suggestions that include it are still absent at times but it's a secondary problem because the button is now always present.

**Comment by ferromint** [comment]
Does this mean that the issue can be closed?
If that's the case, then please do so.
