### ISSUE TITLE
feature request: Add option to disable tiling

### ISSUE THREAD

**Issue by txt-file** [AnySoftKeyboard/AnySoftKeyboard#416]
I am using ASK on a htc vision with CM7 and sometimes ASK tiles the keyboard. From my perspective I see no reason why ASK is tiling the keyboard and I do not like it. I want to have the keys always at the same place. In the settings I found only an option on how to start the keyboard.

So please add an option to disable the keyboard tiling.

**Comment by menny** [comment]
I don't know what _keyboard tiling_ means. Can you attach a screenshot?

**Comment by txt-file** [comment]
I meant the *keyboard splitting*. (At least there is an option called "split/merge initial state" in the English localisation.)

**Comment by menny** [comment]
That's weird.. If you set it to "Start regular" it should never split the keyboard, unless you explicitly ask it to (there is a gesture to do that, or a key in the utilities keyboard).
Which version of ASK are you using?

**Comment by txt-file** [comment]
What is that gesture? Maybe I am doing this gesture without knowing it.

About ASK tells me "v135" build on 2015-03-16.

**Comment by menny** [comment]
In ASK Settings, click on _Gestures_ under _USER INTERFACE_
It's there somewhere

**Comment by txt-file** [comment]
I set "pinch gesture" and "stretch gesture" to "no action" and will
report later if this helps.

Thanks for your help.

**Comment by menny** [comment]
Any news?

**Comment by txt-file** [comment]
works great now. Thank you very much for your help.
