### ISSUE TITLE
Polish Dvorak layout missing a letter

### ISSUE THREAD

**Issue by antekone** [AnySoftKeyboard/AnySoftKeyboard#422]
I can't seem to find the proper place for this, so I'm sorry if I'm doing it wrong.

I'm using ASK + Dvorak layout with Polish language, but the "ń" letter is missing (together with "Ń"). It's a standard letter in Polish alphabet, and I think it should be included. Do you think it's possible to include it? Can I do it myself? (changing the order of the alternative letters also would be nice)

**Comment by menny** [comment]
Which Polish language pack are you using? Can you send me the link?

**Comment by antekone** [comment]
Sorry for my delay.

Actually I was wrong, I'm not using Polish layout at all. I'm using [Alternative English Language Pack](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.alt.english), which includes Dvorak layout. I was confused, because this English pack has most of Polish letters, with a sole exception of "ń" and its uppercase variant. Sorry for that.

Anyway, is it possible to include "ń" in this pack?

**Comment by menny** [comment]
Will track progress with #902
