### ISSUE TITLE
Backup/Restore user dictionary to SDCARD

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#43]

**Comment by maverick74** [comment]
@menny sorry for commenting in such an old bug, but I belive it is I that can't find the feature, so I thougth it would be better to comment here than to open a new bug.
How do I backup and restore the user dictionary?
Thanks

**Comment by menny** [comment]
Go to the settings app. Click on Special Dictionaries in the side menu. Then "Words editor". Click the overflow menu at the top left.
![screenshot_20170220-102916](https://cloud.githubusercontent.com/assets/481272/23131345/a05003e8-f757-11e6-83cf-96466b0954ee.png)

**Comment by maverick74** [comment]
Found it. Thanks!!! My phone does not have the "overflow menu" - it exists as a "physical" button, so i didn't know there were options available here. Thanks once again! :)

**Comment by menny** [comment]
👍
Cool

**Comment by maverick74** [comment]
@menny i have a doubt: the backup also backups the percentage of use of a user added word?
I use a lot of abrevs such as tks, so it will take a while to teach ASK. I would not like to lose that…
