### ISSUE TITLE
Suggestions row "pushes" up page of current app which causes app's page to be hidden

### ISSUE THREAD

**Issue by tsvikip** [AnySoftKeyboard/AnySoftKeyboard#434]
Reproducing:
1. Have "Show suggestions" turned on in "Special dictionaries" setting
2. Open Whatsapp, for example but happens in other apps
3. In one of the chats, touch the message box to start typing
4. Start typing and continue typing until "Suggestions" row appears (by default should appear after two characters)

Actual:
App's page is pushed up by the "Suggestions" row so its top part is hidden a little

Expected:
App's page shouldn't be pushed up but rather its height should be reduced from the bottom.

Reproduced on:
Nexus 5, Lollipop 5.1

**Comment by menny** [comment]
Which version of AnySoftKeyboard are you using?

**Comment by tsvikip** [comment]
That was fast :-)

It was 1.3.20150318 but now that I have an updated version, 1.3.20150322,
it is not reproducible.

Sorry for the trouble.

**Comment by menny** [comment]
That's very good!

Keep enjoying ASK!
