### ISSUE TITLE
Application crashed when run source code.

### ISSUE THREAD

**Issue by Smeet123** [AnySoftKeyboard/AnySoftKeyboard#435]
When i am trying to run the source code, i am getting following error:

Please please help me please. I am stuck.

I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKey.<init>(QuickTextKey.java:63)
I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKeyFactory.createConcreteAddOn(QuickTextKeyFactory.java:141)
I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKeyFactory.createConcreteAddOn(QuickTextKeyFactory.java:34)
I/dalvikvm﹕ at com.anysoftkeyboard.addons.AddOnsFactory.createAddOnFromXmlAttributes(AddOnsFactory.java:361)
I/dalvikvm﹕ at com.anysoftkeyboard.addons.AddOnsFactory.parseAddOnsFromXml(AddOnsFactory.java:317)
I/dalvikvm﹕ at com.anysoftkeyboard.addons.AddOnsFactory.getAddOnsFromResId(AddOnsFactory.java:295)
I/dalvikvm﹕ at com.anysoftkeyboard.addons.AddOnsFactory.loadAddOns(AddOnsFactory.java:231)
I/dalvikvm﹕ at com.anysoftkeyboard.addons.AddOnsFactory.getAllAddOns(AddOnsFactory.java:222)
I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKeyFactory.getAllAvailableQuickKeys(QuickTextKeyFactory.java:62)
I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKeyFactory.getOrderedEnabledQuickKeys(QuickTextKeyFactory.java:87)
I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKeyFactory.getCurrentQuickTextKey(QuickTextKeyFactory.java:58)
I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.AnyKeyboard.initKeysMembers(AnyKeyboard.java:184)
I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.AnyKeyboard.loadKeyboard(AnyKeyboard.java:139)
I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.KeyboardSwitcher.getAlphabetKeyboard(KeyboardSwitcher.java:567)
I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.KeyboardSwitcher.setKeyboardMode(KeyboardSwitcher.java:318)
I/dalvikvm﹕ at com.anysoftkeyboard.AnySoftKeyboard.onStartInputView(AnySoftKeyboard.java:563)
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 6332 (anysoftkeyboard)
I/DEBUG﹕ check process 6332 name:anysoftkeyboard
I/DEBUG﹕ [OnPurpose Redunant in preset_info] pid: 6332, tid: 6332, name: anysoftkeyboard  >>> com.menny.android.anysoftkeyboard <<<
I/DEBUG﹕ pid: 6332, tid: 6332, name: anysoftkeyboard  >>> com.menny.android.anysoftkeyboard <<<
I/DEBUG﹕ #02  bef0a5a0  5d371b21  /data/app/com.menny.android.anysoftkeyboard-1.apk
I/AEE/AED﹕ Current Executing Process:
    pid: 6332, tid: 6332
    com.menny.android.anysoftkeyboard
V/Provider/Settings﹕ from settings cache , name = default_input_method , value = com.menny.android.anysoftkeyboard/.SoftKeyboard
V/InputMethodManager﹕ Starting input: Bind result=InputBindResult{com.android.internal.view.IInputMethodSession$Stub$Proxy@4255d348 com.menny.android.anysoftkeyboard/.SoftKeyboard #2367}
V/InputMethodManager﹕ Starting input: Bind result=InputBindResult{com.android.internal.view.IInputMethodSession$Stub$Proxy@423dfa20 com.menny.android.anysoftkeyboard/.SoftKeyboard #2368}
I/ActivityManager﹕ Process com.menny.android.anysoftkeyboard (pid 6332) has died.
W/ActivityManager﹕ Scheduling restart of crashed service com.menny.android.anysoftkeyboard/.SoftKeyboard in 80000ms
V/Provider/Settings﹕ from settings cache , name = default_input_method , value = com.menny.android.anysoftkeyboard/.SoftKeyboard

**Comment by menny** [comment]
I understand that this is solved now, correct?

**Comment by Smeet123** [comment]
Yes menny, now it is working fine.

**Comment by Smeet123** [comment]
Yes its solved now. Thanks for your support.
