### ISSUE TITLE
Auto-capitalization capitalizes two letters instead of one.

### ISSUE THREAD

**Issue by Umbrael** [AnySoftKeyboard/AnySoftKeyboard#438]
There is a recurring issue of auto-capitalization consistently rendering the first TWO letters as capitals when text is input quickly into any text field: word processors, messaging apps, and the Firefox browser. This problem presents any time that auto-capitalization would be incurred: new sentences, after returns, or upon the first words in a text field. I am running version 136 1.3.20150322 of A.S.K. on a Samsung Galaxy Tab2 10.1 with the default OS. An image of this issue is attached. 
![screenshot_2015-04-04-15-31-48](https://cloud.githubusercontent.com/assets/11801335/6995059/ce6bbbf0-dae4-11e4-9f6d-f113af66dd10.png)

Separately, it would be really great if the vertical height of the "suggested text bar" at the top of the keyboard were configurable; I often mistakenly minimize the keyboard when attempting to select a word from this list.

**Comment by ashirviskas** [comment]
Same thing happens for me on my Nexus 5 too. Words get written in this way: "HEy! HOw are you doing?". Please fix this. It annoys a lot. Otherwise it's the best keyboard I've ever tried.

**Comment by andrewshadura** [comment]
Affects me too.

**Comment by menny** [comment]
Let's see if this fixes things: https://drive.google.com/open?id=0B_4L3UCZ8dDyOE9lcl9wa2ZJWUk&authuser=0

Please note: this APK includes a lot of other changes (notably, key-preview refactor and Emoji history). You may provide feedback on those too :)

**Comment by ashirviskas** [comment]
This beta version didn't fix auto capitalization of second a letter when I multi-press first special symbol. IE when I want to write word Žalia, I double click letter "Z", then I type in alia. But it always writes ŽAlia instead of "Žalia". Another examples are ŠIenas, ŽOlė, ĖRiukas and so on.

**Comment by menny** [comment]
Which language pack are you using?

**Comment by menny** [comment]
@andrewshadura @Umbrael @ashirviskas did the beta fix your issue?

**Comment by ashirviskas** [comment]
@menny I'm using Lithuanian.

**Comment by menny** [comment]
@andrewshadura @Umbrael @ashirviskas can you try the latest release? 1.6 released yesterday and it did include a fix related to multi-tap.

**Comment by ashirviskas** [comment]
Nope, nothing has changed. 1.6.97-all version,​
 2015-11-09-11-14-12_screenRecording.mp4
<https://drive.google.com/file/d/0BxTtIZDD8eXnSGFhaEZtRFhKdE0/view?usp=drive_web>
​

**Comment by menny** [comment]
Please try this version: https://drive.google.com/file/d/0B_4L3UCZ8dDyUmV5NVE1aGVFd00/view?usp=sharing

Let me know if it fixes your issue, and if it introduces new issues.

**Comment by ashirviskas** [comment]
Yes, it did fix it. No other problems so far.
