### ISSUE TITLE
Caps lock issue with JuiceSSH

### ISSUE THREAD

**Issue by gergelypolonkai** [AnySoftKeyboard/AnySoftKeyboard#446]
I'm using JuiceSSH, and when I'm in the terminal, press Shift then a letter, Shift remains active. To turn off Caps Lock(?) I have to press Shift twice (time between presses doesn't count)

**Comment by andrewshadura** [comment]
Identical behaviour here with Irssi ConnectBot.

**Comment by menny** [comment]
Looking into that

**Comment by menny** [comment]
Let's see if this fixes things: https://drive.google.com/open?id=0B_4L3UCZ8dDyOE9lcl9wa2ZJWUk&authuser=0

Please note: this APK includes a lot of other changes (notably, key-preview refactor and Emoji history). You may provide feedback on those too :)

**Comment by menny** [comment]
@gergelypolonkai , I also enabled TAB and ESC keys for JuiceSSH.

**Comment by gergelypolonkai** [comment]
It looks fine, also the emoji history and the Tab/Esc keys. I checked the
key previews, and it doesn't look any different (I guess this is intended).

@gergelypolonkai <https://github.com/gergelypolonkai> , I also enabled TAB
and ESC keys for JuiceSSH.

—
Reply to this email directly or view it on GitHub
<https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/446#issuecomment-100990138>
.

**Comment by menny** [comment]
Please continue to test. Tell me?if you find anything weird related to SGIFT behavior
