### ISSUE TITLE
Cannot turn on Caps Lock

### ISSUE THREAD

**Issue by gergelypolonkai** [AnySoftKeyboard/AnySoftKeyboard#447]
Caps Lock is said to be working by pressing Shift twice, but it doesn't work on any of my devices (HTC One M7 and a Wayteq tablet with ICS)

**Comment by menny** [comment]
I can not reproduce the problem at all.
Can you send me a video?

**Comment by gergelypolonkai** [comment]
I need to install the SDK for this (if you have a better option for
Lollipop, let me know), but sure, I will. What are the current options for
activating CapsLock? I read tap-tap, double tap and long press here and
there, which ones should I test during the screen capture?

**Comment by menny** [comment]
If you are running Lollipop, you should be able to use one of the generic screen-recorders apps in the Play Store. Something like: https://play.google.com/store/apps/details?id=com.nll.screenrecorder
When you record, please turn on "Show touch" in the settings.

Please test with double tap.

**Comment by menny** [comment]
Which language pack are you using?
What layout is that?

**Comment by gergelypolonkai** [comment]
Dvorak from the [alternative english layouts](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.alt.english) pack. But the problem persists even if I uninstall all the language packs (I also have the [Hungarian pack](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hungarian) installed) and use default English. I was suspecting a settings-related problem, e.g. the first thing I turned off was key repeat, but if I turn that back on, it doesn’t help.

**Comment by menny** [comment]
Ok. Which bottom row and top rows are you using?
Which device do you have? Which OS version?

**Comment by gergelypolonkai** [comment]
top: alternate number keys; bottom: new generation — testing. Device is HTC
One M7 with Lollipop provided by HTC (5.0.2). It didn't work in 4.4, too.

**Comment by menny** [comment]
I can't figure what is the problem with your setup.
And I can't see anything in the code that will suggest that there is a settings configuration that will cause that.

Which locale are your phone setup to?

**Comment by gergelypolonkai** [comment]
It's set to English. For some reason I still suspect a setting problem; is
there a way to export my current config and reset to the defaults?

**Comment by gergelypolonkai** [comment]
Sorry, it is actually UK English (I don't know if this matters)

**Comment by gergelypolonkai** [comment]
I have removed everything related to ASK to reset it to defaults. Then I reinstalled ASK and the Alternate English layouts. So far, I cannot reproduce the problem, no matter the settings I try.

**Comment by menny** [comment]
This is a good workaround.
