### ISSUE TITLE
ASK issue error message device not supported 

### ISSUE THREAD

**Issue by ormasoft** [AnySoftKeyboard/AnySoftKeyboard#458]
Hello

I tried several times to install ASK on the an Android based box from this family
www.solid-run.com

Got error message that the ASK version is not suitable for this device, which is very strange.

Thanks for the great work
  Orma

**Comment by menny** [comment]
ASK supports touch-enabled devices only.
Does _solid-run_ supports touch?

**Comment by ormasoft** [comment]
I don't know if solid-run support touch.
There is no touch screeen in the product but maybe the property exist.
(also there is no battery, but the icon of the battery is there all the
time. It is android)

BTW: someone told me that he runs ASK on the cube from solid-run.
But he connect only with mouse, so when he put the mouse on the search
line, in the browser, he gets virtual keyboard.
I connected wireless actual keyboard (rapoo 2700) so I don't get virtual
keyboard that opens :-(

**Comment by menny** [comment]
I'm sorry, I can not help.
Have you tried connecting a mouse?

**Comment by ormasoft** [comment]
yes. Tried. Didn't open virtual keyboard.
And every time I want to install something on the cube I get error message that the device is not supported.
Where do I find the latest APK for Hebrew ?
