### ISSUE TITLE
Crashing on Lollipop / ICS due to Emoji UTF encoding

### ISSUE THREAD

**Issue by MadhuriIndia** [AnySoftKeyboard/AnySoftKeyboard#461]
If compiled on Windows 8.1 64 bit pc on Android studio ASK is crashing for Crashing on Lollipop due to Emoji UTF encoding.
05-18 17:48:30.612  31401-31401/? W/dalvikvm﹕ JNI WARNING: input is not valid Modified UTF-8: illegal start byte 0xf0
05-18 17:48:30.612  31401-31401/? W/dalvikvm﹕ string: '🕐'
05-18 17:48:30.612  31401-31401/? W/dalvikvm﹕ in Landroid/content/res/StringBlock;.nativeGetString:(II)Ljava/lang/String; (NewStringUTF)
05-18 17:48:30.612  31401-31401/? I/dalvikvm﹕ "main" prio=5 tid=1 NATIVE
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x40ac1490 self=0x18f5d50
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ | sysTid=31401 nice=0 sched=0/0 cgrp=default handle=1075021000
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ | schedstat=( 0 0 0 ) utm=131 stm=30 core=0
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at android.content.res.StringBlock.nativeGetString(Native Method)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at android.content.res.StringBlock.get(StringBlock.java:81)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at android.content.res.AssetManager.getResourceText(AssetManager.java:158)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at android.content.res.Resources.getText(Resources.java:262)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at android.content.res.Resources.getString(Resources.java:350)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.QuickTextKey.<init>(QuickTextKey.java:62)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.HistoryQuickTextKey.<init>(HistoryQuickTextKey.java:23)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.quicktextkeys.ui.QuickTextViewFactory.createQuickTextView(QuickTextViewFactory.java:30)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.showQuickKeysView(AnyKeyboardBaseView.java:1902)
05-18 17:48:30.622  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.AnySoftKeyboard.openQuickTextPopup(AnySoftKeyboard.java:1708)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.AnySoftKeyboard.onKey(AnySoftKeyboard.java:1621)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.invokeOnKey(AnyKeyboardView.java:177)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onLongPress(AnyKeyboardView.java:198)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.openPopupIfRequired(AnyKeyboardBaseView.java:1797)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.access$100(AnyKeyboardBaseView.java:86)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView$UIHandler.handleMessage(AnyKeyboardBaseView.java:267)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:154)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:4945)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
05-18 17:48:30.632  31401-31401/? I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
05-18 17:48:30.642  31401-31401/? I/dalvikvm﹕ [ 05-18 17:48:30.642 31401:0x7aa9 E/dalvikvm ]

**Comment by menny** [comment]
I'm building on Mac OS X and Linux. I do not see those issues.
Do you have a suggestion for how to fix it?

**Comment by RajeshDRC** [comment]
i solved it. please remove  <uses-sdk
 />  from menifiest

**Comment by menny** [comment]
Where exactly?

**Comment by RajeshDRC** [comment]
<uses-sdk  tag from menifiest file

**Comment by RajeshDRC** [comment]
or you can keep min sdk version below 4. like <uses-sdk android:minSdkVersion="3"/>
if i keep 8 or some more i got exception

**Comment by RajeshDRC** [comment]
So final answer is either remove <uses-sdk  tag or keep android:minSdkVersion="3"

**Comment by RajeshDRC** [comment]
very nice project works in eclipse also

**Comment by menny** [comment]
Are you using gradle to build the project?

**Comment by RajeshDRC** [comment]
No i am use Eclipse. i have manually convert this project from gradle to eclipse base

**Comment by menny** [comment]
I see.

I don't exactly know what Eclipse do with _aar_ files (which are the libraries format for ASK), but it seems that it incorrectly parses them. Or maybe it uses the exploded version of the, or the generated version of them. I don't really know. Sorry.

**Comment by MadhuriIndia** [comment]
I am using Gradle to build.
I have fond that min SDK version more than 7 will carsh when keybaord is actually opened. Its throwing some unicode related error.Please comment on that.

**Comment by menny** [comment]
Are you using Windows as your build machine?

**Comment by MadhuriIndia** [comment]
Yes
On Jun 25, 2015 9:57 PM, "Menny Even Danan" <notifications@github.com>
wrote:
>
> Are you using Windows as your build machine?
>
> On Thu, Jun 25, 2015, 11:13 AM MadhuriIndia <notifications@github.com>
> wrote:
>
> > I am using Gradle to build.
> > I have fond that min SDK version more than 7 will carsh when keybaord is
> > actually opened. Its throwing some unicode related error.Please comment
on
> > that.
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/461#issuecomment-115288636

**Comment by lerman** [comment]
Any update on this? I have to force a bunch of libs to ignore sdk versions due to the 7 requirement

**Comment by menny** [comment]
I've submitted a bug report to Google: https://code.google.com/p/android/issues/detail?id=267035

Please star it to get it prioritized.

**Comment by menny** [comment]
Since Google did not response yet to the issue, I'm pushing this to the next release.

**Comment by AnXh3L0** [comment]
@menny has this been implemented yet?

**Comment by menny** [comment]
I've fixed this. It should be good to close.
