### ISSUE TITLE
Korean language

### ISSUE THREAD

**Issue by tzmst** [AnySoftKeyboard/AnySoftKeyboard#462]
Is there a korean keyboard done ? Or the question is does AnySoftKeyboard has the korean language formula implemented ?

**Comment by friesenkiwi** [comment]
No, there is no Korean Language Pack for ASK, but you are welcome to create one! :-)
@menny can be closed ;-)

**Comment by friesenkiwi** [comment]
For future reference: A little guideline on how to create a new pack is located here now: https://github.com/AnySoftKeyboard/LanguagePack/blob/master/README.md
If you get stuck at some point and have a specific question, ask over at https://github.com/AnySoftKeyboard/LanguagePack/issues/new
