### ISSUE TITLE
Power Saving Mode

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#463]
In a _Power Saving Mode_ AnySoftKeyboard will not perform dictionary lookups, will not perform any animation, and will not show popups.

**Comment by menny** [comment]
Settings include:
 * Never go into Power Saving Mode
 * When battery in low level
 * Always

**Comment by menny** [comment]
Create an AskConfig wrapper that calculates the ad-hoc values of dictionary, popup and animation (others too?) according to the Power Saving Mode setting and the current battery state.

**Comment by menny** [comment]
http://developer.android.com/training/monitoring-device-state/battery-monitoring.html#MonitorLevel

**Comment by homersimpsons** [comment]
Allow user to customise power saving mode with the function to disable (for me dictionary lookup is great) or set different aggressiveness depending of battery

**Comment by menny** [comment]
I feel this should be done _after_ we move to RxJava.
