### ISSUE TITLE
Word triggered icon suggestion

### ISSUE THREAD

**Issue by mad-engineer** [AnySoftKeyboard/AnySoftKeyboard#469]
It would be nice to have a word triggered icon suggestion. If the user types the word "baby" (in their own language), the suggestion window should show the baby unicode icon: &#128700;

**Comment by menny** [comment]
Like this: https://goo.gl/photos/sXXwo3QAgZ4Cdhku5

**Comment by mad-engineer** [comment]
Huh.. exactly like this. Is it ASK you're using? I couldn't find this feature so far. Is it theme dependent?

**Comment by menny** [comment]
:)

This is the abbreviation dictionary: I went into Settings, in _Special Dictionaries_ I clicked _Abbreviation editor_, and added baby->🚼

**Comment by menny** [comment]
I know that this is not what you expected (probably you wanted a generic, automatic way to parse all the emojies), but that will require going over all of those and creating, well, abbreviations..

**Comment by mad-engineer** [comment]
I'm aware of that. At the moment I'm thinking of an easy way to automatize it to add an "Icon Abbreviation" function. Something like parsing such sites for tags: http://www.typografie.info/3/page/artikel.htm/_/wissen/apple-emoji-natur
