### ISSUE TITLE
The DV layout reorders what i type limiting maximum speed

### ISSUE THREAD

**Issue by Fruzzetti** [AnySoftKeyboard/AnySoftKeyboard#476]
Hey.  I love this product and have donated.  I wonder if you could check into this issue i've been having on Dvorak; i can only type so quickly or else the letters will appear (in correct order) and then rearrange to a different (read: wrong) order.  It seems to happen in portrait mode espeically, where keys on the left side, even if tapped later, may be rendered BEFORE keys on the right side.

So i type words like 'captain' and for a brief moment 'captain' is rendered but it changes to 'captnai' or similar.  Its threshold is too low when lots of memory or cycles are being eaten by processes.

**Comment by dkurzaj** [comment]
I'm facing the exact same problem. And I don't think it's because of your Dvorak keyboard, because I face the same one with a Bépo keyboard.
