### ISSUE TITLE
Where's the Finnish keyboard layout?

### ISSUE THREAD

**Issue by AviBueno** [AnySoftKeyboard/AnySoftKeyboard#485]
Long time ago I could download the Finnish keyboard layout from Google Play, and at some point it just disappeared.
How can it make its way back to Google Play?

(*) Looks like [at least part of] the codebase still exists:
https://code.google.com/p/softkeyboard/source/browse/trunk/LanguagePacks/Finnish/src/com/menny/anysoftkeyboard/finnish?r=601

**Comment by menny** [comment]
I'll republish it.

**Comment by AviBueno** [comment]
Appreciate it, thanks a lot!
