### ISSUE TITLE
Hungary, Greek and Japanese Language packs

### ISSUE THREAD

**Issue by george32** [AnySoftKeyboard/AnySoftKeyboard#486]
Would you please let me access any beta versions of AnySoftKeyboard language packs for Hungary, Greek or Japanese ?  Thanks very much.

**Comment by george32** [comment]
If there is a guide to creating a brand new language pack, please let me know as well.  Thanks.

**Comment by friesenkiwi** [comment]
The Hungary/Magyar pack is maintained independently here: https://github.com/rhornig/anysoftkeyboard-hungarian/issues
The Greek pack will be updated soon (see https://github.com/friesenkiwi/LanguagePack/tree/Greek).
There is no Japanese pack, but you are welcome to create one. Just clone https://github.com/AnySoftKeyboard/LanguagePack/tree/master and have a look at the build.gradle: https://github.com/AnySoftKeyboard/LanguagePack/blob/master/build.gradle it has comments etc. guiding you in the progress.
@menny I'd say you can close this.

**Comment by menny** [comment]
Cool.
I'd gladly accept a PR for Japanese pack.

**Comment by friesenkiwi** [comment]
@george32 : A little guideline on how to create a new pack is located here now: https://github.com/AnySoftKeyboard/LanguagePack/blob/master/README.md
If you get stuck at some point and have a specific question, ask over at https://github.com/AnySoftKeyboard/LanguagePack/issues/new

The PR for Greek is at https://github.com/AnySoftKeyboard/LanguagePack/pull/46 and will shortly be published through Play Store and F-Droid.
