### ISSUE TITLE
Long press SHIFT should move to caps-lock

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#502]

**Comment by pan2003** [comment]
As far as I understand, now CAPS LOCK can be toggled by SHIFT double click. So probably this enhancement is not of high priority...

**Comment by pan2003** [comment]
By the way, after fixing bug #506 about gesture for SHIFT... If I swipe up to toggle SHIFT and than swipe up again, what will happen? Here could be 2 variations:
1) SHIFT is toggled between 2 states: on and off,
2) SHIFT is toggled between 3 states: on, CAPS LOCK, off.

**Comment by menny** [comment]
Option 3: it will cycle between ON->LOCK->OFF (just as if you clicked SHIFT)

**Comment by menny** [comment]
Going to revert this one... this behavior breaks the _hold shift while pressing other keys to get caps, then release shift to return to un-caps state_..
