### ISSUE TITLE
Change the shift output of some keys

### ISSUE THREAD

**Issue by kertase** [AnySoftKeyboard/AnySoftKeyboard#503]
Hello,

I am trying to create a keyboard layout in which the shifted key makes another key than the standard shifted key. It was possible to change the label of the key with ask: ask:shiftedKeyLabel="". but I can’t seem to be able to edit the output. I tried ask:shiftedCodes but it does not seem to work in the LanguagePack add-ons. Can anyone tell me how i could make this work or how to fix ask:shiftedCodes.

Thank you

**Comment by menny** [comment]
@kertase did you close this by mistake?

**Comment by kertase** [comment]
The issue was solved by updating ASK

**Comment by kertase** [comment]
Issue seems to be back in newer versions

**Comment by kertase** [comment]
Is working in v1.7-r7 downloaded from github but not in latest versions from playstore and f-fdroid.

**Comment by menny** [comment]
Can you provide a reproduce sequence?

**Comment by kertase** [comment]
Well when by installing https://github.com/kertase/neo_anysoftkeyboard (any version should do, you can find it build on f-droid) using for example the standard [neo layout](https://github.com/kertase/neo_anysoftkeyboard/blob/master/src/main/res/xml/neo.xml) when shifting ask:shiftedKeyLabel="" is only working for the sign ℓ. 

When I click shift, it does not work for the other sign or it is a not a sticky shift(need to hold shift button to make it work)

**Comment by menny** [comment]
The behavior of shift-codes is as follows:

- if the primary code is a character:
  - show shift-code/shift-label if shift state is enabled (pressed, on, or locked)
  - show regular label otherwise.
- if the primary code is not a character:
  - show shift-code/shift-label if shift state is pressed
  - show regular label otherwise.

**Comment by kertase** [comment]
As I understood it should then show shift-code/shift-label when shift is enable since the keycodes are characters.

Are '°§$' not characters and 'ℓ' is? If that is so I do not quite understand…

Also I do not think that the left and right shift keys should act different since they are coded the same…

**Comment by kertase** [comment]
the issue of the ℓ (8467) character overriding the behaviour for non-character primary code in shiftlocked state still exists.

The issue that when a keyboard has multiple shiftkeys that the shift pressed state works only one shiftkey of the shiftkeys is also not solved.

**Comment by earkhun** [comment]
What are the latest news? I really need for Turkish layout because both the upper and lower case versions have a dot:  `android:codes="105" android:keyLabel="i" ask:shiftedCodes="304" ask:shiftedKeyLabel="İ"`

**Comment by menny** [comment]
This was implemented a few releases ago
