### ISSUE TITLE
Feature request: add more light themes

### ISSUE THREAD

**Issue by pan2003** [AnySoftKeyboard/AnySoftKeyboard#505]
1. The keyboard has several dark but just one light theme. Probably it will be a good idea to inverse each dark theme and add it as new light theme?

2. Maybe make "Lean Dark - Option 2" theme (and its future light version) even more minimalistic? I mean, just black and white, no more colors (or, if really needed, a bit of gray). As of now, this theme uses violet color as a background in letter suggestion.

**Comment by danielegobbetti** [comment]
I made a pull request (#515) with the lean theme in light version. I hope it gets merged. It looks like this:
![lean light](https://raw.githubusercontent.com/danielegobbetti/AnySoftKeyboard/master/src/main/res/drawable/lean_light_theme_screenshot.jpg)

**Comment by pan2003** [comment]
Looks perfect!

**Comment by pan2003** [comment]
I've just looked at this theme in AnySoftKeyboard-debug-1.6.92-all-beta2.apk.

The keyboard looks fine, but the tooltip with the key pressed is "white on orange". Could you change it to "black text on white background" to be more consistent with main skin colors?

**Comment by pan2003** [comment]
And one more issue. I don't see "secondary" letters with this theme.

**Comment by danielegobbetti** [comment]
@pan2003 I think the visibility of the currently selected key is much better with the current approach.
As for the secondary letters as far as I understood they are hidden in the lean dark theme as well, and this theme is a clone of it (see [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/src/main/res/values/styles_lean_dark_keyboard_theme.xml).
