### ISSUE TITLE
Gesture "Swipe up" does not work for "Toggle uppercase"

### ISSUE THREAD

**Issue by pan2003** [AnySoftKeyboard/AnySoftKeyboard#506]
Using latest version 1.5-r4.1.

In settings, I assigned gesture "Swipe up" to "Toggle uppercase". Does not work. Also tried to assign the same action to "Swipe up from space", does not work either.

But "Swipe up from space" for action "Utility keyboard" works fine. And other gestures (toggle languages at swipe right, toggle symbols keyboard at swipe left, hide keyboard at swipe down) works fine.

**Comment by menny** [comment]
Because we are handling the SHIFT state only using the `onPressed` and `onRelease` calls, we are not doing anything when `handleShift` is called.

**Comment by pan2003** [comment]
It works strange in latest AnySoftKeyboard-debug-1.6.92-all-beta2.apk.

The keyboard is now in lowercase state. I swipe up. Now I'm in UPPERCASE state. That's ok.
But now I swipe up to shift back to lowercase state. But I still see UPPERCASE letters.

After some testing I found that when I start to swipe up the keyboard really toggles back to lowercase, but when I continue swiping in shifts to UPPERCASE again.

**Comment by pan2003** [comment]
Just tried AnySoftKeyboard-release-1.6.97-all.apk. Behaves the same.
I'll open a new bug.
