### ISSUE TITLE
Keyboard outside screen

### ISSUE THREAD

**Issue by AndreasSE93** [AnySoftKeyboard/AnySoftKeyboard#507]
On Nexus 7 in portrait mode (doesn't happen in landscape mode or on my Galaxy Nexus) since a recent update, I think it was 1.5-r4 or 1.5-r3, the keyboard stretches outside the right border of the screen.
![screenshot_2015-09-17-22-31-16](https://cloud.githubusercontent.com/assets/5991766/9945523/09f44ac6-5d8e-11e5-8ba5-87007fb72ae9.png)

**Comment by AndreasSE93** [comment]
I've been having this problem for a week or so and now it suddenly works just fine. I have no idea what caused the problem to happen or what fixed it.

**Comment by menny** [comment]
did it begin with an update to the keyboard? Or maybe an OS update?

**Comment by AndreasSE93** [comment]
I believe it was after I updated the keyboard that it began, but I update the OS quite frequently so I'm not sure. However, between the time when I last had this problem and when it stopped occurring (duration of about an hour), I hadn't preformed any update or even rebooted the device.

**Comment by menny** [comment]
Okay. Thanks for the info.
When/if it happens again, please try to collect as much information about
the phone's state (running apps, orientation, etc), I've heard of similar
issues from other people too.
