### ISSUE TITLE
Next-Word statistics

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#512]
Should show various statistics on the usage:
TBD

**Comment by homersimpsons** [comment]
Yes display a lot of statistics like Swiftkey would be great 😃
But currently there are some statistics that look false or misunderstand, have a look at the initial word count and avarage next word count.

In my AnySoftKeyboard it displays (for French language):
- initial word count: 297
- avarage next word count: 1
While if I write 'Tu' I have some proposition for next word: 'dis', 'sois', 'vois', 'te', 'lis' that is 5 words.

And in English I have:
- initial word count: 165
- avarage next word count: 1
While if I write 'is' I have some proposition for next word: 'ok', 'Java', 'it', 'enable', 'only' that is 5 words too.

**Comment by menny** [comment]
Yes, I agree: "average" is a bad statistics in this case.
I think that a range is better ("between 1-5, with 22% fill") or something like this

**Comment by homersimpsons** [comment]
Or display a graph with percent number of next words depending of number of next words
