### ISSUE TITLE
Too quick taps cause wrong characters

### ISSUE THREAD

**Issue by aczelkri** [AnySoftKeyboard/AnySoftKeyboard#518]
In Hungarian language you have to press certain keys twice to get an accented character. Like hitting 'a' twice gets you an 'á'. However, many times, hitting 'a' + other key + 'a' again gets you 'aá', regardless of the second character.

This way if you type 'mama' fast, you will get 'maá'.

What presumably happens is that when you hit the second 'a' the app senses that not long ago you had hit another 'a', so now it must delete one character and replace it with an 'á'. It doesn't take into account that another key was hit between the two 'a' keys.

This bug has been around for a few years now, and I hate to see that such a nice app cannot be used reliably.

I believe the bug is in the main app, and not in the hungarian addon, however, I report this to both contacts.

**Comment by menny** [comment]
Can you send me the link to the language pack you are using?

**Comment by aczelkri** [comment]
Hi,

The language pack I use is

Magyar Anysoftkeyboard
https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hungarian&hl=hu

You can reproduce the bug if you start typing 'mamamamamamamamamamamamamama' real fast. You will get something like 'máàaáàaáàaáàaáàaáàa'. 

Cheers
Kristóf

**Comment by menny** [comment]
Which layout do you use?

**Comment by aczelkri** [comment]
Hungarian (tablet), in portrait mode.

**Comment by aczelkri** [comment]
And the bug is present on a number of Samsung Gaáxy phones (Galaxy written fast = Gaáxy) including S2, S3, Note 2, Note 3. Some seem more affected than others, but it may only be due to some setting.

**Comment by menny** [comment]
Okay. Got it!

**Comment by menny** [comment]
Please try this build: https://drive.google.com/open?id=0B_4L3UCZ8dDySHN0d3Y3SEJKMms

It solved the issue for me, but you may have a different use-case which cases the issue.

**Comment by menny** [comment]
Forget about that. It does not fix the issue.

**Comment by menny** [comment]
I noticed that when typing really quickly, Android will not recycle pointer IDs as quick:
```
D/PointerTracker(19913): Tracker 513884445, id 0, checkMultiTap for m
D/PointerTracker(19913): Tracker 513884445, id 0, checkMultiTap for a
D/PointerTracker(19913): Tracker 515478013, id 1, checkMultiTap for m
D/PointerTracker(19913): Tracker 513884445, id 0, checkMultiTap for a
```
This is not an issue from the framework perspective, but I assumed that pointer ID recycle is instant.
_Assumption is the mother of all fuck ups_.

**Comment by menny** [comment]
I have an idea how to fix this.

**Comment by aczelkri** [comment]
:)

If it helps, I think the position of the pointer is correctly recognized by Android, as when I type 'mama' I get these phases:

m
ma
mam
maá

I don't know about the ID, as I cannot test it. But for me it seems every character gets recognized correctly, and if the app kept track of the last hit characters, it should be easy to avoid this issue. By the time I hit the second 'a', the app already could know that the previous one was not an 'a', so no need to input any special character. Theoretically...

**Comment by menny** [comment]
Ok, I think I got it. Please try this debug build: https://drive.google.com/open?id=0B_4L3UCZ8dDyR2FVWUlIa0pZTFU
Let me know if it fixes your issue.

**Comment by aczelkri** [comment]
Great effort! The bug is almost gone, it shows itself only if I type really really quickly (which I can, for words like 'mama')

Also, sometimes the opposite happens: the 'm' character suppresses the 'a'. (Maybe this happened earlier too, I just didn't notice)

These are my inputs, typed just now:
mamamamammmmmmamamaámamamaáàmama
mamaámamamaáàmama
maá

The popup notion of which key has been pressed is always spot on (never seen any 'á' in the popup, only in the written text).

However, it is much more usable now!

**Comment by menny** [comment]
Cool.
I'll continue to research, but I'm closing this one for now.

**Comment by aczelkri** [comment]
Hi Menny,

How did you solve the issue in the end? Did you just add an exception for
'mama'?

That word is better now, but there are several other words, e.g 'ever' that
are hard to type.

ever -> eér
Aladdin -> Aáddin
Electricity -> Eéctricity
Telephone -> Teéphone
Itinerary -> iínerary

So the solution is unfortunately not optimal yet :(

Chérs
Kristof

**Comment by menny** [comment]
Of course I have not added an exception for `mama` :)
I solved the underlying issue. The original cause for the erroneous state is fixed, but other issues may not been fixed. I was no longer able to reproduce this issue (I was able to reproduce it before) after the fix I submitted.

I'll try again.

Any idea when you started seeing this issue before?

**Comment by aczelkri** [comment]
Hi,

I cant remember not having this issue, that means it is present for at
least 1-2 years.

Strangely, it is more prominent on Galaxy Note 3 than on my previous
phones, but it was always there.

I am more than happy to help you test the software, so if you send debug
versions I can report how it works.

Now that I test it, it even happens for other characters, not only the
accented ones:

Lelelelelelelelelelelelelelele ->
Leleleéleleéeéellllllllellllllll

But it only happens if there is an accented character is involved. For
instance it does not happen for:

Lwlwlwlwlwlwlwlwlwl

I can see as I type that the 'e's are written, then deleted back and
replaced by an l. Why would that happen? Pressing 'l'  has no effect
theoretically.

Btw, the speed of my input above was 85 chars/10 sec. I know that it is
unnaturally fast, and of course I cannot type this fast continuously, but
some words like maá you type so many times that you get pretty fast at it.

Cheers
Kristof

**Comment by aczelkri** [comment]
Hi,

After years of usage, I am reporting this error again, in a bit different
form, maybe it is easier to debug this way. After pressing a key that has
an accented version (tapping twice quickly adds the accent), the next key
cannot be repeated. The attached video says it all.

I am using Hungarian/tablet layout in portrait mode.

Would it be possible to have a look at this issue?

Cheers
K
