### ISSUE TITLE
Can you update Fdroid repo? Please

### ISSUE THREAD

**Issue by timofonic** [AnySoftKeyboard/AnySoftKeyboard#526]
Hello.

Last AnySoftKetboard in Fdroid is from 2013.

Can anyone update it to the latest version? What about providing a fdroid repo with latest ones too.

I don't use Google Play. This is very relevant for me.

Kind regards.

**Comment by menny** [comment]
I will try to figure out what's the problem with fdroid again.
In the meanwhile, you can download the latest releases from: https://github.com/AnySoftKeyboard/AnySoftKeyboard/releases

**Comment by mrflow** [comment]
+1

**Comment by steppenhahn** [comment]
+1
fdroid version still from 2013

**Comment by M2ck** [comment]
Yes please it would be great!

[F-Droid thread](https://f-droid.org/forums/topic/anysoftkeyboard/)
[Gitlab thread](https://gitlab.com/fdroid/fdroiddata/issues/20)

**Comment by homersimpsons** [comment]
Yes please Fdroid 😃 I found this app using F-droid

**Comment by daktak** [comment]
Hoping to see Alternate English keyboard pack in F-Droid

**Comment by poppypundit** [comment]
Yes please...Thanks for the download link. Maybe an anysoft updater app as an alternative? Anyone?

**Comment by menny** [comment]
will report back on https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/618

**Comment by homersimpsons** [comment]
Updated :)
