### ISSUE TITLE
Swipe gesture key

### ISSUE THREAD

**Issue by byturk** [AnySoftKeyboard/AnySoftKeyboard#529]
Hi,

How to get key on swipe down (etc.) 
I want to do swipe up and key UPPERCASE
Thank you.

**Comment by menny** [comment]
You can set up gestures in _AnySoftKeyboard Settings_.
Open the app, and  reveal the side menu (click the menu icon at the top left).
Then pick _Gestures_ from the list, and set up the gestures you want.
