### ISSUE TITLE
 Android NDK: Aborting...    .  Stop.

### ISSUE THREAD

**Issue by swapps** [AnySoftKeyboard/AnySoftKeyboard#538]
Hi, i'm trying to compile the project in Android Studio but i have issues with NDk.

I'm getting this message:
 Android NDK: Aborting...    .  Stop.

i have added the path to ndk but it doesn't work.

What  am i doing wrong ?

**Comment by menny** [comment]
that's very strange.
Are you using `./gradlew` to build?

Can you paste the entire build log (using http://pastebin.com/)

**Comment by swapps** [comment]
Hi, after 12h hours or work i found the problem:
i had a space char in my "AndroidStudio Projects" folder...
after that another problem occured, my path was too long, i had to rename com_anysoftkeyboard_dictionaries_ResourceBinaryDictionary to ResourceBinaryDictionary...

**Comment by menny** [comment]
Good.
