### ISSUE TITLE
Detect text smileys an undo the punctuation swap

### ISSUE THREAD

**Issue by andrewshadura** [AnySoftKeyboard/AnySoftKeyboard#541]
I'm quite used to typing simple text smileys manually, but ASK swaps the preceding space and the colon, turning `:)` into `: )`. I think it should be possible to detect this and similar patterns and undo the swap when such situation occurs.

**Comment by menny** [comment]
yes, I see your point.

I need to think about this a little, try to generalize this request: I mean, `:)` `;)` `:-)` `:(`, etc etc etc... I rather not perform pattern matching all those combinations.

**Comment by menny** [comment]
Was fixed a while ago
