### ISSUE TITLE
No auto replace wanted

### ISSUE THREAD

**Issue by riedenthied** [AnySoftKeyboard/AnySoftKeyboard#549]
Since 1.6 the keyboard replaces the words with it's suggestions and there is no working way to disable this. This is REALLY frustrating. I like suggestions but I don't want to auto "correct" my texts at all. Please fix that, in 1.5 everything is fine.

**Comment by menny** [comment]
It is possible to disable auto-correct by setting _Auto-select suggestion aggressivenes_ to _Off_.
Open _AnySoftKeyboard Settings_, open the side menu and select "Even more" under _Languages_. The auto-correct option is there.

**Comment by riedenthied** [comment]
Ok, thanks. The german translation there is not the best so I didn't find this. 

Am 26. Dezember 2015 03:27, schrieb Menny Even Danan:
It is possible to disable auto-correct by setting Auto-select suggestion aggressivenes to Off.
Open AnySoftKeyboard Settings, open the side menu and select "Even more" under Languages. The auto-correct option is there.

**Comment by Louson** [comment]
I get the same issue on 1.8
"Setting Auto-select suggestion aggressiveness to Off" works but I don't think this is the right solution.
Indeed, in the dictionary option, the checkbox about fast checking and abbreviations seems to have no effect.

**Comment by spaetz** [comment]
I can can confirm.that in 1.18-r12 the option Quick fixes and abbreviations does not seem.to work. Despite being unchecked, autocorrection is being applied.
