### ISSUE TITLE
Add a text field inside the settings

### ISSUE THREAD

**Issue by gwenzek** [AnySoftKeyboard/AnySoftKeyboard#552]
In Swiftkey settings there is a button to display the keyboard.
I found it really useful for checking the changes you just made in the settings without leaving the app.

It would be nice to have one also in ASK. Maybe just adding a text field in the main screen would be enough 

Thanks for this great app😃

**Comment by menny** [comment]
That's a nice idea. I'll try to do that for the next release.

**Comment by M2ck** [comment]
Indeed it will be very useful to have a Floatting Action Button and a test area in main screen (and move changelog in About tab)!

By the way it would be needed to rewrite Settings app, IMHO a navigation drawer it's not appropriate here and improve categories would be necessary too because I'm a bit lost in all these settings.

**Comment by menny** [comment]
What do you suggest? I'm open to suggestions.

**Comment by M2ck** [comment]
What do you think about sliding tab UI (like YouTube)? 
There would be Home tab with the area test, Languages tab, Customization tab and Typing/gestures tab or Something like that.

**Comment by M2ck** [comment]
@menny here is a mockup about sliding tab UI based on YouTube app:

- Home tab: Area testing with FAB
- Languages tab: Keyboards/Dictionnaries settings
- UI tab: Theme/Effects/Gestures settings
- About tab: Changelog - Rate/Share app - G+ community, donate & used libraries links

![screenshot_2016-02-15-08-00-15](https://cloud.githubusercontent.com/assets/6850125/13044986/3e3c1f48-d3d1-11e5-822c-49e11107f144.png)

Do you enjoy it?

**Comment by menny** [comment]
This is a good idea.
I'll push this to the next release, and we'll continue to discuss this.

**Comment by menny** [comment]
I'm going to push this to a later release.

**Comment by NathanC** [comment]
@menny the bot closed this as completed, but unless I'm mistaken I don't see the feature in the existing release. Was there a regression or did the bot get confused?
