### ISSUE TITLE
Prediction not working with spanish accented words

### ISSUE THREAD

**Issue by citytrader** [AnySoftKeyboard/AnySoftKeyboard#554]
if you type "estas" and after that "estás" and continue to using that, the accented estás is never predicted under Spanish dictionary,  for example the next time I write "estas" I will not predict the accented one

**Comment by sobczyk** [comment]
Polish suffers the same problem

**Comment by pchampin** [comment]
It seems to me that this bug is covered by (the first part of) #540.
