### ISSUE TITLE
Long press time should be lower, arround 200ms 

### ISSUE THREAD

**Issue by citytrader** [AnySoftKeyboard/AnySoftKeyboard#555]
Long press time should be lower, arround 200ms , if better to have options in ms.

**Comment by xavihernandez** [comment]
It is already customizable. ot in ms tho, there are 6 steps :

**Comment by citytrader** [comment]
I know that, but the faster option is above 200ms compared with Swiftkey for example, in my opinion instead of that options is better to customize based in ms.

**Comment by xavihernandez** [comment]
Well faster is really fast for me. I have just tried and second letters pop while I don't want to. I have lowered it to "fast"

**Comment by citytrader** [comment]
Well in my phone the response is slower than Swiftkey... I think having a number instead of 6 options is much better.

**Comment by xavihernandez** [comment]
Yep it could be :)

**Comment by menny** [comment]
```
<string-array name="settings_key_long_press_timeout_values">
        <item>100</item>
        <item>250</item>
        <item>350</item>
        <item>450</item>
        <item>600</item>
        <item>1000000</item>
    </string-array>
```
_faster_ -> 100ms

**Comment by menny** [comment]
Maybe something else is messing with the timing on your device.

Which device is it?

**Comment by citytrader** [comment]
yes probably,  Samsung Galaxy Edge+ with LP 5.1.1

**Comment by xavihernandez** [comment]
Knew that lol. It is really fast I was sure it was faster than 200ms.
