### ISSUE TITLE
Can I change the bubble sound?

### ISSUE THREAD

**Issue by marco-brandizi** [AnySoftKeyboard/AnySoftKeyboard#556]
ASK is great, but the bubble sound that is used for letters and alike keys is horrible! Can you add an option to change it? The sound played by keys like Return is much better. Meanwhile, can you point me to the file where it's stored? I guess just replacing it would do the trick?

**Comment by menny** [comment]
It is much harder than it seems: ASK is using the OS's built-in sounds for keys: see [AudioManager.playSoundEffect](http://developer.android.com/reference/android/media/AudioManager.html#playSoundEffect(int))

**Comment by marco-brandizi** [comment]
As far as I understand, an option to play FX_KEYPRESS_DELETE, FX_KEYPRESS_RETURN, in place of  FX_KEY_CLICK or  FX_KEYPRESS_STANDARD (not sure which one actually corresponds to the ugly bubble-up), would be nicer than having to set no sound at all.

**Comment by menny** [comment]
yes, agree.
I'll create a feature request for this and add it to the backlog.

**Comment by menny** [comment]
You can follow #558

**Comment by marco-brandizi** [comment]
Thanks a lot!
