### ISSUE TITLE
Trouble building project 

### ISSUE THREAD

**Issue by Efunbukola** [AnySoftKeyboard/AnySoftKeyboard#559]
I keep getting this error
Error:(32, 0) CreateProcess error=2, The system cannot find the file specified

This is line 32 of build.gradle 'version versionbuilder.VersionBuilder.buildGitVersionNumber()'

**Comment by menny** [comment]
Are you using git? Is the source code still inside a `git` controlled folder?
Which OS are you using?

**Comment by Efunbukola** [comment]
I'm using Windows 10, android studio, but I was able to figure it by adding:
   sourceSets {
        main {
            jni.srcDirs = []
            jniLibs.srcDirs = [ 'libs' ]
        }
    }
to the build.gradle files for both jni dictionary modules

**Comment by ArenaL5** [comment]
`build.gradle`, and especially the versioning system, have changed dramatically since then, so this bug is no longer applicable.

**Comment by menny** [comment]
Yes, agree. The only requirements for building are defined in the README.md file
