### ISSUE TITLE
Theme height factor not working properly

### ISSUE THREAD

**Issue by kinclma1** [AnySoftKeyboard/AnySoftKeyboard#561]
Hello, I've just noticed that changing the "vertical height factor" sometimes doesn't take effect immediately and I have to change the theme for it to take effect.

Changing the "horizontal height factor" doesn't do anything whatsoever even after app restart.

**Comment by kinclma1** [comment]
I looked up the `strings.xml` for the height factor strings' ids and discovered that the "horizontal height factor" (as it's called in the czech locale) does work but its name is very misleading. The less misleading translations for the "height factor" strings would be about twice as long and wouldn't probably fit on the screen so I guess there's no solution to the translation issue.

**Comment by menny** [comment]
![screenshot_20160208-180511-01](https://cloud.githubusercontent.com/assets/481272/12902335/a541ef6c-ce8e-11e5-90b9-12ba5147946b.jpeg)
This is what it says in English. Makes sense in English? 
Do you have a suggestion for Czech?

**Comment by kinclma1** [comment]
Yes it totally makes sense in English. In Czech it would be (in order):
"Faktor výšky kláves v režimu na výšku"
"Faktor výšky kláves v režimu na šířku"

But as I wrote earlier, I'm afraid it won't fit on smaller screens as even the current shorter strings almost fill the width.

Thank you very much.
