### ISSUE TITLE
allow any character (sans whitespaces) to be abbreviations

### ISSUE THREAD

**Issue by VERSEAU44** [AnySoftKeyboard/AnySoftKeyboard#570]
On https://plus.google.com/+MennyEvenDanan/posts/ZoopduU9Fja, you describe a great functionnality

BUT not to confound with another shortcuts not to develop (eg in French: "tt" for "tout" (= "everything") but also for "téléphone travail" (="work phone")), I started all my abbreviations by ? (eg for "work phone" : "?tt")

It seems that AnySoftKeyboard not accepts starting abbreviations by this character "?" (I get this character because it is directly accessible, but it could also be  '  but it does not work either)

Could you accept these characters ?

Thanks a lot for your great job
Kind regards

**Comment by menny** [comment]
This is a really good idea.

**Comment by menny** [comment]
Abbreviations dictionary will be queried for completion on any character and any word length (unlike other dictionaries which require minimum of 2 characters).
