### ISSUE TITLE
On Amazon fire devices Emojis not working

### ISSUE THREAD

**Issue by mithunkundu1983** [AnySoftKeyboard/AnySoftKeyboard#571]

**Comment by menny** [comment]
What do you mean? In what way?

**Comment by NevadaRoz** [comment]
I have this problem too. Emojis can be typed but they do not show on the keyboard (see 2nd screenshot). (Anysoft Keyboard version 1.9.2629, version-code 5204, device model Amazon-KFFOWI187, Android version 5.1.1)
![Screenshot_2019-03-11-01-29-58](https://user-images.githubusercontent.com/48429007/54107154-515a1100-43a6-11e9-97e1-d727a571e424.png)
![Screenshot_2019-03-11-01-38-37](https://user-images.githubusercontent.com/48429007/54107204-6fc00c80-43a6-11e9-8a39-bbe383456214.png)

**Comment by menny** [comment]
this is very strange... 
Are you able to type emojis in all apps? Or are there any apps that fail to show emojis?

**Comment by NevadaRoz** [comment]
🌸💮🏵🥞🥖🧀🚉🚊🚝🕳⏱⏰🕒🕺💈💅🎪…so they show up here, anyway, if I find any apps that fail to show them I will let you know.
