### ISSUE TITLE
Disable double tap on punctuation 

### ISSUE THREAD

**Issue by homersimpsons** [AnySoftKeyboard/AnySoftKeyboard#572]
Hello ,first thank you for this apps :)
But there is a problem for me : when I want to put 3 dot '...' the double tap over dot make me ':' then I'm force to wait beetween each pressure , so please add a function to disable this :)

**Comment by menny** [comment]
Can you provide a more detailed scenario?

**Comment by homersimpsons** [comment]
I have installed AnySoftKeyboard and a French language pack (not yours because there is a latest):
- AnySoftKeyboard: French (Language pack for AnySoftKeyboard) - https://f-droid.org/app/com.anysoftkeyboard.languagepack.french_xlarge (shared with F-Droid)
And when I use the bépo layout I have some double tap feature:
é -> è
a -> à
u -> ù
k -> …
- -> —
q -> ç
? -> !
, -> ;
. -> :
At the left of each arrow you got simple touch and at the right there are the double tap char and I would like to be able to disable some of the double tap feature on punctuation

**Comment by gwenzek** [comment]
A long press on the '.' will allow you to choose the '…' character. Typing this with my Anysoftkeyboard Bépo keyboard.

**Comment by homersimpsons** [comment]
Yes, but I think this is the un code char and not 3 Ascii, then it restrict SMS length. And a long press is longer than 3 little pressures

**Comment by ArenaL5** [comment]
This is a problem with a badly-designed language pack, not with the AnySoftKeyboard base code, and the pack appears to have been unpublished since then. Multi-tap can be set to expire more quickly in order to mitigate this bug.

This bug is no longer relevant.

**Comment by AnXh3L0** [comment]
Thanks @ArenaL5, closing this.
