### ISSUE TITLE
not able to add words to the user dictionary anymore

### ISSUE THREAD

**Issue by mkarliuk** [AnySoftKeyboard/AnySoftKeyboard#573]
I am unable to add words to the user dictionary by typing a word and then double-clicking it in the suggestions field. The option 'double-click a typed-suggestion to add' is on. Previously it would work like that: if there is a word not in the dictionary, you would click it in the suggestions field and it would ask to click again to add to the dictionary. In the latest versions of ASK this second click is not available for some reason. I have to use an older version of the application for this feature to work (e.g. I have found the 1.2.20140705 apk, and this one works well).
I'm using Android 6.0.1, Nexus 5X

**Comment by menny** [comment]
Yes, I was able to confirm.
I'll work on a fix.

Thanks for reporting.

**Comment by menny** [comment]
Please sign-up to the [beta](https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard) version.
Expect a fix to be pushed in the next couple of hours.

**Comment by mkarliuk** [comment]
thanks, signed up.

**Comment by mkarliuk** [comment]
works well now, thanks!
