### ISSUE TITLE
(Re)assignment of Polish diacritics in English 16 key layout

### ISSUE THREAD

**Issue by dagashiya** [AnySoftKeyboard/AnySoftKeyboard#579]
Hello,
would it be possible to assign letter ą to _"abc"_ key's popup in 16 key English layout and reassign ł to key _"jkl"_ instead of _"ghi"_? The former would make it possible to use all Polish diacritics with that layout and I think the latter would make more logical sense considering ł is a derivative of l (and not i).

**Comment by raaphal** [comment]
I second that.
