### ISSUE TITLE
Allow to switch dictionnaries the same way as keyboard layouts

### ISSUE THREAD

**Issue by pieleric** [AnySoftKeyboard/AnySoftKeyboard#582]
This is a feature request. Right now keyboard layout and dictionaries are considered more or less independent (each layout has a preferred dicitonary, but that's it). However, in some cases it'd be nice to switch to another dictionary the same way as of keyboard layout (eg, left/right swift on the space key).
There are two cases, which I both face:
- Some languages (eg, Dutch) use the US keyboard layout, so they don't have their own layout. Still, it'd be nice to switch between Dutch and English the same way as you switch between German and English.
- Some languages have keyboard layouts so similar but with small differences that it's annoying to have the layout changed just because you're writting in a different language. For instance, I prefer to write French and English with the same (US) keyboard layout, the same way that it works on a physical keyboard.

So it'd be nice to either:
- Be able to switch dictionaries by swift on the space key or via the "world" key
- Be able to "create" new keyboard layouts by selecting a layout and a dictionary.

**Comment by kertase** [comment]
Good feature enhancement needed!

Maybe would be nice to just be able to have multiple languages at once and have an option on keyboard to fast chose dictionary's.
