### ISSUE TITLE
Weird autocorrect behaviour

### ISSUE THREAD

**Issue by SassuWunnu** [AnySoftKeyboard/AnySoftKeyboard#585]
### Steps to reproduce
1.write a word misspelled
2.jump back cursor to correct it
3.Try correcting what you wanted to

### Expected behaviour
Nothing

### Actual behaviour
Word is inserted where the cursor is.

**Android OS version:**
6.1
**Device manufacturer and model:**
LG Nexus 5 2013
**List of installed add-ons (like languages, or themes):**
Hungarian

**Comment by menny** [comment]
thank for reporting.
I'll have this fixed for the new release.

**Comment by menny** [comment]
A nightly will be available in a few hours with a fix ready for testing, it would be nice if you can verify it.

Sign up for the beta here: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard

**Comment by SassuWunnu** [comment]
The issue is still there.  I type a word and hit space, then go back and
hit backspace inside the word. All the characters before the cursor are
deleted and the entire word is inserted in their place. For example:
Rectifyctify . This was supposed to be the word 'rectify'. Typing this I
realize the issue is much deeper. Writing this in the gmail app. The whole
previous words is deleted. Might be context dependent.

I have Hungarian layouts installed and am currently using one. Will try
investigating this further.

Ákos.

**Comment by menny** [comment]
Mmm, yes, this is harder than I thought.

**Comment by menny** [comment]
A new update will be available shortly in the _beta_ channel.

**Comment by SassuWunnu** [comment]
Seems to be solved. Thanks for all the effort you put into this app.

**Comment by menny** [comment]
Thanks for reporting.
