### ISSUE TITLE
Word list for Latvian language

### ISSUE THREAD

**Issue by ValdisVitolins** [AnySoftKeyboard/AnySoftKeyboard#586]
Regarding to your request for Latvian word list in AnySoftKeyboard, pleas look at list of Latvian words from LibreOffice dictionary (with suffix settings stripped out).
[lv-word-list.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/151630/lv-word-list.txt)

**Comment by friesenkiwi** [comment]
Thanks for the suggestion, @ValdisVitolins, it would have been a valid source, but for the sake of consistency, the latest Latvian pack incorporates the AOSP dictionary.
@menny this can be closed now.
