### ISSUE TITLE
Please return back ŗ and ō for Latvian layout

### ISSUE THREAD

**Issue by ValdisVitolins** [AnySoftKeyboard/AnySoftKeyboard#587]
### Steps to reproduce
1. Set up Latvian layout for keyboard
2. Check that no letters with diacritics marks are provided for r and o letters
### Expected behaviour

Letters ŗ and ō were removed from Latvian language during Soviet times.
Even reasoning was that it will make writing simpler, it actually worsened language rules because "simplification" added inconsistencies in many rules:
1. In consonant flexion (e.g. **egLe**, **egĻu**, and also should be: **vaRa**, **vaŖu**, not **vaRa**, **vaRu**),
2. homonyms where they should not be (e.g. **vaRu**, **vaŖu**, **gaRa**, **gaŖa** are different words),
3. no consistency how o is pronunciated (e.g. **koks** can be spelled as "_kuoks_" or "_koks_", **borons** is actually spelled as "_borōns_", etc.)
### Actual behaviour

Keyboard should propose entering diacriticized letters **ŗ** and **ō** for **r *\* and **o** accordingly.

**List of installed add-ons (like languages, or themes):**
Latvian language

**Comment by friesenkiwi** [comment]
@ValdisVitolins ŗ and ō are back now in the latest pack updates.
@menny this can be closed now.

**Comment by menny** [comment]
👍
