### ISSUE TITLE
Split dictionary and theme

### ISSUE THREAD

**Issue by homersimpsons** [AnySoftKeyboard/AnySoftKeyboard#590]
I think that splitting dictionary and keyboard theme (key) would be great for a better modular keyboard. The user would be allow to choose which dictionary to link with each keyboard.
For example I download:
- English and French dictionary
- Azerty, Qwerty, Qwertz, bépo layout
And then I choose:
English - Qwerty
English - Azerty
French - bépo
French - Azerty
With this method I can use an Azerty with English typing because I more often use Azerty

**Comment by menny** [comment]
Currently, they are separated:
The keyboard is declaring which _locale_ it is, and _AnySoftKeyboard_ tries to match a dictionary which has the same _locale_ to it.

Also, today, the user _can_ override this and ask for a specific dictionary to be used with a specific keyboard: long press **ENTER** and pick _Override default dictionary_.
