### ISSUE TITLE
keyboard default layout, and orientation change

### ISSUE THREAD

**Issue by akibaki** [AnySoftKeyboard/AnySoftKeyboard#592]
### Steps to reproduce
1. Set at least two layouts, that you can swich
2. Try to set the second one as default.
3. After you had choosed the second one try to change orientation(portrait-landscape)

### Expected behaviour
Tell us what should happen

1. To set a layout as default, for instance the hungarian one, instead of the english one, which has top order automatically. I mean,  when I start using keyboard it should be hungarian as default, instead of english, but I want to have english as secondary layout. 

2. When I change orientation, I expect the same layout to use.

### Actual behaviour
Tell us what happens instead

1. Always english layout turns up as default, I cannot change it.

2. When I change orientation, it resets the english layout, even if I use hungarian.

**Android OS version:**
4.4.4
**Device manufacturer and model:**

Jiayu S3

**List of installed add-ons (like languages, or themes):**

Hungarian
Italian
German
3D theme

**Comment by menny** [comment]
Try later beta for the fix.

Thanks for reporting.

**Comment by alexander255** [comment]
I'm using ASK 1.8.8 and can observe the keyboard layout being reset regularily as well. Rotating definitely triggers this, but it does't seem to be the only thing.
I'm also not sure were I'm supposed to set a “default layout”, but I'm consistently having to switch to it. Anybody know were that option is?

**Comment by trevor87** [comment]
Same here with ASK 1.8.1333 # 2658 on Lineage OS 14.1. This problem also occurs randomly when I change apps. Instead of german I regularly have the english setting.

@alexander255  I don't think that there is a setting for default layout, haven't found that myself yet.

**Comment by nicoursi** [comment]
Still same problem. Kind of annoying having to change layout everytime I'm using the keyboard
