### ISSUE TITLE
Can't press the popup keys! (when they are out of the keyboard area)

### ISSUE THREAD

**Issue by sabisab** [AnySoftKeyboard/AnySoftKeyboard#593]
### Steps to reproduce
1. Remove the keyboard top row (of the navigation keys).
2. Long press the letter "o", for getting two lines for popup keys.
3. Try to select one of the keys from the top line.
### Actual behaviour

The popup keys that are located above/outside the keyboard can't be reached by swiping the finger up.
Only if you swipe the finger up and then to left/right, it will work.

**Android OS version:**
5.0

**Device manufacturer and model:**
Samsung Note 3

**List of installed add-ons (like languages, or themes):**
None

**Comment by ArenaL5** [comment]
No longer a problem since the popup for the O key spans two rows.

Please close this issue.
