### ISSUE TITLE
Hebrew-english jump-switch

### ISSUE THREAD

**Issue by xomril** [AnySoftKeyboard/AnySoftKeyboard#607]
### Steps to reproduce
1.open any application when keyboard is already on 'hebrew' state (if its on english, try to switch to hebrew, close the keyboard and open it again)
2.hit any key

### Expected behaviour
Keyboard should remain on same state

### Actual behaviour
keyboard will (sometime) switch to english

**Android OS version:**
5.1
**Device manufacturer and model: **
xioami redmi note 2

**List of installed add-ons (like languages, or themes):**
Hebrew package

**Comment by menny** [comment]
I received many reports on this, but I was unable to reproduce this issue.
Can you try to find a case where you know it happens?

Also, can you try checking off _Languages_->_Remember alphabet layout per App_ ?
