### ISSUE TITLE
Package newer AnySoftKeyboard for F-Droid

### ISSUE THREAD

**Issue by alexander-b** [AnySoftKeyboard/AnySoftKeyboard#618]
The last update to AnySoftKeyboard in F-Droid[0] is three years old. It would be wonderful if F-Droid received the same treatment as Google Play. There are a lot of people out there that refuse to use Google Play, and F-Droid is the main package manager used by them.

It looks rather trivial to author F-Droid packages (as an example, here's the AnySoftKeyboard package: [1]), but I don't know a lot about building Java/Android projects myself.

It would also be nice to have more themes and languages available in F-Droid. I feel rather useless without a Dvorak layout!

Thank you for your time and consideration.

[0]  <https://f-droid.org/>
[1]  <https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.menny.android.anysoftkeyboard.txt>

**Comment by menny** [comment]
I really would like to get AnySoftKeyboard back on F-Droid, but the process is unclear to me.

**Comment by alexander-b** [comment]
I agree that it is unclear.

From what I can tell, you add packages to the repo[0] by forking it and submitting a pull request. It already has AnySoftKeyboard, with several antiquated releases, as you can see in my original post.

They have an FAQ for app developers[1] that has some valuable information, and a Server Manual[2] that seems to be somewhat relevant... but I really can't find any simple "how to package an app for F-Droid" guide. I will try to contact the F-Droid guys for more info.

[0]  <https://gitlab.com/fdroid/fdroiddata>
[1]  <https://f-droid.org/wiki/page/FAQ_-_App_Developers>
[2]  <https://f-droid.org/manual/fdroid.html>

**Comment by alexander-b** [comment]
The F-Droid guys linked me their CONTRIBUTING[0], which is a bit more focussed than the reference manual I previously linked. Does this help you?

[0]  <https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests>

**Comment by SvGeloven** [comment]
The asking on the F-Droid forum will get your questions answered quickly.

**Comment by menny** [comment]
working on this: https://gitlab.com/fdroid/fdroiddata/merge_requests/1527

**Comment by alexander-b** [comment]
This is excellent! Is there any chance of getting the dvorak layout into F-Droid as well? If it's a third-party thing, apologies for the noise -- I just heard there supposedly was one.

**Comment by menny** [comment]
Updated.
https://f-droid.org/repository/browse/?fdfilter=Anysoftkeyboard&fdid=com.menny.android.anysoftkeyboard
