### ISSUE TITLE
Cursor acts as if it's in another place

### ISSUE THREAD

**Issue by ashirviskas** [AnySoftKeyboard/AnySoftKeyboard#620]
### Steps to reproduce
1. Enable multitap special characters in other languages and word suggestions
2. Type a few fords
3. Go back those few words and make a double space
4. Type a word inbetween double space, the word must end with a special character, typed by multitaping (I.e. „Eglė” or „Liepą”)
5. Tap in the end of the string to place cursor in there
6. Press backspace
   ### Expected behaviour
   The last letter of the string should be deleted
### Actual behaviour

Cursor appears in the last place it's been — after the last special character (I.E. after Liepą) and then deletes the letter in a middle of this string.

I'm using Lithuanian language pack

**Comment by menny** [comment]
Can you try out the latest beta release?
Sign up here: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard
and download from the Play-Store

**Comment by ashirviskas** [comment]
I tried, same.
