### ISSUE TITLE
Make documentation Google Store independent

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#628]
Is it OK to make documentation Google Store independent? In other words talk about "app store" instead of "Google Play" in files such as https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/src/main/res/values/strings.xml and https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/src/main/res/values-nl/strings.xml ?

If yes, I am willing to provide a pull request for it.

**Comment by menny** [comment]
That makes sense, but I would suggest that this should come with the extra logic of performing actions (for example 'search') in the originating app-store.
If the app was installed from F-Droid, then it should perform add-ons and language packs search on F-Droid.

An easy way to find which app-store install the app, is by calling [PackageManager#getInstallerPackageName](http://developer.android.com/reference/android/content/pm/PackageManager.html#getInstallerPackageName(java.lang.String))

**Comment by PanderMusubi** [comment]
Some people have multiple app stores installed, no problem for Android. So split this off in app store independent documentation and an issue for app store independent search functionality

**Comment by menny** [comment]
sure

**Comment by PanderMusubi** [comment]
Done in https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/629

You can close this issue or recycle it for improving finding app store code.
