### ISSUE TITLE
Import words from SwiftKey

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#631]
Feature request to import words from SwiftKey. This can be run upon installation once or manually whenever the users feels like.

The files from SwiftKey with extentions .lm containing words are binary. The format is hinted by "Dynamic language model created in DynamicTermModel" in the beginning of the file. Files can also have the extension .lm1 .lm2 and .lm3

lm stands for language model and there will probably be an n-gram and/or word frequency list in the files.

**Comment by alekksander** [comment]
+1

**Comment by lindhe** [comment]
It would also be **great** to be able to build a dictionary from local SMS and/or e-mail and other services.

**Comment by yshalsager** [comment]
It seems that Swiftkey now allows to download a JSON file of user words from here https://data.swiftkey.com/view-data 
This may make migration and import easier.
