### ISSUE TITLE
[Request] Material icon launcher

### ISSUE THREAD

**Issue by M2ck** [AnySoftKeyboard/AnySoftKeyboard#632]
It would be nice to update current icon launcher to Material Design.

Possible to create an icon launcher easily via this tool: [Android Material Icon Generator](http://bitdroid.de/Android-Material-Icon-Generator/)
Source code: [Github.com/Maddoc42/Android Material Icon Generator](https://github.com/Maddoc42/Android-Material-Icon-Generator)

Example below (using purple color found in app & keyboard)
![ic_launcher](https://cloud.githubusercontent.com/assets/6850125/14495497/fedee4ec-018f-11e6-8488-78a9f453ae15.png)
[icons.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/217223/icons.zip)

**Comment by menny** [comment]
This is very nice. Thanks.
Could you add "ask" above the keyboard icon, but inside the purple square?

**Comment by M2ck** [comment]
Unfortunately no, the tool above doesn't allow to add custom text and myself I have no skills for it sorry.

**Comment by menny** [comment]
![ic_ask_launcher](https://cloud.githubusercontent.com/assets/481272/15881765/91c2f7f2-2d06-11e6-8e4e-f3af527f20c8.png)

**Comment by menny** [comment]
![ask_logo](https://cloud.githubusercontent.com/assets/481272/15917422/93814b38-2dca-11e6-90fb-65b96a0e8daa.png)

**Comment by M2ck** [comment]
Nice job, thanks!
