### ISSUE TITLE
Backspace deletes two characters

### ISSUE THREAD

**Issue by SassuWunnu** [AnySoftKeyboard/AnySoftKeyboard#633]
### Steps to reproduce
1.Type in more than one word.
2.Start deleting with backspace
3.After the first word is deleted, two characters get erased. Seems to affect facebook messenger only

### Expected behaviour
Only one char should be deleted

### Actual behaviour 
Two chars get deleted

**Android OS version:**
Lg Nexus 5 android 6.0.1.

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
Got a few reports on that.
Can you send over a video?

**Comment by menny** [comment]
Also, are you using any other language than English ?

**Comment by SassuWunnu** [comment]
I do not seem to be able to reproduce it even. Do you know a good capturing
app for Android if I figure out how? Also, yes, I am using Hungarian
layouts and and the so called logic keyboard is also installed. Unrelated,
but it seems keyboards appear erratically, sometimest the English layout
appears, sometimes not. Is that a feature? Maybe app dependent keyboard
layout, or last used?

**Comment by menny** [comment]
I've used https://play.google.com/store/apps/details?id=com.tools.screenshot&hl=en to record video from time to time. Works pretty well.

**Comment by SassuWunnu** [comment]
So you have to start typing, choose a suggestion and delete, that's when it happens and only in messenger for me.

**Comment by SassuWunnu** [comment]
Here you go hope this helps.

On Apr 14, 2016 18:00, "Menny Even Danan" <notifications@github.com> wrote:
>
> I've used
https://play.google.com/store/apps/details?id=com.tools.screenshot&hl=en to
record video from time to time. Works pretty well.

**Comment by menny** [comment]
Can you attach the video?

**Comment by SassuWunnu** [comment]
[
[
[issue.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/222234/issue.zip)
](url)
](url)

**Comment by menny** [comment]
This is so strange, I am unable to reproduce this at all, and I can't figure out why it would happen.
What happens if you clear AnySoftKeyboard's data? (make sure you backup your user words, just in case).

**Comment by SassuWunnu** [comment]
That helped.

**Comment by menny** [comment]
Problem solved? The beta version fixes your backspace issue?

**Comment by SassuWunnu** [comment]
Clearing the data did.

**Comment by menny** [comment]
Interesting

**Comment by hamid255** [comment]
Hi!
It still exists for me.
I have three languages installed: Persian, Turkish and English.
It just happens in KISS Launcher search bar and deleting the app data has not fixed it.
