### ISSUE TITLE
Status bar icons for some languages don't look right

### ISSUE THREAD

**Issue by mkarliuk** [AnySoftKeyboard/AnySoftKeyboard#636]
Keyboard icons in status bar for the following languages don't look right: russian, greek, belarusian.
Android 6.0.1
Nexus 5x
Language add-ons: Russian Language Pack by pelya, Greek Language Pack by Menny, Belarusian Language Pack by Ales Bulojcyk (alex73).

![screenshot_20160417-155558](https://cloud.githubusercontent.com/assets/17430343/14640929/8e57e2e8-064c-11e6-943c-1250a358b01d.png)
![screenshot_20160417-155602](https://cloud.githubusercontent.com/assets/17430343/14640931/8e7112cc-064c-11e6-96a3-2aaf1546a98a.png)
![screenshot_20160417-155606](https://cloud.githubusercontent.com/assets/17430343/14640933/8e88027a-064c-11e6-95a3-bb0ce1065fc4.png)
![screenshot_20160417-155617](https://cloud.githubusercontent.com/assets/17430343/14640934/8e8a6966-064c-11e6-88ca-f4ab833d3c4c.png)

**Comment by menny** [comment]
ya... that's not that cool. This icon is coming from the language pack, so that should be fixed there. You can try to hunt down the pack developers :)

In the next release the status-bar icon will be off by default.

**Comment by mkarliuk** [comment]
ok, i'll try. but it says that the greek pack is by you, right?

**Comment by menny** [comment]
That could be...
I'll take a look.

**Comment by mkarliuk** [comment]
many thanks!
