### ISSUE TITLE
Improve speed when loading dictionary

### ISSUE THREAD

**Issue by frankFic** [AnySoftKeyboard/AnySoftKeyboard#639]
Hello Menny,

I have found that `AsyncTask.execute` is used to load main dictionary and abbreviation dictionary in `setMainDictionary` in class Suggest. However, this API became slower on devices newer than Honeycomb. Tasks started by this API will be run sequentially in one thread instead of in real multiple threads. (Found in [API guide](http://developer.android.com/intl/zh-cn/reference/android/os/AsyncTask.html#execute(Params...))) So that abbreviation dictionary will be loaded after loading main dictionary finished.

Use executeOnExecutor instead will schedule tasks to real multiple threads and speed up this process.

Thanks.

**Comment by menny** [comment]
That's a good idea

**Comment by menny** [comment]
A beta build will be available shortly.
Signup for the beta channel: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard
