### ISSUE TITLE
problem import

### ISSUE THREAD

**Issue by Badash2** [AnySoftKeyboard/AnySoftKeyboard#644]
hi I'm trying  to import the project from github to andrid studio and the gradle say:

Bad   method call from inside of a branch Exception Details: Location: versionbuilder/GitVersionBuilder. (III)V @33: invokespecial Reason: Error exists in the bytecode Bytecode: 0x0000000: b800 123a 04b8 0018 9a00 06a7 001c 2a1b 0x0000010: 1c1d 1904 1219 3212 02b9 001f 0200 b800 0x0000020: 25b7 0028 a700 0d2a 1b1c 1db8 002c b700 0x0000030: 28b1 Stackmap Table: append_frame(@14,Object[#51]) same_frame(@39) full_frame(@49,{Object[#2],Integer,Integer,Integer,Object[#51]},{})  Consult IDE log for more details (Help | Show Log)

what to do?
### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by AnXh3L0** [comment]
Did you manage to import the project successfully? Please read the README as some changes have happened. Closing for now.
