### ISSUE TITLE
Feature request: Resizable keyboard height

### ISSUE THREAD

**Issue by ashirviskas** [AnySoftKeyboard/AnySoftKeyboard#648]
Basically the ability to change the size of the screen the keyboard uses. It would be really useful.

**Comment by menny** [comment]
This is already available: Go to User-Interface->Tweaks

**Comment by jerefeltan** [comment]
I am using the version 1.8.78 (v 1403) and I can't find the option "Keys height factor". It isn't in User-Interface -> Tweaks.

**Comment by menny** [comment]
Look under "Tweaks" in "Themes"

**Comment by jerefeltan** [comment]
I went to "User Interface" -> "Keyboard themes" and there are only images to choose, no other options.
I installed it from Google Play.
But later I installed it from F-Droid the version 1.8.84 (v1409). And now I see the option. The app in Google Play is old. Thanks.

**Comment by menny** [comment]
The version is Play Store is newer.
"Tweaks" are in the overflow menu (the three vertical dots at the top bar).

**Comment by jerefeltan** [comment]
That is not true for me in Android 4.1.2. Today 2016-09-13, Android version: 1.8.82 (v1407). F-Droid version: 1.8.146 (v1471). But I found the option in both.

**Comment by houindcon** [comment]
I also do not have the "three vertical dots" in the top bar and thus, can no longer adjust the size of my keys. Has this menu button been removed in he latest update? Very frustrating that my keys are stuck on very large size. Please advise?

**Comment by houindcon** [comment]
To clarify, in place of what USED to be the vertical dots, there is a "Search for add-ons" button in the top right now but no dots, no menu, no way to get to the size option...

**Comment by L1lith** [comment]
I have an s10e and I really need this feature as the keyboard basically takes up the entire screen, it's really annoying.
