### ISSUE TITLE
Keylogging or not

### ISSUE THREAD

**Issue by karencho777** [AnySoftKeyboard/AnySoftKeyboard#656]
Hello i have Android 4.2.2 i have intalled georgian and russian language packs and dark theme when i am turneng on anysoftkeyboard in system setings system gives an message that anysoft keyboard collecting personal ata keylogging so can you tell me why it saying it does anysoft keyboard keylogging

**Comment by menny** [comment]
Hey.
If you define a _keylogger_ as a software that keeps track on your keyboard typing and sends it off somewhere over the internet, then: NO!

AnySoftkeyboard does not record your key-strokes to send it off somewhere. We do record the typing (as words) to create personalized user-dictionary (to help you type faster), but this information is stored only inside your device and never goes out.
