### ISSUE TITLE
Quickly switching languages using lang-key, causes switch-loop

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#668]
### Steps to reproduce
1.quickly press the Lang-key several times
2.ASK will switch languages in a loop without stopping

**Android OS version:**
Android-N
**Device manufacturer and model:**
Nexus 5X
**List of installed add-ons (like languages, or themes):**
English,Hebrew

**Comment by Tahvok** [comment]
Have the same issue.
Android OS version:
Android 6.0.1
Device manufacturer and model:
One plus one
List of installed add-ons (like languages, or themes):
English,Colemak,Hebrew,Russian

**Comment by menny** [comment]
Expect a beta release shortly.
Sign up here: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard

**Comment by Tahvok** [comment]
Latest beta looking good.
Will keep myself on beta to catch problems before they are released.

**Comment by menny** [comment]
That would be very helpful
