### ISSUE TITLE
Error:(198) *** Android NDK: Aborting...    .  Stop.

### ISSUE THREAD

**Issue by monowar1993** [AnySoftKeyboard/AnySoftKeyboard#672]
Facing the following error when importing project.

Error:Execution failed for task ':jnidictionaryv1:compileReleaseNdk'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'G:\Android\sdk\android-ndk-r12b\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by fakefacebook** [comment]
Same Problem @monowar1993  are you solve it?

**Comment by monowar1993** [comment]
nope. not yet.

**Comment by fakefacebook** [comment]
I can solve it

**Comment by menny** [comment]
Can you share the solution?

**Comment by fakefacebook** [comment]
Nothing to do for that ... 
<img width="727" alt="ndk-install_2-2_2x" src="https://cloud.githubusercontent.com/assets/20983834/19407411/2fcfc1d2-92bf-11e6-94a4-873e376476b3.png">

1). as shown in picture update this three things
2). And move Ndk into My root directory to My D:\  drive then REbuild Project 

(Make Sure No one Space can be allowed in NDK Location)

Then It Can Be Solve This Error

**Comment by mahirekici** [comment]
Hi
@menny @fakefacebook  i have this problem

Warning:Deprecated NDK integration enabled by useDeprecatedNdk flag in gradle.properties will be removed from Android Gradle plugin soon.
/Volumes/SNur/android/sdk2016/ndk-bundle/build/core/add-application.mk
Error:(198) *** Android NDK: Aborting...    .  Stop.
Error:(198) *** Android NDK: Aborting...    .  Stop.


Help me please

me dradle console


Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv1/build/intermediates/ndk/release/Android.mk    

Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv2/build/intermediates/ndk/release/Android.mk    


/Volumes/SNur/android/sdk2016/ndk-bundle/build/core/add-application.mk:198: *** Android NDK: Aborting...    .  Stop.

/Volumes/SNur/android/sdk2016/ndk-bundle/build/core/add-application.mk:198: *** Android NDK: Aborting...    .  Stop.


:jnidictionaryv1:compileReleaseNdk FAILED
:jnidictionaryv2:compileReleaseNdk FAILED

Note: /Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/base/src/main/java/com/anysoftkeyboard/base/utils/CompatUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':jnidictionaryv1:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: Error while executing process /Volumes/SNur/android/sdk2016/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv1/build/intermediates/ndk/release/Android.mk APP_PLATFORM=android-25 NDK_OUT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv1/build/intermediates/ndk/release/obj NDK_LIBS_OUT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv1/build/intermediates/ndk/release/lib APP_ABI=all}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':jnidictionaryv2:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: Error while executing process /Volumes/SNur/android/sdk2016/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv2/build/intermediates/ndk/release/Android.mk APP_PLATFORM=android-25 NDK_OUT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv2/build/intermediates/ndk/release/obj NDK_LIBS_OUT=/Volumes/SNur/Mobil Uygulama Projeler/Osmanlıca Klavye Çalışması/AnySoftKeyboard-1.8-r7.1/jnidictionaryv2/build/intermediates/ndk/release/lib APP_ABI=all}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUİLD FAILED

Total time: 2.665 secs

**Comment by shoaibakram-regexsoft** [comment]
Hi @mahirekici Have you resolved this issue "NDK_PROJECT_PATH = null"

**Comment by DenBond7** [comment]
Hello, I resolved this problem for me. I just remove project to root folder of local disk (in my case E:/).

**Comment by imrananeuronsolutions** [comment]
Hi i have the same issue ...

Anyone has resolved ?

**Comment by imrananeuronsolutions** [comment]
> 
> 
> I can solve it

Please suggest , if you can solve this.

**Comment by menny** [comment]
Which version of NDK are you using? AnySoftKeyboard should be built with NDK 14b

**Comment by imrananeuronsolutions** [comment]
Pkg.Desc = Android NDK
Pkg.Revision = 18.1.5063045

**Comment by menny** [comment]
You should use 14b.
AnySoftKeyboard is targeting Android devices all the way back to API level 9, and the last NDK version that supported that was 14b

**Comment by harsh023** [comment]
/home/quad11/Android/Sdk/ndk-bundle/build/core/add-application.mk:88: *** Android NDK: Aborting...    .  Stop.

**Comment by menny** [comment]
Are you using the correct NDK version? You should use 14b.

**Comment by harsh023** [comment]
I have got this error while using NDK 19

Error while executing process /home/quad11/Downloads/android-ndk-r14b-linux-x86_64/android-ndk-r14b/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/quad11/Documents/Quad/Complete Project/MusicEditor/app/Android.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=/home/quad11/Documents/Quad/Complete Project/MusicEditor/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/home/quad11/Documents/Quad/Complete Project/MusicEditor/app/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /home/quad11/Documents/Quad/Complete Project/MusicEditor/app/Android.mk    

/home/quad11/Downloads/android-ndk-r14b-linux-x86_64/android-ndk-r14b/build/core/add-application.mk:198: *** Android NDK: Aborting...    .  Stop.

**Comment by harsh023** [comment]
Not to solve that problem when i'm using ndk 14b

**Comment by vaibhavsonu** [comment]
I also having issue Please guide me how to solve
