### ISSUE TITLE
Behavior of gesture action "Switch layout mode" has changed

### ISSUE THREAD

**Issue by tompinkas** [AnySoftKeyboard/AnySoftKeyboard#678]
### Steps to reproduce
1. set up swipe down action to "Switch layout mode"
2. have more then 1 keyboard installed
3. perform swipe down action repeatedly

### Expected behaviour
- in ASK version 20130919 (v111) it switched to symbols keyboard and then after second swipe down action it switched back to alphabet keyboard

### Actual behaviour
- in ASK version 1.8.84 (v1409) it cycles through available keyboards
- conclusion: I can't have one gesture to cycle between alphabet and symbols on one keyboard (I have to have two gestures: Next alphabet keyboard and Next symbols keyboard)

**Android OS version:**
Android 4.2.2

**Device manufacturer and model:**
Sencor Element 

**List of installed add-ons (like languages, or themes):**
AnySoftKeyboard - Czech Language Pack (20120114-yzvszy)
SSH for AnySoftKeyboard (0.4.20120611-beta)

**Comment by menny** [comment]
thanks for reporting. I'll fix it for the next release.

**Comment by menny** [comment]
I'm curious, have you downloaded the app from F-Droid?

**Comment by tompinkas** [comment]
Yes, it was from F-Drops... Tom

Dne úterý 19. července 2016 Menny Even Danan <notifications@github.com>
napsal(a):
