### ISSUE TITLE
Build broken after move to app/

### ISSUE THREAD

**Issue by mvdan** [AnySoftKeyboard/AnySoftKeyboard#689]
We used to build in F-Droid like this:

`gradle makeEnglishDictionary assembleRelease`

Since you moved to `app/`, we're now running it in there. I had to modify the steps to these for it to work, since you didn't move the dictionary task:

`gradle :makeEnglishDictionary assembleRelease`

Which then fails:

```
* What went wrong:
Execution failed for task ':makeEnglishDictionary'.
> Could not get unknown property 'android' for root project 'com.menny.android.anysoftkeyboard' of type org.gradle.api.Project.
```

If the answer to this is "run it from the root of the repo", then having the app subdir makes no sense at all.

**Comment by menny** [comment]
Thanks for reporting.
Fixed with https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/fc97deb9ec8579ef716b16333afcd178d87563f0

**Comment by mvdan** [comment]
FWIW I need a tag/release with that fix, otherwise we can't update the app.

**Comment by menny** [comment]
Of course, I'll release a new version soon, and f-droid will get a tag too
