### ISSUE TITLE
[Vietnamese] Support telex typing

### ISSUE THREAD

**Issue by duypeng9** [AnySoftKeyboard/AnySoftKeyboard#696]
Hi all,
At first, this is the vietnamese alphabet: a, ă, â, b, c, d, đ, e, ê, g, h, i, k, l, m, n, o, ô, ơ, p, q, r, s, t, u, ư, v, x, y and 05 accent marks: acute accent("´"), grave"`"), hook(" ̉ "), tilde("~") and dot(".")

And these are some telex typing rules:
aa = â
aw = ă
ew = ê
oo = ô
ow = ơ
dd = đ
uw = ư
Typing 05 diacritics (or accent marks):
-To add acute accent: S, for example: as=á.
-To add grave accent: F, for example: af=à
-To add hook accent: R, for example: ar=ả
-To add tilde accent: X, for example: ax=ã
-To add dot accent: J, for example: aj=ạ.

More example: if we want to write Việt Nam, need to type: Vieetj Nam or Vieejt Nam or Vietej Nam or Vietje Nam.

google keyboard version 5.0.1 (file apk on CHplay ) supported typing but i can't find google keyboard source code version 5.0.1
can you help me?

**Android OS version:**
6.0

**Comment by ddtuan99** [comment]
Hey i'm trying to find out how to implement it. Do you have any idea?

**Comment by sh000gun** [comment]
@duypeng9 @ddtuan99 Take a look here as my telex integration

https://github.com/sh000gun/vietnamese-anysoftkeyboard

**Comment by ddtuan99** [comment]
@sh000gun thanks for your effort. Would you like to publish it on FDroid?
