### ISSUE TITLE
"Light" vibration feedback is not light at all

### ISSUE THREAD

**Issue by ClaudeSpeed** [AnySoftKeyboard/AnySoftKeyboard#698]
### Steps to reproduce
1. In menu "Effects" choose "light" vibration mode
2. Press keys on AnySoft keyboard
### Expected behaviour

I expect the vibration feedback at every keystroke to be very light/soft, hardly perceptible, like it is the case at the original Samsung keyboard.
### Actual behaviour

Instead the feedback is rather hard, in fact loud. The other two vibration options medium and strong are even stronger of course. Please, either adjust the "light" option to be really light, or add a "super light" option. 

**Android OS version:**
6.0.1

**Device manufacturer and model:**
Samsung Galaxy S7

**List of installed add-ons (like languages, or themes):**

**Comment by grenzor** [comment]
Agreed. Possibly a 'Very Light' option for this would be good?

**Comment by simomat** [comment]
As a workaround, I exported settings, changed the value for "vibrate_on_key_press_duration" and imported settings again. The lowest default value is 17, I was satisfied with 8.

**Comment by stanelie** [comment]
Thanks for the workaround,  works for me too, even if not very user friendly
