### ISSUE TITLE
Please document creating new layouts

### ISSUE THREAD

**Issue by marmistrz** [AnySoftKeyboard/AnySoftKeyboard#699]
Issue #646 complains that the Polish language pack is not working. But, anyway, the dictionary bundled with the language pack is poor (tried with the Hacker's keyboard), so I'm thinking about creating the Polish language pack from scratch.

But there's absolutely no documentation how to create one. Can you please make one?

**Comment by ArenaL5** [comment]
This issue's really old and already solved. There is (https://github.com/AnySoftKeyboard/LanguagePack)[some documentation in the `README.MD` for LanguagePack] now, and I can confirm it's enough to create a custom keyboard plugin with different symbols.

You'll need to install and learn to use Gradle, though. I barely managed using the provided `gradlew` script.

Could someone close this issue?

**Comment by marmistrz** [comment]
The instructions look legit. Thanks!
