### ISSUE TITLE
The gesture actions are unclear and difficult to set

### ISSUE THREAD

**Issue by marmistrz** [AnySoftKeyboard/AnySoftKeyboard#700]
I have no idea what in fact do the following: "Next in current mode", "Swtich layout mode", "Cycle through all keyboards".

Besides, I'd like to set up the following gesture system: swipe left/right takes next keyboard layout (Polish, English, SSH). Swiping the space bar toggles the symbols keyboard. It seems impossible to achieve it. Is it really so?

**Comment by AnXh3L0** [comment]
Thanks for opening this issue @marmistrz, we will be working on improving the settings UI and the UX in general. Closing for now.
