### ISSUE TITLE
No Autocomplete/prediction in browsers 

### ISSUE THREAD

**Issue by slipslider** [AnySoftKeyboard/AnySoftKeyboard#701]
Android 6.01 Sony Xperia Z3 Compact
Love Anysoftkeyboard, except...
Auto Complete/prediction doesn't work when I use it in a browser (Apus, CM, Firefox) and I can't see any way to make it happen.
Why? And is there a way?
Bzzzup! BB

**Comment by menny** [comment]
In which inputs boxes does it not predict? In the web address text-box? Or in the webpage itself?

**Comment by slipslider** [comment]
Hi Menny,

Anysoftkeyboard doesn't predict/suggest anything when I use it in any 
text box in a brower - Search box, Forms, etc.

ie. The top line that comes up on top of the keyboard everywhere else 
with suggestions/predictions, is on top when using the keyboard in a 
browser, but no suggestions/predictions.

BB

**Comment by menny** [comment]
I installed the latest Firefox and the latest ASK beta.
Then, went to https://www.twitter.com and clicked the SEARCH icon.
Started type "he" and got suggestions (e.i., hell, he'll, hello, etc.)
