### ISSUE TITLE
Crash while writing

### ISSUE THREAD

**Issue by akistartio** [AnySoftKeyboard/AnySoftKeyboard#703]
This crash report occurs when typing 2 or 3 letters.
If predictive text is off, the error does not occur.

Hi. It seems that we have crashed.... Here are some details:
*****\* UTC Time: 23:11:39 11.09.2016
*****\* Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.8.146 release 1471. Installed on 1473628086957, first release installed was 1471.

---

*****\* Exception type: java.lang.NullPointerException
*****\* Exception message: Attempt to write to null array
*****\* Trace trace:
at com.anysoftkeyboard.g.a.a(IMEUtil.java:88)
at com.anysoftkeyboard.AnySoftKeyboard.d(AnySoftKeyboard.java:50285)
at com.anysoftkeyboard.j.handleMessage(KeyboardUIStateHandler.java:65)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5683)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

---

*****\* Device information:
BRAND:bq
DEVICE:Aquaris_A45_sprout
Build ID:2.8.0-20160811-1650
changelist number:MRA58K
MODEL:Aquaris_A4.5
PRODUCT:Aquaris_A45
TAGS:dev-keys
VERSION.INCREMENTAL:1470905006
VERSION.RELEASE:6.0
VERSION.SDK_INT:23
Locale:es_ES
configuration:{1.1 214mcc1mnc es_ES ldltr sw360dp w360dp h568dp 240dpi nrml port finger -keyb/v/h -nav/h s.34}
That's all I know.******************************
*****\* Log-Cat:
Not supported in RELEASE mode!

**Comment by menny** [comment]
any additional information?
Does it happen in a specific layout?

**Comment by akistartio** [comment]
This crash occurs in all layouts. Appears a message that says:
Unfortunately, there is a problem with AnySoftKeyboard. Do not panic, there is something you can do to help resolve this: send us the crash report and we'll do our best to solve this crash and get you back with an awesone keyboard experience!

**Comment by menny** [comment]
very strange. Which languages do you have installed?

**Comment by akistartio** [comment]
English, Spanish and Catalan. My usual language is Spanish.

**Comment by ArenaL5** [comment]
This is a three-year-old bug and I believe code has been added to fix it. Does it still happen?

**Comment by akistartio** [comment]
Hello. 
I don't know if it's been fixed, because I changed my phone. In the new phone I also use anysoftkeyboard and I don't have any problem.
