### ISSUE TITLE
Add interrobang (‽)

### ISSUE THREAD

**Issue by steelman** [AnySoftKeyboard/AnySoftKeyboard#704]
Please make it possible to type in an interrobang (‽).

Please visit http://www.shadycharacters.co.uk/series/the-interrobang/

**Comment by menny** [comment]
www.fileformat.info/info/unicode/char/203d/index.htm

**Comment by menny** [comment]
will be available when long-pressing `?` or `!` in the symbols layout.

**Comment by menny** [comment]
sign up for beta here: https://play.google.com/apps/testing/com.menny.android.anysoftkeyboard
