### ISSUE TITLE
Slow layout/language change

### ISSUE THREAD

**Issue by Tahvok** [AnySoftKeyboard/AnySoftKeyboard#711]
### Steps to reproduce

Change layout.
### Expected behaviour

It would have changed really fast.
### Actual behaviour

It takes more than a second to change now. It's really is a problem when using multiple layouts, so it's really annoying to change forth and back now.

**Android OS version:**
6.0.1
**Device manufacturer and model:**
Oneplus one
**List of installed add-ons (like languages, or themes):**
English, Russian, Hebrew, Alternative (using colemak)

**Comment by menny** [comment]
Two questions:
1. How many words do you have in your User-Dictionary?
2. What happens when you start typing immediately when the layout changes? Does it provide suggestions?

**Comment by Tahvok** [comment]
1. 10

2. only on second character

Also, I forgot to.mention that I'm on beta, and I think it started with latest update, but I might be wrong..

Your input on dictionaries made me check change speed from qwerty to colemak. It actually is much faster than changing a language (like from hebrew to russian).

**Comment by AnXh3L0** [comment]
Hello @Tahvok, does this still happen with the latest beta/stable version of ASK for you?

**Comment by albertpx** [comment]
No, it's not the case for a long time already.. 
I had other issues, like the keyboard used to crash when changing layout, but I didn't have this issue for a few weeks now either.
I'm using the beta btw.

**Comment by menny** [comment]
Thanks for following through
