### ISSUE TITLE
Keyboard layout is reset on orientation change

### ISSUE THREAD

**Issue by alexander255** [AnySoftKeyboard/AnySoftKeyboard#713]
### Steps to reproduce
1. Install ASK 1.8.84 and set it as default IME
2. Enable a second keyboard layout in the settings
3. Select any input text field to make ASK visible
4. Switch to the previously enabled, secondary keyboard layout
5. Rotate device by 90°
### Expected behaviour

The keyboard layout should be resized, nothing else
### Actual behaviour

ASK switches back to the default, english keyboard layout (and resizes that)

This is identical to #592.

**Android OS version:
Android 6.0.1 / CyanogenMod 13.0
(unofficial release, actually NightOwl 13)

**Device manufacturer and model:**
Samsung Galaxy Note I (n7000)

**List of installed add-ons (like languages, or themes):**
Neo 2 keyboard layout

**Comment by menny** [comment]
I'm unable to reproduce this at all.

Can you provide more information? Anything.

**Comment by alexander255** [comment]
Thanks for responding!

I retried this on a *LG Optimus 2X (p990)* using CyanogenMod 11.0 (Android 4.4.4) and it's still 100% reproducible. Current ASK version is *1.8.195* (as obtained by F-Droid).
Also the layout switch doesn't happen immediately on rotation, but shortly afterwards, so there is a split-second where the old layout is still visible. (Invisible on more modern devices such as the *Galaxy Note I*.)

Just to be sure I retried with NEO2 uninstalled and ASK restarted and recorded the following `logcat` while it happened:

    E/AudioPolicyManagerBase(  114): stopOutput() output 4, stream 1, session 277
    E/AudioPolicyManagerBase(  114): changeRefCount() stream 1, count 0
    E/AudioPolicyManagerBase(  114): getNewDevice() selected device 0
    E/AudioPolicyManagerBase(  114): setOutputDevice() output 4 device 0 delayMs 0
    E/AudioPolicyManagerBase(  114): setOutputDevice() setting same device 0 or null device for output 4 prevDevice=2
    I/InputReader(  460): Reconfiguring input devices.  changes=0x00000004
    I/InputReader(  460): Device reconfigured: id=3, name='star_synaptics', size 480x800, orientation 1, mode 1, display id 0
    I/ActivityManager(  460): Config changes=480 {1.0 232mcc11mnc de_AT ldltr sw320dp w533dp h294dp 240dpi nrml long land finger -keyb/v/h -nav/h s.29 themeResource=null}
    D/PhoneStatusBar(  614): mSettingsPanelGravity = 55
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() strategy=3, device=2
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() from cache strategy 3, device 2
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() strategy=0, device=2
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() from cache strategy 0, device 2
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() strategy=2, device=2
    V/NvAudioALSAPolicyManager(  114): getDeviceForStrategy() from cache strategy 2, device 2
    V/NvAudioALSAStreamOut(  114): standby: IN
    V/NvAudioALSARenderer(  114): stop
    V/NvAudioALSA(  114): [NVALSA] NvAudioALSADevClose() hDev=0x438f1140
    V/NvAudioALSA(  114): [NVALSA] Closing ALSA device!, curDev[0x2], curMode[0] HPCM[0x4007bcb0]
    I/ASK_KF  ( 3269): Creating enabled addons list. I have a total of 3 addons
    W/WindowManager(  460): Window freeze timeout expired.
    W/WindowManager(  460): Force clearing orientation change: Window{42381fa0 u0 InputMethod}
    W/WindowManager(  460): Force clearing orientation change: Window{41f3abd8 u0 com.android.systemui.ImageWallpaper}
    I/Choreographer(  811): Skipped 92 frames!  The application may be doing too much work on its main thread.
    W/IInputConnectionWrapper(  811): showStatusIcon on inactive InputConnection
    I/Timeline(  460): Timeline: Activity_windows_visible id: ActivityRecord{41f43240 u0 fr.neamar.kiss/.MainActivity t1} time:42628221
    I/WindowManager(  460): Screen frozen for +2s428ms due to Window{426ad878 u0 fr.neamar.kiss/fr.neamar.kiss.MainActivity}
    I/Choreographer(27477): Skipped 64 frames!  The application may be doing too much work on its main thread.
    W/InputMethodManagerService(  460): Illegal subtype state: old subtype = null, new subtype = android.view.inputmethod.InputMethodSubtype@423dc666
    W/IInputConnectionWrapper(  811): getCursorCapsMode on inactive InputConnection
    I/ASK_KF  ( 3269): Creating enabled addons list. I have a total of 3 addons
    I/Choreographer( 3269): Skipped 177 frames!  The application may be doing too much work on its main thread.
    W/InputMethodManagerService(  460): Illegal subtype state: old subtype = null, new subtype = android.view.inputmethod.InputMethodSubtype@423dc666
    W/IInputConnectionWrapper(  811): finishComposingText on inactive InputConnection
    W/IInputConnectionWrapper(  811): finishComposingText on inactive InputConnection
    W/IInputConnectionWrapper(  811): finishComposingText on inactive InputConnection
    I/Timeline(  811): Timeline: Activity_idle id: android.os.BinderProxy@41d1c8e8 time:42629563

I also generated a trace involving this behaviour.

It there anything else that might help getting this debugged?

**Comment by trevor87** [comment]
Same here with ASK 1.8.1333 # 2658 on Lineage OS 14.1. This problem also occurs randomly when I change apps. Instead of german I regularly have the english setting.

Is there anything I can do to help debug this problem?

Thanks

**Comment by alexander255** [comment]
Still occurs on all of my devices, too. I found a workaround however: It turns out that if you long-press on any keyboard layout in the settings you can rearrange the given layout. So if you move the given layout to the top ASK will start glitching toward that layout instead of the default english one. Works for me…™

**Comment by trevor87** [comment]
@alexander255 Thanks for the workaround, also works for me now!

**Comment by Mikaela** [comment]
I see this or something similar on OnePlus 3 with Android 8.0 (OP3_O2_BETA_39) and Nokia 1 with Android Go 8.1.0 on Nokia 1 (TA-1047). 1.9.2481 from Play Store Beta.

When I close apps or open them or just somehow hide and open the keyboard a lot, the layout is reset to Colemak. However on Android 1 I had to do it more to trigger this. The workaround works on OP3, I didn't test Nokia1 yet.

**Comment by GitHorst** [comment]
@menny can you please reopen this -- the issue still exists. _might_ be related to #2970
