### ISSUE TITLE
In the English layout, colon is inserted before the sign before the cursor

### ISSUE THREAD

**Issue by marmistrz** [AnySoftKeyboard/AnySoftKeyboard#715]
### Steps to reproduce
1. type space
2. long press the comma to get the colon
### Expected behaviour

the colon appears after the space
### Actual behaviour

the colon appears before the space

**Android OS version:**
CM 13.0 
**Device manufacturer and model:**
OnePlus3
**List of installed add-ons (like languages, or themes):**
Using plain dark theme.

**Comment by marmistrz** [comment]
The problem above appeared only if there was a space before the cursor.

The same happens if the combination <space> <dot> is inserted: the dot is inserted before the space.

**Comment by menny** [comment]
I can't reproduce this.
Can you provide video? Or more specific repro sequence?

**Comment by marmistrz** [comment]
Ok, I see that it's not 100% reproducible.

But I'm able to always reproduce it when trying to type `aaa .`

What I get is always  `aaa. `

Using the built-in English keyboard
-- 
Marcin

**Comment by marmistrz** [comment]
I discovered that there's an option called "swap space and punctuation". I think it's a better idea to have it disabled by default.
