### ISSUE TITLE
Add button Get it on F-Droid on website

### ISSUE THREAD

**Issue by PanderMusubi** [AnySoftKeyboard/AnySoftKeyboard#720]
On https://anysoftkeyboard.github.io/ add a button Get it on F-Droid as is in the README of https://github.com/AnySoftKeyboard/AnySoftKeyboard

Please, also enable issues for https://github.com/AnySoftKeyboard/AnySoftKeyboard.github.io

For more background info on these buttons, see https://gitlab.com/fdroid/fdroidserver/issues/168

**Comment by menny** [comment]
done
