### ISSUE TITLE
New password keyboard issue

### ISSUE THREAD

**Issue by Sp3EdeR** [AnySoftKeyboard/AnySoftKeyboard#730]
### Steps to reproduce
I have been using the Hungarian keyboard layout with the basic 4 lines of text and control buttons. Once the password number line update came, I get the additional number line above the keyboard as normal. However in portrait mode, the bottom line of buttons are no longer visible (shift, space, enter, etc.).

### Expected behaviour
In all cases, the default keyboard lines are visible.

### Actual behaviour
In portrait mode, the bottom line of buttons is no longer visible when typing into password fields.

**Android OS version:**
6.0.1
**Device manufacturer and model:**
Samsung Galaxy S7
**List of installed add-ons (like languages, or themes):**
Lean Dark - Large Keys
Hungarian QWERTZ layout with 3 lines

**Comment by menny** [comment]
Is it visible in landscape mode?

**Comment by Sp3EdeR** [comment]
Hello!

Yes, it is visible in landscape mode, I get 5 lines of buttons total.

But it seems to have a weird behaviour for the top line of buttons... (This seems to be a separate issue from the above and may need another ticket.) Please note that my landscape keyboard is set to non-fullscreen mode, so I can interact with the window while it is up.
When focusing the password field, I get the number line on the top. If I leave keyboard up and switch from the password field to a normal text field, the top line of buttons stays up, and the top buttons switch to a symbolic input line.
If I initially focus a text input field, the top line of buttons does not appear, but if I leave the keyboard up and switch over to the password field, the top number-bar does NOT appear. The switching inconsistency applies to the portrait keyboard too. It only applies when switching from text-to-password field and the issue does not happen when switching from numeric-to-password field.

**Comment by Sp3EdeR** [comment]
Oh and upon switching from text keyboard view to symbolic keyboard view, the bottom line appears in portrait mode. That keyboard view inherently contains a numeric line of buttons, so this view shows double numeric line.

btw, is there an option with which it is possible to disable the new password-number feature? The issue requires me to switch keyboards to access a certain portait-only application. :)

**Comment by pcroland** [comment]
I have the same issue. [Here](https://imgur.com/a/g4W75) are some pictures. On the first screenshot you can see the old keyboard, on the second you can see the new keyboard where the Shift, the ü and ö are not available.

**Comment by Sp3EdeR** [comment]
That is strange. For me, the whole bottom row of buttons is missing. We have somewhat different behaviours.

**Comment by menny** [comment]
Please make sure you are updated to the latest release. This issue was addressed.

**Comment by pcroland** [comment]
The whole bottom row was missing for me as well. Until it get solved I made a Titanium Backup, installed an older version and restore the data for that one. And now when I updated the app for make the screenshots the bottom row was looking like that.

**Comment by pcroland** [comment]
@menny The screenshot of the error is taken from the latest update. I literally update it 5-6 minutes ago :D

**Comment by Sp3EdeR** [comment]
Ah yes, I'm sorry. My behaviour is now almost the same as pcroland's behaviour. The shift and special keys are missing, but I do see a microphone button as extra.

**Comment by menny** [comment]
That's a bug with the Hungarian language pack, which is now incompatible with the latest version of AnySoftKeyboard.

I've emailed the developer.

**Comment by pcroland** [comment]
There probably won't even get the e-mail I think. The MobiWIA Kft. company is not active as I see. But until than we can use an older version. 

By the way, is there any chance that you will add an option to disable the password keyboard option?

**Comment by Sp3EdeR** [comment]
As far as I see, the Hungarian extension is open source and under GPL license, tracked at:
https://github.com/rhornig/anysoftkeyboard-hungarian

So if the author really is inactive, a fork and an update would easily be possible. Of course since I don't know what became incompatible and I'm not familiar with the plugin interface, I don't think I could update it in an easy way... :)

**Comment by pcroland** [comment]
@Sp3EdeR, by the way the same error is present when typing links in browsers: [LINKħ(https://i.imgur.com/wyXwvL6.png)
You can type ö and ü by longpressing on o and u, but when it comes to uppercase letters in links you have to type it in somewhere else and then paste it. This should be fixed as well I think.

**Comment by Sp3EdeR** [comment]
Is there anyone who knows where I could find a 1.8 r4 release? :\

**Comment by pcroland** [comment]
[https://apkplz.com/android-apps/anysoftkeyboard/anysoftkeyboard-1-8-56](https://apkplz.com/android-apps/anysoftkeyboard/anysoftkeyboard-1-8-56)

**Comment by menny** [comment]
You find that on F-Droid.

**Comment by pcroland** [comment]
Why is there a 1.8.[numbers] and a 1.8 r[number] line in updates? Sorry for the dumb question.

**Comment by menny** [comment]
Got an email back from the developer of the Hungarian language pack.
They fixed the issue: https://github.com/rhornig/anysoftkeyboard-hungarian/commit/5e9cb674c1f13c7b8cceb437e484337c611f5ef5

and have released an updated version of the language pack to the play-store. Should be available shortly.
