### ISSUE TITLE
schifted backspace without shift

### ISSUE THREAD

**Issue by jknockaert** [AnySoftKeyboard/AnySoftKeyboard#738]
When enabling shifted backspace to delete words rather than single characters upon shift+backspace, the specified behaviour (deleting words rather than single characters) also happens upon backspace without shift.
This changed after a recent update of the app.

**Comment by menny** [comment]
Thanks for reporting
I'll fix this quickly

**Comment by menny** [comment]
Fixed here: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/741
