### ISSUE TITLE
[Request] Hide emoji key

### ISSUE THREAD

**Issue by christarazi** [AnySoftKeyboard/AnySoftKeyboard#740]
I was wondering if there was a way to hide the emoji key. I don't use emojis and I'd like expand the size of the space-bar at the expense of the emoji button.

**Comment by mimf** [comment]
I would also like this, and would also like to hide the keyboard key, when in landscape.

**Comment by menny** [comment]
There isn't a freeform functionality, but there are several options for
generic bottom row. Look for it in the settings app

**Comment by mimf** [comment]
@menny, none of which hides the emoji key, which is what this issue is about.

**Comment by menny** [comment]
The `iPhone` styles do not have emojis. right?

**Comment by christarazi** [comment]
Where do I find the iPhone styles?

**Comment by landry314** [comment]
in the anysoftkeyboard settings, under user interface tap even more... then common generic bottom row. there are the iphone styles.
