### ISSUE TITLE
Cannot disable top row numbers in latest update

### ISSUE THREAD

**Issue by 5nefarious** [AnySoftKeyboard/AnySoftKeyboard#745]
**EDIT:**
It seems that the issue does not appear in all text fields. The only place I am noticing it currently is in the search field for the KISS launcher.
### Steps to reproduce
1. Installed latest version from F-Droid
2. Navigate to "Even more..." in the User Interface section of the ASK settings app.
3. Set "Common top generic row" to "No top row"
### Expected behaviour

Top generic row should disappear.
### Actual behaviour

No difference between "No top row" and "Numbers keys." Additionally, selecting "Small keys" causes the small keys to display above the number keys rather than replacing them.

**Android OS version:**
6.0 Marshmallow

**Device manufacturer and model:**
Motorola Moto X Pure

**List of installed add-ons (like languages, or themes):**
English, Tamil Keyboard (David Shenba)

**Comment by Pacien** [comment]
Experiencing the same issue in KISS Launcher and Turbo Editor on Android 5.1.

**Comment by Tony-il-Capo** [comment]
I think that was an added feature to 'facilitate' inserting passwords, you can see it on v1.8-r5 update log, it should only show up in a password field.

In my opinion, I think should be an option in settings to disable this. When I need to insert numbers I always use long press keys or switch to numeric keyboard, it's fast and not as intrusive as having the numbers top row on screen. 

On small screen devices it makes keyboard too big, making it very annoying.

**Comment by LugiaDepression** [comment]
>>

**Comment by LugiaDepression** [comment]
@inefarius @Tony-il-Capo @Pacien  I'll be damned, but I FOUD now how I we can disable that row. I prepared to delete the whole app but noted my setting before, and I found it accidentally. I don"t understand why the author didn't said where we can find it so here: Languages >>Even more... >> [on the bottom] Sharp tuning >> [on the bottom] **Show password-field related keys**

god, what a suffering it was.

**Comment by Tony-il-Capo** [comment]
When first introduced there was no option to turn this feature on/off, but then an option in settings was added.
This was fixed quite some time ago, [here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/839)
Same problem was reported here, https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/839 and https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/802
This should be closed.

**Comment by AnXh3L0** [comment]
Closing this as fixed from https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/9608213ca535f69234ab498b2f5eea93f2f72a2f
