### ISSUE TITLE
Please import the alternate layouts to GitHub

### ISSUE THREAD

**Issue by marmistrz** [AnySoftKeyboard/AnySoftKeyboard#748]
The Dvorak and Colemak keyboards used to be in the SVN repo: http://softkeyboard.googlecode.com/svn/trunk/LanguagePacks/AlternativeEnglishKeyboards/
which is no more

This may refer to all your language packs. So please import everything that was there :)

Thanks

**Comment by menny** [comment]
Will track progress with #902
