### ISSUE TITLE
The keyboard closes when the leftmost point is pressed (when the simple black glow design is used)

### ISSUE THREAD

**Issue by AndrewPy** [AnySoftKeyboard/AnySoftKeyboard#751]
### Steps to reproduce
1. Select the design "simple black glow".
2. Open an app to enter a text and press the leftmost point of the keyboard (e.g., the left margin of the "a" key).
   ![simple_black_glow](https://cloud.githubusercontent.com/assets/20823006/19655129/38c77b64-9a1b-11e6-9338-5f609f35fd57.png)
### Expected behaviour

The character "a" should be written. 
### Actual behaviour

The keyboard closes.

**Android OS version:**
5.1.1

**Device manufacturer and model:**
Wiko Pulp 4G

**List of installed add-ons (like languages, or themes):**
German language add-on

**Comment by menny** [comment]
Thanks for reporting
