### ISSUE TITLE
Add setting for turn off "use suggetion with space,coma, and dot" 

### ISSUE THREAD

**Issue by fakefacebook** [AnySoftKeyboard/AnySoftKeyboard#753]
### Expected behaviour

-I want to disable the use of suggetion with **"space"**     ,     **".(dot)"**    and      **",(coma)"**
suggetion is true but i do not use suggetion with this three key 
add the function in setting menu to disable this future
### Actual behaviour
- When I type messege then show suggetion in top row ,  i want to type  "**Niku,**"   and see what happen with me.. 

-this is also happen with space and coma please add setting to turn of this future!! 

![bug anysoftkeyboard](https://cloud.githubusercontent.com/assets/20983834/19757895/2473b5ea-9c43-11e6-8915-7b19e29cc441.gif)

**Android OS version:**
All version

Regards
fakefacebook

**Comment by menny** [comment]
This can be turned off by picking "Off" in "Auto-select suggestion aggressiveness"
