### ISSUE TITLE
Backspace after new word select scrambles word

### ISSUE THREAD

**Issue by Ademisk** [AnySoftKeyboard/AnySoftKeyboard#754]
### Steps to reproduce
1. Type in a new word unrecognized by language pack.
2. Select word from recommended (greyed out since it's new). Word is added with following space to screen.
3. Add punctuation (,.! work consistently) after word, which should place it a space away. Ex. 'Voila !'
4. Hit backspace once. The word is shifted right once, with an after image. Ex. 'VVoila
### Expected behaviour

Tell us what should happen
No weird word shifting
### Actual behaviour

Tell us what happens instead
Word shifts character to the right, leaving after image of first letter. If there isn't enough space to fit the word after shifting, it's last letter gets truncated.

**Android OS version:**
6.0.1

**Device manufacturer and model:**
OnePlus One

**List of installed add-ons (like languages, or themes):**
Russian language pack

**Comment by menny** [comment]
Thanks for reporting.
Will fix it soon. You may want to sign up to the beta release to check out the fix as soon as it's ready.
