### ISSUE TITLE
On android 6.0 the keyboard automatically change back to the original one

### ISSUE THREAD

**Issue by szmsszms** [AnySoftKeyboard/AnySoftKeyboard#756]
### Steps to reproduce

1.set as default keyboard
2.use it
3.after a while, when you want to use it again in any app it changed back to the basic/original android keyboard. 
### Expected behaviour

Tell us what should happen
Never change back automatically
### Actual behaviour

Tell us what happens instead

**Android OS version:**
6.0
**Device manufacturer and model:**
Cubot dinosaur
**List of installed add-ons (like languages, or themes):**
Hungarian

**Comment by menny** [comment]
I can't see such behavior. Which device is that?

**Comment by szmsszms** [comment]
Cubot Dinosaur

**Comment by menny** [comment]
I have a feeling it related to the device's custom Android.
What is the default keyboard? Google's?

**Comment by szmsszms** [comment]
Yes

**Comment by menny** [comment]
Can you try a different keyboard to see if it happens there too?
Hacker Keyboard, for example.

**Comment by szmsszms** [comment]
Yes it happens as well...

**Comment by menny** [comment]
Ya… some devices do that. There is nothing we can do about that. Sorry.
