### ISSUE TITLE
Revisit bottom row

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#76]
A better bottom row is required.
Main issue is that the space bar is too short.

@kati42 and @herrlado , can you suggest how to fix this? Which keys do you think it is safe to remove?

**Comment by benneti** [comment]
I actually have this problem, too. Would it be possible, to add a custom bottom row, where one could add the button s/he wants and the spacebar fills the left place? 
It also would be great to have the option to have ? , . on letter keys like b n m, smileys on return and language change on space (all on long press). 
Thanks for the projec,  it is awesome to have a foss keyboard wich is configurable 😊

**Comment by landry314** [comment]
the smiley key pulls up the horribly ugly android emoticons. all my messengers have the good emojione built in so i have no reason for the smiley key. why not make it optional to save room?
