### ISSUE TITLE
Optionally hyphen key instead of voice key

### ISSUE THREAD

**Issue by SvGeloven** [AnySoftKeyboard/AnySoftKeyboard#762]
### Steps to reproduce
1. Look at the keyboard
2. Tap on the voice key (microphone)
3. Popup "Voice is Not Installed"

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**
all

**Device manufacturer and model:**
all

**List of installed add-ons (like languages, or themes):**
none

Some users never ever want to use voice input, for whatever reason. For these users the key with the microphone is taking up space and is not only non-functional, it could be used in a functional way.

I would like to propose that the popup dialog "Voice is Not Installed" offers a third option (a wide button) below the two existing choices called: "Never show voice, show hyphen instead". And the text below: "Showing hyphen key instead of voice key can be undone via AnySoftKeyboards settings."

When the user chooses "Never show voice, show hyphen instead", a key with a hyphen is shown instead of the microphone key. When the user goes into settings menu of anySoftKeyboard, there would be always a boolean setting called  "Never show voice key, show hyphen key instead" which is off/false by default. When the choice discussed above has been chosen, this boolean will be set to on/true. The user can manipulate this setting and the effect can be seen on the keyboard.

Implementing this will improve the speed of using the hyphen, which is very common in certain languages or contexts, especially for users that never ever want to use voice input.

See the attachment for an impression.

![screenshot_20161103-144947](https://cloud.githubusercontent.com/assets/3276314/19968597/8accc5f6-a1d5-11e6-93e5-ed0947544264.png)

PS   The two sentences shown currently at the top of this dialog should not be on two different lines. So no new line after "... on your device." but directly continue with "That can be ..."

**Comment by menny** [comment]
I can do this:
if VoiceInput is not installed, the third (new) button will allow the user to pick a different bottom row

**Comment by SvGeloven** [comment]
Perhaps with different keyboard layouts, only pick a replacement button for that button. That would not interfere with other keyboard layouts that might have differences in the bottom row.

**Comment by PanderOpenTaal** [comment]
in `AnySoftKeyboard/app/src/main/res/xml` do a

    cp ext_kbd_bottom_row_regular.xml ext_kbd_bottom_row_regular_with_hyphen.xml

and later the line(s) before `keyLabel="\?"` to offer hyphen/minus `-`. This key is used so often, especially when not using a microphone and the reserved place becomes available. At least `keyboard_mode_normal` and `keyboard_mode_im` should be altered like this. Checking here before doing commit and making making pull request.
