### ISSUE TITLE
swiping up and out of keyboard from space, closes keyboard

### ISSUE THREAD

**Issue by digi-owl** [AnySoftKeyboard/AnySoftKeyboard#768]
### Steps to reproduce
1. start from space and swipe up intil you leave the keyboard and enter the underlying app.

### Expected behaviour
Well not really sure, but i would have expected either the utility keyboard or the extension keyboard to show.

### Actual behaviour
keyboard closes.

**Android OS version:**
4.2

**Device manufacturer and model:**
Huawei Ascend P6

**List of installed add-ons (like languages, or themes):**
Norwegian keyboard.

**Comment by menny** [comment]
Seems that when I fixed https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/751, I also fix this one 👍
