### ISSUE TITLE
Next button does not work in landscape mode

### ISSUE THREAD

**Issue by bacizone** [AnySoftKeyboard/AnySoftKeyboard#771]
### Steps to reproduce
When using Anysoftkeyboard in landscape mode with multiple fields, the "Next" button does not work - it does nothing actually. 

I always have to swipe it down to forward...

Please fix it.
### Expected behaviour
When I press Next it goes to the next field.

### Actual behaviour
Nothing happens

**Android OS version:**
4.2.1

**Device manufacturer and model:**
Zopo 980

**List of installed add-ons (like languages, or themes):**
Hungarian Anysoft Keyboard

**Comment by menny** [comment]
This was fixed. You can get the updated version right now in the BETA, or wait awhile for it be in the stable channel.
