### ISSUE TITLE
Why Have Two Apostrophe Keys In the New Generation Keyboard?

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#774]
In the "New Generation - Testing" row type you have two ['] keys... why? It is a waste of room and possible functionality.

**Comment by menny** [comment]
There shouldn't be.
In my installation there is only one. Can you send a screenshot? Where did you install ASK from?

**Comment by landry314** [comment]
got it on f-droid: anysoftkeyboard version 1.8.253. there is an apostrophe key just to the right of the question mark key AND one above the delete key. do you not see that? the lower one has curly double apostrophes as well and « and » but the top one just has single and double apostrophes.

**Comment by landry314** [comment]
oooh, i am using "QWERTY Latin keyboard with symbols (on long press)" and that one has the double apostrophe key issue when combined with the New Generation Layout. I see...

I like how the middle row is more like a computer keyboard with margins on each end when the second apostrophe key is removed... but I do not like how you can't see the corresponding numbers on the top row above the letters, just <.> or whatever that is...

It is wonderful that I can combine different layouts with top and bottom row options but sometimes you get an issue like this with two keys that are almost the same.

**Comment by menny** [comment]
Can you provide a screenshot of the issue?

**Comment by landry314** [comment]
just switch to using "QWERTY Latin keyboard with symbols (on long press)" and combine it with the New Generation Layout and you will see the issue.

**Comment by menny** [comment]
I see. I think I'm going to skip on fixing this. 

At some future release I'll provide a way to completely customize the bottom row, that will solve your issue.

**Comment by landry314** [comment]
awesome, because i am tired of hitting that annoying emoji key which pulls up the ugly android emojis... all my messengers have their own awesome emojis...

**Comment by landry314** [comment]
but this still leaves more problems i have... the best keyboard in my opinion has the middle row offset just like on a traditional keyboard where there is space to the left of the "a" key and to the right of the "l" key, it is the most natural... BUT this keyboard choice leaves us with ugly <-> above the keys and LESS options for characters. for example, if i hold the "w"(2) key in the long press keyboard then i can do a subscript like in CO₂ which is cool but with the normal qwerty keyboard i would have to hit symbol to even get to the 2 key variations and there i can only do a 1/2 or a superscript 2... no subscript 2. i can not find anywhere at all to do a subscript for any numbers. basically, the normal qwerty keyboard is weaker than the long press in every way except it has that annoying ' key to the right of the "l" which is useless in the regular, classic, and new generation bottom row configurations... allowing us to configure the bottom row would be amazing but it would not solve this problem. that key to the right of the "l" key would still be there in my way unless i switched to a weaker keyboard.

i beg you to remove that key completely or to fix the long press version to not have such a weaker long press layout missing subscripts and just over all making it harder to get to symbols...

does anyone agree with me, here?
