### ISSUE TITLE
Add Setting to Disable Top Extension Keyboard

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#776]
I see there is no way to disable the top extension keyboard... I would like to.

I also suggest you conform the way you refer to it. Is it an "extension keyboard" or a "top extension keyboard"? Maybe change "Sticky extension keyboard" to "Make top extension keyboard sticky"... The others settings around it start with verbs "Show" and "Use" and it is also better form to say in a setting what the action is than what the object is, in my opinion.

**Comment by lerman** [comment]
@landry314 not sure if you are referring to the "Common top generic row" or not...but if you are, you can disable it by going to Settings -> User Interface -> Even More..

**Comment by landry314** [comment]
No, I am talking about the top extension keyboard... i already have "no top row" on for the top row. the top extension keyboard is activated by an up swipe that goes above the keyboard.

**Comment by menny** [comment]
I can add an option to disable the extension keyboard.

Also, about the strings to change: can you open another ticket for those?

**Comment by landry314** [comment]
i just did in #853
