### ISSUE TITLE
"Split/Merge initial state" set to "Start split in landscape" Acts Strange After Many Orientation Changes

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#777]
### Steps to reproduce
1. Set Split/Merge Initial State to "Start split in landscape"
2. In portrait mode, tap in a field to open keyboard
3. You see the proper behavior of no split
4. Turn the phone to landscape
5. It is not split. ok, it just says "STARTS split", i understand.
6. Turn it BACK to portrait.
7. It is SPLIT!

The same thing happens starting in the other state. Start in landscape, switch to portrait then back to landscape, it is NOT SPLIT!

I am using Cyanogenmod 13 on a Nexus 5X.

This is just not the intended consequence of the setting. It should stay split in landscape all the time if i start split in landscape.

I suggest you add another option to the setting "Keep split in landscape and regular in portrait". Isn't that what most people would want anyway? I can't imagine wanting LESS room for the keys in portrait anyway... I would make my new option the default.

OR, why not just create two settings, one that sets the starting state in portrait and the other that sets the starting state in landscape? Then keep the current state for each in a flag bit until the next keyboard opens...

OR add another setting "Remember last split/merge state for each orientation"...

Anyway, I think a rehaul of the control over this feature is in order!

**Comment by dracometallium** [comment]
I just tested it on v1.8-r6 from f-droid and got the same results. When I returned to portrait it got split.

**Comment by landry314** [comment]
Can we just have a setting that can fix the code for split in landspace and non-split in portrait regardless of which orientation it starts in? That is what I want and I can imagine what other uses would want too. Make a setting to do this. We should be able to fix the mode we want for each orientation. "Start Split in Landscape" is good but what if I start in portrait then turn the phone? it isn't split. I always have to split it myself.

**Comment by maverick74** [comment]
I agree whit landry314.

I want the keyboard to be always split in landscape mode but not in portrait (no matter how it is started)!

**Comment by maverick74** [comment]
@menny Is there a chance to get this behavior changed? (or is there a reason for it to be the way it is?)

**Comment by landry314** [comment]
yeah, seriously, this is the most annoying thing for me about using this keyboard. i did a swipe up on spacebar to merge layout and then set it to always split and this is better, when i use it in portrait i just swipe up on spacebar quickly and it am set. annoying, but better than trying to use this broken feature. I hope this feature gets fixed soon!

**Comment by menny** [comment]
Yes, I can see why it is annoying. Got it.

I'll revamp this feature for the next release.

**Comment by maverick74** [comment]
Great!!! Thanks @menny .
Would be good if we could set different settings for each state.
 E.g.: I would like to always have the keyboard split when the phone is on the horizontal position and always have the keyboard compacted on the right when the phone is on the vertical position.

**Comment by menny** [comment]
The fix will be available in the next beta

**Comment by landry314** [comment]
thank you for this! i love it!

it would nice, though, if when the phone changes orientations while the keyboard is open, it would keep the keyboard open but change the state to the initial state set for the new orientation. now, an orientation change while the keyboard is open just closes the keyboard and it has to be manually opened again.

**Comment by landry314** [comment]
hey, strange, some apps are behaving one way and others another.

whatsapp is closing the keyboard and so is telegram but signal is keeping it open on orientation change. forkhub is closing it. my text editor, lesserpad, is keeping it open. materialfbook is closing it. wow, it seems quite split at 50% of apps close the keyboard on orientation change. i guess they are calling a close function on orientation change and there is nothing you can do about it!

**Comment by maverick74** [comment]
My SMS's app always closes it
