### ISSUE TITLE
New theme by Algimantas Jočys

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#780]
Main keyboard:
- [ ] icons
- [ ] keyboard background
- [ ] button backgrounds (normal, normal-pressed, function-normal, function-pressed)
- [ ] text color and size

popup keyboard:
- [ ] icons
- [ ] keyboard background
- [ ] button backgrounds (normal, normal-pressed, function-normal, function-pressed)
- [ ] text color and size

Author: Algimantas Jočys - https://plus.google.com/u/0/102742363761018374351

**Comment by yochees** [comment]
Hi,
You can find first mock-ups here:
https://www.dropbox.com/sh/xvkmo95wl0syrmc/AACK0b9eR_-qWO0gLOEYBv_Pa?dl=0

Mainly the changes are in skin only. Same layout, new icons, less contrast, unified graphic style. 

However, there was one huge usability issue - text on top right button. I understand the current logic very well - it shows the next language layout (as does the left top row button). It works well if you are switching form Latin to other script (i.e. Russian or Chinese), because the current state is obvious. The same is true for the top left button if you are in ABC mode (you are absolutely sure that it is not a number mode). But... When you are switching between multiple languages using Latin script - the keyboards look nearly (or absolutely) the same. And it comes natural to interpret top right button as the current (as opposed to next) state indicator. As is its much bigger/brighter/more-visible than the current language layout indicator on spacebar. It is really confusing. Not just for me, but virtually for anyone I've asked to try ASK (with Lithuanian and English keyboards).

There are lot's of possible solutions, but IMO the one showed here would be easiest to implement, least confusing for users who've got used to current behavior and solves UX issue pretty well.

**Comment by menny** [comment]
@yochees this is great!
I can start working on this.

For the first phase, I'll do the colors and text sizes:
1) what is the color hex for the buttons' backgrounds (normal, normal-pressed, function and function-pressed)?
2) what is the radius of the button background corner?
3) what are the text colors and sizes?

**Comment by yochees** [comment]
@menny - great to hear that.
I'm glad you like it!
I've slightly updated the design. The URL is the same:
https://www.dropbox.com/sh/xvkmo95wl0syrmc/AACK0b9eR_-qWO0gLOEYBv_Pa?dl=0

You'll find it in folder v2.
Also you find all the icons in assets folder. 

There is also alternative design for language switcher (v2/05 alternative language switcher.jpg) it is even easier to implement. "123!#()" is the button to enter number/sign mode. Ant it indicates the mode it will enable. "Lithuanian" indicates current layout, but <> symbols helps to find a) you can switch language, b) changed behavior from previous version.

****

Background #262626

Key background:
Normal key #383838
Special key #444444
Pressed key / highlight: #29ABE2 *

Text/icon colors:
Normal #FFFFFF
Alternative (i.e. letters on dial pad) #B3B3B3
Next layout #666666


Border radius - 5px
Gap between the keys - 12 px
(The measurements are relative to 360x640px, [mdpi] display)

Other descriptions and designs (i.e. popup keyboard) coming soon. Hopefully on Monday.
I'll try to find the solution how to indicate that pop up keyboard is available - it is currently really difficult to discover it. 


(*) At best - it should match current OS theme highlight color, sadly I don't think it is possible. 
So the second best solution - let user customize this color. Ant default it to #29ABE2.

**Comment by yochees** [comment]
BTW I've uust found out, that what thought is "popup keyboard" is actually "utility keyboard".
So... what is then "popup keyboard" ? ;)

**Comment by menny** [comment]
utility keyboard is a popup keyboard. You got it right.
So, when you long-press some keys (like "a"), a popup will be shown, with "a" accents. This is a popup keyboard.
The utility keyboard is also using the same theme details as a popup keyboard.

**Comment by menny** [comment]
![screenshot_1481258049](https://cloud.githubusercontent.com/assets/481272/21037830/e10ef5bc-bd9e-11e6-8e70-7cc6a35deff5.png)

**Comment by menny** [comment]
I'll also need definitions for the _suggestions_ strip

**Comment by yochees** [comment]
That's quick ;)
May I get alpha release as separate install? 
Please check the dropbox, for v3 and assets v2.
You can use good old link, or shortlink http://diz.lt/ask


Some notes:
- Now all the keys ar colored in #444444, which is only for special keys. Normal keys (i.e. letter keys should be - #383838.
- It was my mistake - distance between keys shoud be 4px, not 5 (as it is now). And I suggest to make vertical distance the same 4 px. So the key height in v3 layout is is 46.5 px. 
- I would align space symbol with the bottom of the question mark. 
- In current layout you can split symbols 123!#() in to lines 1. "123" ; 2. "!#()" so we will have large enough font size. 
- I've redone caps lock and shift icons.
- New alpha, beta icons (it is actually Roboto regular 13 pt, #C64191)
- In highly unlikely event more colours would be needed. Here is the color scheme: https://coolors.co/29abe2-c64191-1a5e63-028090-383b3d

**Comment by menny** [comment]
Sure thing:
a few technicals:

- The ALPHA/BETA icons a there only for the developer builds, so don't worry about those.
- Can you provide the assets in Android's structure?
  - no dash, use underscores, for example, `shift-on.png` should be `shift_on.png`
  - Instead of specifying the density in the filename, can you put them in separate folders? for example `enterhdpi.png` should be `hdpi/enter.png`
  - The space assets should be nine-patches, if you can do that.

If this doesn't work for you, that's fine, I can handle the renaming it just takes time.

**Comment by menny** [comment]
@yochees this is what I have till now:
![screenshot_1481495762](https://cloud.githubusercontent.com/assets/481272/21083912/512a7c4c-bfc8-11e6-9cdf-6c549b844d1a.png)

The assets I've used are here:
[res_yochees.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/644857/res_yochees.zip)

The `space` icon needs to be tweaked: some paddings to the sides and the bottom will do the trick.

**Comment by menny** [comment]
There is also some misalignment with the shifts. I'll provide you with an APK to test out.

**Comment by menny** [comment]
@yochees please download a debug build from here: https://s3.amazonaws.com/anysoftkeyboard/build_777/apk/app-debug.apk

**Comment by yochees** [comment]
I've updated shift, shift-on, caps-lock icons. 
They are at "assets v3".

Please add some padding for "alpha" icons as well ;)

**Comment by menny** [comment]
@yochees try out this one: https://s3.amazonaws.com/anysoftkeyboard/build_789/apk/app-debug.apk

**Comment by menny** [comment]
@yochees I'm pushing this to the next release. There are some critical bug fixes I want to ship as quickly as possible.

**Comment by yochees** [comment]
@menny, I've updated the design from the ground, added other two skins. I'll write the description soon (hopefully in the next few hours). Please see "v4" and "assets v4".

**Comment by yochees** [comment]
**Dark theme (v4/01-yo-dark-suggstions.jpg)**

Background #222222

Key background:
Normal key #2A2A2A
Special key #323232
Pressed key / highlight: #29ABE2 *

Text/icon colors:
Normal #FFFFFF
Alternative (i.e. letters on dial pad) #B3B3B3

Border radius - 5px 
Gap between the keys - 5 px (yes 5px are back, and also there is 5px margin around all the keyboard)


**Lean theme A (v4/02-yo-lean-a.jpg)**

Background #33373a

Key background:
Normal key none or #33373a 
Special key #3f4346
Pressed key / highlight: #29ABE2 *

Text/icon colors:
Normal #FFFFFF
Alternative (i.e. letters on dial pad) #B3B3B3

Border radius - 2px 
Gap between the keys - 5 px (and also there is 5px margin around all the keyboard)


**Lean theme B  (v4/02-yo-lean-b.jpg)**

Background #1a1a1a

Key background:
Normal key none or #1a1a1a
Special key none or #1a1a1a
Pressed key / highlight: #29ABE2 *

Text/icon colors:
Normal #ffffff
Special #ffffff
Alternative (i.e. letters on dial pad) #aaaaaa

Border radius - 2px 

**Light theme (v4/04-yo-light.jpg)**

Background #fafafa

Key background:
Normal key #f0f0f0
Special key #dddddd
Pressed key / highlight: #29ABE2 *

Text/icon colors:
Normal #69696b
Special #838387
Alternative (i.e. letters on dial pad) #aaaaaa

Border radius - 5px 
Gap between the keys - 5 px (yes 5px are back, and also there is 5px margin around all the keyboard)


**General stuff (v4/05-misc.jpg)**
When key is pressed first pop up should be ~20% bigger than key  (current lean theme behavior is actually right), and pop up for alternative symbols should have the same color as the first pop up (29ABE2) currently it is purple.

**Comment by menny** [comment]
I'm back.

These are really nice! I'm going to work on one theme (Dark theme ( http://diz.lt/ask -> v4/01-yo-dark-suggstions.jpg)), and once we feel it is stable, it wouldnt be too hard to define the others. But right now, it's too many moving parts to handle

**Comment by menny** [comment]
Closing for now, as we have a basic theme ready
