### ISSUE TITLE
Overall dictionnary improvements

### ISSUE THREAD

**Issue by kertase** [AnySoftKeyboard/AnySoftKeyboard#787]
I think that the dictionary handling needs improvement first it should be able to support way more words.

Second to be able to reduce the word toll word composition rules as for example dictionary apps like Hunspell use should be integrated this allows a much more complex correct word spelling correction in many languages.

Thank you very much for the great app.

**Comment by menny** [comment]
I've updated the dictionary with many more words and more precise frequencies. Please try the latest beta.

**Comment by kertase** [comment]
That is great.

But I think you might have misunderstood me. I was commenting from the point of view of somebody composing for example a german dictionary. The size of the dictionary being limited is quite problematic since the vocabulary is quite large because german has a lot of composite words.  Other modern dictionary solutions make it possible to integrate such things so for example for regular verbs you only have to add the base form and the program knows the conjugation which reduces the size of the dictionary by a very large amount, and a the same time allowing a much bigger span of corrected words.

**Comment by ildar** [comment]
@menny, the thing that kertase was writing is morphology / affix processing that hunspell can do quite well, see https://github.com/hunspell/hunspell
Indeed hunspell support would be awesome and allowed decreasing the dict sizes through the affix rules and such.
So guys, please reopen the issue and change the title to e.g. __Hunspell support__
