### ISSUE TITLE
lost option by author's update: the "learning words with a touch during typing"

### ISSUE THREAD

**Issue by LugiaDepression** [AnySoftKeyboard/AnySoftKeyboard#788]
### Steps to reproduce
1. Type words anywhere
2. The typed word appears on the suggestion line
3. Touch the actual word you typed

### Expected behaviour
Before *that* update, when I touched the word on the keyboard's suggestion line which I typed it offered instant on the suggestion line "touch it again to add it to the dictionary?", or something like that, so I was able to add any word to the dictionary during typing. I just touched the word again and it says on the keyboard's suggestion line "added to the dictionary".

After the author's update (which was long time ago) I tweeted to them this option got lost with the update, but no reply came.

### Actual behaviour
Now when I touch the word on the keyboard's suggestion line for a !tiny second! the option appears on the line like "Touch it again to add it to the dictionary", but when I touch the word again, this line appears again, nothing else.

**Android OS version:**
Android 4.4.2

**Device manufacturer and model:**
Vodafone Smart 4.

**List of installed add-ons (like languages, or themes):**
Added hungarian language

**Comment by menny** [comment]
Hey. Which version of AnySoftKeyboard do you use?

**Comment by LugiaDepression** [comment]
The last one. I downloaded it today from PlayStore.

**Comment by menny** [comment]
I don't see that problem at all..

I'll need more information:
Do you have suggestions enabled?
Which language-packs do you have installed?
Does it happen with all languages?
Does it happen with all apps?

Also, is there a chance you can create a video of the issue?

**Comment by LugiaDepression** [comment]
As I wrote above, I use added hungarian language. (https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hungarian&hl=hu)

Yes, suggested words displayed/appears above the keyboard, this option is still on, of course.

I never blocked the hungarian language app just to use the english one, BUT as I said, this problem is only came after an update. For long time I used this keyboard app with the hungairan laguage **without** any issue. Then got that automatic update, and the problems with it.

I can make a video in two days, but I don't know how I should put that in my reply.

**Comment by LugiaDepression** [comment]
Okay, I don't know what magic you doing, but just keep doing it. A few minutes ago I tried to make a video about this, and unbelievable but as I started the video the option started to working. Never sooner, and since then it's working without issue, the saving option isn't disappearing after a tiny moment, I can touch it finally and works fine, it adding the words to the dictionary. Strange, but it's a big relief for me, so deleted the vid and thank you. _Looks like I had to scare it or I dunno...._

**Comment by menny** [comment]
👍
Are you using the beta?

**Comment by LugiaDepression** [comment]
I use still the regular app from the plasytore, and I didn't changed anything, didn't donwloaded anything else, this is why I don't understand the random change. My playstore also have this option to not to reffresh the apps automatically.
