### ISSUE TITLE
After the last update another line of keys (numbers) appear when I type passwords

### ISSUE THREAD

**Issue by LugiaDepression** [AnySoftKeyboard/AnySoftKeyboard#789]
### Steps to reproduce
1. Type the (screenlock) password

### Expected behaviour
Before the update that line was't appeared.

### Actual behaviour
Another line of keys appear when I type passwords, above the regular letters I got a number line too. But why? With a swift I already HAVE the numbers board too, so it's unwanted, no need for it and it's ate away space form the screen unnecessary.
It happened after the update by it's own, I didn't touched any option in the settings.

Look how horrible it's look like after I switched from the letter to the numbers.... 
![viber image](https://cloud.githubusercontent.com/assets/24565263/21180944/ad5476c8-c1fb-11e6-90c2-632f4248bc78.jpg)

Android OS version:
Android 4.4.2

Device manufacturer and model:
Vodafone Smart 4.

List of installed add-ons (like languages, or themes):
Added hungarian language

**Comment by sivanrehan** [comment]
Same for me

**Comment by menny** [comment]
will be available in the next beta release.
