### ISSUE TITLE
Emojis do not show 

### ISSUE THREAD

**Issue by sivanrehan** [AnySoftKeyboard/AnySoftKeyboard#790]
### Steps to reproduce
1. Click on emoji icon

### Expected behaviour
Emojis are visible

### Actual behaviour
Emojis are not visible

**Android OS version:** 5.1.1

**Device manufacturer and model:** OPPO R7Plusf

**List of installed add-ons (like languages, or themes):** Hebrew

**Comment by menny** [comment]
@sivanrehan a single press should output the default emoji icon, for example, 😀
Long-press should open the emoji keyboard with all the emoji options.

This is not the behavior you see?

**Comment by sivanrehan** [comment]
If it worked like that I would not post a bug ;-)
Look at the screenshots.
The emojis show only under history and none on the other tabs.
The default became this instead of a smiley:
 ߘÀ ߓʀ ߎÀCCDefine the swipe right from space bar gesture action. Currently,
%s

On Dec 14, 2016 1:16 PM, "Menny Even Danan" <notifications@github.com>
wrote:

@sivanrehan <https://github.com/sivanrehan> a single press should output
the default emoji icon, for example, 😀
Long-press should open the emoji keyboard with all the emoji options.

This is not the behavior you see?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/790#issuecomment-267110666>,
or mute the thread

**Comment by menny** [comment]
Can you repost the screenshot?

**Comment by sivanrehan** [comment]
![screenshot_2016-12-14-10-36-35-84](https://cloud.githubusercontent.com/assets/18218725/21196123/885c84b0-c204-11e6-92df-6639177a5faa.png)
![screenshot_2016-12-14-10-36-30-07](https://cloud.githubusercontent.com/assets/18218725/21196127/89f0770a-c204-11e6-9fbe-0eb32b7e1644.png)
![screenshot_2016-12-14-10-36-19-97](https://cloud.githubusercontent.com/assets/18218725/21196131/8ba7f226-c204-11e6-96f7-44f51864ce9d.png)
![screenshot_2016-12-14-10-37-43-46](https://cloud.githubusercontent.com/assets/18218725/21196133/8d1e8098-c204-11e6-8b4b-a02e4e914e1f.png)

**Comment by menny** [comment]
holy shit! that's completely broken...
I think I'll have to disable a bunch of emojis for Android v5

**Comment by menny** [comment]
@sivanrehan are you signed up to the beta releases?

**Comment by menny** [comment]
This is an issue with Android v5 and v5.1. There isn't a quick fix for it.
It was fixed with Android v6: https://android-review.googlesource.com/#/c/130121/

**Comment by sivanrehan** [comment]
Yes

**Comment by sivanrehan** [comment]
But it used to work just fine. Suddenly stopped working.

**Comment by menny** [comment]
Maybe this is happening because of a library or build-tools update. Let me try some stuff.

**Comment by moshpirit** [comment]
I have a similar problem: only some of them are shown. I'm using Android 6.0.1 (official ROM) and latest version of ASK on F-droid
