### ISSUE TITLE
Utility keyboard shows only on every other gesture

### ISSUE THREAD

**Issue by digi-owl** [AnySoftKeyboard/AnySoftKeyboard#794]
### Steps to reproduce
1. set any gesture to show the utility keyboard
2. perform gesture

### Expected behaviour
Utility keyboard should show up every time the gesture is performed.

### Actual behaviour
Utility keyboard only show up every other time the gesture is performed, or if a key on the keyboard is pressed in between performing the gesture.

**Android OS version:**
4.2

**Device manufacturer and model:**
Huawei P6

**Comment by menny** [comment]
A fix will be available in the next release (and the next beta)
