### ISSUE TITLE
Suggested words/the quality of the suggestions are low

### ISSUE THREAD

**Issue by LugiaDepression** [AnySoftKeyboard/AnySoftKeyboard#796]
### Expected behaviour
Before I downloaded the last version the suggested words worked excellent, always suggested the most closer words for what I wanted to use, its guesses was highly accurate.

### Actual behaviour
Now as I typing words the quality of the suggestions are low are pretty low. Like I type
**let** for let's, but the suggested words I got: _lethal, lets, letters, lettings,_ let's...
**don** for don't, but the suggested words I got: _Donaldson, Donahue, donors, donkey, donald, donate, done, donations,_ don't... (I don't even have any Donaldson or Donahue in my conctact list)
**beli** for believe, but the suggested words I got: _believable, bell, belies, belief, belitted, believes, believer, believed, believing, beliefs,_ believe...
**typ** for typing, but the suggested words I got: _typhoons, typically, typifies, typical, type, typography, typhoon,_ typing
**tou** for touch, but the suggested words I got: _toughened, touching, tourists, tourist, tourism, tour, touched, touches, though,_ touch... 
**thou** for thought, but the suggested words I got: _thoughtful, thousand, though, thoughts, thoughtfully,_ thought...
**thro** for through, but the suggested words I got: _theo, throwing,_ through

It's just a few from the most used words where I want type something and the suggestion give seriously  different words, and most of time I have to scroll a lof to find a word I would like to use.... I don't want to show myself like somebody who always complain or are lazy, but this worked pretty well before the last update, and now it isn't.

See as I wrote in the examples, like the "don" for don't, that's the worst one, but not the last like that. As english isn't my original language the correct suggestions are pertty important to me, make my typing faster and easier.
Can you correct it and restore it as it was before? Thank you.

I made a video, but I only can share it with youtube:
https://youtu.be/RKz_tHhVnW8

**Android OS version:**
Android 4.4.2

**Device manufacturer and model:**
Vodafone Smart 4.

**List of installed add-ons (like languages, or themes):**
Added hungarian language from playstore

**Comment by LugiaDepression** [comment]
"grrrrr" also opened a thread about this issue on Aug 25:

https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/694

**Comment by menny** [comment]
I've updated the dictionary with many more words and more precise frequencies. Please try the latest beta.

**Comment by mostafachatillon** [comment]
Still awful suggestions, compare with Swiftkey
