### ISSUE TITLE
Cant switch back to alphabet layout and editor loose focus.

### ISSUE THREAD

**Issue by MTomi78** [AnySoftKeyboard/AnySoftKeyboard#804]
### Steps to reproduce
1. To loose editor field's focus: simply press the left or the right arrow.
2. i'm still looking for the way to reproduce the layout changing problem.
  (i know others already reported similar problem)

### Expected behaviour
If i type anything, the focus should be get back to the editor field

### Actual behaviour
I have to manually get the focus back to the editor field before typing
 Typing the spacebar switch back to abc mode.

**Android OS version:**
4.4.2

**Device manufacturer and model:**
Samsung Galaxy S3 Neo

**List of installed add-ons (like languages, or themes):**
Hungarian keyboard.

**Comment by menny** [comment]
I think that what you are describing is an Android behavior: when pressing an arrow key at the end/start of a line, Android will interpret it as "exit the text field"
