### ISSUE TITLE
Shift missing in URL mode

### ISSUE THREAD

**Issue by HorvathPeterHub** [AnySoftKeyboard/AnySoftKeyboard#805]
The shift button is missing when typing urls, which is rarely useful, but sometimes necessary. E.g. I had to switch to another keyboard to type this github url :)

**Android OS version:**
6.0.1

**Device manufacturer and model:**
Samsung Galaxy S7

**List of installed add-ons (like languages, or themes):**
Hungarian

**Comment by menny** [comment]
in which layout?

**Comment by HorvathPeterHub** [comment]
In Hungarian layout. I've enabled english and there is a shift button.

**Comment by menny** [comment]
@HorvathPeterHub is this the language pack you are using: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hungarian

**Comment by HorvathPeterHub** [comment]
@menny yes, it is. This is how it looks like.
![screenshot_20170113-103221](https://cloud.githubusercontent.com/assets/24753465/21925015/d42eaa24-d97b-11e6-81f0-1e6734c1a148.jpg)

**Comment by menny** [comment]
@HorvathPeterHub you should contact the Hungarian language pack developers. They are using a layout that overrides AnySoftKeyboard.

**Comment by HorvathPeterHub** [comment]
@menny you closed my previous issue here: [https://github.com/AnySoftKeyboard/LanguagePack/issues/24](url)
Then where else should I contact them?

**Comment by menny** [comment]
This is the email address they provided: support@eclipsim.com
