### ISSUE TITLE
Text smileys became too small

### ISSUE THREAD

**Issue by dark159123** [AnySoftKeyboard/AnySoftKeyboard#816]
The text smileys (eg. :-P ) became too small compared to the text on the keyboard and the emojies after the latest update.

**Comment by menny** [comment]
Can you provide a screenshot?

**Comment by menny** [comment]
Is this fixed for you?

**Comment by dark159123** [comment]
I reflashed my phone for other reasons shortly after and was never able to replicate the problem.

**Comment by menny** [comment]
Thanks for reporting back
