### ISSUE TITLE
Search button doesn't work with CAPS

### ISSUE THREAD

**Issue by anibyl** [AnySoftKeyboard/AnySoftKeyboard#818]
### Steps to reproduce
1. Open an app with search box (e.g. Gmail).
2. Tap search button in the app (text field became active).
3. Tap 2 times on ↑ (Shift) button of AnySoftKeyboard to enable “CAPS” mode.
4. Enter text.
5. Tap search button of AnySoftKeyboard.

### Expected behaviour
Searching process starts.

### Actual behaviour
One more space is added to text field.

**Android OS version:** 6.0.1 (MIUI8)

**Device manufacturer and model:** Xiaomi MI4 (also Xiaomi Note 3)

**List of installed add-ons (like languages, or themes):** -

**Comment by menny** [comment]
Which version of ASK are you using?
I recently made a fix for something around that area, and the fix is in the latest beta.

**Comment by anibyl** [comment]
I use 1.8.406. I'll try to find ASK open beta if you have one.

**Comment by anibyl** [comment]
1.8.490 (that in beta now) hasn't this issue. Many thanks!

**Comment by menny** [comment]
nice! thanks for verifying.
