### ISSUE TITLE
Enter key doen't do linebreak

### ISSUE THREAD

**Issue by kelmas** [AnySoftKeyboard/AnySoftKeyboard#827]
### Steps to reproduce
Press ENTER.

### Expected behaviour
Line break is inserted.

### Actual behaviour
Moves focus to another input field.

**Android OS version: 7.0**

**Device manufacturer and model: Motorola Nexus 6**

**List of installed add-ons (like languages, or themes): Lithuanian layout**

**Comment by menny** [comment]
are you on the latest BETA or Stable?
Please make sure. 

If so, which apps give you this behavior?

**Comment by kelmas** [comment]
Latest beta and it was on most apps: Firefox, OpenTask, etc.

But with today's new version issue is gone - works as expected, thanks!

**Comment by menny** [comment]
good, I did push a fix so it wasn't magic 😆
