### ISSUE TITLE
Wider spacebar to avoid accidental full stop presses

### ISSUE THREAD

**Issue by divansantana** [AnySoftKeyboard/AnySoftKeyboard#830]
### Steps to reproduce
1. Try type quickly a sentence with spaces in it, like this one.
2. Notice that the above sentence looks like this: `Try type.quickly a sentence.with spaces.in it, like this one.`
3. Get annoyed

Would be nice to have a more natural "feel" for the spacebar position.

Often I and I'm sure many others hit the `.` full stop character by accident instead of the spacebar. Would be awesome if I could configure the spacebar to be wider and disable other character keys on the bottom row as mentioned in #716 

**Android OS version:**
All

**Device manufacturer and model:**
All

**List of installed add-ons (like languages, or themes):**
Stock

**Comment by menny** [comment]
@divansantana Did you try a different generic bottom row?

**Comment by divansantana** [comment]
Not following? Didn't see another keyboard layout or option that solved this.

**Comment by menny** [comment]
You can pick a different bottom keys row by going into the settings app, and picking "Even more…" option under "User interface" in the side-menu

**Comment by divansantana** [comment]
@menny Awesome! Thanks a ton. I did try digging through the settings but clearly missed this.
