### ISSUE TITLE
Yochees Dark Theme QuickText keyboard broken

### ISSUE THREAD

**Issue by lerman** [AnySoftKeyboard/AnySoftKeyboard#831]
### Steps to reproduce
1. Choose Yochees Dark Theme
2. Long press the smiley button to get to the quicktext popup keyboard
3. Notice that keyboard crashes

### Expected behaviour
QuickText keyboard should open. It work in Yochees Light Theme amongst others.

### Actual behaviour
I see this error:

ASK CHEWBACCA: Caught an unhandled exception!!!
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.anysoftkeyboard.keyboards.views.QuickKeysKeyboardView

**Android OS version:**
6.0.0

**Device manufacturer and model:**
Nexus 5X

**List of installed add-ons (like languages, or themes):**
No additional addons installed

**Comment by menny** [comment]
Thanks for reporting.
Just to be clear, this theme will not be in the stable version of the app, it's still in design phase
