### ISSUE TITLE
16key's keyboard and two letters word

### ISSUE THREAD

**Issue by maverick74** [AnySoftKeyboard/AnySoftKeyboard#834]
### Steps to reproduce
1.select the 16keys keyboard
2.try to write "hi"

### Expected behaviour
Coming from a T9 keyboard, one would expect it should suggest "Hi" (cause i pressed the key twice, once for each letter) 

### Actual behaviour
Suggests only "H" or words started with "G"

**Comment by menny** [comment]
T9 technology is patented: https://worldwide.espacenet.com/publicationDetails/biblio?CC=US&NR=5818437&KC=&FT=E&locale=en_EP
