### ISSUE TITLE
keyPreviewBackground is not change in Theme

### ISSUE THREAD

**Issue by fakefacebook** [AnySoftKeyboard/AnySoftKeyboard#835]
I am installing ICS for AnySoftKeyboard theme

ICS for AnySoftKeyboard
https://play.google.com/store/apps/details?id=com.anysoftkeyboard.theme.ics

### Actual behaviour
Inside this  theme keyPreviewBackground is showing 
![keyboard_key_feedback_background_holo 9](https://cloud.githubusercontent.com/assets/20983834/21708285/fa6d7f6e-d3fc-11e6-9825-b07dd7b2773e.png)

but in my phone it will showing onether keypriview background... it will get default keypreview of LeanDark theme.

![device-2017-01-06-102436](https://cloud.githubusercontent.com/assets/20983834/21708318/4a33b900-d3fd-11e6-8c06-33254d249a2c.png)

### Expected behaviour
solve this problem ....

**Android OS version:**
6.0 Marshmellow

**List of installed add-ons (like languages, or themes):**
ICS for AnySoftKeyboard

**Comment by fakefacebook** [comment]
@menny  now issue is solved??
yes or no...

**Comment by menny** [comment]
Yes. Next beta and stable versions will have the fix

**Comment by fakefacebook** [comment]
Thank you so much...
