### ISSUE TITLE
Another line of keys appear when I type passwords, still on

### ISSUE THREAD

**Issue by LugiaDepression** [AnySoftKeyboard/AnySoftKeyboard#839]
**Copied from the closed one:**
Steps to reproduce
Type the (screenlock) password

**Expected behaviour**
Before the update that line was't appeared.

**Actual behaviour**
Another line of keys appear when I type passwords, above the regular letters I got a number line too. But why? With a swift I already HAVE the numbers board too, so it's unwanted, no need for it and it's ate away space form the screen unnecessary.
It happened after the update by it's own, I didn't touched any option in the settings.

Look how horrible it's look like after I switched from the letter to the numbers....
![ad5476c8-c1fb-11e6-90c2-632f4248bc78](https://cloud.githubusercontent.com/assets/24565263/21743356/aa55bdd4-d500-11e6-82f9-26e0657bb006.jpg)

It was told it will be fixed with the next update, which I downloaded a few days ago, but the plus line is still there. #789 I still hoping it's just a missed fixing.

**Android OS version:**
Android 4.4.2
**Device manufacturer and model:**
Vodafone Smart 4.
**List of installed add-ons (like languages, or themes):**
Added hungarian language

**Comment by menny** [comment]
which version of the app are you using? This was fixed.

**Comment by LugiaDepression** [comment]
The last newest version from the playstore 1.8.406, no another version avaiable
