### ISSUE TITLE
[Feature Request] Long press to insert special characters

### ISSUE THREAD

**Issue by soaringowl2145** [AnySoftKeyboard/AnySoftKeyboard#840]
The AOSP keyboard supports the ability to type special characters such as ( $ % # @, ect. by simply long pressing the corresponding letter.

Any chance we can get this feature as well?

Thanks!

**Comment by menny** [comment]
Long-pressing on which keys?
You can output those characters by switching to the symbols keyboard.

**Comment by PeterHindes** [comment]
This is currently my most wanted feature, alongside backspace swipe to delete word, and space swipe to seek. These are what keeps me from switching from gboard.
