### ISSUE TITLE
switching to landscape entry do not switch to full-screen automatically.

### ISSUE THREAD

**Issue by digi-owl** [AnySoftKeyboard/AnySoftKeyboard#845]
### Steps to reproduce
1. set landscape to use full-screen text entry.
2. tap a text entry field while in portrait
3. rotate device to landscape

### Expected behaviour
keyboard should display the full-screen text entry mode

### Actual behaviour
text entry only enters full-screen mode when text field is tapped after rotating the device to landscape

**Android OS version:**
4.2

**Device manufacturer and model:**
Huawei P6

**Comment by menny** [comment]
Fullscreen mode will be initiated only if the keyboard is shown. If the keyboard is not shown Android will not allow the keyboard to take over the UI

**Comment by digi-owl** [comment]
This happens when the keyboard is showing.

And apparently it gets "better". If i am to tilt the device back to portrait the keyboard will go into full screen while in portrait, something that is directly opposite of what it selected in the settings.
