### ISSUE TITLE
suggestions interfer with completing full-screen text entry

### ISSUE THREAD

**Issue by digi-owl** [AnySoftKeyboard/AnySoftKeyboard#846]
### Steps to reproduce
1. start entering text in full-screen mode
2. tap the top right button to complete entry

### Expected behaviour
Keyboard should close.

### Actual behaviour
Suggestions line goes away but keyboard stays full-screen until the top right button is tapped once more.

**Android OS version:**
4.2
**Device manufacturer and model:**
Huawei P6

**Comment by menny** [comment]
That button is not used to close the keyboard, it is used to stop suggestions.
If you wish to close the keyboard, the easiest way is to press the device's BACK button.

**Comment by digi-owl** [comment]
Thing is that on most other keyboards, hitting done (or whatever it is labeled in other languages) will close the whole keyboard, not just the suggestions bar.
