### ISSUE TITLE
Keyboard freezes when writing a reply in a Disqus 'reply window'. Am using a Note 4.

### ISSUE THREAD

**Issue by Pebef** [AnySoftKeyboard/AnySoftKeyboard#852]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
Can you provide with a URL where it happens?

**Comment by Pebef** [comment]
Hi Menny!
The problem of getting completely stuck in the emoji mode has now occurred
using both Note 3 and Note 4, and when writing a comment on a website using
Disqus (for comments and replies) and also in Facebook.

Another problem that I experienced in a different context was that I could
not write anything because the keyboard refused to appear. I will revert to
the stable version for a while and see if both problems appear, and will
let you know it one or both do.
Cheers
Peter

**Comment by Pebef** [comment]
🙌🙋👍👍👍

On 14 Jan 2017 1:10 PM, "Menny Even Danan" <notifications@github.com> wrote:

Can you provide with a URL where it happens?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/852#issuecomment-272593667>,
or mute the thread

**Comment by Pebef** [comment]
Cannot leave emoji mode and go back to text/keyboard mode by pressing the icon. Happens in Gmail and Facebook, also.

**Comment by Pebef** [comment]
It seems having inserted an emoji causes the freeze.
