### ISSUE TITLE
Add option to change the language used in the user interface of the app

### ISSUE THREAD

**Issue by aldatsa** [AnySoftKeyboard/AnySoftKeyboard#855]
Some apps (Firefox, Telegram…) give the option to change the language used in the user interface of the app without changing the locale of the device. It would be great if AnySoftKeyboard did the same.

Basque language is an officially supported language in Android but most manufacturers don’t include it in their custom Android builds yet, as a consecuence, many Basque speakers have devices with Spanish/French locales. I think that it’s a common issue with other minoritary languages as well.

In older versions of Android it was easy to change the locale of the device using apps like EveryLocale, but nowadays it’s more difficult. The user must use adb to give permission to EveryLocale to change the locale, that’s too complex for most users.

**Comment by menny** [comment]
@aldatsa will you be able to test this change?

**Comment by aldatsa** [comment]
@menny Sure! I'm at work now. I will test it later.

**Comment by aldatsa** [comment]
I've just tested it and it works, but I needed to close and reopen ASK or restart my phone to change the language. It's good enough for me and I really appreciate your effort but Firefox and Telegram apply the language change immediately. I don't know how they do it but it would be more intuitive that way.

**Comment by aldatsa** [comment]
Applying the language immediately would be an improvement but I think that the feature is useful as it is.

**Comment by menny** [comment]
I think I'll leave it as is, unless I find a way to apply changes  immediately

**Comment by aldatsa** [comment]
Ok. Thanks for your work!
