### ISSUE TITLE
Changed color of pop-up keys background

### ISSUE THREAD

**Issue by ProWax** [AnySoftKeyboard/AnySoftKeyboard#857]
Color of background of pop-up keys after the last update become the blue and it is now difficult to see char.
![badcolor](https://cloud.githubusercontent.com/assets/25215509/22093080/8f2564ec-de24-11e6-9128-8f4662cb8147.jpg)

Please change it back (purple color)

App v1.8-r8

Android 5.1

Bluboo Xtouch

Russian Language

**Comment by menny** [comment]
Which theme is that?

**Comment by ProWax** [comment]
In russian it called "flat dark" , in "3d theme" the same blue color. In black themes is good purple color.

**Comment by ProWax** [comment]
So you make the correction?

**Comment by menny** [comment]
this is not a regression, it is as intended.

I understand that you do not like it?

**Comment by ProWax** [comment]
Yes.
As the contrast is lost and when the cursory look at the letters they merge with a light background.
