### ISSUE TITLE
Background in emoji selector too dark, impossible to choose emojis

### ISSUE THREAD

**Issue by motatuc** [AnySoftKeyboard/AnySoftKeyboard#858]
### Steps to reproduce
1. Install AnySoftKeyBoard 1.8.329 or 1.8.489 (built from source today)
2. Set keyboard as standard
3. Choose white or black theme
4. Open emoji selector

### Expected behaviour
It would be easy to choose emojis like :) and :-) etc.

### Actual behaviour
They are almost invisible because of the dark background.

**Android OS version:**
Nougat (Lineage 14.1)

**Condensated report**

It's almost impossible to use and choose smileys/emojis because of the dark background in the selector.
Also the section descriptions are invisible. The selector should be white or bright or whatever the standard material theme coloring is.

P.S.: In the picture it seems not soo dark, but on the phone it actually is really dark.

![screenshot_20170119-212534](https://cloud.githubusercontent.com/assets/15171154/22125677/ed71a9be-de94-11e6-8f2e-b827e0f55ab7.jpg)

**Comment by menny** [comment]
Which theme?

**Comment by motatuc** [comment]
Lean Light. All of them.

**Comment by menny** [comment]
A fix will be available in the next Beta. Shortly.
