### ISSUE TITLE
Crash Reports OPT-IN

### ISSUE THREAD

**Issue by soaringowl2145** [AnySoftKeyboard/AnySoftKeyboard#859]
Currently crash reporting is an opt-out process.  Please consider making this opt-in or at least a separate apk for F-Droid that is opt-in.  Currently the F-Droid version at least needs to be flagged with a tracking anti-feature because it tracks users without consent by default.

Thanks!

**Comment by menny** [comment]
There isn't any analytic, tracking or crash reporting in the f-droid version. As far as I know. Can you elaborate?

**Comment by soaringowl2145** [comment]
Look under:  User interface, even more, tweaks, Report on crash.

The option is checked by default.  it says:

"Upon ASK crash, open crash report dialog"

**Comment by menny** [comment]
This just generates a crash report locally. It does not send it
