### ISSUE TITLE
Rapid typing makes autocorrection move cursor randomly

### ISSUE THREAD

**Issue by lindhe** [AnySoftKeyboard/AnySoftKeyboard#860]
### Steps to reproduce
Spam a bunch of keys (using two fingers), in a field where auto correction is enabled.

### Expected behaviour
Cursor should always be at end of word, so that new text input is appended to end of word.

### Actual behaviour
Cursor appears in the middle of the string, where the text input will start to appear. Cursor jumps backwards further if I continue to spam/type. Bug does not appear in browser address field, where autocorrect is off. So I assume it's caused by autocorrect.

![Rapid text input breaks cursor](https://fat.gfycat.com/WelldocumentedSelfassuredIndochinahogdeer.gif)

**Android OS version:**
5.0.2

**Cyanogen OS version:**
12.0-YNG1TAS2I3

**Device manufacturer and model:**
Oneplus One A0001 (bacon)

**List of installed add-ons (like languages, or themes):**
Swedish keyboard (but bug appears in English too), only stock themes installed (have tried Lean Dark Grey and Plain dark theme). No other add-ons, I think.

**Comment by ArenaL5** [comment]
I noticed this report long after I replied to a duplicate, so discussion of this bug is being done there: #1875.

I'm sorry this has been forgotten for so long.
