### ISSUE TITLE
Enhancement : Allow configurable Emoji Keyboard

### ISSUE THREAD

**Issue by flide** [AnySoftKeyboard/AnySoftKeyboard#868]
How about allowing the user to install and use any emoji keyboard he/she prefers?
When the emoji button in pressed, switch to the keyboard the user configured keyboard (hopefully he/she will choose a emoji keyboard of choice)
This should remove the burden of developing an emoji keyboard as part of AnySoftKeyboard and also gives user the freedom to use whatever he/she likes for the emoji's.

Shameless plug : I am suggesting this because I develop a Emoji Only keyboard that is also open source and can be found [here](https://github.com/flide/Emoji-Keyboard).

**Comment by menny** [comment]
this is an interesting idea.
I'll add this to the backlog.

**Comment by flide** [comment]
I figured out a way to achieve this, but I do not understand the Anysoftkeyboard's code base so... here is the basic framework for implementation: 

Following piece of code finds all available ime's

    final InputMethodManager imeManager = (InputMethodManager)eightVimInputMethodService.getApplicationContext().getSystemService(eightVimInputMethodService.INPUT_METHOD_SERVICE);
    List<InputMethodInfo> inputMethods = imeManager.getEnabledInputMethodList();
    
    Map<String, String> inputMethodsNameAndId = new HashMap<>();
    for (InputMethodInfo inputMethodInfo: inputMethods){
    inputMethodsNameAndId.put(inputMethodInfo.loadLabel(eightVimInputMethodService.getPackageManager()).toString(), inputMethodInfo.getId());
    }

This map can be used to populate a selection box in settings for the user to select the keyboard of there choice of "emoji - keyboard" and this choice can be stored in a variable.

For the emoji button something like below will help : 

    private void switchToExternalEmojiKeyboard() {
    //Check if the user has ever set up the emoji keyboard?
        // if no then display a dialog box and allow him to select one of the available keyboards or previous keyboard
        // if yes then try switching to external keyboard
    InputMethodManager inputMethodManager = (InputMethodManager) this.getSystemService(Context.INPUT_METHOD_SERVICE);
    
    IBinder iBinder = this.getWindow().getWindow().getAttributes().token;
    
    inputMethodManager.setInputMethod(iBinder, getSelectedEmojiKeyboardId());
    }

and the method "getSelectedEmojiKeyboardId" essentially returns the id of the selected keyboard.
