### ISSUE TITLE
[Feature request] Long space bar with all punctuations on colon and dot

### ISSUE THREAD

**Issue by ElSebita** [AnySoftKeyboard/AnySoftKeyboard#870]
The short spacebar annoys me. Every now and then I end pushing the dot.between.words. Alternate layouts are not useful to me since I write mainly in Spanish and need special symbols like ¿¡.
My.suggestion: a layout where all symbols are accessible long pressing the dot (.) and/or the colon (,), eliminating (') and (?).

**Comment by ElSebita** [comment]
My bad: I wanted to say the "short" space bar annoys me

**Comment by merwok** [comment]
Can this be reopened?  At present, it seems that the only way to do non-alphanumeric characters is to memorize all options when all keys are long pressed, which is wildly unpractical.
