### ISSUE TITLE
[Feature request] Suggestion elimination and prioritization

### ISSUE THREAD

**Issue by ElSebita** [AnySoftKeyboard/AnySoftKeyboard#871]
When typing in.Spanish, many accented words I first type with no accents get suggested that way by ASK. It would be useful if ASK suggested the accented word to autocorrect quickly. After manually tapping the accented word, ASK doesn't improve.its suggestion. It would be great if I could eliminate or at least downgrade suggestions to ensure they are not the first selection in suggested words list.

**Comment by sobczyk** [comment]
this is a duplicate of #554
