### ISSUE TITLE
[Feature request] Autocomplete/prediction in browsers URL bar

### ISSUE THREAD

**Issue by qfvldaa2xn** [AnySoftKeyboard/AnySoftKeyboard#872]
The quickest way to use the default search engine when having the browser open is obviously just typing in URL bar. Would it be possible to have prediction enabled in the URL bar?

**Comment by qfvldaa2xn** [comment]
I was rather thinking about suggestions that are displayed above the keyboard, than auto correct.
But you are completely right about auto correct. Nevertheless, I think that suggestions (without auto correct obviously) wouldn't be intrusive though.

**Comment by yaomtc** [comment]
Google Keyboard, Hacker Keyboard, AnySoftKeyboard, and AOSP keyboard all have this same issue - in certain text fields, usually fields that involve searching, corrections and the suggestion bar are disabled, with no way to change it. SwiftKey and Swype both allow you to type things into search fields with correction. Why not give an option? Having to slowly, carefully, precisely type things with my big fat thumbs is a pain. Without correction, searching things is a lot slower. I can understand if you're not going to change the default behavior, but PLEASE add an option for this. I'd gladly donate all the money (~$25) from my Google Play account if someone adds this. I really don't want to have to go back to SwiftKey!

**Comment by qfvldaa2xn** [comment]
It works as of version 1.8-r12.
