### ISSUE TITLE
German Language Pack – wrong correction

### ISSUE THREAD

**Issue by ghost** [AnySoftKeyboard/AnySoftKeyboard#874]
Dear Sir or Madame,
Since the last update from 25.01. (v2.0.1) many correct German words are change by the correction. But in the last version this worked fine.

For example. „Correct German word” -> „due correction changed, in this context, wrong word”:
„Könnten” -> „Konnten”
„Straße” -> „Strasse”
„Verfügung” -> „Vertagung”
„Änderungen” -> „Wanderungen”
„schön“ -> „schon“
„schönes“ -> „Scholes“
„groß“ -> „gros“
„Öl“ -> „Ol“
„ölen“ -> „open“
„würde“ -> „wurde“
…

(Where) can I download the old version again? Or can I see somewhere the changes from the old version (and edit them)? Or can I see (and edit) the whole German dictionary?

Sorry for my bad English;-)
Thanks in advance!

### Steps to reproduce
1. Install the AnySoftKeyboard and the German Language Pack.
2. Activate the keyboard and the German Language Pack.
3. Try some correct German words and the correction change this correct word (examples see above).

### Expected behaviour
The correction change correct German words to (in this context) wrong words.

### Actual behaviour
It shouldn't change correct words (like the old version).

**Android OS version:**
4.4.4 KTU84P

**Device manufacturer and model:**
Xiaomi Redmi 1S

**List of installed add-ons (like languages, or themes):** 
AnySoftKeyboard with German Language Pack

**Comment by AnXh3L0** [comment]
The account that opened the issue has been deleted and the German pack has been updated since, closing the issue as fixed.
