### ISSUE TITLE
Double space to period doesn't remove space after last word.

### ISSUE THREAD

**Issue by qfvldaa2xn** [AnySoftKeyboard/AnySoftKeyboard#875]
### Steps to reproduce
1. When choosing a word from the suggestions then the word and a space right after it is entered.
2. Now a double space enters a period, but the space after the word is not removed.

### Expected behaviour
Question marks, exclamation marks, etc. are working as expected (i.e. the last space after the word is removed before the question mark is entered.

**Comment by menny** [comment]
I'm unable to reproduce this. Can you provide more information?

**Comment by Zykino** [comment]
For me a single space entered the point next to the word and give a space.
An other space leave the point, a space and write an other point. :
"Hello. " [Space]
"Hello. ." [Space]

So I don't reproduce the behavior mentioned.

**Comment by menny** [comment]
If I hit space fast enough, multiple times, I get this:
`Hello....`
If I wait a bit between spaces, I get this:
`Hello. . .`

This is as intended

**Comment by qfvldaa2xn** [comment]
Sorry I missed your comment from three days ago.

**Case 1:**
When I type ``Hello`` without selecting it from the suggestion bar (i.e. by typing it letter by letter), then I see ``Hello`` without a trailing space in the input box.

**Case 2:**
When I type the first letter of the word ``Hello`` and then select ``Hello`` in the suggestion bar, then I see ``Hello `` including a trailing space in the input box.

**Seeing the word with trailing space or without has difference for me when using the double space:**
Using the double after case 1, I get ``Hello. ``, no space between word and punctuation.
Using the double after case 2, I get ``Hello . ``, I get a space between word and punctuation.

Using other ways to write punctuation with the keyboard than the double space, I don't get this behaviour.

ASK version 1.8.401 (v1726) and my Android is 4.4.4.

**Comment by menny** [comment]
@qfvldaa2xn if you wait between picking the word from the suggestion bar and pressing the space bar then you will have a space between the word and the period. Pressing SPACE quickly after picking the word from the suggestion bar will convert it to a period.
