### ISSUE TITLE
Reconsider onEvaluateInputViewShown - Keyboard does not shown in Android 7.X genymotion

### ISSUE THREAD

**Issue by lerman** [AnySoftKeyboard/AnySoftKeyboard#876]
### Steps to reproduce
1. Install ASK on genymotion google nexus 5x 7.0.0 api 24. Also an issue with api 25.
2. Configure as desired
3. Goto notepad app and switch to ASK input

### Expected behaviour
Keyboard should popup and work normally

### Actual behaviour
Keyboard appears to load based on logs, but does not display. No real errors in log.

Logs from Android monitor:
01-30 16:02:08.985 13550-13550/com.menny.android.anysoftkeyboard I/ASK: ****** AnySoftKeyboard v1.8.-245 (1080) service started.
01-30 16:02:08.985 13550-13550/com.menny.android.anysoftkeyboard W/ASK: Could not find Animation_InputMethodFancy, using default animation
01-30 16:02:08.988 13550-13550/com.menny.android.anysoftkeyboard I/ASK: Custom volume un-checked.
01-30 16:02:08.993 13550-13550/com.menny.android.anysoftkeyboard D/TextEntryState: State = START
01-30 16:02:08.994 13550-13550/com.menny.android.anysoftkeyboard D/TextEntryState: State = START
01-30 16:02:08.994 13550-13550/com.menny.android.anysoftkeyboard D/TextEntryState: State = START

**Android OS version:**
7.0.0

**Device manufacturer and model:**
Google Nexus 5X (genymotion emulator)

**List of installed add-ons (like languages, or themes):**
None. Fresh VM with google apps installed

**Comment by lerman** [comment]
Seems like it is never getting to onCreateInputView

**Comment by menny** [comment]
I think that on some emulators you suppose to check some option to show the on-screen keyboard.. otherwise android will report as having a physical keyboard and will not ask the IME to create a view

**Comment by lerman** [comment]
Hey @menny, haven't had any issues with any other android version with the nexus 5x device emulator. Confirmed that setting onEvaluateInputViewShown to always return true, will make the keyboard show.

I 100% have the option checked to show onscreen keyboard. Any idea what may be causing this? I don't have a device I can actually test on unfortunately.

**Comment by lerman** [comment]
Confirmed using genymotion with the same exact device and setting that with android 6.X and 5.X config.keyboard == KEYBOARD_NOKEYS while on android 7.X config.keyboard == KEYBOARD_QWERTY

Weird!

If I comment out your override to onEvaluateInputViewShown it works perfectly in all. Any reason for this override in the first place?

**Comment by menny** [comment]
I'll try it again, but I think I added that override to support devices with physical or Bluetooth keyboards
