### ISSUE TITLE
Being able to write multiples languages on the same keyboard layout

### ISSUE THREAD

**Issue by Zykino** [AnySoftKeyboard/AnySoftKeyboard#878]
### Steps to reproduce
1. Select a french layout (AZERTY / BéPO)
2. Open the keyboard anywhere you have the auto-complete function
3. Try to write an english sentence and read it again.

### Expected behavior
I am able to write in english (select english in the list of languages I want to be corrected in).
I also want to keep my layout (QWERTY feels far from natural for me, even if I write in english I use an AZERTY keyboard)

I think having an option to select multiples languages and the keyboard layouts separated is the way to go.

### Actual behavior
The keyboard keep correcting me from english to french

**Android OS version:**
7.0

**Device manufacturer and model:**
OnePlus
3

**List of installed add-ons (like languages, or themes):**
(up to date from F-Droid) v1.8-r7.1
French 20111029

**Comment by lindhe** [comment]
I might have the same problem. If I write Swedish, the only corrections I get are the names from my contact list. English works fine.

**Comment by menny** [comment]
A new beta will be available in a few hours for testing. Please test!

**Comment by maverick74** [comment]
This feature seems OK as well. Thanks for adding it :)
