### ISSUE TITLE
Disable key popup on quick tap

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#895]
We are able to disable sounds and vibrations on the key taps but we can't disable the key popup. I would like a setting to only have a popup above a key when a long press occurs and a subkey is needed to be chosen. I personally don't see the point otherwise. An idea.

**Comment by menny** [comment]
Actually, this is already implemented:
Go to "Themes" in the settings app, and click "Tweaks" (in the overflow menu).
Uncheck "Key preview popup".

**Comment by landry314** [comment]
i am using android 6 and i see no tweaks in an overflow menu in themes in settings...

nothing in the language and input either...

**Comment by menny** [comment]
![screenshot_20170224-100221-01](https://cloud.githubusercontent.com/assets/481272/23308304/cb8f0b66-fa78-11e6-9280-6c934019db42.jpeg)

**Comment by landry314** [comment]
omg, i had no idea this was there!!!! more features!!!! wow, this keyboard is customizable!

when you said "themes in the settings app" i went to android settings like, what?

in the anysoftkeyboard settings under "keyboard themes" there is a menu with one item, tweaks, ok! this is like finding a hidden room in your basement.

**Comment by menny** [comment]
hahahah cool! Enjoy your new found booty
