### ISSUE TITLE
Delete Polish from "supported language" from app description. 

### ISSUE THREAD

**Issue by ReportingRaccoon** [AnySoftKeyboard/AnySoftKeyboard#898]
Since there's open issue about Polish language pack not being recognized by ASK (https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/646) and there's no progress to fix that issue I am recommending to delete Polish from supported languages in app description in Google Play. Why? Because there are alot bad ratings from Polish users that said their language pack is not working anymore. When 646 will be fixed, you could bring Polish back on a list.

**Comment by menny** [comment]
where do you see that? I thought I removed all "supported languages" clause awhile ago.

**Comment by AnXh3L0** [comment]
This is not relevant anymore and the Polish language works with ASK.
