### ISSUE TITLE
Redesign settings app

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#904]
no drawer
several bottom (or top) tabs:

1. Main + link to About
2. Keyboards. shows the keyboard, then buttons:
..1. Layouts
..2. Themes
..3. Generic rows
3. Dictionaries and Grammar
4. Gestures
5. Emojies

**Comment by maverick74** [comment]
I would suggest this could be marked as ASK v2.0…

**Comment by menny** [comment]
@maverick74, we're planning to release swype support with v2.

I mean, it could be changed.. and have this marked as v2 and swype as v3...
Let me think about this.
