### ISSUE TITLE
In URL input box, keyboard switches to EN keyboard automatically

### ISSUE THREAD

**Issue by Mannshoch** [AnySoftKeyboard/AnySoftKeyboard#905]
For general use I have a German Keyboard Layout active. But if I use it on Firefox, AnySoftKeyboard switch to my SSH layout. This Layout I normally use in a Terminal.

**Comment by Rudloff** [comment]
I can reproduce this with French and SSH layouts: Firefox's URL bar automatically switches to the SSH layout, which is pretty annoying.

**Comment by Exagone313** [comment]
I'm affected too, I don't understand how it's possible. I use Icecat (Firefox ESR fork).

**Comment by menny** [comment]
This is the desired behavior, but I can see why it should be configurable.
I'll add a setting to disable this feature.

Note to self: Code to change at com/anysoftkeyboard/keyboards/KeyboardSwitcher.java:307

**Comment by Mannshoch** [comment]
@menny What do you mean with desired behavior? What is the idea behind this?

**Comment by menny** [comment]
It assumes that most cases you type a URL in those type of inputs, and thus switches to an ASCII/Latin keyboard

**Comment by Mannshoch** [comment]
Hm... The Idea is not bad. Configuring should be a good Idea. There is an other Keyboard activ I would like to use with Firefox. Deactivating or choose the prefered Keyboard would be a good Idea.

**Comment by Exagone313** [comment]
Should I/someone post a new issue for suggesting the ability to choose keyboard layout preference order, in addition to this?

**Comment by menny** [comment]
Yes, please open another ticket for that.

**Comment by menny** [comment]
@Exagone313 @Mannshoch please verify this with the latest beta (should be available in Play Store in a few hours).

**Comment by Exagone313** [comment]
I don't use Play Store, only builds from F-droid.

**Comment by Mannshoch** [comment]
Me to

**Comment by menny** [comment]
You can download a signed build here: https://480-4063516-gh.circle-artifacts.com/0/apks/app-canary.apk
Note, it is the Play-Store signature not F-Droid, so you may need to uninstall and install this version.
Or just wait till the stable release is at f-droid.
