### ISSUE TITLE
Setup wizard: Suggest downloading language pack if current locale does not have installed pack

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#906]

**Comment by maverick74** [comment]
@menny Would be nice if the Setup Wizard would have a few more steps. Something like:

**Activate AnySoftKeyboard > Change to AnySoftKeyboard > Select Dictionary/Dictionaries > Select Keyboard Layout (for Portrait & Landscape)** > select theme (not sure about this one).

I think it would help new users getting started ;)

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/986
