### ISSUE TITLE
Hebrew diacritics

### ISSUE THREAD

**Issue by abartov** [AnySoftKeyboard/AnySoftKeyboard#907]
There does not seem to be a way to produce Hebrew Diacritics (nikkud) in the Hebrew keyboard. Is there?

(Searched issues and wiki, to no avail.)

**Android OS version: 7.1.1

**Device manufacturer and model: Google Pixel

**List of installed add-ons (like languages, or themes):**
Hebrew language pack

**Comment by menny** [comment]
I'd like to do that.
I'm thinking to allow nikud as a long-press option for each Hebrew letter. Does that make sense?

**Comment by abartov** [comment]
Yeah, that would work for me.
Or just long-press options in one of the punctuation keys.

It's the one feature I'm missing, which occasionally makes me switch back to another keyboard.

**Comment by abartov** [comment]
Any thoughts on when you might get around to implementing this? Thanks in advance.

**Comment by abartov** [comment]
Ping?

**Comment by menny** [comment]
This is implemented in the latest Hebrew language pack
