### ISSUE TITLE
[feature request] Decouple language from keyboard layout

### ISSUE THREAD

**Issue by pchampin** [AnySoftKeyboard/AnySoftKeyboard#908]
I just installed AnySoftKeyboard and like very much. Thank you for a very good alternative to proprietary keyboards :)

I'm a bit confused, though, by the fact that the keyboard layout is coupled with the spellchecker language. I'm used to the french AZERTY keyboard, regardless of the language in which I write (French or English), so I would like to be able to use an English spellchecker with the AZERTY keyboard as well...

I know I could fix this by proposing a new "english keyboard" with an AZERTY layout, but it would seem cleaner to have the keep the two settings independent (even if each layout could have a *default* dictionary associated to it).

**Comment by menny** [comment]
we're working on it: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/832
