### ISSUE TITLE
[feature request] Automatically detect language

### ISSUE THREAD

**Issue by pchampin** [AnySoftKeyboard/AnySoftKeyboard#909]
I frequently switch between French and English. Whenever I start typing in a language different from the one currently set, the spellchecker insists on replacing each word I type, until I manually switch to the correct language.

Wouldn't it be possible that the keyboard automatically detect the language change? When I type words that are incorrect in the current language, but correct in another installed dictionary, it would automatically switch to that language...

Currently, this would also change the keyboard layout, which could arguably be disturbing for the user, so it should be possible to disable the language detect feature -- and probably it should not be enabled by default. In the longer term, as I suggested in #908, the language could be decoupled from the layout...

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/832 will solve it, right?

**Comment by pchampin** [comment]
#832 will definitely solve #908 -- sorry about the duplicate, btw, I should have looked more thoroughly before submitting it.

And solving #832/#908 is clearly a pre-requisite for the feature discussed here, but I'm not sure it includes it. In the discussions about #832, I don't see anyone suggesting *automatic* language selection, only manual selection is proposed.

If you prefer to address both problems together, I see no harm in closing this issue as a duplicate of #832. But I was suspecting that the automatic language switching might be extra work, that's why I submitted two separate issues.

Thanks a lot for your reactivity.

**Comment by woj-tek** [comment]
@menny I don't think this should be closed as this is different from #832. The basic idea that you select some layout, then you (separately) select languages that you would like to use (for example English and Spanish) and then when typing ASK would make suggestions from both languages without the need to manually switch between languages - it could detect/favour language context (put more stress on making suggestions from the language that we already typed a couple of words but should not limit if there is almost exact match with word in different language).
I'm not sure how feasible it is.

SwiftKey works like that and this was one of the reasons I started to use it - I finally was able to type without constant switching between languages (I use on daily basis Polish/English/Spanish and switching every couple of seconds language is simply tedious).

----

There is also a notion of regional characters that touches on the layout (and maybe would suit better separate issue - basically enabling particular language packs would include diacritics for that language in the basic QWERTY layout)

**Comment by LoukaOctave** [comment]
@woj-tek Your last comment in this thread is the exact reason I'm currently digging through this repo right now. I believe language context aware suggestions/corrections would be nice as I'm currently using a single keyboard layout with multiple language dictionaries. Don't know why this issue was closed as this doesn't seem to be a feature as of yet (correct me if I'm wrong).
