### ISSUE TITLE
Top Row Key Popups on "QWERTY Latin keyboard with symbols (on long press)" Don't Default To Numbers

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#912]
In "QWERTY Latin keyboard" when you hold on a key on the top row (without a number hint) it pops up and offers one of the digits FIRST then other symbols if you swipe towards them.

In "QWERTY Latin keyboard with symbols (on long press)" when you hold a key on the top row (WITH a number hint) it SOMETIMES defaults to the digits (with 1, 2, 4, 5, 6) but sometimes has other symbols (with 3, 7, 8, 9, 0) as the first options. This prevents a long-press-release from always being a number.

This is funny, especially because the hint IS the number in the "long press" keyboard where it doesn't always give you a number immediately but the hint is just mostly annoying (with w and p) and mostly useless (the symbols "<->") in the "QWERTY Latin keyboard" where is DOES ALWAYS give you the digit even though it is not the hint. Quite strange choices for the layout of hints.

**Comment by landry314** [comment]
whoa! the new update fixes this problem! nevermind!!!

**Comment by menny** [comment]
Ya, took care of that
