### ISSUE TITLE
Some emojis are not shown, just a box

### ISSUE THREAD

**Issue by moshpirit** [AnySoftKeyboard/AnySoftKeyboard#913]
### Steps to reproduce
1. Open the keyboard
2. Go to emojis section
3. See the lack of some emojis and a box (or unicode) instead

### Expected behaviour
All emojis should be shown 

### Actual behaviour
Most of them are shown but not all of them

**Android OS version:** 6.0.1 (Official)

**Device manufacturer and model:** BQ Aquaris M5

**List of installed add-ons (like languages, or themes):** Dark magra 2 theme and Spanish dictionary

**Screenshot**: 
![screenshot_20170225-110433](https://cloud.githubusercontent.com/assets/7888062/23330295/bfa1836a-fb4a-11e6-8dd3-e5fb3c5ad523.png)

**Comment by landry314** [comment]
this is because the android built-in "blob" emoji set doesn't support the new standard created by emojione (i think) which has new emojis. it just shows a box when it can't draw it.

it would be awesome if anysoftkeyboard could directly support the new standard instead of going to android for the emojis. all my messengers support it now (whatsapp, telegram, signal) and iphone does too.

http://emojione.com/

**Comment by dkm** [comment]
This is still true using 1.8.735 from f-droid. Any hint on how to fix this ?

**Comment by landry314** [comment]
yes

**Comment by github-tomster** [comment]
hello board
i have found this open issue here by chance as i was looking for an
solution to my similar problem.
on my device: AOSP 7.1.2 i have 
- installed ask1.9r5 from f-droid
- there is also the latest unicode 11 notocoloremoji.ttf installed
though i dont see all emojis on ask :-(
to verify my system i installed gboard(latest)
et voila: all emojis visible.

is it on ask or on my system?

**Comment by moshpirit** [comment]
I'm having no trouble with that now but I'm using a different phone so I can't say it's fixed. I have other issues though (problems to load some emojis & size too big) but that's two different issues.

**Comment by zmylls** [comment]
I have the same problem and i use the newest version. One 5.1 is normal, the other 7.1 appears。
