### ISSUE TITLE
')' Isn't The Default Long-Press Popup Choice For The L Key

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#918]
in QWERTY (on long press) the ')' key defaults to an accented 'l' character instead of the ')' which is the hint on the key and a more generally useful character!

i suggest making sure all the defaults are optimal! ;-)

**Comment by landry314** [comment]
Is this a problem for anyone else?

**Comment by menny** [comment]
In which language and layout is that happening?

**Comment by landry314** [comment]
"QWERTY Latin keyboard with symbols (on long press)" in English.

the '(' works fine but the ')' pulls up a long popup menu where i have to go 4 places to the left.

**Comment by landry314** [comment]
The newest update does not fix this issue.

Every time I need to use the ')' character I have to tap 'l' and drag 4 places to the left. It is quite a pain.

In general, shouldn't the character displayed in blue at the top of a key be the DEFAULT pop up choice after a quick tap and hold for ALL THE KEYS?

Right?

**Comment by ainola** [comment]
I can confirm this. The preview shows the closing paren but long pressing adds a ľ

Using English Latin as well.

**Comment by landry314** [comment]
I don't know why this is being ignored, @ainola, right? it would be so simple to fix and really improve our typing! I use the ) key quite a lot as I assume do you!

I was hoping the just released version would have fixed this but no :-( .

**Comment by ainola** [comment]
> I don't know why this is being ignored, @ainola, right? it would be so
> simple to fix and really improve our typing!

Let's not pester the developers too much. Do remember that this is a
free software project and not everyone on it has time to fix every
little issue. These great guys will get to it eventually.

> I use the ) key quite a > lot as I assume do you!

I do; however, I've been quite fine using the click-hold comma for now.

**Comment by landry314** [comment]
You are right, I'm being annoying.

Yes, click hold comma IS easier, thanks!

**Comment by landry314** [comment]
I hate to be annoying again but can I bump this issue right here? :grimacing:

It is a really quick fix. We just need to reorganize the order of the characters in the long-press popup for the L key. Move the ')' character all the way to the right so it is the first character that is selected when you long-press. Super easy.

People use this character all the time. I feel like this is an important issue.

And we all do agree that the default character on long-press should be the one that appears on the key, as a general rule, right? From a design standpoint.

I am excited about the next milestone and hope this makes it in!
