### ISSUE TITLE
first letter reapeted after writing a word, press ENTER and then backspace

### ISSUE THREAD

**Issue by lucamp** [AnySoftKeyboard/AnySoftKeyboard#920]
### Steps to reproduce
1. write a word, for instance "hello". Do not auto correct it or press the highlighted word on the suggestion bar
2. press ENTER
3. press BACKSPACE

### Expected behaviour
word "hello" is displayed

### Actual behaviour
word "hhello" is displayed

**Android OS version:**
4.4.1

**Device manufacturer and model:**
LG D620

**List of installed add-ons (like languages, or themes):**
English QUERTY Latin Keyboard
Italian querty + language pack

bug affected both layouts

**Comment by mtbu** [comment]
This happens to me using v1.8.1333  from F-Droid, on LineageOS 14.1 using English QWERTY layout.

**Comment by menny** [comment]
I'm really having issues reproducing this. Sometimes I can make it will happen and sometimes backspace will behave correctly. I'm still trying to figure this out, but I might need to push that to a later release.

**Comment by tedkotz** [comment]
I'm able to get very similar results with a build of master when using gesture typing. if I swipe in "this", It looks fine. if I hit any other letter say "d" then hit back space I get "tthis" with "this" underlined.

**Comment by mtbu** [comment]
I think it may depend what app is running, for instance it happens to me with com.simplemobiletools.notes (v2.3.0 from F-Droid)

**Comment by menny** [comment]
I think I found the issue, or at least, one of the issues. It's related to typing in apps that have a slow InputConnection implementation. It is not uncommon to see apps like that.

**Comment by menny** [comment]
The fix will be available in the next ALPHA and BETA
