### ISSUE TITLE
Missing some key_codes in api

### ISSUE THREAD

**Issue by kertase** [AnySoftKeyboard/AnySoftKeyboard#922]
Hi,

I would like to add the keys forward_del, page_up, page_down and insert to my keyboard. Would it be possible to add the necessary  key codes to https://github.com/AnySoftKeyboard/AnySoftKeyboard-API/blob/master/api/src/main/res/values/functional_key_codes.xml ?

Thanks

**Comment by menny** [comment]
@kertase, Will you do the implementation for those keys?

**Comment by kertase** [comment]
I would if I understood where the strings and integers are taken from…
