### ISSUE TITLE
French language use A LOT of apostrophe in words which are reconised as mistakes.

### ISSUE THREAD

**Issue by ghost** [AnySoftKeyboard/AnySoftKeyboard#924]
Nevermind, I just found one issue closed with apostrophe in french, I'm sorry to have opened one more !

### Steps to reproduce
1. set the language to french
2. write in french
3. any time it use an apostrophe in the word, the word is correcting in another word, but a wrong one.

### Expected behaviour
Tell us what should happen
The apostrophe (or single quotation mark) hasn't to be recognised as a mistake.

### Actual behaviour
Tell us what happens instead
All words with apostrophe are recognised as wrong and are automatically change in other words.
e.g "je n'ai pas d'idée" which means "I have no idea" is corrected to "je n'ai pas sniffée" "I didn't snort" (drugs), and "n'ai" are not corrected because I already "add" it as a new word in the dictionary.
It is really annoying to add all the dictionary 3 times or more. I can't explain, demonstrate how much we use apostrophe in sentences, just for "aimer" (love) with some combination : j'aime l'application, t'aimes l'application, l'application t'aime, ... And for the negative way : je n'aime pas, tu n'aimes pas, ...
(translation : I like the application, you like the application, the application likes you, I don't like, you don't like)
We can make a lot of combination with word and apostrophe, I agree French has an horrible grammar, but I think turning all "apostrophed" words into another word is a serious brake on the distribution of Anysoftkeyboard in the french speaking country.

**Android OS version:**
4.4.2

**Device manufacturer and model:**
htc desire 320

**List of installed add-ons (like languages, or themes):**
french language, german language

best regards,
JB

**Comment by Zykino** [comment]
I think it's a duplicate of #109 (but it's still annoying)
