### ISSUE TITLE
French word suggestions do not work with words containing accents

### ISSUE THREAD

**Issue by Rudloff** [AnySoftKeyboard/AnySoftKeyboard#933]
Hello,

Since my latest update (1.8.585), I have found a regression with suggestions.

### Steps to reproduce
1. Enable suggestions.
1. Switch to French (azerty) keyboard.
2. Type `pates`.

### Expected behaviour
It should suggest `pâtes`.

### Actual behaviour
It only suggests words without accents (pares, payes, etc.).

(But if I type `pâte`, it correctly suggests  `pâtes`.)

**Android OS version:** 5.1

**Device manufacturer and model:** Fairphone 2

**List of installed add-ons (like languages, or themes):*** 
* French language pack (20111029)
* SSH language pack (0.4.2012611-beta)

**Comment by Rudloff** [comment]
Sorry, I just realized this might be a duplicate of #921.

**Comment by menny** [comment]
I'll try to fix that for the next release.
