### ISSUE TITLE
Words with tildes are not suggested when the word is completely written

### ISSUE THREAD

**Issue by moshpirit** [AnySoftKeyboard/AnySoftKeyboard#941]
### Steps to reproduce
1. Write some word in Spanish with tilde (eg: que/qué, tenia/tenía, podre (there's actually no "podre", just "podré"))
2. See that there's no "qué" suggested when you complete writing "que"
3. delete the last e and put "é" if you want "qué" (which is kind of annoying)

ASF 1.8.585 (F-droid)

### Expected behaviour
words with tildes being shown when you completely write the word

### Actual behaviour
they're not shown

**Android OS version:** 6.0.1

**Device manufacturer and model:** BQ Aquaris M5

**List of installed add-ons (like languages, or themes):** Spanish (20110717)

**Comment by menny** [comment]
This is duplicate to https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/921
I'm working on fixing that.

**Comment by moshpirit** [comment]
Sorry, I didn't see it! thank you so much for your support!!
