### ISSUE TITLE
Please leave the volume rocker alone for sound volume control — the now reverted to again be nicely thin arrows are entirely sufficient. 

### ISSUE THREAD

**Issue by Pebef** [AnySoftKeyboard/AnySoftKeyboard#949]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
Are those two reports?
1 - volume rocker does not work
2 - something about the new arrows icons?
