### ISSUE TITLE
Keyboard stay on screen when returning Home (instead of back)

### ISSUE THREAD

**Issue by Zykino** [AnySoftKeyboard/AnySoftKeyboard#954]
### Steps to reproduce
1. Write some text (anywhere)
2. Hit the Android "Home Button"

### Expected behaviour
The app and the keyboard are minimized

### Actual behaviour
Only the app is minimized.
The keyboard stay open in over the home screen. I have to hit the back button to close it.

**Android OS version:**
7.0 (OxygenOS 4.0.3)

**Device manufacturer and model:**
OnePlus 3

**List of installed add-ons (like languages, or themes):**
French (AZERTY/bépo)

**Comment by lkelemen** [comment]
Same here. Gal S7. Android 7.0. Samsung launcher. ASK Finnish and Hungarian languages installed

**Comment by dkurzaj** [comment]
The latest update (https://github.com/AnySoftKeyboard/AnySoftKeyboard/releases/tag/1.8-r10) fixed it for me.

**Comment by menny** [comment]
Cool!
I did have a fix in for a similar issue and I had a suspicion that this issue is fixed too.

Thanks for verifying

**Comment by adf111** [comment]
Hi Kenny,
Unfortunately started today again.
Note Edge, v6.0.1 android.
Even whenge screen is dark, the keyboard remains seen, but "greyed out"...

**Comment by Zykino** [comment]
Yeah I wasn't sure I received the update of the app with this correction. But now that I just did an update with F-Droid I'm confirm that the keyboard (normal not emoji one) stay on the home screen.

Emoji keyboard disappear when I click home.

Android 8.0.0
ASK Version 1.9.1117, version-code 3692
