### ISSUE TITLE
Landscape mode screen has black frame

### ISSUE THREAD

**Issue by lkelemen** [AnySoftKeyboard/AnySoftKeyboard#974]
I also have a landscape issue. ASK v1.8.735 with no extensions.App:whatsapp, os:android 7.0, phone:samsung galaxy s7. Settings:landscape full screen, word prediction on. How to get it: go landscape in WhatsApp, start to write, screen OK. Press the back key (ASK disappears) and then touch the input field so ASK is shown again. ASK UI covered with a dark transparent frame on the right and bottom part.

**Comment by menny** [comment]
can you share a screenshot of that?

**Comment by lkelemen** [comment]
![screenshot_20170418-131833](https://cloud.githubusercontent.com/assets/11487871/25268131/3b423644-2680-11e7-87e4-bcec867d3cf2.png)
![screenshot_20170418-131853](https://cloud.githubusercontent.com/assets/11487871/25268132/3b424b70-2680-11e7-9484-2a2d662ebd1c.png)

**Comment by lkelemen** [comment]
Here is the same with another theme. Not so visible as the black frame is under the keys.

![screenshot_20170421-105558](https://cloud.githubusercontent.com/assets/11487871/25268528/b32d3b76-2681-11e7-825c-8bf35bcc5736.png)
![screenshot_20170421-105628](https://cloud.githubusercontent.com/assets/11487871/25268527/b32abe46-2681-11e7-8b0b-f32cef3f6387.png)

**Comment by lkelemen** [comment]
Can this be Android OS version related? My phone has 7.0. The latest is 7.1.2 ?

**Comment by maverick74** [comment]
I can confirm this bug as well. It happens occasionally to me as well. I can share screenshots as well if they're needed.

**Comment by lkelemen** [comment]
@maverick74 what is your Andrlkd version?

**Comment by maverick74** [comment]
@lkelemen 4.2

**Comment by maverick74** [comment]
I can add that this happens only when the keyboard is set to use Fullscreen when in landscape mode

**Comment by lkelemen** [comment]
The bug is still reproducible on v1.8.834 of AnySoftKeyboard. Unzip the attached file see the video.
[2017_06_15_13_08_26_1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/1077278/2017_06_15_13_08_26_1.zip)

**Comment by eickeh** [comment]
Hey there, first of all thanks for this great app! 
I'm opening the bug again as it still persists on v1.10.1109 on Android 10 (LOS 17.1) one oneplus 5t. In my case, I can get rid of the black frame by switching to portrait and back to landscape mode. After that, the black frame is gone for some time. 
Can you maybe point me to some part of the code where the issue could be located? Maybe I'll find some time to look into it.
I'd love to see this bug vanish.
