### ISSUE TITLE
Caps lock doesn't work

### ISSUE THREAD

**Issue by maverick74** [AnySoftKeyboard/AnySoftKeyboard#997]
### Steps to reproduce
1. Go to Menu - Interface - Even more - Tweaks - Time between multiple touches - disable
2. Try to enable CAPS to always on (use to be double press on shift)

### Expected behaviour
Double press on shift key should still work because there is no other way to enable Caps Lock

### Actual behaviour
I have to press shift before every key i want in caps

**Android OS version:**
4.2

**Comment by maverick74** [comment]
With the long-press on shift to lock it, released in the latest r12, this can be marked as fixed.

Thanks Menny

**Comment by menny** [comment]
👍
